nouns = [
    {"indefinite": "person", "definite": "personen", "plural": "personer", "plural_definite": "personerna", "english": "person"},
    {"indefinite": "namn", "definite": "namnet", "plural": "namn", "plural_definite": "namnen", "english": "name"},
    {"indefinite": "ålder", "definite": "åldern", "plural": "åldrar", "plural_definite": "åldrarna", "english": "age"},
    {"indefinite": "kön", "definite": "könet", "plural": "kön", "plural_definite": "könen", "english": "gender"},
    {"indefinite": "nationalitet", "definite": "nationaliteten", "plural": "nationaliteter", "plural_definite": "nationaliteterna", "english": "nationality"},
    {"indefinite": "ursprung", "definite": "ursprunget", "plural": "ursprung", "plural_definite": "ursprungen", "english": "origin"},
    {"indefinite": "bakgrund", "definite": "bakgrunden", "plural": "bakgrunder", "plural_definite": "bakgrunderna", "english": "background"},
    {"indefinite": "familj", "definite": "familjen", "plural": "familjer", "plural_definite": "familjerna", "english": "family"},
    {"indefinite": "förälder", "definite": "föräldern", "plural": "föräldrar", "plural_definite": "föräldrarna", "english": "parent"},
    {"indefinite": "barn", "definite": "barnet", "plural": "barn", "plural_definite": "barnen", "english": "child"},
    {"indefinite": "son", "definite": "sonen", "plural": "söner", "plural_definite": "sönerna", "english": "son"},
    {"indefinite": "dotter", "definite": "dottern", "plural": "döttrar", "plural_definite": "döttrarna", "english": "daughter"},
    {"indefinite": "syskon", "definite": "syskonet", "plural": "syskon", "plural_definite": "syskonen", "english": "sibling"},
    {"indefinite": "bror", "definite": "brodern", "plural": "bröder", "plural_definite": "bröderna", "english": "brother"},
    {"indefinite": "syster", "definite": "systern", "plural": "systrar", "plural_definite": "systrarna", "english": "sister"},
    {"indefinite": "släkting", "definite": "släktingen", "plural": "släktingar", "plural_definite": "släktingarna", "english": "relative"},
    {"indefinite": "vän", "definite": "vännen", "plural": "vänner", "plural_definite": "vännerna", "english": "friend"},
    {"indefinite": "granne", "definite": "grannen", "plural": "grannar", "plural_definite": "grannarna", "english": "neighbor"},
    {"indefinite": "partner", "definite": "partnern", "plural": "partner", "plural_definite": "partnerna", "english": "partner"},
    {"indefinite": "make", "definite": "maken", "plural": "män", "plural_definite": "männen", "english": "husband"},
    {"indefinite": "maka", "definite": "makan", "plural": "makor", "plural_definite": "makorna", "english": "wife"},
    {"indefinite": "pojkvän", "definite": "pojkvännen", "plural": "pojkvänner", "plural_definite": "pojkvännerna", "english": "boyfriend"},
    {"indefinite": "flickvän", "definite": "flickvännen", "plural": "flickvänner", "plural_definite": "flickvännerna", "english": "girlfriend"},
    {"indefinite": "relation", "definite": "relationen", "plural": "relationer", "plural_definite": "relationerna", "english": "relationship"},
    {"indefinite": "liv", "definite": "livet", "plural": "liv", "plural_definite": "liven", "english": "life"},
    {"indefinite": "intresse", "definite": "intresset", "plural": "intressen", "plural_definite": "intressena", "english": "interest"},
    {"indefinite": "hobby", "definite": "hobbyn", "plural": "hobbyer", "plural_definite": "hobbyerna", "english": "hobby"},
    {"indefinite": "vana", "definite": "vanan", "plural": "vanor", "plural_definite": "vanorna", "english": "habit"},
    {"indefinite": "dröm", "definite": "drömmen", "plural": "drömmar", "plural_definite": "drömmarna", "english": "dream"},
    {"indefinite": "mål", "definite": "målet", "plural": "mål", "plural_definite": "målen", "english": "goal"},
    {"indefinite": "utbildning", "definite": "utbildningen", "plural": "utbildningar", "plural_definite": "utbildningarna", "english": "education"},
    {"indefinite": "erfarenhet", "definite": "erfarenheten", "plural": "erfarenheter", "plural_definite": "erfarenheterna", "english": "experience"},
    {"indefinite": "kunskap", "definite": "kunskapen", "plural": "kunskaper", "plural_definite": "kunskaperna", "english": "knowledge, skill"},
    {"indefinite": "språk", "definite": "språket", "plural": "språk", "plural_definite": "språken", "english": "language"},
    {"indefinite": "modersmål", "definite": "modersmålet", "plural": "modersmål", "plural_definite": "modersmålen", "english": "mother tongue"},
    {"indefinite": "kultur", "definite": "kulturen", "plural": "kulturer", "plural_definite": "kulturerna", "english": "culture"},
    {"indefinite": "tradition", "definite": "traditionen", "plural": "traditioner", "plural_definite": "traditionerna", "english": "tradition"},
    {"indefinite": "värdering", "definite": "värderingen", "plural": "värderingar", "plural_definite": "värderingarna", "english": "value (moral)"},
    {"indefinite": "religion", "definite": "religionen", "plural": "religioner", "plural_definite": "religionerna", "english": "religion"},
    {"indefinite": "tro", "definite": "tron", "plural": "tror", "plural_definite": "trorna", "english": "faith, belief"},
    {"indefinite": "land", "definite": "landet", "plural": "länder", "plural_definite": "länderna", "english": "country"},
    {"indefinite": "stad", "definite": "staden", "plural": "städer", "plural_definite": "städerna", "english": "city"},
    {"indefinite": "plats", "definite": "platsen", "plural": "platser", "plural_definite": "platserna", "english": "place"},
    {"indefinite": "område", "definite": "området", "plural": "områden", "plural_definite": "områdena", "english": "area, region"},
    {"indefinite": "hemstad", "definite": "hemstaden", "plural": "hemstäder", "plural_definite": "hemstäderna", "english": "hometown"},
    {"indefinite": "adress", "definite": "adressen", "plural": "adresser", "plural_definite": "adresserna", "english": "address"},
    {"indefinite": "postnummer", "definite": "postnumret", "plural": "postnummer", "plural_definite": "postnumren", "english": "postal code"},
    {"indefinite": "identitet", "definite": "identiteten", "plural": "identiteter", "plural_definite": "identiteterna", "english": "identity"},
    {"indefinite": "personnummer", "definite": "personnumret", "plural": "personnummer", "plural_definite": "personnumren", "english": "personal identity number"},
    {"indefinite": "bakgrundshistoria", "definite": "bakgrundshistorien", "plural": "bakgrundshistorier", "plural_definite": "bakgrundshistorierna", "english": "background story"},
    {"indefinite": "uppväxt", "definite": "uppväxten", "plural": "uppväxter", "plural_definite": "uppväxterna", "english": "upbringing"},
]

verbs = [
    {"infinitive": "vara", "present": "är", "past": "var", "supine": "varit", "english": "to be"},
    {"infinitive": "heta", "present": "heter", "past": "hette", "supine": "hett", "english": "to be called"},
    {"infinitive": "bo", "present": "bor", "past": "bodde", "supine": "bott", "english": "to live, reside"},
    {"infinitive": "födas", "present": "föds", "past": "föddes", "supine": "fötts", "english": "to be born"},
    {"infinitive": "växa upp", "present": "växer upp", "past": "växte upp", "supine": "växt upp", "english": "to grow up"},
    {"infinitive": "komma", "present": "kommer", "past": "kom", "supine": "kommit", "english": "to come"},
    {"infinitive": "flytta", "present": "flyttar", "past": "flyttade", "supine": "flyttat", "english": "to move"},
    {"infinitive": "leva", "present": "lever", "past": "levde", "supine": "levt", "english": "to live (exist)"},
    {"infinitive": "studera", "present": "studerar", "past": "studerade", "supine": "studerat", "english": "to study"},
    {"infinitive": "skriva", "present": "skriver", "past": "skrev", "supine": "skrivit", "english": "to write"},
    {"infinitive": "tala", "present": "talar", "past": "talade", "supine": "talat", "english": "to speak"},
    {"infinitive": "säga", "present": "säger", "past": "sa", "supine": "sagt", "english": "to say"},
    {"infinitive": "berätta", "present": "berättar", "past": "berättade", "supine": "berättat", "english": "to tell, narrate"},
    {"infinitive": "förklara", "present": "förklarar", "past": "förklarade", "supine": "förklarat", "english": "to explain"},
    {"infinitive": "förstå", "present": "förstår", "past": "förstod", "supine": "förstått", "english": "to understand"},
    {"infinitive": "lära", "present": "lär", "past": "lärde", "supine": "lärt", "english": "to learn"},
    {"infinitive": "känna", "present": "känner", "past": "kände", "supine": "känt", "english": "to feel, to know (a person)"},
    {"infinitive": "tro", "present": "tror", "past": "trodde", "supine": "trott", "english": "to believe"},
    {"infinitive": "tycka", "present": "tycker", "past": "tyckte", "supine": "tyckt", "english": "to think, have an opinion"},
    {"infinitive": "älska", "present": "älskar", "past": "älskade", "supine": "älskat", "english": "to love"},
    {"infinitive": "hata", "present": "hatar", "past": "hatade", "supine": "hatat", "english": "to hate"},
    {"infinitive": "drömma", "present": "drömmer", "past": "drömde", "supine": "drömt", "english": "to dream"},
    {"infinitive": "önska", "present": "önskar", "past": "önskade", "supine": "önskat", "english": "to wish"},
    {"infinitive": "minnas", "present": "minns", "past": "mindes", "supine": "mints", "english": "to remember"},
    {"infinitive": "glömma", "present": "glömmer", "past": "glömde", "supine": "glömt", "english": "to forget"},
    {"infinitive": "bo kvar", "present": "bor kvar", "past": "bodde kvar", "supine": "bott kvar", "english": "to stay living (remain)"},
    {"infinitive": "umgås", "present": "umgås", "past": "umgicks", "supine": "umgåtts", "english": "to socialize"},
    {"infinitive": "resa", "present": "reser", "past": "reste", "supine": "rest", "english": "to travel"},
    {"infinitive": "stanna", "present": "stannar", "past": "stannade", "supine": "stannat", "english": "to stay, remain"},
    {"infinitive": "börja om", "present": "börjar om", "past": "började om", "supine": "börjat om", "english": "to start over"},
    {"infinitive": "delta", "present": "deltar", "past": "deltog", "supine": "deltagit", "english": "to participate"},
]

misc = [
    # Adjectives (personality, identity)
    {"swedish": "snäll", "english": "kind"},
    {"swedish": "ärlig", "english": "honest"},
    {"swedish": "tyst", "english": "quiet"},
    {"swedish": "pratsam", "english": "talkative"},
    {"swedish": "social", "english": "social"},
    {"swedish": "blyg", "english": "shy"},
    {"swedish": "positiv", "english": "positive"},
    {"swedish": "negativ", "english": "negative"},
    {"swedish": "aktiv", "english": "active"},
    {"swedish": "lat", "english": "lazy"},
    {"swedish": "glad", "english": "happy"},
    {"swedish": "ledsen", "english": "sad"},
    {"swedish": "rolig", "english": "funny"},
    {"swedish": "allvarlig", "english": "serious"},
    {"swedish": "öppen", "english": "open"},
    {"swedish": "stängd", "english": "closed"},
    {"swedish": "självständig", "english": "independent"},
    {"swedish": "beroende", "english": "dependent"},
    {"swedish": "vänlig", "english": "friendly"},
    {"swedish": "omtänksam", "english": "considerate"},

    # Adverbs (narrative connectors / time)
    {"swedish": "först", "english": "first"},
    {"swedish": "sedan", "english": "then"},
    {"swedish": "därefter", "english": "after that"},
    {"swedish": "till slut", "english": "finally"},
    {"swedish": "ofta", "english": "often"},
    {"swedish": "ibland", "english": "sometimes"},
    {"swedish": "sällan", "english": "rarely"},
    {"swedish": "alltid", "english": "always"},
    {"swedish": "aldrig", "english": "never"},
    {"swedish": "vanligtvis", "english": "usually"},
    {"swedish": "tidigare", "english": "earlier"},
    {"swedish": "numera", "english": "nowadays"},
    {"swedish": "ännu", "english": "still"},
    {"swedish": "redan", "english": "already"},
    {"swedish": "nyligen", "english": "recently"},

    # Connectors (causal / contrast)
    {"swedish": "därför att", "english": "because"},
    {"swedish": "eftersom", "english": "since, because"},
    {"swedish": "men", "english": "but"},
    {"swedish": "trots att", "english": "even though"},
    {"swedish": "fastän", "english": "although"},
    {"swedish": "dessutom", "english": "in addition"},
    {"swedish": "för att", "english": "in order to"},
    {"swedish": "tack vare", "english": "thanks to"},
]

