nouns = [
    {"indefinite": "person", "definite": "personen", "plural": "personer", "plural_definite": "personerna", "english": "person", "cefr": 1, "frequency": 568.43},
    {"indefinite": "namn", "definite": "namnet", "plural": "namn", "plural_definite": "namnen", "english": "name", "cefr": 1, "frequency": 323.21},
    {"indefinite": "ålder", "definite": "åldern", "plural": "åldrar", "plural_definite": "åldrarna", "english": "age", "cefr": 1, "frequency": 93.87},
    {"indefinite": "kön", "definite": "könet", "plural": "kön", "plural_definite": "könen", "english": "gender", "cefr": 2, "frequency": 48.94},
    {"indefinite": "nationalitet", "definite": "nationaliteten", "plural": "nationaliteter", "plural_definite": "nationaliteterna", "english": "nationality", "cefr": 1, "frequency": None},
    {"indefinite": "ursprung", "definite": "ursprunget", "plural": "ursprung", "plural_definite": "ursprungen", "english": "origin", "cefr": 2, "frequency": 43.07},
    {"indefinite": "bakgrund", "definite": "bakgrunden", "plural": "bakgrunder", "plural_definite": "bakgrunderna", "english": "background", "cefr": 1, "frequency": 118.12},
    {"indefinite": "familj", "definite": "familjen", "plural": "familjer", "plural_definite": "familjerna", "english": "family", "cefr": 1, "frequency": 244.19},
    {"indefinite": "förälder", "definite": "föräldern", "plural": "föräldrar", "plural_definite": "föräldrarna", "english": "parent", "cefr": 1, "frequency": 167.00},
    {"indefinite": "barn", "definite": "barnet", "plural": "barn", "plural_definite": "barnen", "english": "child", "cefr": 1, "frequency": 700.31},
    {"indefinite": "son", "definite": "sonen", "plural": "söner", "plural_definite": "sönerna", "english": "son", "cefr": 1, "frequency": 560.93},
    {"indefinite": "dotter", "definite": "dottern", "plural": "döttrar", "plural_definite": "döttrarna", "english": "daughter", "cefr": 1, "frequency": 75.82},
    {"indefinite": "syskon", "definite": "syskonet", "plural": "syskon", "plural_definite": "syskonen", "english": "sibling", "cefr": 3, "frequency": 15.23},
    {"indefinite": "bror", "definite": "brodern", "plural": "bröder", "plural_definite": "bröderna", "english": "brother", "cefr": 2, "frequency": 60.45},
    {"indefinite": "syster", "definite": "systern", "plural": "systrar", "plural_definite": "systrarna", "english": "sister", "cefr": 2, "frequency": 51.59},
    {"indefinite": "släkting", "definite": "släktingen", "plural": "släktingar", "plural_definite": "släktingarna", "english": "relative", "cefr": 3, "frequency": 22.07},
    {"indefinite": "vän", "definite": "vännen", "plural": "vänner", "plural_definite": "vännerna", "english": "friend", "cefr": 1, "frequency": 205.79},
    {"indefinite": "granne", "definite": "grannen", "plural": "grannar", "plural_definite": "grannarna", "english": "neighbor", "cefr": 2, "frequency": 37.82},
    {"indefinite": "partner", "definite": "partnern", "plural": "partner", "plural_definite": "partnerna", "english": "partner", "cefr": 2, "frequency": 24.16},
    {"indefinite": "make", "definite": "maken", "plural": "män", "plural_definite": "männen", "english": "husband", "cefr": 2, "frequency": 52.21},
    {"indefinite": "maka", "definite": "makan", "plural": "makor", "plural_definite": "makorna", "english": "wife", "cefr": 1, "frequency": None},
    {"indefinite": "pojkvän", "definite": "pojkvännen", "plural": "pojkvänner", "plural_definite": "pojkvännerna", "english": "boyfriend", "cefr": 1, "frequency": None},
    {"indefinite": "flickvän", "definite": "flickvännen", "plural": "flickvänner", "plural_definite": "flickvännerna", "english": "girlfriend", "cefr": 1, "frequency": None},
    {"indefinite": "relation", "definite": "relationen", "plural": "relationer", "plural_definite": "relationerna", "english": "relationship", "cefr": 1, "frequency": 94.81},
    {"indefinite": "liv", "definite": "livet", "plural": "liv", "plural_definite": "liven", "english": "life", "cefr": 1, "frequency": 624.66},
    {"indefinite": "intresse", "definite": "intresset", "plural": "intressen", "plural_definite": "intressena", "english": "interest", "cefr": 1, "frequency": 197.41},
    {"indefinite": "hobby", "definite": "hobbyn", "plural": "hobbyer", "plural_definite": "hobbyerna", "english": "hobby", "cefr": 1, "frequency": None},
    {"indefinite": "vana", "definite": "vanan", "plural": "vanor", "plural_definite": "vanorna", "english": "habit", "cefr": 2, "frequency": 24.66},
    {"indefinite": "dröm", "definite": "drömmen", "plural": "drömmar", "plural_definite": "drömmarna", "english": "dream", "cefr": 2, "frequency": 58.07},
    {"indefinite": "mål", "definite": "målet", "plural": "mål", "plural_definite": "målen", "english": "goal", "cefr": 1, "frequency": 331.84},
    {"indefinite": "utbildning", "definite": "utbildningen", "plural": "utbildningar", "plural_definite": "utbildningarna", "english": "education", "cefr": 1, "frequency": 165.87},
    {"indefinite": "erfarenhet", "definite": "erfarenheten", "plural": "erfarenheter", "plural_definite": "erfarenheterna", "english": "experience", "cefr": 1, "frequency": 127.97},
    {"indefinite": "kunskap", "definite": "kunskapen", "plural": "kunskaper", "plural_definite": "kunskaperna", "english": "knowledge, skill", "cefr": 1, "frequency": 179.19},
    {"indefinite": "språk", "definite": "språket", "plural": "språk", "plural_definite": "språken", "english": "language", "cefr": 1, "frequency": 156.31},
    {"indefinite": "modersmål", "definite": "modersmålet", "plural": "modersmål", "plural_definite": "modersmålen", "english": "mother tongue", "cefr": 1, "frequency": None},
    {"indefinite": "kultur", "definite": "kulturen", "plural": "kulturer", "plural_definite": "kulturerna", "english": "culture", "cefr": 1, "frequency": 170.10},
    {"indefinite": "tradition", "definite": "traditionen", "plural": "traditioner", "plural_definite": "traditionerna", "english": "tradition", "cefr": 1, "frequency": 82.91},
    {"indefinite": "värdering", "definite": "värderingen", "plural": "värderingar", "plural_definite": "värderingarna", "english": "value (moral)", "cefr": 1, "frequency": 75.62},
    {"indefinite": "religion", "definite": "religionen", "plural": "religioner", "plural_definite": "religionerna", "english": "religion", "cefr": 1, "frequency": 136.55},
    {"indefinite": "tro", "definite": "tron", "plural": "tror", "plural_definite": "trorna", "english": "faith, belief", "cefr": 1, "frequency": 928.39},
    {"indefinite": "land", "definite": "landet", "plural": "länder", "plural_definite": "länderna", "english": "country", "cefr": 1, "frequency": 949.12},
    {"indefinite": "stad", "definite": "staden", "plural": "städer", "plural_definite": "städerna", "english": "city", "cefr": 1, "frequency": 413.66},
    {"indefinite": "plats", "definite": "platsen", "plural": "platser", "plural_definite": "platserna", "english": "place", "cefr": 1, "frequency": 374.33},
    {"indefinite": "område", "definite": "området", "plural": "områden", "plural_definite": "områdena", "english": "area, region", "cefr": 1, "frequency": 380.95},
    {"indefinite": "hemstad", "definite": "hemstaden", "plural": "hemstäder", "plural_definite": "hemstäderna", "english": "hometown", "cefr": 1, "frequency": None},
    {"indefinite": "adress", "definite": "adressen", "plural": "adresser", "plural_definite": "adresserna", "english": "address", "cefr": 2, "frequency": 29.89},
    {"indefinite": "postnummer", "definite": "postnumret", "plural": "postnummer", "plural_definite": "postnumren", "english": "postal code", "cefr": 1, "frequency": None},
    {"indefinite": "identitet", "definite": "identiteten", "plural": "identiteter", "plural_definite": "identiteterna", "english": "identity", "cefr": 2, "frequency": 43.18},
    {"indefinite": "personnummer", "definite": "personnumret", "plural": "personnummer", "plural_definite": "personnumren", "english": "personal identity number", "cefr": 1, "frequency": None},
    {"indefinite": "bakgrundshistoria", "definite": "bakgrundshistorien", "plural": "bakgrundshistorier", "plural_definite": "bakgrundshistorierna", "english": "background story", "cefr": 1, "frequency": None},
    {"indefinite": "uppväxt", "definite": "uppväxten", "plural": "uppväxter", "plural_definite": "uppväxterna", "english": "upbringing", "cefr": 1, "frequency": None},
]

verbs = [
    {"infinitive": "vara", "present": "är", "past": "var", "supine": "varit", "english": "to be", "cefr": 1, "frequency": 23017.26},
    {"infinitive": "heta", "present": "heter", "past": "hette", "supine": "hett", "english": "to be called", "cefr": 1, "frequency": 170.22},
    {"infinitive": "bo", "present": "bor", "past": "bodde", "supine": "bott", "english": "to live, reside", "cefr": 1, "frequency": 209.48},
    {"infinitive": "födas", "present": "föds", "past": "föddes", "supine": "fötts", "english": "to be born", "cefr": 1, "frequency": None},
    {"infinitive": "växa upp", "present": "växer upp", "past": "växte upp", "supine": "växt upp", "english": "to grow up", "cefr": 1, "frequency": None},
    {"infinitive": "komma", "present": "kommer", "past": "kom", "supine": "kommit", "english": "to come", "cefr": 1, "frequency": 3224.74},
    {"infinitive": "flytta", "present": "flyttar", "past": "flyttade", "supine": "flyttat", "english": "to move", "cefr": 1, "frequency": 167.68},
    {"infinitive": "leva", "present": "lever", "past": "levde", "supine": "levt", "english": "to live (exist)", "cefr": 1, "frequency": 363.55},
    {"infinitive": "studera", "present": "studerar", "past": "studerade", "supine": "studerat", "english": "to study", "cefr": 1, "frequency": 73.17},
    {"infinitive": "skriva", "present": "skriver", "past": "skrev", "supine": "skrivit", "english": "to write", "cefr": 1, "frequency": 1141.32},
    {"infinitive": "tala", "present": "talar", "past": "talade", "supine": "talat", "english": "to speak", "cefr": 1, "frequency": 423.10},
    {"infinitive": "säga", "present": "säger", "past": "sa", "supine": "sagt", "english": "to say", "cefr": 1, "frequency": 1998.46},
    {"infinitive": "berätta", "present": "berättar", "past": "berättade", "supine": "berättat", "english": "to tell, narrate", "cefr": 1, "frequency": 266.34},
    {"infinitive": "förklara", "present": "förklarar", "past": "förklarade", "supine": "förklarat", "english": "to explain", "cefr": 1, "frequency": 198.04},
    {"infinitive": "förstå", "present": "förstår", "past": "förstod", "supine": "förstått", "english": "to understand", "cefr": 1, "frequency": 403.12},
    {"infinitive": "lära", "present": "lär", "past": "lärde", "supine": "lärt", "english": "to learn", "cefr": 1, "frequency": 376.66},
    {"infinitive": "känna", "present": "känner", "past": "kände", "supine": "känt", "english": "to feel, to know (a person)", "cefr": 1, "frequency": 840.25},
    {"infinitive": "tro", "present": "tror", "past": "trodde", "supine": "trott", "english": "to believe", "cefr": 1, "frequency": 928.39},
    {"infinitive": "tycka", "present": "tycker", "past": "tyckte", "supine": "tyckt", "english": "to think, have an opinion", "cefr": 1, "frequency": 924.85},
    {"infinitive": "älska", "present": "älskar", "past": "älskade", "supine": "älskat", "english": "to love", "cefr": 1, "frequency": 120.93},
    {"infinitive": "hata", "present": "hatar", "past": "hatade", "supine": "hatat", "english": "to hate", "cefr": 2, "frequency": 34.52},
    {"infinitive": "drömma", "present": "drömmer", "past": "drömde", "supine": "drömt", "english": "to dream", "cefr": 2, "frequency": 30.66},
    {"infinitive": "önska", "present": "önskar", "past": "önskade", "supine": "önskat", "english": "to wish", "cefr": 1, "frequency": 105.47},
    {"infinitive": "minnas", "present": "minns", "past": "mindes", "supine": "mints", "english": "to remember", "cefr": 1, "frequency": 145.43},
    {"infinitive": "glömma", "present": "glömmer", "past": "glömde", "supine": "glömt", "english": "to forget", "cefr": 1, "frequency": 122.09},
    {"infinitive": "bo kvar", "present": "bor kvar", "past": "bodde kvar", "supine": "bott kvar", "english": "to stay living (remain)", "cefr": 1, "frequency": None},
    {"infinitive": "umgås", "present": "umgås", "past": "umgicks", "supine": "umgåtts", "english": "to socialize", "cefr": 2, "frequency": 23.99},
    {"infinitive": "resa", "present": "reser", "past": "reste", "supine": "rest", "english": "to travel", "cefr": 1, "frequency": 122.43},
    {"infinitive": "stanna", "present": "stannar", "past": "stannade", "supine": "stannat", "english": "to stay, remain", "cefr": 1, "frequency": 119.33},
    {"infinitive": "börja om", "present": "börjar om", "past": "började om", "supine": "börjat om", "english": "to start over", "cefr": 1, "frequency": None},
    {"infinitive": "delta", "present": "deltar", "past": "deltog", "supine": "deltagit", "english": "to participate", "cefr": 1, "frequency": 152.80},
]

misc = [
    {"swedish": "snäll", "english": "kind", "cefr": 2, "frequency": 47.36},
    {"swedish": "ärlig", "english": "honest", "cefr": 2, "frequency": 47.97},
    {"swedish": "tyst", "english": "quiet", "cefr": 2, "frequency": 30.67},
    {"swedish": "pratsam", "english": "talkative", "cefr": 1, "frequency": None},
    {"swedish": "social", "english": "social", "cefr": 1, "frequency": 226.91},
    {"swedish": "blyg", "english": "shy", "cefr": 1, "frequency": None},
    {"swedish": "positiv", "english": "positive", "cefr": 1, "frequency": 147.36},
    {"swedish": "negativ", "english": "negative", "cefr": 1, "frequency": 83.54},
    {"swedish": "aktiv", "english": "active", "cefr": 1, "frequency": 91.62},
    {"swedish": "lat", "english": "lazy", "cefr": 3, "frequency": 14.25},
    {"swedish": "glad", "english": "happy", "cefr": 1, "frequency": 120.57},
    {"swedish": "ledsen", "english": "sad", "cefr": 3, "frequency": 22.86},
    {"swedish": "rolig", "english": "funny", "cefr": 1, "frequency": 147.33},
    {"swedish": "allvarlig", "english": "serious", "cefr": 1, "frequency": 84.74},
    {"swedish": "öppen", "english": "open", "cefr": 1, "frequency": 150.86},
    {"swedish": "stängd", "english": "closed", "cefr": 3, "frequency": 14.94},
    {"swedish": "självständig", "english": "independent", "cefr": 2, "frequency": 39.17},
    {"swedish": "beroende", "english": "dependent", "cefr": 1, "frequency": None},
    {"swedish": "vänlig", "english": "friendly", "cefr": 2, "frequency": 25.46},
    {"swedish": "omtänksam", "english": "considerate", "cefr": 1, "frequency": None},
    {"swedish": "först", "english": "first", "cefr": 1, "frequency": 290.35},
    {"swedish": "sedan", "english": "then", "cefr": 1, "frequency": 1115.12},
    {"swedish": "därefter", "english": "after that", "cefr": 1, "frequency": 129.33},
    {"swedish": "till slut", "english": "finally", "cefr": 1, "frequency": None},
    {"swedish": "ofta", "english": "often", "cefr": 1, "frequency": 501.79},
    {"swedish": "ibland", "english": "sometimes", "cefr": 1, "frequency": 258.58},
    {"swedish": "sällan", "english": "rarely", "cefr": 1, "frequency": 76.95},
    {"swedish": "alltid", "english": "always", "cefr": 1, "frequency": 446.85},
    {"swedish": "aldrig", "english": "never", "cefr": 1, "frequency": 511.81},
    {"swedish": "vanligtvis", "english": "usually", "cefr": 2, "frequency": 24.95},
    {"swedish": "tidigare", "english": "earlier", "cefr": 1, "frequency": 366.98},
    {"swedish": "numera", "english": "nowadays", "cefr": 1, "frequency": 97.08},
    {"swedish": "ännu", "english": "still", "cefr": 1, "frequency": None},
    {"swedish": "redan", "english": "already", "cefr": 1, "frequency": 533.67},
    {"swedish": "nyligen", "english": "recently", "cefr": 1, "frequency": 71.03},
    {"swedish": "därför att", "english": "because", "cefr": 1, "frequency": 93.55},
    {"swedish": "eftersom", "english": "since, because", "cefr": 1, "frequency": 652.00},
    {"swedish": "men", "english": "but", "cefr": 1, "frequency": 4545.97},
    {"swedish": "trots att", "english": "even though", "cefr": 1, "frequency": 156.41},
    {"swedish": "fastän", "english": "although", "cefr": 3, "frequency": 19.04},
    {"swedish": "dessutom", "english": "in addition", "cefr": 1, "frequency": 381.45},
    {"swedish": "för att", "english": "in order to", "cefr": 1, "frequency": 109.47},
    {"swedish": "tack vare", "english": "thanks to", "cefr": 2, "frequency": 50.23},
]
