misc = [
    {"swedish": "och", "english": "and"},
    {"swedish": "men", "english": "but"},
    {"swedish": "eller", "english": "or"},
    {"swedish": "eftersom", "english": "because"},
    {"swedish": "för att", "english": "in order to / because"},
    {"swedish": "så att", "english": "so that"},
    {"swedish": "så", "english": "so / then"},
    {"swedish": "därför", "english": "therefore"},
    {"swedish": "dock", "english": "however"},
    {"swedish": "också", "english": "also"},
    {"swedish": "bara", "english": "only / just"},
    {"swedish": "mycket", "english": "much / very"},
    {"swedish": "under", "english": "under / during"},
    {"swedish": "över", "english": "over / above"},
    {"swedish": "framför", "english": "in front of"},
    {"swedish": "bakom", "english": "behind"},
    {"swedish": "mellan", "english": "between"},
    {"swedish": "utan", "english": "without / but (after negative)"},
    {"swedish": "hos", "english": "at (someone’s place)"},
    {"swedish": "genom", "english": "through"},
    {"swedish": "innan", "english": "before"},
    {"swedish": "efter", "english": "after"},
    {"swedish": "på", "english": "on / at"},
    {"swedish": "i", "english": "in / inside"},
    {"swedish": "av", "english": "of / by"},
    {"swedish": "till", "english": "to / until"},
    {"swedish": "från", "english": "from"},
    {"swedish": "när", "english": "when"},
    {"swedish": "om", "english": "if / about"},
    {"swedish": "för", "english": "for / to"},
    {"swedish": "mot", "english": "against / toward"},
    {"swedish": "bland", "english": "among"},
    {"swedish": "trots", "english": "despite"},
    {"swedish": "redan", "english": "already"},
    {"swedish": "ännu", "english": "still / yet"},
    {"swedish": "aldrig", "english": "never"},
    {"swedish": "alltid", "english": "always"},
    {"swedish": "ofta", "english": "often"},
    {"swedish": "ibland", "english": "sometimes"},
    {"swedish": "snart", "english": "soon"},
    {"swedish": "kanske", "english": "maybe / perhaps"},
    {"swedish": "nästan", "english": "almost/next"},
    {"swedish": "fortfarande", "english": "still"},
    {"swedish": "här", "english": "here"},
    {"swedish": "där", "english": "there"},
    {"swedish": "hit", "english": "to here"},
    {"swedish": "dit", "english": "to there"},
    {"swedish": "hem", "english": "home (motion)"},
    {"swedish": "hemma", "english": "at home"},
    {"swedish": "borta", "english": "away / gone"},
    {"swedish": "inne", "english": "inside"},
    {"swedish": "ute", "english": "outside"},
    {"swedish": "finns", "english": "there is / there are"},
    {"swedish": "än", "english": "yet / than"},
    {"swedish": "igen", "english": "again"},
    {"swedish": "tillsammans", "english": "together"},
    {"swedish": "ensam", "english": "alone"},
    {"swedish": "däremot", "english": "on the other hand"},
    {"swedish": "dessutom", "english": "in addition / furthermore"},
    {"swedish": "fastän", "english": "although"},
    {"swedish": "även om", "english": "even though"},
    {"swedish": "således", "english": "thus"},
    {"swedish": "nämligen", "english": "namely / that is"},
    {"swedish": "till exempel", "english": "for example"},
    {"swedish": "alltså", "english": "so / that means"},
    {"swedish": "typ", "english": "like / kind of"},
    {"swedish": "ju", "english": "(as you know / indeed)"},
    {"swedish": "väl", "english": "surely / well"},
    {"swedish": "precis", "english": "exactly"},
    {"swedish": "liksom", "english": "like / sort of"},
    {"swedish": "nyss", "english": "just (recently)"},
    {"swedish": "nära", "english": "near"},
    {"swedish": "vanligt", "english": "usual"},
    {"swedish": "ovanligt", "english": "unusual"},
    {"swedish": "plötsligt", "english": "suddenly"},
    {"swedish": "lyckligtvis", "english": "luckily"},
    {"swedish": "särskilt", "english": "particularly/ especially"},
    {"swedish": "i närheten", "english": "nearby"},
    {"swedish": "illa", "english": "badly"},
    {"swedish": "senaste", "english": "recent/latest"},
    {"swedish": "istället", "english": "instead"},
    {"swedish": "vilket", "english": "which"},
    {"swedish": "både", "english": "both"},
    {"swedish": "fler", "english": "more"},
    {"swedish": "viktiga", "english": "important"},
    {"swedish": "samtidigt", "english": "simultaneously/at the same time"},
    {"swedish": "fler", "english": "next to"},
    {"swedish": "flera", "english": "several"},
    {"swedish": "nedan", "english": "below"}, #as in below on the page
    {"swedish": "endast", "english": "only"},
    {"swedish": "tidigare", "english": "previously" },
    {"swedish": "sådant", "english": "such"},
    {"swedish": "hela", "english": "whole/all"},
    {"swedish": "tidigt", "english": "early"},
    {"swedish": "någonstans", "english": "anywhere"},
    {"swedish": "för", "english": "too [adjective]"},
    {"swedish": "vanligtvis", "english": "usually"},
    {"swedish": "tillräckligt med", "english": "enough"},
    {"swedish": "förmodligen", "english": "probably"},
    {"swedish": "medan", "english": "while"},
    {"swedish": "varje", "english": "every/each"},
    {"swedish": "annan", "english": "other"},
    {"swedish": "imorse", "english": "this morning"},
    {"swedish": "del", "english": "part/portion"},
    {"swedish": "helt", "english": "completely"},
    {"swedish": "inom", "english": "within"},
    {"swedish": "fram", "english": "up/forward"},
    {"swedish": "enligt", "english": "according to"},
    {"swedish": "särskilt", "english": "particularly"},
    {"swedish": "utom", "english": "except"},
    # {"swedish": "", "english": ""},
]