misc = [
    {"swedish": "och", "english": "and", "cefr": 1, "frequency": 26019.68},
    {"swedish": "eller", "english": "or", "cefr": 1, "frequency": 3138.92},
    {"swedish": "så att", "english": "so that", "cefr": 1, "frequency": 400.31},
    {"swedish": "så", "english": "so / then", "cefr": 1, "frequency": 4004.97},
    {"swedish": "därför", "english": "therefore", "cefr": 1, "frequency": 461.58},
    {"swedish": "runt", "english": "around", "cefr": 1, "frequency": 203.50},
    {"swedish": "dock", "english": "however", "cefr": 1, "frequency": 614.54},
    {"swedish": "också", "english": "also", "cefr": 1, "frequency": 1797.39},
    {"swedish": "bara", "english": "only / just", "cefr": 1, "frequency": 1582.15},
    {"swedish": "mycket", "english": "much / very", "cefr": 1, "frequency": 3112.13},
    {"swedish": "under", "english": "under / during", "cefr": 1, "frequency": 1851.63},
    {"swedish": "över", "english": "over / above", "cefr": 1, "frequency": 1267.18},
    {"swedish": "framför", "english": "in front of", "cefr": 1, "frequency": 110.51},
    {"swedish": "bakom", "english": "behind", "cefr": 1, "frequency": 206.72},
    {"swedish": "mellan", "english": "between", "cefr": 1, "frequency": 841.51},
    {"swedish": "utan", "english": "without / but (after negative)", "cefr": 1, "frequency": 707.53},
    {"swedish": "hos", "english": "at (someone’s place)", "cefr": 1, "frequency": 453.15},
    {"swedish": "genom", "english": "through", "cefr": 1, "frequency": 733.74},
    {"swedish": "innan", "english": "before", "cefr": 1, "frequency": 429.65},
    {"swedish": "efter", "english": "after", "cefr": 1, "frequency": 1323.97},
    {"swedish": "på", "english": "on / at", "cefr": 1, "frequency": 12591.15},
    {"swedish": "i", "english": "in / inside", "cefr": 1, "frequency": 19272.89},
    {"swedish": "av", "english": "of / by", "cefr": 1, "frequency": 11540.13},
    {"swedish": "till", "english": "to / until", "cefr": 1, "frequency": 8662.68},
    {"swedish": "från", "english": "from", "cefr": 1, "frequency": 3117.46},
    {"swedish": "när", "english": "when", "cefr": 1, "frequency": 2386.89},
    {"swedish": "om", "english": "if / about", "cefr": 1, "frequency": 5278.24},
    {"swedish": "för", "english": "for / to", "cefr": 1, "frequency": 11408.82},
    {"swedish": "mot", "english": "against / toward", "cefr": 1, "frequency": 1592.42},
    {"swedish": "bland", "english": "among", "cefr": 1, "frequency": 282.47},
    {"swedish": "trots", "english": "despite", "cefr": 1, "frequency": 192.43},
    {"swedish": "snart", "english": "soon", "cefr": 1, "frequency": 199.90},
    {"swedish": "kanske", "english": "maybe / perhaps", "cefr": 1, "frequency": 809.75},
    {"swedish": "nästan", "english": "almost/next", "cefr": 1, "frequency": 284.00},
    {"swedish": "fortfarande", "english": "still", "cefr": 1, "frequency": 319.39},
    {"swedish": "här", "english": "here", "cefr": 1, "frequency": 1194.91},
    {"swedish": "där", "english": "there", "cefr": 1, "frequency": 1790.68},
    {"swedish": "hit", "english": "to here", "cefr": 1, "frequency": 78.19},
    {"swedish": "dit", "english": "to there", "cefr": 1, "frequency": 126.29},
    {"swedish": "hem", "english": "home (motion)", "cefr": 1, "frequency": 172.22},
    {"swedish": "hemma", "english": "at home", "cefr": 1, "frequency": 129.59},
    {"swedish": "borta", "english": "away / gone", "cefr": 1, "frequency": 66.14},
    {"swedish": "inne", "english": "inside", "cefr": 1, "frequency": 85.10},
    {"swedish": "ute", "english": "outside", "cefr": 1, "frequency": 167.61},
    {"swedish": "finns", "english": "there is / there are", "cefr": 1, "frequency": None},
    {"swedish": "än", "english": "yet / than", "cefr": 1, "frequency": 1428.89},
    {"swedish": "igen", "english": "again", "cefr": 1, "frequency": 321.76},
    {"swedish": "tillsammans", "english": "together", "cefr": 1, "frequency": 274.88},
    {"swedish": "ensam", "english": "alone", "cefr": 1, "frequency": 200.63},
    {"swedish": "däremot", "english": "on the other hand", "cefr": 1, "frequency": 194.90},
    {"swedish": "även om", "english": "even though", "cefr": 1, "frequency": 314.71},
    {"swedish": "således", "english": "thus", "cefr": 1, "frequency": 87.49},
    {"swedish": "nämligen", "english": "namely / that is", "cefr": 1, "frequency": 165.98},
    {"swedish": "till exempel", "english": "for example", "cefr": 1, "frequency": 274.97},
    {"swedish": "alltså", "english": "so / that means", "cefr": 1, "frequency": 419.06},
    {"swedish": "väl", "english": "surely / well", "cefr": 1, "frequency": 705.75},
    {"swedish": "precis", "english": "exactly", "cefr": 1, "frequency": 277.18},
    {"swedish": "liksom", "english": "like / sort of", "cefr": 1, "frequency": 174.75},
    {"swedish": "nyss", "english": "just (recently)", "cefr": 2, "frequency": 33.64},
    {"swedish": "nära", "english": "near", "cefr": 1, "frequency": 237.62},
    {"swedish": "vanligt", "english": "usual", "cefr": 2, "frequency": 23.67},
    {"swedish": "ovanligt", "english": "unusual", "cefr": 2, "frequency": 23.67},
    {"swedish": "plötsligt", "english": "suddenly", "cefr": 1, "frequency": 93.95},
    {"swedish": "lyckligtvis", "english": "luckily", "cefr": 1, "frequency": None},
    {"swedish": "särskilt", "english": "particularly/ especially", "cefr": 1, "frequency": 232.35},
    {"swedish": "i närheten", "english": "nearby", "cefr": 1, "frequency": None},
    {"swedish": "illa", "english": "badly", "cefr": 1, "frequency": 80.73},
    {"swedish": "senaste", "english": "recent/latest", "cefr": 1, "frequency": None},
    {"swedish": "istället", "english": "instead", "cefr": 1, "frequency": 291.38},
    {"swedish": "vilket", "english": "which", "cefr": 1, "frequency": None},
    {"swedish": "både", "english": "both", "cefr": 1, "frequency": 554.95},
    {"swedish": "fler", "english": "more", "cefr": 1, "frequency": 717.99},
    {"swedish": "viktig", "english": "important", "cefr": 1, "frequency": 662.11},
    {"swedish": "samtidigt", "english": "simultaneously/at the same time", "cefr": 1, "frequency": 247.54},
    {"swedish": "flera", "english": "several", "cefr": 1, "frequency": 94.49},
    {"swedish": "nedan", "english": "below", "cefr": 2, "frequency": 57.98},
    {"swedish": "endast", "english": "only", "cefr": 1, "frequency": 302.17},
    {"swedish": "sådant", "english": "such", "cefr": 1, "frequency": None},
    {"swedish": "hela", "english": "whole/all", "cefr": 1, "frequency": None},
    {"swedish": "tidigt", "english": "early", "cefr": 2, "frequency": 62.99},
    {"swedish": "någonstans", "english": "anywhere", "cefr": 2, "frequency": 62.31},
    {"swedish": "tillräckligt med", "english": "enough", "cefr": 1, "frequency": None},
    {"swedish": "förmodligen", "english": "probably", "cefr": 1, "frequency": 79.75},
    {"swedish": "medan", "english": "while", "cefr": 1, "frequency": 257.43},
    {"swedish": "varje", "english": "every/each", "cefr": 1, "frequency": 501.70},
    {"swedish": "annan", "english": "other", "cefr": 1, "frequency": 2624.20},
    {"swedish": "imorse", "english": "this morning", "cefr": 1, "frequency": None},
    {"swedish": "del", "english": "part/portion", "cefr": 1, "frequency": 1202.45},
    {"swedish": "helt", "english": "completely", "cefr": 1, "frequency": 721.67},
    {"swedish": "inom", "english": "within", "cefr": 1, "frequency": 758.15},
    {"swedish": "fram", "english": "up/forward", "cefr": 1, "frequency": 600.53},
    {"swedish": "enligt", "english": "according to", "cefr": 1, "frequency": 680.22},
    {"swedish": "utom", "english": "except", "cefr": 1, "frequency": 122.27},
    {"swedish": "sedan dess", "english": "since then", "cefr": 1, "frequency": None},
    {"swedish": "under tiden", "english": "in the meantime", "cefr": 1, "frequency": None},
    {"swedish": "däri", "english": "in that / therein", "cefr": 1, "frequency": None},
    {"swedish": "därmed", "english": "thereby / with that", "cefr": 1, "frequency": 206.58},
    {"swedish": "däreför", "english": "for that reason", "cefr": 1, "frequency": None},
    {"swedish": "dessförinnan", "english": "before that / previously", "cefr": 1, "frequency": None},
    {"swedish": "därefteråt", "english": "afterwards", "cefr": 1, "frequency": None},
    {"swedish": "först och främst", "english": "first and foremost", "cefr": 3, "frequency": 18.98},
    {"swedish": "slutligen", "english": "finally / ultimately", "cefr": 1, "frequency": 68.46},
    {"swedish": "sammanfattningsvis", "english": "in summary / to sum up", "cefr": 1, "frequency": None},
    {"swedish": "avslutningsvis", "english": "in conclusion", "cefr": 1, "frequency": None},
    {"swedish": "kort sagt", "english": "in short / briefly", "cefr": 1, "frequency": None},
    {"swedish": "å ena sidan", "english": "on one hand", "cefr": 1, "frequency": None},
    {"swedish": "å andra sidan", "english": "on the other hand", "cefr": 1, "frequency": None},
    {"swedish": "med andra ord", "english": "in other words", "cefr": 2, "frequency": 44.51},
    {"swedish": "i själva verket", "english": "in fact / actually", "cefr": 2, "frequency": 40.15},
    {"swedish": "verkligen", "english": "really / truly", "cefr": 1, "frequency": 321.76},
    {"swedish": "troligen", "english": "likely / probably", "cefr": 2, "frequency": 54.11},
    {"swedish": "antagligen", "english": "probably / presumably", "cefr": 2, "frequency": 52.05},
    {"swedish": "möjligen", "english": "possibly", "cefr": 2, "frequency": 49.17},
    {"swedish": "eventuellt", "english": "possibly / potentially", "cefr": 2, "frequency": 36.69},
    {"swedish": "sannolikt", "english": "likely", "cefr": 2, "frequency": 49.49},
    {"swedish": "för det mesta", "english": "for the most part / usually", "cefr": 1, "frequency": None},
    {"swedish": "i allmänhet", "english": "in general", "cefr": 2, "frequency": 46.20},
    {"swedish": "generellt sett", "english": "generally speaking", "cefr": 1, "frequency": None},
    {"swedish": "till viss del", "english": "to some extent", "cefr": 1, "frequency": None},
    {"swedish": "för det första", "english": "first of all", "cefr": 1, "frequency": None},
    {"swedish": "för det andra", "english": "secondly", "cefr": 1, "frequency": None},
    {"swedish": "för det tredje", "english": "thirdly", "cefr": 1, "frequency": None},
    {"swedish": "dels", "english": "partly / in part", "cefr": 1, "frequency": 148.09},
    {"swedish": "så småningom", "english": "eventually", "cefr": 2, "frequency": 40.70},
    {"swedish": "däremellan", "english": "in between", "cefr": 1, "frequency": None},
    {"swedish": "förutom att", "english": "besides / apart from", "cefr": 1, "frequency": None},
    {"swedish": "så länge", "english": "as long as", "cefr": 1, "frequency": None},
    {"swedish": "så snart", "english": "as soon as", "cefr": 1, "frequency": None},
    {"swedish": "innan dess", "english": "before that", "cefr": 1, "frequency": None},
    {"swedish": "därigenom", "english": "thereby / through that", "cefr": 2, "frequency": 32.50},
    {"swedish": "i stället för", "english": "instead of", "cefr": 1, "frequency": None},
    {"swedish": "utan att", "english": "without (doing something)", "cefr": 1, "frequency": None},
    {"swedish": "på grund av", "english": "because of / due to", "cefr": 1, "frequency": 229.03},
    {"swedish": "i synnerhet", "english": "especially / particularly", "cefr": 2, "frequency": 48.31},
    {"swedish": "bland annat", "english": "among other things", "cefr": 1, "frequency": 275.20},
    {"swedish": "till skillnad från", "english": "in contrast to / unlike", "cefr": 1, "frequency": None},
    {"swedish": "i jämförelse med", "english": "in comparison with", "cefr": 3, "frequency": 13.07},
    {"swedish": "jämfört med", "english": "compared with", "cefr": 1, "frequency": None},
    {"swedish": "förr eller senare", "english": "sooner or later", "cefr": 1, "frequency": None},
    {"swedish": "för närvarande", "english": "at present / currently", "cefr": 2, "frequency": 34.84},
    {"swedish": "nuförtiden", "english": "these days / nowadays", "cefr": 1, "frequency": None},
    {"swedish": "tidvis", "english": "at times / occasionally", "cefr": 1, "frequency": None},
    {"swedish": "emellanåt", "english": "now and then", "cefr": 1, "frequency": None},
    {"swedish": "vanligen", "english": "commonly / usually", "cefr": 3, "frequency": 20.88},
    {"swedish": "plötsligen", "english": "suddenly", "cefr": 1, "frequency": None},
    {"swedish": "dessvärre", "english": "unfortunately", "cefr": 3, "frequency": 21.51},
    {"swedish": "tyvärr", "english": "unfortunately", "cefr": 1, "frequency": 159.15},
    {"swedish": "förhoppningsvis", "english": "hopefully", "cefr": 2, "frequency": 41.58},
    {"swedish": "lyckligt nog", "english": "luckily enough", "cefr": 1, "frequency": None},
    {"swedish": "tvärtom", "english": "on the contrary", "cefr": 1, "frequency": 71.67},
    {"swedish": "därutöver", "english": "besides that / moreover", "cefr": 1, "frequency": None},
    {"swedish": "i tillägg", "english": "in addition", "cefr": 1, "frequency": None},
    {"swedish": "för övrigt", "english": "by the way / incidentally", "cefr": 1, "frequency": 70.76},
    {"swedish": "desslike", "english": "the like / of the same kind", "cefr": 1, "frequency": None},
    {"swedish": "utan vidare", "english": "without further ado", "cefr": 1, "frequency": None},
    {"swedish": "förresten", "english": "by the way", "cefr": 2, "frequency": 39.86},
    {"swedish": "kort därefter", "english": "shortly after", "cefr": 1, "frequency": None},
    {"swedish": "strax efter", "english": "just after", "cefr": 3, "frequency": 13.01},
    {"swedish": "strax före", "english": "just before", "cefr": 1, "frequency": None},
    {"swedish": "i samband med", "english": "in connection with", "cefr": 1, "frequency": 106.30},
    {"swedish": "med hjälp av", "english": "with the help of", "cefr": 1, "frequency": 71.84},
    {"swedish": "i fråga om", "english": "regarding / concerning", "cefr": 2, "frequency": 54.28},
    {"swedish": "beträffande", "english": "regarding / concerning", "cefr": 2, "frequency": 47.59},
    {"swedish": "angående", "english": "regarding / concerning", "cefr": 2, "frequency": 57.49},
    {"swedish": "på så sätt", "english": "in that way / thus", "cefr": 2, "frequency": 39.33},
    {"swedish": "på samma sätt", "english": "in the same way", "cefr": 1, "frequency": None},
    {"swedish": "till följd av", "english": "as a result of", "cefr": 2, "frequency": 34.39},
    {"swedish": "som ett resultat av", "english": "as a result of", "cefr": 1, "frequency": None},
    {"swedish": "med anledning av", "english": "due to / because of", "cefr": 2, "frequency": 28.44},
    {"swedish": "i och med", "english": "as a result of / in connection with", "cefr": 3, "frequency": 21.81},
    {"swedish": "så fort", "english": "as soon as", "cefr": 1, "frequency": None},
    {"swedish": "eftersom att", "english": "because (colloquial)", "cefr": 1, "frequency": None},
    {"swedish": "i alla fall", "english": "in any case / anyway", "cefr": 1, "frequency": 195.28},
    {"swedish": "hur som helst", "english": "anyhow / anyway", "cefr": 2, "frequency": 35.69},
    {"swedish": "på något sätt", "english": "somehow", "cefr": 1, "frequency": None},
    {"swedish": "på grund därav", "english": "because of that", "cefr": 1, "frequency": None},
    {"swedish": "för det syftet", "english": "for that purpose", "cefr": 1, "frequency": None},
    {"swedish": "till exempelvis", "english": "for example (formal)", "cefr": 1, "frequency": None},
    {"swedish": "i synnerhet när", "english": "especially when", "cefr": 1, "frequency": None},
    {"swedish": "särskilt om", "english": "especially if", "cefr": 1, "frequency": None},
    {"swedish": "för att inte tala om", "english": "not to mention", "cefr": 1, "frequency": None},
    {"swedish": "i likhet med", "english": "similar to", "cefr": 3, "frequency": 17.46},
    {"swedish": "till och med", "english": "even", "cefr": 1, "frequency": 139.70},
    {"swedish": "fram tills", "english": "until / up to", "cefr": 1, "frequency": None},
    {"swedish": "utan tvekan", "english": "without a doubt", "cefr": 1, "frequency": None},
    {"swedish": "av den anledningen", "english": "for that reason", "cefr": 1, "frequency": None},
    {"swedish": "såvitt jag vet", "english": "as far as I know", "cefr": 1, "frequency": None},
    {"swedish": "så länge som", "english": "as long as", "cefr": 1, "frequency": None},
    {"swedish": "allt eftersom", "english": "gradually / as", "cefr": 1, "frequency": None},
    {"swedish": "hellre än", "english": "rather than", "cefr": 1, "frequency": None},
]
