nouns = [
    {"indefinite": "kultur", "definite": "kulturen", "plural": "kulturer", "plural_definite": "kulturerna", "english": "culture"},
    {"indefinite": "tradition", "definite": "traditionen", "plural": "traditioner", "plural_definite": "traditionerna", "english": "tradition"},
    {"indefinite": "högtid", "definite": "högtiden", "plural": "högtider", "plural_definite": "högtiderna", "english": "holiday, festival"},
    {"indefinite": "konst", "definite": "konsten", "plural": "konster", "plural_definite": "konsterna", "english": "art"},
    {"indefinite": "målning", "definite": "målningen", "plural": "målningar", "plural_definite": "målningarna", "english": "painting"},
    {"indefinite": "konstnär", "definite": "konstnären", "plural": "konstnärer", "plural_definite": "konstnärerna", "english": "artist"},
    {"indefinite": "musiker", "definite": "musikern", "plural": "musiker", "plural_definite": "musikerna", "english": "musician"},
    {"indefinite": "sångare", "definite": "sångaren", "plural": "sångare", "plural_definite": "sångarna", "english": "singer"},
    {"indefinite": "dansare", "definite": "dansaren", "plural": "dansare", "plural_definite": "dansarna", "english": "dancer"},
    {"indefinite": "film", "definite": "filmen", "plural": "filmer", "plural_definite": "filmerna", "english": "movie"},
    {"indefinite": "teater", "definite": "teatern", "plural": "teatrar", "plural_definite": "teatrarna", "english": "theater"},
    {"indefinite": "pjäs", "definite": "pjäsen", "plural": "pjäser", "plural_definite": "pjäserna", "english": "play (theatre)"},
    {"indefinite": "museum", "definite": "museet", "plural": "museer", "plural_definite": "museerna", "english": "museum"},
    {"indefinite": "utställning", "definite": "utställningen", "plural": "utställningar", "plural_definite": "utställningarna", "english": "exhibition"},
    {"indefinite": "bok", "definite": "boken", "plural": "böcker", "plural_definite": "böckerna", "english": "book"},
    {"indefinite": "författare", "definite": "författaren", "plural": "författare", "plural_definite": "författarna", "english": "author"},
    {"indefinite": "tidning", "definite": "tidningen", "plural": "tidningar", "plural_definite": "tidningarna", "english": "newspaper"},
    {"indefinite": "artikel", "definite": "artikeln", "plural": "artiklar", "plural_definite": "artiklarna", "english": "article"},
    {"indefinite": "berättelse", "definite": "berättelsen", "plural": "berättelser", "plural_definite": "berättelserna", "english": "story"},
    {"indefinite": "historia", "definite": "historien", "plural": "historier", "plural_definite": "historierna", "english": "history, story"},
    {"indefinite": "språk", "definite": "språket", "plural": "språk", "plural_definite": "språken", "english": "language"},
    {"indefinite": "litteratur", "definite": "litteraturen", "plural": "litteraturer", "plural_definite": "litteraturerna", "english": "literature"},
    {"indefinite": "poesi", "definite": "poesin", "plural": "poesier", "plural_definite": "poesierna", "english": "poetry"},
    {"indefinite": "sång", "definite": "sången", "plural": "sånger", "plural_definite": "sångerna", "english": "song"},
    {"indefinite": "musik", "definite": "musiken", "plural": "musiker", "plural_definite": "musikerna", "english": "music"},
    {"indefinite": "instrument", "definite": "instrumentet", "plural": "instrument", "plural_definite": "instrumenten", "english": "instrument"},
    {"indefinite": "konsert", "definite": "konserten", "plural": "konserter", "plural_definite": "konserterna", "english": "concert"},
    {"indefinite": "festival", "definite": "festivalen", "plural": "festivaler", "plural_definite": "festivalerna", "english": "festival"},
    {"indefinite": "bio", "definite": "bion", "plural": "biografer", "plural_definite": "biograferna", "english": "cinema"},
    {"indefinite": "tv-program", "definite": "tv-programmet", "plural": "tv-program", "plural_definite": "tv-programmen", "english": "TV show"},
    {"indefinite": "serie", "definite": "serien", "plural": "serier", "plural_definite": "serierna", "english": "series"},
    {"indefinite": "skådespelare", "definite": "skådespelaren", "plural": "skådespelare", "plural_definite": "skådespelarna", "english": "actor"},
    {"indefinite": "publik", "definite": "publiken", "plural": "publiker", "plural_definite": "publikerna", "english": "audience"},
    {"indefinite": "scen", "definite": "scenen", "plural": "scener", "plural_definite": "scenerna", "english": "stage"},
    {"indefinite": "ljus", "definite": "ljuset", "plural": "ljus", "plural_definite": "ljusen", "english": "light"},
    {"indefinite": "färg", "definite": "färgen", "plural": "färger", "plural_definite": "färgerna", "english": "color"},
    {"indefinite": "känsla", "definite": "känslan", "plural": "känslor", "plural_definite": "känslorna", "english": "emotion"},
    {"indefinite": "upplevelse", "definite": "upplevelsen", "plural": "upplevelser", "plural_definite": "upplevelserna", "english": "experience"},
    {"indefinite": "minne", "definite": "minnet", "plural": "minnen", "plural_definite": "minnena", "english": "memory"},
    {"indefinite": "vän", "definite": "vännen", "plural": "vänner", "plural_definite": "vännerna", "english": "friend"},
    {"indefinite": "gemenskap", "definite": "gemenskapen", "plural": "gemenskaper", "plural_definite": "gemenskaperna", "english": "community"},
    {"indefinite": "förening", "definite": "föreningen", "plural": "föreningar", "plural_definite": "föreningarna", "english": "association"},
    {"indefinite": "evenemang", "definite": "evenemanget", "plural": "evenemang", "plural_definite": "evenemangen", "english": "event"},
    {"indefinite": "besökare", "definite": "besökaren", "plural": "besökare", "plural_definite": "besökarna", "english": "visitor"},
    {"indefinite": "publik", "definite": "publiken", "plural": "publiker", "plural_definite": "publikerna", "english": "audience"},
    {"indefinite": "inbjudan", "definite": "inbjudan", "plural": "inbjudningar", "plural_definite": "inbjudningarna", "english": "invitation"},
    {"indefinite": "fest", "definite": "festen", "plural": "fester", "plural_definite": "festerna", "english": "party"},
    {"indefinite": "present", "definite": "presenten", "plural": "presenter", "plural_definite": "presenterna", "english": "gift"},
    {"indefinite": "nationaldag", "definite": "nationaldagen", "plural": "nationaldagar", "plural_definite": "nationaldagarna", "english": "national day"},
    {"indefinite": "midsommar", "definite": "midsommaren", "plural": "midsomrar", "plural_definite": "midsomrarna", "english": "Midsummer"},
]

verbs = [
    {"infinitive": "sjunga", "present": "sjunger", "past": "sjöng", "supine": "sjungit", "english": "to sing"},
    {"infinitive": "dansa", "present": "dansar", "past": "dansade", "supine": "dansat", "english": "to dance"},
    {"infinitive": "måla", "present": "målar", "past": "målade", "supine": "målat", "english": "to paint"},
    {"infinitive": "rita", "present": "ritar", "past": "ritade", "supine": "ritat", "english": "to draw"},
    {"infinitive": "skriva", "present": "skriver", "past": "skrev", "supine": "skrivit", "english": "to write"},
    {"infinitive": "läsa", "present": "läser", "past": "läste", "supine": "läst", "english": "to read"},
    {"infinitive": "lyssna", "present": "lyssnar", "past": "lyssnade", "supine": "lyssnat", "english": "to listen"},
    {"infinitive": "titta", "present": "tittar", "past": "tittade", "supine": "tittat", "english": "to watch"},
    {"infinitive": "spela", "present": "spelar", "past": "spelade", "supine": "spelat", "english": "to play (instrument)"},
    {"infinitive": "delta", "present": "deltar", "past": "deltog", "supine": "deltagit", "english": "to participate"},
    {"infinitive": "besöka", "present": "besöker", "past": "besökte", "supine": "besökt", "english": "to visit"},
    {"infinitive": "fira", "present": "firar", "past": "firade", "supine": "firat", "english": "to celebrate"},
    {"infinitive": "uppträda", "present": "uppträder", "past": "uppträdde", "supine": "uppträtt", "english": "to perform"},
    {"infinitive": "fotografera", "present": "fotograferar", "past": "fotograferade", "supine": "fotograferat", "english": "to photograph"},
    {"infinitive": "diskutera", "present": "diskuterar", "past": "diskuterade", "supine": "diskuterat", "english": "to discuss"},
    {"infinitive": "inbjuda", "present": "inbjuder", "past": "inbjöd", "supine": "inbjudit", "english": "to invite"},
    {"infinitive": "ordna", "present": "ordnar", "past": "ordnade", "supine": "ordnat", "english": "to organize"},
    {"infinitive": "delta", "present": "deltar", "past": "deltog", "supine": "deltagit", "english": "to take part"},
    {"infinitive": "uppleva", "present": "upplever", "past": "upplevde", "supine": "upplevt", "english": "to experience"},
    {"infinitive": "skapa", "present": "skapar", "past": "skapade", "supine": "skapat", "english": "to create"},
]

misc = [
    {"swedish": "kulturell", "english": "cultural"},
    {"swedish": "konstnärlig", "english": "artistic"},
    {"swedish": "populär", "english": "popular"},
    {"swedish": "modern", "english": "modern"},
    {"swedish": "klassisk", "english": "classical"},
    {"swedish": "traditionell", "english": "traditional"},
    {"swedish": "spännande", "english": "exciting"},
    {"swedish": "intressant", "english": "interesting"},
    {"swedish": "tråkig", "english": "boring"},
    {"swedish": "rolig", "english": "fun"},
    {"swedish": "känd", "english": "famous"},
    {"swedish": "okänd", "english": "unknown"},
    {"swedish": "berömd", "english": "renowned"},
    {"swedish": "särskild", "english": "special"},
    {"swedish": "viktig", "english": "important"},
    {"swedish": "gemensam", "english": "shared, common"},
    {"swedish": "vanlig", "english": "usual, common"},
    {"swedish": "ovanlig", "english": "unusual"},
    {"swedish": "intresserad", "english": "interested"},
    {"swedish": "engagerad", "english": "engaged, involved"},
    {"swedish": "aktivt", "english": "actively"},
    {"swedish": "ofta", "english": "often"},
    {"swedish": "sällan", "english": "rarely"},
    {"swedish": "ibland", "english": "sometimes"},
    {"swedish": "nästan alltid", "english": "almost always"},
    {"swedish": "på grund av", "english": "because of"},
    {"swedish": "trots", "english": "despite"},
    {"swedish": "även om", "english": "even if"},
    {"swedish": "dessutom", "english": "in addition"},
    {"swedish": "slutligen", "english": "finally"},
]
