nouns = [
    {"indefinite": "högtid", "definite": "högtiden", "plural": "högtider", "plural_definite": "högtiderna", "english": "holiday, festival", "cefr": 1, "frequency": None},
    {"indefinite": "konst", "definite": "konsten", "plural": "konster", "plural_definite": "konsterna", "english": "art", "cefr": 1, "frequency": 77.53},
    {"indefinite": "målning", "definite": "målningen", "plural": "målningar", "plural_definite": "målningarna", "english": "painting", "cefr": 3, "frequency": 15.13},
    {"indefinite": "konstnär", "definite": "konstnären", "plural": "konstnärer", "plural_definite": "konstnärerna", "english": "artist", "cefr": 2, "frequency": 40.20},
    {"indefinite": "musiker", "definite": "musikern", "plural": "musiker", "plural_definite": "musikerna", "english": "musician", "cefr": 1, "frequency": None},
    {"indefinite": "sångare", "definite": "sångaren", "plural": "sångare", "plural_definite": "sångarna", "english": "singer", "cefr": 1, "frequency": None},
    {"indefinite": "dansare", "definite": "dansaren", "plural": "dansare", "plural_definite": "dansarna", "english": "dancer", "cefr": 1, "frequency": None},
    {"indefinite": "film", "definite": "filmen", "plural": "filmer", "plural_definite": "filmerna", "english": "movie", "cefr": 1, "frequency": 258.67},
    {"indefinite": "teater", "definite": "teatern", "plural": "teatrar", "plural_definite": "teatrarna", "english": "theater", "cefr": 3, "frequency": 22.82},
    {"indefinite": "pjäs", "definite": "pjäsen", "plural": "pjäser", "plural_definite": "pjäserna", "english": "play (theatre)", "cefr": 3, "frequency": 13.00},
    {"indefinite": "museum", "definite": "museet", "plural": "museer", "plural_definite": "museerna", "english": "museum", "cefr": 2, "frequency": 35.28},
    {"indefinite": "utställning", "definite": "utställningen", "plural": "utställningar", "plural_definite": "utställningarna", "english": "exhibition", "cefr": 2, "frequency": 34.11},
    {"indefinite": "bok", "definite": "boken", "plural": "böcker", "plural_definite": "böckerna", "english": "book", "cefr": 1, "frequency": 478.59},
    {"indefinite": "författare", "definite": "författaren", "plural": "författare", "plural_definite": "författarna", "english": "author", "cefr": 1, "frequency": 133.87},
    {"indefinite": "tidning", "definite": "tidningen", "plural": "tidningar", "plural_definite": "tidningarna", "english": "newspaper", "cefr": 1, "frequency": 191.91},
    {"indefinite": "artikel", "definite": "artikeln", "plural": "artiklar", "plural_definite": "artiklarna", "english": "article", "cefr": 1, "frequency": 501.28},
    {"indefinite": "berättelse", "definite": "berättelsen", "plural": "berättelser", "plural_definite": "berättelserna", "english": "story", "cefr": 1, "frequency": 78.05},
    {"indefinite": "historia", "definite": "historien", "plural": "historier", "plural_definite": "historierna", "english": "history, story", "cefr": 1, "frequency": 267.25},
    {"indefinite": "litteratur", "definite": "litteraturen", "plural": "litteraturer", "plural_definite": "litteraturerna", "english": "literature", "cefr": 2, "frequency": 57.85},
    {"indefinite": "poesi", "definite": "poesin", "plural": "poesier", "plural_definite": "poesierna", "english": "poetry", "cefr": 3, "frequency": 14.28},
    {"indefinite": "sång", "definite": "sången", "plural": "sånger", "plural_definite": "sångerna", "english": "song", "cefr": 2, "frequency": 43.18},
    {"indefinite": "musik", "definite": "musiken", "plural": "musiker", "plural_definite": "musikerna", "english": "music", "cefr": 1, "frequency": 185.07},
    {"indefinite": "instrument", "definite": "instrumentet", "plural": "instrument", "plural_definite": "instrumenten", "english": "instrument", "cefr": 2, "frequency": 37.17},
    {"indefinite": "konsert", "definite": "konserten", "plural": "konserter", "plural_definite": "konserterna", "english": "concert", "cefr": 3, "frequency": 23.52},
    {"indefinite": "festival", "definite": "festivalen", "plural": "festivaler", "plural_definite": "festivalerna", "english": "festival", "cefr": 3, "frequency": 14.90},
    {"indefinite": "bio", "definite": "bion", "plural": "biografer", "plural_definite": "biograferna", "english": "cinema", "cefr": 1, "frequency": None},
    {"indefinite": "tv-program", "definite": "tv-programmet", "plural": "tv-program", "plural_definite": "tv-programmen", "english": "TV show", "cefr": 1, "frequency": None},
    {"indefinite": "serie", "definite": "serien", "plural": "serier", "plural_definite": "serierna", "english": "series", "cefr": 1, "frequency": 70.44},
    {"indefinite": "skådespelare", "definite": "skådespelaren", "plural": "skådespelare", "plural_definite": "skådespelarna", "english": "actor", "cefr": 3, "frequency": 18.51},
    {"indefinite": "publik", "definite": "publiken", "plural": "publiker", "plural_definite": "publikerna", "english": "audience", "cefr": 2, "frequency": 58.71},
    {"indefinite": "scen", "definite": "scenen", "plural": "scener", "plural_definite": "scenerna", "english": "stage", "cefr": 2, "frequency": 55.67},
    {"indefinite": "ljus", "definite": "ljuset", "plural": "ljus", "plural_definite": "ljusen", "english": "light", "cefr": 1, "frequency": 84.31},
    {"indefinite": "färg", "definite": "färgen", "plural": "färger", "plural_definite": "färgerna", "english": "color", "cefr": 1, "frequency": 74.81},
    {"indefinite": "känsla", "definite": "känslan", "plural": "känslor", "plural_definite": "känslorna", "english": "emotion", "cefr": 1, "frequency": 159.45},
    {"indefinite": "upplevelse", "definite": "upplevelsen", "plural": "upplevelser", "plural_definite": "upplevelserna", "english": "experience", "cefr": 2, "frequency": 62.97},
    {"indefinite": "minne", "definite": "minnet", "plural": "minnen", "plural_definite": "minnena", "english": "memory", "cefr": 1, "frequency": 75.11},
    {"indefinite": "gemenskap", "definite": "gemenskapen", "plural": "gemenskaper", "plural_definite": "gemenskaperna", "english": "community", "cefr": 1, "frequency": 87.17},
    {"indefinite": "förening", "definite": "föreningen", "plural": "föreningar", "plural_definite": "föreningarna", "english": "association", "cefr": 1, "frequency": 87.48},
    {"indefinite": "evenemang", "definite": "evenemanget", "plural": "evenemang", "plural_definite": "evenemangen", "english": "event", "cefr": 1, "frequency": None},
    {"indefinite": "besökare", "definite": "besökaren", "plural": "besökare", "plural_definite": "besökarna", "english": "visitor", "cefr": 2, "frequency": 34.03},
    {"indefinite": "inbjudan", "definite": "inbjudan", "plural": "inbjudningar", "plural_definite": "inbjudningarna", "english": "invitation", "cefr": 1, "frequency": None},
    {"indefinite": "fest", "definite": "festen", "plural": "fester", "plural_definite": "festerna", "english": "party", "cefr": 2, "frequency": 38.12},
    {"indefinite": "present", "definite": "presenten", "plural": "presenter", "plural_definite": "presenterna", "english": "gift", "cefr": 3, "frequency": 15.71},
    {"indefinite": "nationaldag", "definite": "nationaldagen", "plural": "nationaldagar", "plural_definite": "nationaldagarna", "english": "national day", "cefr": 1, "frequency": None},
    {"indefinite": "midsommar", "definite": "midsommaren", "plural": "midsomrar", "plural_definite": "midsomrarna", "english": "Midsummer", "cefr": 1, "frequency": None},
]

verbs = [
    {"infinitive": "sjunga", "present": "sjunger", "past": "sjöng", "supine": "sjungit", "english": "to sing", "cefr": 2, "frequency": 59.53},
    {"infinitive": "dansa", "present": "dansar", "past": "dansade", "supine": "dansat", "english": "to dance", "cefr": 2, "frequency": 25.41},
    {"infinitive": "måla", "present": "målar", "past": "målade", "supine": "målat", "english": "to paint", "cefr": 2, "frequency": 37.96},
    {"infinitive": "rita", "present": "ritar", "past": "ritade", "supine": "ritat", "english": "to draw", "cefr": 3, "frequency": 19.01},
    {"infinitive": "läsa", "present": "läser", "past": "läste", "supine": "läst", "english": "to read", "cefr": 1, "frequency": 823.05},
    {"infinitive": "lyssna", "present": "lyssnar", "past": "lyssnade", "supine": "lyssnat", "english": "to listen", "cefr": 1, "frequency": 152.94},
    {"infinitive": "titta", "present": "tittar", "past": "tittade", "supine": "tittat", "english": "to watch", "cefr": 1, "frequency": 195.79},
    {"infinitive": "spela", "present": "spelar", "past": "spelade", "supine": "spelat", "english": "to play (instrument)", "cefr": 1, "frequency": 401.87},
    {"infinitive": "besöka", "present": "besöker", "past": "besökte", "supine": "besökt", "english": "to visit", "cefr": 1, "frequency": 92.36},
    {"infinitive": "fira", "present": "firar", "past": "firade", "supine": "firat", "english": "to celebrate", "cefr": 2, "frequency": 56.93},
    {"infinitive": "uppträda", "present": "uppträder", "past": "uppträdde", "supine": "uppträtt", "english": "to perform", "cefr": 2, "frequency": 27.94},
    {"infinitive": "fotografera", "present": "fotograferar", "past": "fotograferade", "supine": "fotograferat", "english": "to photograph", "cefr": 3, "frequency": 13.54},
    {"infinitive": "diskutera", "present": "diskuterar", "past": "diskuterade", "supine": "diskuterat", "english": "to discuss", "cefr": 1, "frequency": 183.54},
    {"infinitive": "inbjuda", "present": "inbjuder", "past": "inbjöd", "supine": "inbjudit", "english": "to invite", "cefr": 1, "frequency": None},
    {"infinitive": "ordna", "present": "ordnar", "past": "ordnade", "supine": "ordnat", "english": "to organize", "cefr": 2, "frequency": 43.33},
    {"infinitive": "uppleva", "present": "upplever", "past": "upplevde", "supine": "upplevt", "english": "to experience", "cefr": 1, "frequency": 118.65},
    {"infinitive": "skapa", "present": "skapar", "past": "skapade", "supine": "skapat", "english": "to create", "cefr": 1, "frequency": 445.51},
]

misc = [
    {"swedish": "kulturell", "english": "cultural", "cefr": 2, "frequency": 53.02},
    {"swedish": "konstnärlig", "english": "artistic", "cefr": 3, "frequency": 16.81},
    {"swedish": "populär", "english": "popular", "cefr": 2, "frequency": 56.93},
    {"swedish": "modern", "english": "modern", "cefr": 1, "frequency": 127.04},
    {"swedish": "klassisk", "english": "classical", "cefr": 2, "frequency": 56.38},
    {"swedish": "traditionell", "english": "traditional", "cefr": 1, "frequency": 69.22},
    {"swedish": "spännande", "english": "exciting", "cefr": 1, "frequency": 81.20},
    {"swedish": "intressant", "english": "interesting", "cefr": 1, "frequency": 272.16},
    {"swedish": "tråkig", "english": "boring", "cefr": 2, "frequency": 47.67},
    {"swedish": "känd", "english": "famous", "cefr": 1, "frequency": 140.65},
    {"swedish": "okänd", "english": "unknown", "cefr": 2, "frequency": 40.81},
    {"swedish": "berömd", "english": "renowned", "cefr": 1, "frequency": None},
    {"swedish": "särskild", "english": "special", "cefr": 1, "frequency": 177.43},
    {"swedish": "gemensam", "english": "shared, common", "cefr": 1, "frequency": 189.45},
    {"swedish": "vanlig", "english": "usual, common", "cefr": 1, "frequency": 265.84},
    {"swedish": "ovanlig", "english": "unusual", "cefr": 2, "frequency": 29.84},
    {"swedish": "intresserad", "english": "interested", "cefr": 1, "frequency": 93.21},
    {"swedish": "engagerad", "english": "engaged, involved", "cefr": 1, "frequency": None},
    {"swedish": "aktivt", "english": "actively", "cefr": 2, "frequency": 35.10},
    {"swedish": "nästan alltid", "english": "almost always", "cefr": 1, "frequency": None},
]
