nouns = [
    {"indefinite": "miljö", "definite": "miljön", "plural": "miljöer", "plural_definite": "miljöerna", "english": "environment", "cefr": 1, "frequency": 120.16},
    {"indefinite": "natur", "definite": "naturen", "plural": "naturer", "plural_definite": "naturerna", "english": "nature", "cefr": 1, "frequency": 110.01},
    {"indefinite": "skog", "definite": "skogen", "plural": "skogar", "plural_definite": "skogarna", "english": "forest", "cefr": 1, "frequency": 76.52},
    {"indefinite": "träd", "definite": "trädet", "plural": "träd", "plural_definite": "träden", "english": "tree", "cefr": 2, "frequency": 45.68},
    {"indefinite": "växt", "definite": "växten", "plural": "växter", "plural_definite": "växterna", "english": "plant", "cefr": 1, "frequency": 107.37},
    {"indefinite": "blomma", "definite": "blomman", "plural": "blommor", "plural_definite": "blommorna", "english": "flower", "cefr": 2, "frequency": 27.10},
    {"indefinite": "djur", "definite": "djuret", "plural": "djur", "plural_definite": "djuren", "english": "animal", "cefr": 1, "frequency": 108.73},
    {"indefinite": "hav", "definite": "havet", "plural": "hav", "plural_definite": "haven", "english": "sea", "cefr": 1, "frequency": 82.66},
    {"indefinite": "sjö", "definite": "sjön", "plural": "sjöar", "plural_definite": "sjöarna", "english": "lake", "cefr": 2, "frequency": 40.70},
    {"indefinite": "flod", "definite": "floden", "plural": "floder", "plural_definite": "floderna", "english": "river", "cefr": 2, "frequency": 34.29},
    {"indefinite": "berg", "definite": "berget", "plural": "berg", "plural_definite": "bergen", "english": "mountain", "cefr": 2, "frequency": 51.57},
    {"indefinite": "luft", "definite": "luften", "plural": "lufter", "plural_definite": "lufterna", "english": "air", "cefr": 2, "frequency": 61.33},
    {"indefinite": "vatten", "definite": "vattnet", "plural": "vatten", "plural_definite": "vattnen", "english": "water", "cefr": 1, "frequency": 161.30},
    {"indefinite": "mark", "definite": "marken", "plural": "marker", "plural_definite": "markerna", "english": "land, soil", "cefr": 1, "frequency": 105.63},
    {"indefinite": "jord", "definite": "jorden", "plural": "jordar", "plural_definite": "jordarna", "english": "earth, soil", "cefr": 1, "frequency": 159.88},
    {"indefinite": "väder", "definite": "vädret", "plural": "väder", "plural_definite": "vädren", "english": "weather", "cefr": 2, "frequency": 48.25},
    {"indefinite": "klimat", "definite": "klimatet", "plural": "klimat", "plural_definite": "klimaten", "english": "climate", "cefr": 2, "frequency": 54.24},
    {"indefinite": "temperatur", "definite": "temperaturen", "plural": "temperaturer", "plural_definite": "temperaturerna", "english": "temperature", "cefr": 2, "frequency": 28.99},
    {"indefinite": "avfall", "definite": "avfallet", "plural": "avfall", "plural_definite": "avfallen", "english": "waste", "cefr": 3, "frequency": 20.30},
    {"indefinite": "sopor", "definite": "soporna", "plural": "sopor", "plural_definite": "soporna", "english": "garbage", "cefr": 1, "frequency": None},
    {"indefinite": "återvinning", "definite": "återvinningen", "plural": "återvinningar", "plural_definite": "återvinningarna", "english": "recycling", "cefr": 1, "frequency": None},
    {"indefinite": "energi", "definite": "energin", "plural": "energier", "plural_definite": "energierna", "english": "energy", "cefr": 1, "frequency": 82.37},
    {"indefinite": "el", "definite": "elen", "plural": "elar", "plural_definite": "elarna", "english": "electricity", "cefr": 1, "frequency": 925.85},
    {"indefinite": "ström", "definite": "strömmen", "plural": "strömmar", "plural_definite": "strömmarna", "english": "current, power", "cefr": 3, "frequency": 21.03},
    {"indefinite": "bränsle", "definite": "bränslet", "plural": "bränslen", "plural_definite": "bränslena", "english": "fuel", "cefr": 3, "frequency": 21.40},
    {"indefinite": "bensin", "definite": "bensinen", "plural": "bensiner", "plural_definite": "bensinerna", "english": "gasoline", "cefr": 1, "frequency": None},
    {"indefinite": "olja", "definite": "oljan", "plural": "oljor", "plural_definite": "oljorna", "english": "oil", "cefr": 2, "frequency": 40.38},
    {"indefinite": "förorening", "definite": "föroreningen", "plural": "föroreningar", "plural_definite": "föroreningarna", "english": "pollution", "cefr": 1, "frequency": None},
    {"indefinite": "utsläpp", "definite": "utsläppet", "plural": "utsläpp", "plural_definite": "utsläppen", "english": "emission", "cefr": 2, "frequency": 38.92},
    {"indefinite": "växthusgas", "definite": "växthusgasen", "plural": "växthusgaser", "plural_definite": "växthusgaserna", "english": "greenhouse gas", "cefr": 1, "frequency": None},
    {"indefinite": "klimatförändring", "definite": "klimatförändringen", "plural": "klimatförändringar", "plural_definite": "klimatförändringarna", "english": "climate change", "cefr": 3, "frequency": 22.16},
    {"indefinite": "resurs", "definite": "resursen", "plural": "resurser", "plural_definite": "resurserna", "english": "resource", "cefr": 1, "frequency": 115.04},
    {"indefinite": "plastsäck", "definite": "plastsäcken", "plural": "plastsäckar", "plural_definite": "plastsäckarna", "english": "plastic bag", "cefr": 1, "frequency": None},
    {"indefinite": "cykel", "definite": "cykeln", "plural": "cyklar", "plural_definite": "cyklarna", "english": "bicycle", "cefr": 2, "frequency": 28.46},
    {"indefinite": "kollektivtrafik", "definite": "kollektivtrafiken", "plural": "kollektivtrafiker", "plural_definite": "kollektivtrafikerna", "english": "public transport", "cefr": 3, "frequency": 11.89},
    {"indefinite": "bil", "definite": "bilen", "plural": "bilar", "plural_definite": "bilarna", "english": "car", "cefr": 1, "frequency": 186.44},
    {"indefinite": "buss", "definite": "bussen", "plural": "bussar", "plural_definite": "bussarna", "english": "bus", "cefr": 2, "frequency": 52.35},
    {"indefinite": "tåg", "definite": "tåget", "plural": "tåg", "plural_definite": "tågen", "english": "train", "cefr": 2, "frequency": 61.07},
    {"indefinite": "naturresurs", "definite": "naturresursen", "plural": "naturresurser", "plural_definite": "naturresurserna", "english": "natural resource", "cefr": 1, "frequency": None},
    {"indefinite": "återanvändning", "definite": "återanvändningen", "plural": "återanvändningar", "plural_definite": "återanvändningarna", "english": "reuse", "cefr": 1, "frequency": None},
    {"indefinite": "koldioxid", "definite": "koldioxiden", "plural": "koldioxider", "plural_definite": "koldioxiderna", "english": "carbon dioxide", "cefr": 3, "frequency": 18.08},
    {"indefinite": "vindkraft", "definite": "vindkraften", "plural": "vindkrafter", "plural_definite": "vindkrafterna", "english": "wind power", "cefr": 1, "frequency": None},
    {"indefinite": "solenergi", "definite": "solenergin", "plural": "solenergier", "plural_definite": "solenergierna", "english": "solar energy", "cefr": 1, "frequency": None},
    {"indefinite": "återvinningsstation", "definite": "återvinningsstationen", "plural": "återvinningsstationer", "plural_definite": "återvinningsstationerna", "english": "recycling station", "cefr": 1, "frequency": None},
    {"indefinite": "samhälle", "definite": "samhället", "plural": "samhällen", "plural_definite": "samhällena", "english": "society", "cefr": 1, "frequency": 420.38},
    {"indefinite": "framtid", "definite": "framtiden", "plural": "framtider", "plural_definite": "framtiderna", "english": "future", "cefr": 1, "frequency": 203.16},
    {"indefinite": "ansvar", "definite": "ansvaret", "plural": "ansvar", "plural_definite": "ansvaren", "english": "responsibility", "cefr": 1, "frequency": 213.48},
    {"indefinite": "lösning", "definite": "lösningen", "plural": "lösningar", "plural_definite": "lösningarna", "english": "solution", "cefr": 1, "frequency": 144.58},
    {"indefinite": "problem", "definite": "problemet", "plural": "problem", "plural_definite": "problemen", "english": "problem", "cefr": 1, "frequency": 520.62},
    {"indefinite": "hot", "definite": "hotet", "plural": "hot", "plural_definite": "hoten", "english": "threat", "cefr": 1, "frequency": 104.27},
]

verbs = [
    {"infinitive": "återvinna", "present": "återvinner", "past": "återvann", "supine": "återvunnit", "english": "to recycle", "cefr": 1, "frequency": None},
    {"infinitive": "återanvända", "present": "återanvänder", "past": "återanvände", "supine": "återanvänt", "english": "to reuse", "cefr": 1, "frequency": None},
    {"infinitive": "sortera", "present": "sorterar", "past": "sorterade", "supine": "sorterat", "english": "to sort", "cefr": 3, "frequency": 11.95},
    {"infinitive": "minska", "present": "minskar", "past": "minskade", "supine": "minskat", "english": "to reduce", "cefr": 1, "frequency": 195.42},
    {"infinitive": "öka", "present": "ökar", "past": "ökade", "supine": "ökat", "english": "to increase", "cefr": 1, "frequency": 462.83},
    {"infinitive": "spara", "present": "sparar", "past": "sparade", "supine": "sparat", "english": "to save", "cefr": 1, "frequency": 68.81},
    {"infinitive": "förbruka", "present": "förbrukar", "past": "förbrukade", "supine": "förbrukat", "english": "to consume", "cefr": 1, "frequency": None},
    {"infinitive": "förstöra", "present": "förstör", "past": "förstörde", "supine": "förstört", "english": "to destroy", "cefr": 2, "frequency": 61.58},
    {"infinitive": "påverka", "present": "påverkar", "past": "påverkade", "supine": "påverkat", "english": "to affect", "cefr": 1, "frequency": 196.40},
    {"infinitive": "skydda", "present": "skyddar", "past": "skyddade", "supine": "skyddat", "english": "to protect", "cefr": 1, "frequency": 88.30},
    {"infinitive": "plantera", "present": "planterar", "past": "planterade", "supine": "planterat", "english": "to plant", "cefr": 1, "frequency": None},
    {"infinitive": "rensa", "present": "rensar", "past": "rensade", "supine": "rensat", "english": "to clean up", "cefr": 3, "frequency": 16.00},
    {"infinitive": "bränna", "present": "bränner", "past": "brände", "supine": "bränt", "english": "to burn", "cefr": 2, "frequency": 30.94},
    {"infinitive": "förorena", "present": "förorenar", "past": "förorenade", "supine": "förorenat", "english": "to pollute", "cefr": 1, "frequency": None},
    {"infinitive": "förändra", "present": "förändrar", "past": "förändrade", "supine": "förändrat", "english": "to change", "cefr": 1, "frequency": 121.43},
    {"infinitive": "utveckla", "present": "utvecklar", "past": "utvecklade", "supine": "utvecklat", "english": "to develop", "cefr": 1, "frequency": 241.91},
    {"infinitive": "påminna", "present": "påminner", "past": "påminde", "supine": "påmint", "english": "to remind", "cefr": 2, "frequency": 56.57},
    {"infinitive": "ansvara", "present": "ansvarar", "past": "ansvarade", "supine": "ansvarat", "english": "to be responsible", "cefr": 2, "frequency": 26.59},
    {"infinitive": "förbättra", "present": "förbättrar", "past": "förbättrade", "supine": "förbättrat", "english": "to improve", "cefr": 1, "frequency": 95.10},
]

misc = [
    {"swedish": "miljövänlig", "english": "environmentally friendly", "cefr": 3, "frequency": 13.28},
    {"swedish": "hållbar", "english": "sustainable", "cefr": 2, "frequency": 55.61},
    {"swedish": "grön", "english": "green", "cefr": 1, "frequency": 77.31},
    {"swedish": "ren", "english": "clean", "cefr": 1, "frequency": 114.14},
    {"swedish": "smutsig", "english": "dirty", "cefr": 3, "frequency": 12.25},
    {"swedish": "naturlig", "english": "natural", "cefr": 1, "frequency": 93.87},
    {"swedish": "farlig", "english": "dangerous", "cefr": 1, "frequency": 73.07},
    {"swedish": "sund", "english": "healthy", "cefr": 2, "frequency": 31.91},
    {"swedish": "ekologisk", "english": "organic", "cefr": 2, "frequency": 26.08},
    {"swedish": "förnybar", "english": "renewable", "cefr": 1, "frequency": None},
    {"swedish": "global", "english": "global", "cefr": 1, "frequency": 95.78},
    {"swedish": "lokal", "english": "local", "cefr": 1, "frequency": 132.16},
    {"swedish": "nödvändig", "english": "necessary", "cefr": 1, "frequency": 133.42},
    {"swedish": "billig", "english": "cheap", "cefr": 1, "frequency": 73.02},
    {"swedish": "dyr", "english": "expensive", "cefr": 1, "frequency": 63.35},
    {"swedish": "ansvarsfullt", "english": "responsibly", "cefr": 1, "frequency": None},
]
