nouns = [
    {"indefinite": "miljö", "definite": "miljön", "plural": "miljöer", "plural_definite": "miljöerna", "english": "environment"},
    {"indefinite": "natur", "definite": "naturen", "plural": "naturer", "plural_definite": "naturerna", "english": "nature"},
    {"indefinite": "skog", "definite": "skogen", "plural": "skogar", "plural_definite": "skogarna", "english": "forest"},
    {"indefinite": "träd", "definite": "trädet", "plural": "träd", "plural_definite": "träden", "english": "tree"},
    {"indefinite": "växt", "definite": "växten", "plural": "växter", "plural_definite": "växterna", "english": "plant"},
    {"indefinite": "blomma", "definite": "blomman", "plural": "blommor", "plural_definite": "blommorna", "english": "flower"},
    {"indefinite": "djur", "definite": "djuret", "plural": "djur", "plural_definite": "djuren", "english": "animal"},
    {"indefinite": "hav", "definite": "havet", "plural": "hav", "plural_definite": "haven", "english": "sea"},
    {"indefinite": "sjö", "definite": "sjön", "plural": "sjöar", "plural_definite": "sjöarna", "english": "lake"},
    {"indefinite": "flod", "definite": "floden", "plural": "floder", "plural_definite": "floderna", "english": "river"},
    {"indefinite": "berg", "definite": "berget", "plural": "berg", "plural_definite": "bergen", "english": "mountain"},
    {"indefinite": "luft", "definite": "luften", "plural": "lufter", "plural_definite": "lufterna", "english": "air"},
    {"indefinite": "vatten", "definite": "vattnet", "plural": "vatten", "plural_definite": "vattnen", "english": "water"},
    {"indefinite": "mark", "definite": "marken", "plural": "marker", "plural_definite": "markerna", "english": "land, soil"},
    {"indefinite": "jord", "definite": "jorden", "plural": "jordar", "plural_definite": "jordarna", "english": "earth, soil"},
    {"indefinite": "väder", "definite": "vädret", "plural": "väder", "plural_definite": "vädren", "english": "weather"},
    {"indefinite": "klimat", "definite": "klimatet", "plural": "klimat", "plural_definite": "klimaten", "english": "climate"},
    {"indefinite": "temperatur", "definite": "temperaturen", "plural": "temperaturer", "plural_definite": "temperaturerna", "english": "temperature"},
    {"indefinite": "avfall", "definite": "avfallet", "plural": "avfall", "plural_definite": "avfallen", "english": "waste"},
    {"indefinite": "sopor", "definite": "soporna", "plural": "sopor", "plural_definite": "soporna", "english": "garbage"},
    {"indefinite": "återvinning", "definite": "återvinningen", "plural": "återvinningar", "plural_definite": "återvinningarna", "english": "recycling"},
    {"indefinite": "energi", "definite": "energin", "plural": "energier", "plural_definite": "energierna", "english": "energy"},
    {"indefinite": "el", "definite": "elen", "plural": "elar", "plural_definite": "elarna", "english": "electricity"},
    {"indefinite": "ström", "definite": "strömmen", "plural": "strömmar", "plural_definite": "strömmarna", "english": "current, power"},
    {"indefinite": "bränsle", "definite": "bränslet", "plural": "bränslen", "plural_definite": "bränslena", "english": "fuel"},
    {"indefinite": "bensin", "definite": "bensinen", "plural": "bensiner", "plural_definite": "bensinerna", "english": "gasoline"},
    {"indefinite": "olja", "definite": "oljan", "plural": "oljor", "plural_definite": "oljorna", "english": "oil"},
    {"indefinite": "förorening", "definite": "föroreningen", "plural": "föroreningar", "plural_definite": "föroreningarna", "english": "pollution"},
    {"indefinite": "utsläpp", "definite": "utsläppet", "plural": "utsläpp", "plural_definite": "utsläppen", "english": "emission"},
    {"indefinite": "växthusgas", "definite": "växthusgasen", "plural": "växthusgaser", "plural_definite": "växthusgaserna", "english": "greenhouse gas"},
    {"indefinite": "klimatförändring", "definite": "klimatförändringen", "plural": "klimatförändringar", "plural_definite": "klimatförändringarna", "english": "climate change"},
    {"indefinite": "resurs", "definite": "resursen", "plural": "resurser", "plural_definite": "resurserna", "english": "resource"},
    {"indefinite": "plastsäck", "definite": "plastsäcken", "plural": "plastsäckar", "plural_definite": "plastsäckarna", "english": "plastic bag"},
    {"indefinite": "cykel", "definite": "cykeln", "plural": "cyklar", "plural_definite": "cyklarna", "english": "bicycle"},
    {"indefinite": "kollektivtrafik", "definite": "kollektivtrafiken", "plural": "kollektivtrafiker", "plural_definite": "kollektivtrafikerna", "english": "public transport"},
    {"indefinite": "bil", "definite": "bilen", "plural": "bilar", "plural_definite": "bilarna", "english": "car"},
    {"indefinite": "buss", "definite": "bussen", "plural": "bussar", "plural_definite": "bussarna", "english": "bus"},
    {"indefinite": "tåg", "definite": "tåget", "plural": "tåg", "plural_definite": "tågen", "english": "train"},
    {"indefinite": "naturresurs", "definite": "naturresursen", "plural": "naturresurser", "plural_definite": "naturresurserna", "english": "natural resource"},
    {"indefinite": "återanvändning", "definite": "återanvändningen", "plural": "återanvändningar", "plural_definite": "återanvändningarna", "english": "reuse"},
    {"indefinite": "koldioxid", "definite": "koldioxiden", "plural": "koldioxider", "plural_definite": "koldioxiderna", "english": "carbon dioxide"},
    {"indefinite": "vindkraft", "definite": "vindkraften", "plural": "vindkrafter", "plural_definite": "vindkrafterna", "english": "wind power"},
    {"indefinite": "solenergi", "definite": "solenergin", "plural": "solenergier", "plural_definite": "solenergierna", "english": "solar energy"},
    {"indefinite": "återvinningsstation", "definite": "återvinningsstationen", "plural": "återvinningsstationer", "plural_definite": "återvinningsstationerna", "english": "recycling station"},
    {"indefinite": "samhälle", "definite": "samhället", "plural": "samhällen", "plural_definite": "samhällena", "english": "society"},
    {"indefinite": "framtid", "definite": "framtiden", "plural": "framtider", "plural_definite": "framtiderna", "english": "future"},
    {"indefinite": "ansvar", "definite": "ansvaret", "plural": "ansvar", "plural_definite": "ansvaren", "english": "responsibility"},
    {"indefinite": "lösning", "definite": "lösningen", "plural": "lösningar", "plural_definite": "lösningarna", "english": "solution"},
    {"indefinite": "problem", "definite": "problemet", "plural": "problem", "plural_definite": "problemen", "english": "problem"},
    {"indefinite": "hot", "definite": "hotet", "plural": "hot", "plural_definite": "hoten", "english": "threat"},
]

verbs = [
    {"infinitive": "återvinna", "present": "återvinner", "past": "återvann", "supine": "återvunnit", "english": "to recycle"},
    {"infinitive": "återanvända", "present": "återanvänder", "past": "återanvände", "supine": "återanvänt", "english": "to reuse"},
    {"infinitive": "sortera", "present": "sorterar", "past": "sorterade", "supine": "sorterat", "english": "to sort"},
    {"infinitive": "minska", "present": "minskar", "past": "minskade", "supine": "minskat", "english": "to reduce"},
    {"infinitive": "öka", "present": "ökar", "past": "ökade", "supine": "ökat", "english": "to increase"},
    {"infinitive": "spara", "present": "sparar", "past": "sparade", "supine": "sparat", "english": "to save"},
    {"infinitive": "förbruka", "present": "förbrukar", "past": "förbrukade", "supine": "förbrukat", "english": "to consume"},
    {"infinitive": "förstöra", "present": "förstör", "past": "förstörde", "supine": "förstört", "english": "to destroy"},
    {"infinitive": "påverka", "present": "påverkar", "past": "påverkade", "supine": "påverkat", "english": "to affect"},
    {"infinitive": "skydda", "present": "skyddar", "past": "skyddade", "supine": "skyddat", "english": "to protect"},
    {"infinitive": "plantera", "present": "planterar", "past": "planterade", "supine": "planterat", "english": "to plant"},
    {"infinitive": "rensa", "present": "rensar", "past": "rensade", "supine": "rensat", "english": "to clean up"},
    {"infinitive": "bränna", "present": "bränner", "past": "brände", "supine": "bränt", "english": "to burn"},
    {"infinitive": "förorena", "present": "förorenar", "past": "förorenade", "supine": "förorenat", "english": "to pollute"},
    {"infinitive": "förändra", "present": "förändrar", "past": "förändrade", "supine": "förändrat", "english": "to change"},
    {"infinitive": "utveckla", "present": "utvecklar", "past": "utvecklade", "supine": "utvecklat", "english": "to develop"},
    {"infinitive": "påminna", "present": "påminner", "past": "påminde", "supine": "påmint", "english": "to remind"},
    {"infinitive": "ansvara", "present": "ansvarar", "past": "ansvarade", "supine": "ansvarat", "english": "to be responsible"},
    {"infinitive": "diskutera", "present": "diskuterar", "past": "diskuterade", "supine": "diskuterat", "english": "to discuss"},
    {"infinitive": "förbättra", "present": "förbättrar", "past": "förbättrade", "supine": "förbättrat", "english": "to improve"},
]

misc = [
    {"swedish": "miljövänlig", "english": "environmentally friendly"},
    {"swedish": "hållbar", "english": "sustainable"},
    {"swedish": "grön", "english": "green"},
    {"swedish": "ren", "english": "clean"},
    {"swedish": "smutsig", "english": "dirty"},
    {"swedish": "naturlig", "english": "natural"},
    {"swedish": "farlig", "english": "dangerous"},
    {"swedish": "sund", "english": "healthy"},
    {"swedish": "ekologisk", "english": "organic"},
    {"swedish": "förnybar", "english": "renewable"},
    {"swedish": "global", "english": "global"},
    {"swedish": "lokal", "english": "local"},
    {"swedish": "nödvändig", "english": "necessary"},
    {"swedish": "viktig", "english": "important"},
    {"swedish": "billig", "english": "cheap"},
    {"swedish": "dyr", "english": "expensive"},
    {"swedish": "aktivt", "english": "actively"},
    {"swedish": "ansvarsfullt", "english": "responsibly"},
    {"swedish": "vanligtvis", "english": "usually"},
    {"swedish": "sällan", "english": "rarely"},
    {"swedish": "ofta", "english": "often"},
    {"swedish": "ibland", "english": "sometimes"},
    {"swedish": "på grund av", "english": "because of"},
    {"swedish": "trots", "english": "despite"},
    {"swedish": "för att", "english": "in order to"},
    {"swedish": "eftersom", "english": "because"},
    {"swedish": "dessutom", "english": "in addition"},
    {"swedish": "därför", "english": "therefore"},
    {"swedish": "till slut", "english": "in the end"},
    {"swedish": "till exempel", "english": "for example"},
]
