nouns = [
    {"indefinite": "kropp", "definite": "kroppen", "plural": "kroppar", "plural_definite": "kropparna", "english": "body"},
    {"indefinite": "hälsa", "definite": "hälsan", "plural": "hälsor", "plural_definite": "hälsorna", "english": "health"},
    {"indefinite": "sjukdom", "definite": "sjukdomen", "plural": "sjukdomar", "plural_definite": "sjukdomarna", "english": "illness, disease"},
    {"indefinite": "symptom", "definite": "symptomet", "plural": "symptom", "plural_definite": "symptomen", "english": "symptom"},
    {"indefinite": "smärta", "definite": "smärtan", "plural": "smärtor", "plural_definite": "smärtorna", "english": "pain"},
    {"indefinite": "huvudvärk", "definite": "huvudvärken", "plural": "huvudvärkar", "plural_definite": "huvudvärkarna", "english": "headache"},
    {"indefinite": "feber", "definite": "febern", "plural": "febrar", "plural_definite": "febrarna", "english": "fever"},
    {"indefinite": "förkylning", "definite": "förkylningen", "plural": "förkylningar", "plural_definite": "förkylningarna", "english": "cold (illness)"},
    {"indefinite": "influensa", "definite": "influensan", "plural": "influensor", "plural_definite": "influensorna", "english": "flu"},
    {"indefinite": "skada", "definite": "skadan", "plural": "skador", "plural_definite": "skadorna", "english": "injury"},
    {"indefinite": "blod", "definite": "blodet", "plural": "blod", "plural_definite": "bloden", "english": "blood"},
    {"indefinite": "hjärta", "definite": "hjärtat", "plural": "hjärtan", "plural_definite": "hjärtana", "english": "heart"},
    {"indefinite": "mage", "definite": "magen", "plural": "magar", "plural_definite": "magarna", "english": "stomach"},
    {"indefinite": "rygg", "definite": "ryggen", "plural": "ryggar", "plural_definite": "ryggarna", "english": "back"},
    {"indefinite": "muskel", "definite": "muskeln", "plural": "muskler", "plural_definite": "musklerna", "english": "muscle"},
    {"indefinite": "hud", "definite": "huden", "plural": "hudar", "plural_definite": "hudarna", "english": "skin"},
    {"indefinite": "hjärna", "definite": "hjärnan", "plural": "hjärnor", "plural_definite": "hjärnorna", "english": "brain"},
    {"indefinite": "lunga", "definite": "lungan", "plural": "lungor", "plural_definite": "lungorna", "english": "lung"},
    {"indefinite": "nerv", "definite": "nerven", "plural": "nerver", "plural_definite": "nerverna", "english": "nerve"},
    {"indefinite": "sjukhus", "definite": "sjukhuset", "plural": "sjukhus", "plural_definite": "sjukhusen", "english": "hospital"},
    {"indefinite": "vårdcentral", "definite": "vårdcentralen", "plural": "vårdcentraler", "plural_definite": "vårdcentralerna", "english": "health center"},
    {"indefinite": "klinik", "definite": "kliniken", "plural": "kliniker", "plural_definite": "klinikerna", "english": "clinic"},
    {"indefinite": "apotek", "definite": "apoteket", "plural": "apotek", "plural_definite": "apoteken", "english": "pharmacy"},
    {"indefinite": "läkare", "definite": "läkaren", "plural": "läkare", "plural_definite": "läkarna", "english": "doctor"},
    {"indefinite": "sjuksköterska", "definite": "sjuksköterskan", "plural": "sjuksköterskor", "plural_definite": "sjuksköterskorna", "english": "nurse"},
    {"indefinite": "patient", "definite": "patienten", "plural": "patienter", "plural_definite": "patienterna", "english": "patient"},
    {"indefinite": "behandling", "definite": "behandlingen", "plural": "behandlingar", "plural_definite": "behandlingarna", "english": "treatment"},
    {"indefinite": "operation", "definite": "operationen", "plural": "operationer", "plural_definite": "operationerna", "english": "operation, surgery"},
    {"indefinite": "undersökning", "definite": "undersökningen", "plural": "undersökningar", "plural_definite": "undersökningarna", "english": "examination"},
    {"indefinite": "recept", "definite": "receptet", "plural": "recept", "plural_definite": "recepten", "english": "prescription"},
    {"indefinite": "medicin", "definite": "medicinen", "plural": "mediciner", "plural_definite": "medicinerna", "english": "medicine"},
    {"indefinite": "tablett", "definite": "tabletten", "plural": "tabletter", "plural_definite": "tablettena", "english": "tablet, pill"},
    {"indefinite": "spruta", "definite": "sprutan", "plural": "sprutor", "plural_definite": "sprutorna", "english": "injection, syringe"},
    {"indefinite": "sjuksköterska", "definite": "sjuksköterskan", "plural": "sjuksköterskor", "plural_definite": "sjuksköterskorna", "english": "nurse"},
    {"indefinite": "hälsoundersökning", "definite": "hälsoundersökningen", "plural": "hälsoundersökningar", "plural_definite": "hälsoundersökningarna", "english": "health check-up"},
    {"indefinite": "kost", "definite": "kosten", "plural": "koster", "plural_definite": "kosterna", "english": "diet, nutrition"},
    {"indefinite": "motion", "definite": "motionen", "plural": "motioner", "plural_definite": "motionerna", "english": "exercise"},
    {"indefinite": "träning", "definite": "träningen", "plural": "träningar", "plural_definite": "träningarna", "english": "training, workout"},
    {"indefinite": "vila", "definite": "vilan", "plural": "vilor", "plural_definite": "vilorna", "english": "rest"},
    {"indefinite": "sömn", "definite": "sömnen", "plural": "sömn", "plural_definite": "sömnerna", "english": "sleep"},
    {"indefinite": "stress", "definite": "stressen", "plural": "stresser", "plural_definite": "stresserna", "english": "stress"},
    {"indefinite": "energi", "definite": "energin", "plural": "energier", "plural_definite": "energierna", "english": "energy"},
    {"indefinite": "balans", "definite": "balansen", "plural": "balanser", "plural_definite": "balanserna", "english": "balance"},
    {"indefinite": "självkänsla", "definite": "självkänslan", "plural": "självkänslor", "plural_definite": "självkänslorna", "english": "self-esteem"},
    {"indefinite": "känsla", "definite": "känslan", "plural": "känslor", "plural_definite": "känslorna", "english": "feeling, emotion"},
    {"indefinite": "oro", "definite": "oron", "plural": "oror", "plural_definite": "ororna", "english": "anxiety, worry"},
    {"indefinite": "ångest", "definite": "ångesten", "plural": "ångestar", "plural_definite": "ångestarna", "english": "anxiety"},
    {"indefinite": "humör", "definite": "humöret", "plural": "humör", "plural_definite": "humören", "english": "mood"},
    {"indefinite": "själ", "definite": "själen", "plural": "själar", "plural_definite": "själarna", "english": "soul"},
    {"indefinite": "livsstil", "definite": "livsstilen", "plural": "livsstilar", "plural_definite": "livsstilarna", "english": "lifestyle"},
    {"indefinite": "vanor", "definite": "vanan", "plural": "vanor", "plural_definite": "vanorna", "english": "habit"},
]

verbs = [
    {"infinitive": "må", "present": "mår", "past": "mådde", "supine": "mått", "english": "to feel (emotionally or physically)"},
    {"infinitive": "andas", "present": "andas", "past": "andades", "supine": "andats", "english": "to breathe"},
    {"infinitive": "röra sig", "present": "rör sig", "past": "rörde sig", "supine": "rört sig", "english": "to move"},
    {"infinitive": "träna", "present": "tränar", "past": "tränade", "supine": "tränat", "english": "to exercise, to train"},
    {"infinitive": "vila", "present": "vilar", "past": "vilade", "supine": "vilat", "english": "to rest"},
    {"infinitive": "sova", "present": "sover", "past": "sov", "supine": "sovit", "english": "to sleep"},
    {"infinitive": "vakna", "present": "vaknar", "past": "vaknade", "supine": "vaknat", "english": "to wake up"},
    {"infinitive": "somna", "present": "somnar", "past": "somnade", "supine": "somnat", "english": "to fall asleep"},
    {"infinitive": "äta", "present": "äter", "past": "åt", "supine": "ätit", "english": "to eat"},
    {"infinitive": "dricka", "present": "dricker", "past": "drack", "supine": "druckit", "english": "to drink"},
    {"infinitive": "röka", "present": "röker", "past": "rökte", "supine": "rökt", "english": "to smoke"},
    {"infinitive": "hosta", "present": "hostar", "past": "hostade", "supine": "hostat", "english": "to cough"},
    {"infinitive": "nysa", "present": "nyser", "past": "nös", "supine": "nyst", "english": "to sneeze"},
    {"infinitive": "blöda", "present": "blöder", "past": "blödde", "supine": "blött", "english": "to bleed"},
    {"infinitive": "läka", "present": "läker", "past": "läkte", "supine": "läkt", "english": "to heal"},
    {"infinitive": "vårda", "present": "vårdar", "past": "vårdade", "supine": "vårdat", "english": "to care for, to treat"},
    {"infinitive": "undersöka", "present": "undersöker", "past": "undersökte", "supine": "undersökt", "english": "to examine"},
    {"infinitive": "behandla", "present": "behandlar", "past": "behandlade", "supine": "behandlat", "english": "to treat"},
    {"infinitive": "förbättra", "present": "förbättrar", "past": "förbättrade", "supine": "förbättrat", "english": "to improve"},
    {"infinitive": "försämra", "present": "försämrar", "past": "försämrade", "supine": "försämrat", "english": "to worsen"},
    {"infinitive": "röntga", "present": "röntgar", "past": "röntgade", "supine": "röntgat", "english": "to X-ray"},
    {"infinitive": "mäta", "present": "mäter", "past": "mätte", "supine": "mätt", "english": "to measure"},
    {"infinitive": "väga", "present": "väger", "past": "vägde", "supine": "vägt", "english": "to weigh"},
    {"infinitive": "orka", "present": "orkar", "past": "orkade", "supine": "orkat", "english": "to have energy, to manage"},
    {"infinitive": "slappna av", "present": "slappnar av", "past": "slappnade av", "supine": "slappnat av", "english": "to relax"},
    {"infinitive": "stressa", "present": "stressar", "past": "stressade", "supine": "stressat", "english": "to stress"},
    {"infinitive": "lugna", "present": "lugnade", "past": "lugnade", "supine": "lugnade", "english": "to calm"},
    {"infinitive": "oroa sig", "present": "oroar sig", "past": "oroade sig", "supine": "oroat sig", "english": "to worry"},
    {"infinitive": "känna", "present": "känner", "past": "kände", "supine": "känt", "english": "to feel, to sense"},
    {"infinitive": "lida", "present": "lider", "past": "led", "supine": "lidit", "english": "to suffer"},
    {"infinitive": "gråta", "present": "gråter", "past": "grät", "supine": "gråtit", "english": "to cry"},
    {"infinitive": "le", "present": "ler", "past": "log", "supine": "lett", "english": "to smile"},
    {"infinitive": "skratta", "present": "skrattar", "past": "skrattade", "supine": "skrattat", "english": "to laugh"},
    {"infinitive": "andas in", "present": "andas in", "past": "andades in", "supine": "andats in", "english": "to inhale"},
    {"infinitive": "andas ut", "present": "andas ut", "past": "andades ut", "supine": "andats ut", "english": "to exhale"},
    {"infinitive": "röra", "present": "rör", "past": "rörde", "supine": "rört", "english": "to touch, to move"},
    {"infinitive": "lyssna", "present": "lyssnar", "past": "lyssnade", "supine": "lyssnat", "english": "to listen"},
    {"infinitive": "titta", "present": "tittar", "past": "tittade", "supine": "tittat", "english": "to look, to watch"},
    {"infinitive": "andas djupt", "present": "andas djupt", "past": "andades djupt", "supine": "andats djupt", "english": "to breathe deeply"},
    {"infinitive": "sluta", "present": "slutar", "past": "slutade", "supine": "slutat", "english": "to quit, to stop"},
    {"infinitive": "börja", "present": "börjar", "past": "började", "supine": "börjat", "english": "to start, to begin"},
    {"infinitive": "förebygga", "present": "förebygger", "past": "förebyggde", "supine": "förebyggt", "english": "to prevent"},
    {"infinitive": "hämta", "present": "hämtar", "past": "hämtade", "supine": "hämtat", "english": "to fetch, to pick up"},
    {"infinitive": "lämna", "present": "lämnar", "past": "lämnade", "supine": "lämnat", "english": "to leave"},
    {"infinitive": "besöka", "present": "besöker", "past": "besökte", "supine": "besökt", "english": "to visit"},
    {"infinitive": "kontakta", "present": "kontaktar", "past": "kontaktade", "supine": "kontaktat", "english": "to contact"},
    {"infinitive": "förklara", "present": "förklarar", "past": "förklarade", "supine": "förklarat", "english": "to explain"},
    {"infinitive": "ställa frågor", "present": "ställer frågor", "past": "ställde frågor", "supine": "ställt frågor", "english": "to ask questions"},
    {"infinitive": "rekommendera", "present": "rekommenderar", "past": "rekommenderade", "supine": "rekommenderat", "english": "to recommend"},
    {"infinitive": "kontrollera", "present": "kontrollerar", "past": "kontrollerade", "supine": "kontrollerat", "english": "to check, to control"},
    {"infinitive": "uppleva", "present": "upplever", "past": "upplevde", "supine": "upplevt", "english": "to experience"},
    {"infinitive": "acceptera", "present": "accepterar", "past": "accepterade", "supine": "accepterat", "english": "to accept"},
]

misc = [
    {"swedish": "frisk", "english": "healthy"},
    {"swedish": "sjuk", "english": "sick, ill"},
    {"swedish": "trött", "english": "tired"},
    {"swedish": "pigg", "english": "alert, energetic"},
    {"swedish": "hungrig", "english": "hungry"},
    {"swedish": "mätt", "english": "full (after eating)"},
    {"swedish": "törstig", "english": "thirsty"},
    {"swedish": "svag", "english": "weak"},
    {"swedish": "stark", "english": "strong"},
    {"swedish": "skadad", "english": "injured"},
    {"swedish": "allvarlig", "english": "serious"},
    {"swedish": "lindrig", "english": "mild (illness)"},
    {"swedish": "smittsam", "english": "contagious"},
    {"swedish": "nyttig", "english": "healthy (food), useful"},
    {"swedish": "ohälsosam", "english": "unhealthy"},
    {"swedish": "lugn", "english": "calm"},
    {"swedish": "orolig", "english": "worried, anxious"},
    {"swedish": "stressad", "english": "stressed"},
    {"swedish": "avslappnad", "english": "relaxed"},
    {"swedish": "nervös", "english": "nervous"},
    {"swedish": "deprimerad", "english": "depressed"},
    {"swedish": "glad", "english": "happy"},
    {"swedish": "ledsen", "english": "sad"},
    {"swedish": "arg", "english": "angry"},
    {"swedish": "besviken", "english": "disappointed"},
    {"swedish": "oroligt", "english": "uneasily, anxiously"},
    {"swedish": "lugnt", "english": "calmly, peacefully"},
    {"swedish": "förkyld", "english": "having a cold"},
    {"swedish": "febrig", "english": "feverish"},
    {"swedish": "yr", "english": "dizzy"},
    {"swedish": "utmattad", "english": "exhausted"},
    {"swedish": "avslappnat", "english": "in a relaxed way"},
    {"swedish": "hälsosam", "english": "healthy (for lifestyle)"},
    {"swedish": "balanserad", "english": "balanced"},
    {"swedish": "regelbunden", "english": "regular"},
    {"swedish": "daglig", "english": "daily"},
    {"swedish": "tillräcklig", "english": "sufficient, enough"},
    {"swedish": "nödvändig", "english": "necessary"},
    {"swedish": "positiv", "english": "positive"},
    {"swedish": "negativ", "english": "negative"},
    {"swedish": "aktiv", "english": "active"},
    {"swedish": "passiv", "english": "passive"},
    {"swedish": "självständig", "english": "independent"},
    {"swedish": "beroende", "english": "dependent, addicted"},
    {"swedish": "nöjd", "english": "content, satisfied"},
    {"swedish": "oroligt", "english": "uneasily"},
    {"swedish": "noggrant", "english": "carefully"},
    {"swedish": "regelbundet", "english": "regularly"},
    {"swedish": "tyst", "english": "quiet"},
    {"swedish": "högljudd", "english": "loud"},
    {"swedish": "inre", "english": "inner"},
    {"swedish": "yttre", "english": "outer"},
    {"swedish": "mentalt", "english": "mentally"},
    {"swedish": "fysiskt", "english": "physically"},
    {"swedish": "hälsosamt", "english": "healthily"},
    {"swedish": "försiktigt", "english": "carefully"},
]
