nouns = [
    {"indefinite": "kropp", "definite": "kroppen", "plural": "kroppar", "plural_definite": "kropparna", "english": "body", "cefr": 1, "frequency": 145.82},
    {"indefinite": "hälsa", "definite": "hälsan", "plural": "hälsor", "plural_definite": "hälsorna", "english": "health", "cefr": 2, "frequency": 59.45},
    {"indefinite": "sjukdom", "definite": "sjukdomen", "plural": "sjukdomar", "plural_definite": "sjukdomarna", "english": "illness, disease", "cefr": 1, "frequency": 84.27},
    {"indefinite": "symptom", "definite": "symptomet", "plural": "symptom", "plural_definite": "symptomen", "english": "symptom", "cefr": 3, "frequency": 17.90},
    {"indefinite": "smärta", "definite": "smärtan", "plural": "smärtor", "plural_definite": "smärtorna", "english": "pain", "cefr": 2, "frequency": 31.20},
    {"indefinite": "huvudvärk", "definite": "huvudvärken", "plural": "huvudvärkar", "plural_definite": "huvudvärkarna", "english": "headache", "cefr": 1, "frequency": None},
    {"indefinite": "feber", "definite": "febern", "plural": "febrar", "plural_definite": "febrarna", "english": "fever", "cefr": 1, "frequency": None},
    {"indefinite": "förkylning", "definite": "förkylningen", "plural": "förkylningar", "plural_definite": "förkylningarna", "english": "cold (illness)", "cefr": 1, "frequency": None},
    {"indefinite": "influensa", "definite": "influensan", "plural": "influensor", "plural_definite": "influensorna", "english": "flu", "cefr": 3, "frequency": 12.81},
    {"indefinite": "skada", "definite": "skadan", "plural": "skador", "plural_definite": "skadorna", "english": "injury", "cefr": 1, "frequency": 80.74},
    {"indefinite": "blod", "definite": "blodet", "plural": "blod", "plural_definite": "bloden", "english": "blood", "cefr": 2, "frequency": 45.98},
    {"indefinite": "hjärta", "definite": "hjärtat", "plural": "hjärtan", "plural_definite": "hjärtana", "english": "heart", "cefr": 1, "frequency": 102.88},
    {"indefinite": "mage", "definite": "magen", "plural": "magar", "plural_definite": "magarna", "english": "stomach", "cefr": 2, "frequency": 35.09},
    {"indefinite": "rygg", "definite": "ryggen", "plural": "ryggar", "plural_definite": "ryggarna", "english": "back", "cefr": 2, "frequency": 45.55},
    {"indefinite": "muskel", "definite": "muskeln", "plural": "muskler", "plural_definite": "musklerna", "english": "muscle", "cefr": 3, "frequency": 12.80},
    {"indefinite": "hud", "definite": "huden", "plural": "hudar", "plural_definite": "hudarna", "english": "skin", "cefr": 3, "frequency": 18.22},
    {"indefinite": "hjärna", "definite": "hjärnan", "plural": "hjärnor", "plural_definite": "hjärnorna", "english": "brain", "cefr": 2, "frequency": 53.02},
    {"indefinite": "lunga", "definite": "lungan", "plural": "lungor", "plural_definite": "lungorna", "english": "lung", "cefr": 1, "frequency": None},
    {"indefinite": "nerv", "definite": "nerven", "plural": "nerver", "plural_definite": "nerverna", "english": "nerve", "cefr": 1, "frequency": None},
    {"indefinite": "sjukhus", "definite": "sjukhuset", "plural": "sjukhus", "plural_definite": "sjukhusen", "english": "hospital", "cefr": 2, "frequency": 50.51},
    {"indefinite": "vårdcentral", "definite": "vårdcentralen", "plural": "vårdcentraler", "plural_definite": "vårdcentralerna", "english": "health center", "cefr": 1, "frequency": None},
    {"indefinite": "klinik", "definite": "kliniken", "plural": "kliniker", "plural_definite": "klinikerna", "english": "clinic", "cefr": 1, "frequency": None},
    {"indefinite": "apotek", "definite": "apoteket", "plural": "apotek", "plural_definite": "apoteken", "english": "pharmacy", "cefr": 1, "frequency": None},
    {"indefinite": "läkare", "definite": "läkaren", "plural": "läkare", "plural_definite": "läkarna", "english": "doctor", "cefr": 1, "frequency": 81.81},
    {"indefinite": "sjuksköterska", "definite": "sjuksköterskan", "plural": "sjuksköterskor", "plural_definite": "sjuksköterskorna", "english": "nurse", "cefr": 3, "frequency": 12.07},
    {"indefinite": "patient", "definite": "patienten", "plural": "patienter", "plural_definite": "patienterna", "english": "patient", "cefr": 2, "frequency": 59.58},
    {"indefinite": "behandling", "definite": "behandlingen", "plural": "behandlingar", "plural_definite": "behandlingarna", "english": "treatment", "cefr": 1, "frequency": 76.64},
    {"indefinite": "operation", "definite": "operationen", "plural": "operationer", "plural_definite": "operationerna", "english": "operation, surgery", "cefr": 2, "frequency": 30.83},
    {"indefinite": "undersökning", "definite": "undersökningen", "plural": "undersökningar", "plural_definite": "undersökningarna", "english": "examination", "cefr": 1, "frequency": 94.27},
    {"indefinite": "recept", "definite": "receptet", "plural": "recept", "plural_definite": "recepten", "english": "prescription", "cefr": 3, "frequency": 20.79},
    {"indefinite": "medicin", "definite": "medicinen", "plural": "mediciner", "plural_definite": "medicinerna", "english": "medicine", "cefr": 2, "frequency": 38.84},
    {"indefinite": "tablett", "definite": "tabletten", "plural": "tabletter", "plural_definite": "tablettena", "english": "tablet, pill", "cefr": 1, "frequency": None},
    {"indefinite": "spruta", "definite": "sprutan", "plural": "sprutor", "plural_definite": "sprutorna", "english": "injection, syringe", "cefr": 1, "frequency": None},
    {"indefinite": "hälsoundersökning", "definite": "hälsoundersökningen", "plural": "hälsoundersökningar", "plural_definite": "hälsoundersökningarna", "english": "health check-up", "cefr": 1, "frequency": None},
    {"indefinite": "kost", "definite": "kosten", "plural": "koster", "plural_definite": "kosterna", "english": "diet, nutrition", "cefr": 2, "frequency": 28.82},
    {"indefinite": "motion", "definite": "motionen", "plural": "motioner", "plural_definite": "motionerna", "english": "exercise", "cefr": 1, "frequency": 120.87},
    {"indefinite": "träning", "definite": "träningen", "plural": "träningar", "plural_definite": "träningarna", "english": "training, workout", "cefr": 2, "frequency": 51.25},
    {"indefinite": "vila", "definite": "vilan", "plural": "vilor", "plural_definite": "vilorna", "english": "rest", "cefr": 2, "frequency": 39.26},
    {"indefinite": "sömn", "definite": "sömnen", "plural": "sömn", "plural_definite": "sömnerna", "english": "sleep", "cefr": 3, "frequency": 19.96},
    {"indefinite": "stress", "definite": "stressen", "plural": "stresser", "plural_definite": "stresserna", "english": "stress", "cefr": 3, "frequency": 19.27},
    {"indefinite": "balans", "definite": "balansen", "plural": "balanser", "plural_definite": "balanserna", "english": "balance", "cefr": 2, "frequency": 35.09},
    {"indefinite": "självkänsla", "definite": "självkänslan", "plural": "självkänslor", "plural_definite": "självkänslorna", "english": "self-esteem", "cefr": 1, "frequency": None},
    {"indefinite": "oro", "definite": "oron", "plural": "oror", "plural_definite": "ororna", "english": "anxiety, worry", "cefr": 2, "frequency": 50.14},
    {"indefinite": "ångest", "definite": "ångesten", "plural": "ångestar", "plural_definite": "ångestarna", "english": "anxiety", "cefr": 2, "frequency": 23.60},
    {"indefinite": "humör", "definite": "humöret", "plural": "humör", "plural_definite": "humören", "english": "mood", "cefr": 3, "frequency": 15.64},
    {"indefinite": "själ", "definite": "själen", "plural": "själar", "plural_definite": "själarna", "english": "soul", "cefr": 2, "frequency": 53.26},
    {"indefinite": "livsstil", "definite": "livsstilen", "plural": "livsstilar", "plural_definite": "livsstilarna", "english": "lifestyle", "cefr": 3, "frequency": 16.85},
    {"indefinite": "vanor", "definite": "vanan", "plural": "vanor", "plural_definite": "vanorna", "english": "habit", "cefr": 1, "frequency": None},
]

verbs = [
    {"infinitive": "må", "present": "mår", "past": "mådde", "supine": "mått", "english": "to feel (emotionally or physically)", "cefr": 1, "frequency": 135.98},
    {"infinitive": "andas", "present": "andas", "past": "andades", "supine": "andats", "english": "to breathe", "cefr": 3, "frequency": 16.23},
    {"infinitive": "röra sig", "present": "rör sig", "past": "rörde sig", "supine": "rört sig", "english": "to move", "cefr": 1, "frequency": None},
    {"infinitive": "träna", "present": "tränar", "past": "tränade", "supine": "tränat", "english": "to exercise, to train", "cefr": 2, "frequency": 59.09},
    {"infinitive": "vila", "present": "vilar", "past": "vilade", "supine": "vilat", "english": "to rest", "cefr": 2, "frequency": 39.26},
    {"infinitive": "sova", "present": "sover", "past": "sov", "supine": "sovit", "english": "to sleep", "cefr": 1, "frequency": 85.26},
    {"infinitive": "vakna", "present": "vaknar", "past": "vaknade", "supine": "vaknat", "english": "to wake up", "cefr": 2, "frequency": 59.51},
    {"infinitive": "somna", "present": "somnar", "past": "somnade", "supine": "somnat", "english": "to fall asleep", "cefr": 2, "frequency": 27.63},
    {"infinitive": "äta", "present": "äter", "past": "åt", "supine": "ätit", "english": "to eat", "cefr": 1, "frequency": 169.74},
    {"infinitive": "dricka", "present": "dricker", "past": "drack", "supine": "druckit", "english": "to drink", "cefr": 1, "frequency": 72.16},
    {"infinitive": "röka", "present": "röker", "past": "rökte", "supine": "rökt", "english": "to smoke", "cefr": 3, "frequency": 19.20},
    {"infinitive": "hosta", "present": "hostar", "past": "hostade", "supine": "hostat", "english": "to cough", "cefr": 1, "frequency": None},
    {"infinitive": "nysa", "present": "nyser", "past": "nös", "supine": "nyst", "english": "to sneeze", "cefr": 1, "frequency": None},
    {"infinitive": "blöda", "present": "blöder", "past": "blödde", "supine": "blött", "english": "to bleed", "cefr": 1, "frequency": None},
    {"infinitive": "läka", "present": "läker", "past": "läkte", "supine": "läkt", "english": "to heal", "cefr": 1, "frequency": None},
    {"infinitive": "vårda", "present": "vårdar", "past": "vårdade", "supine": "vårdat", "english": "to care for, to treat", "cefr": 3, "frequency": 14.22},
    {"infinitive": "undersöka", "present": "undersöker", "past": "undersökte", "supine": "undersökt", "english": "to examine", "cefr": 2, "frequency": 53.89},
    {"infinitive": "behandla", "present": "behandlar", "past": "behandlade", "supine": "behandlat", "english": "to treat", "cefr": 1, "frequency": 114.58},
    {"infinitive": "försämra", "present": "försämrar", "past": "försämrade", "supine": "försämrat", "english": "to worsen", "cefr": 3, "frequency": 21.83},
    {"infinitive": "röntga", "present": "röntgar", "past": "röntgade", "supine": "röntgat", "english": "to X-ray", "cefr": 1, "frequency": None},
    {"infinitive": "mäta", "present": "mäter", "past": "mätte", "supine": "mätt", "english": "to measure", "cefr": 2, "frequency": 38.30},
    {"infinitive": "väga", "present": "väger", "past": "vägde", "supine": "vägt", "english": "to weigh", "cefr": 2, "frequency": 42.23},
    {"infinitive": "orka", "present": "orkar", "past": "orkade", "supine": "orkat", "english": "to have energy, to manage", "cefr": 1, "frequency": 75.09},
    {"infinitive": "slappna av", "present": "slappnar av", "past": "slappnade av", "supine": "slappnat av", "english": "to relax", "cefr": 1, "frequency": None},
    {"infinitive": "stressa", "present": "stressar", "past": "stressade", "supine": "stressat", "english": "to stress", "cefr": 1, "frequency": None},
    {"infinitive": "lugna", "present": "lugnade", "past": "lugnade", "supine": "lugnade", "english": "to calm", "cefr": 3, "frequency": 14.01},
    {"infinitive": "oroa sig", "present": "oroar sig", "past": "oroade sig", "supine": "oroat sig", "english": "to worry", "cefr": 1, "frequency": None},
    {"infinitive": "lida", "present": "lider", "past": "led", "supine": "lidit", "english": "to suffer", "cefr": 2, "frequency": 58.60},
    {"infinitive": "gråta", "present": "gråter", "past": "grät", "supine": "gråtit", "english": "to cry", "cefr": 2, "frequency": 31.33},
    {"infinitive": "le", "present": "ler", "past": "log", "supine": "lett", "english": "to smile", "cefr": 2, "frequency": 26.54},
    {"infinitive": "skratta", "present": "skrattar", "past": "skrattade", "supine": "skrattat", "english": "to laugh", "cefr": 2, "frequency": 44.04},
    {"infinitive": "andas in", "present": "andas in", "past": "andades in", "supine": "andats in", "english": "to inhale", "cefr": 1, "frequency": None},
    {"infinitive": "andas ut", "present": "andas ut", "past": "andades ut", "supine": "andats ut", "english": "to exhale", "cefr": 1, "frequency": None},
    {"infinitive": "röra", "present": "rör", "past": "rörde", "supine": "rört", "english": "to touch, to move", "cefr": 1, "frequency": 165.68},
    {"infinitive": "andas djupt", "present": "andas djupt", "past": "andades djupt", "supine": "andats djupt", "english": "to breathe deeply", "cefr": 1, "frequency": None},
    {"infinitive": "sluta", "present": "slutar", "past": "slutade", "supine": "slutat", "english": "to quit, to stop", "cefr": 1, "frequency": 249.47},
    {"infinitive": "börja", "present": "börjar", "past": "började", "supine": "börjat", "english": "to start, to begin", "cefr": 1, "frequency": 1039.45},
    {"infinitive": "förebygga", "present": "förebygger", "past": "förebyggde", "supine": "förebyggt", "english": "to prevent", "cefr": 3, "frequency": 16.36},
    {"infinitive": "hämta", "present": "hämtar", "past": "hämtade", "supine": "hämtat", "english": "to fetch, to pick up", "cefr": 1, "frequency": 82.84},
    {"infinitive": "lämna", "present": "lämnar", "past": "lämnade", "supine": "lämnat", "english": "to leave", "cefr": 1, "frequency": 369.70},
    {"infinitive": "kontakta", "present": "kontaktar", "past": "kontaktade", "supine": "kontaktat", "english": "to contact", "cefr": 2, "frequency": 36.81},
    {"infinitive": "ställa frågor", "present": "ställer frågor", "past": "ställde frågor", "supine": "ställt frågor", "english": "to ask questions", "cefr": 1, "frequency": None},
    {"infinitive": "rekommendera", "present": "rekommenderar", "past": "rekommenderade", "supine": "rekommenderat", "english": "to recommend", "cefr": 2, "frequency": 57.61},
    {"infinitive": "kontrollera", "present": "kontrollerar", "past": "kontrollerade", "supine": "kontrollerat", "english": "to check, to control", "cefr": 1, "frequency": 74.97},
    {"infinitive": "acceptera", "present": "accepterar", "past": "accepterade", "supine": "accepterat", "english": "to accept", "cefr": 1, "frequency": 111.33},
]

misc = [
    {"swedish": "frisk", "english": "healthy", "cefr": 2, "frequency": 47.12},
    {"swedish": "sjuk", "english": "sick, ill", "cefr": 1, "frequency": 113.46},
    {"swedish": "trött", "english": "tired", "cefr": 1, "frequency": 63.63},
    {"swedish": "pigg", "english": "alert, energetic", "cefr": 1, "frequency": None},
    {"swedish": "hungrig", "english": "hungry", "cefr": 3, "frequency": 13.31},
    {"swedish": "mätt", "english": "full (after eating)", "cefr": 3, "frequency": 13.70},
    {"swedish": "törstig", "english": "thirsty", "cefr": 1, "frequency": None},
    {"swedish": "svag", "english": "weak", "cefr": 1, "frequency": 73.87},
    {"swedish": "stark", "english": "strong", "cefr": 2, "frequency": 56.58},
    {"swedish": "skadad", "english": "injured", "cefr": 3, "frequency": 22.39},
    {"swedish": "lindrig", "english": "mild (illness)", "cefr": 1, "frequency": None},
    {"swedish": "smittsam", "english": "contagious", "cefr": 1, "frequency": None},
    {"swedish": "nyttig", "english": "healthy (food), useful", "cefr": 3, "frequency": 23.20},
    {"swedish": "ohälsosam", "english": "unhealthy", "cefr": 1, "frequency": None},
    {"swedish": "lugn", "english": "calm", "cefr": 2, "frequency": 43.08},
    {"swedish": "orolig", "english": "worried, anxious", "cefr": 2, "frequency": 33.60},
    {"swedish": "stressad", "english": "stressed", "cefr": 1, "frequency": None},
    {"swedish": "avslappnad", "english": "relaxed", "cefr": 1, "frequency": None},
    {"swedish": "nervös", "english": "nervous", "cefr": 1, "frequency": None},
    {"swedish": "deprimerad", "english": "depressed", "cefr": 1, "frequency": None},
    {"swedish": "arg", "english": "angry", "cefr": 2, "frequency": 35.03},
    {"swedish": "besviken", "english": "disappointed", "cefr": 3, "frequency": 22.89},
    {"swedish": "oroligt", "english": "uneasily, anxiously", "cefr": 1, "frequency": None},
    {"swedish": "lugnt", "english": "calmly, peacefully", "cefr": 2, "frequency": 29.74},
    {"swedish": "förkyld", "english": "having a cold", "cefr": 1, "frequency": None},
    {"swedish": "febrig", "english": "feverish", "cefr": 1, "frequency": None},
    {"swedish": "yr", "english": "dizzy", "cefr": 1, "frequency": None},
    {"swedish": "utmattad", "english": "exhausted", "cefr": 1, "frequency": None},
    {"swedish": "avslappnat", "english": "in a relaxed way", "cefr": 1, "frequency": None},
    {"swedish": "hälsosam", "english": "healthy (for lifestyle)", "cefr": 1, "frequency": None},
    {"swedish": "balanserad", "english": "balanced", "cefr": 1, "frequency": None},
    {"swedish": "regelbunden", "english": "regular", "cefr": 3, "frequency": 12.28},
    {"swedish": "daglig", "english": "daily", "cefr": 2, "frequency": 29.75},
    {"swedish": "tillräcklig", "english": "sufficient, enough", "cefr": 2, "frequency": 39.49},
    {"swedish": "passiv", "english": "passive", "cefr": 3, "frequency": 12.11},
    {"swedish": "nöjd", "english": "content, satisfied", "cefr": 1, "frequency": 69.02},
    {"swedish": "noggrant", "english": "carefully", "cefr": 3, "frequency": 12.36},
    {"swedish": "regelbundet", "english": "regularly", "cefr": 3, "frequency": 20.53},
    {"swedish": "högljudd", "english": "loud", "cefr": 1, "frequency": None},
    {"swedish": "inre", "english": "inner", "cefr": 2, "frequency": 58.31},
    {"swedish": "yttre", "english": "outer", "cefr": 2, "frequency": 38.53},
    {"swedish": "mentalt", "english": "mentally", "cefr": 1, "frequency": None},
    {"swedish": "fysiskt", "english": "physically", "cefr": 1, "frequency": None},
    {"swedish": "hälsosamt", "english": "healthily", "cefr": 1, "frequency": None},
    {"swedish": "försiktigt", "english": "carefully", "cefr": 3, "frequency": 12.25},
]
