nouns = [
    {"indefinite": "fritid", "definite": "fritiden", "plural": "fritider", "plural_definite": "fritiderna", "english": "free time"},
    {"indefinite": "intresse", "definite": "intresset", "plural": "intressen", "plural_definite": "intressena", "english": "interest"},
    {"indefinite": "hobby", "definite": "hobbyn", "plural": "hobbier", "plural_definite": "hobbierna", "english": "hobby"},
    {"indefinite": "sport", "definite": "sporten", "plural": "sporter", "plural_definite": "sporterna", "english": "sport"},
    {"indefinite": "träning", "definite": "träningen", "plural": "träningar", "plural_definite": "träningarna", "english": "training"},
    {"indefinite": "gym", "definite": "gymmet", "plural": "gym", "plural_definite": "gymmen", "english": "gym"},
    {"indefinite": "motion", "definite": "motionen", "plural": "motioner", "plural_definite": "motionerna", "english": "exercise"},
    {"indefinite": "löpning", "definite": "löpningen", "plural": "löpningar", "plural_definite": "löpningarna", "english": "running"},
    {"indefinite": "cykling", "definite": "cyklingen", "plural": "cyklingar", "plural_definite": "cyklingarna", "english": "cycling"},
    {"indefinite": "simning", "definite": "simningen", "plural": "simningar", "plural_definite": "simningarna", "english": "swimming"},
    {"indefinite": "promenad", "definite": "promenaden", "plural": "promenader", "plural_definite": "promenaderna", "english": "walk"},
    {"indefinite": "vandring", "definite": "vandringen", "plural": "vandringar", "plural_definite": "vandringarna", "english": "hike"},
    {"indefinite": "spel", "definite": "spelet", "plural": "spel", "plural_definite": "spelen", "english": "game"},
    {"indefinite": "brädspel", "definite": "brädspelet", "plural": "brädspel", "plural_definite": "brädspelen", "english": "board game"},
    {"indefinite": "datorspel", "definite": "datorspelet", "plural": "datorspel", "plural_definite": "datorspelen", "english": "computer game"},
    {"indefinite": "musik", "definite": "musiken", "plural": "musiker", "plural_definite": "musikerna", "english": "music"},
    {"indefinite": "instrument", "definite": "instrumentet", "plural": "instrument", "plural_definite": "instrumenten", "english": "instrument"},
    {"indefinite": "gitarr", "definite": "gitarren", "plural": "gitarrer", "plural_definite": "gitarrerna", "english": "guitar"},
    {"indefinite": "piano", "definite": "pianot", "plural": "pianon", "plural_definite": "pianona", "english": "piano"},
    {"indefinite": "sång", "definite": "sången", "plural": "sånger", "plural_definite": "sångerna", "english": "song"},
    {"indefinite": "konsert", "definite": "konserten", "plural": "konserter", "plural_definite": "konserterna", "english": "concert"},
    {"indefinite": "film", "definite": "filmen", "plural": "filmer", "plural_definite": "filmerna", "english": "movie"},
    {"indefinite": "bio", "definite": "bion", "plural": "biografer", "plural_definite": "biograferna", "english": "cinema"},
    {"indefinite": "bok", "definite": "boken", "plural": "böcker", "plural_definite": "böckerna", "english": "book"},
    {"indefinite": "tidning", "definite": "tidningen", "plural": "tidningar", "plural_definite": "tidningarna", "english": "magazine"},
    {"indefinite": "roman", "definite": "romanen", "plural": "romaner", "plural_definite": "romanerna", "english": "novel"},
    {"indefinite": "målning", "definite": "målningen", "plural": "målningar", "plural_definite": "målningarna", "english": "painting"},
    {"indefinite": "teckning", "definite": "teckningen", "plural": "teckningar", "plural_definite": "teckningarna", "english": "drawing"},
    {"indefinite": "fotografi", "definite": "fotografiet", "plural": "fotografier", "plural_definite": "fotografierna", "english": "photograph"},
    {"indefinite": "kamera", "definite": "kameran", "plural": "kameror", "plural_definite": "kamerorna", "english": "camera"},
    {"indefinite": "resa", "definite": "resan", "plural": "resor", "plural_definite": "resorna", "english": "trip"},
    {"indefinite": "semester", "definite": "semestern", "plural": "semestrar", "plural_definite": "semestrarna", "english": "vacation"},
    {"indefinite": "strand", "definite": "stranden", "plural": "stränder", "plural_definite": "stränderna", "english": "beach"},
    {"indefinite": "fjäll", "definite": "fjället", "plural": "fjäll", "plural_definite": "fjällen", "english": "mountain area"},
    {"indefinite": "park", "definite": "parken", "plural": "parker", "plural_definite": "parkerna", "english": "park"},
    {"indefinite": "förening", "definite": "föreningen", "plural": "föreningar", "plural_definite": "föreningarna", "english": "club, association"},
    {"indefinite": "evenemang", "definite": "evenemanget", "plural": "evenemang", "plural_definite": "evenemangen", "english": "event"},
    {"indefinite": "konst", "definite": "konsten", "plural": "konster", "plural_definite": "konsterna", "english": "art"},
    {"indefinite": "teater", "definite": "teatern", "plural": "teatrar", "plural_definite": "teatrarna", "english": "theatre"},
    {"indefinite": "bibliotek", "definite": "biblioteket", "plural": "bibliotek", "plural_definite": "biblioteken", "english": "library"},
    {"indefinite": "dans", "definite": "dansen", "plural": "danser", "plural_definite": "danserna", "english": "dance"},
    {"indefinite": "lektion", "definite": "lektionen", "plural": "lektioner", "plural_definite": "lektionerna", "english": "lesson"},
    {"indefinite": "kurs", "definite": "kursen", "plural": "kurser", "plural_definite": "kurserna", "english": "course"},
    {"indefinite": "aktivitet", "definite": "aktiviteten", "plural": "aktiviteter", "plural_definite": "aktiviteterna", "english": "activity"},
    {"indefinite": "föreningsliv", "definite": "föreningslivet", "plural": "föreningsliv", "plural_definite": "föreningsliven", "english": "association life"},
    {"indefinite": "vila", "definite": "vilan", "plural": "vilor", "plural_definite": "vilorna", "english": "rest"},
    {"indefinite": "spelare", "definite": "spelaren", "plural": "spelare", "plural_definite": "spelarna", "english": "player"},
    {"indefinite": "publik", "definite": "publiken", "plural": "publiker", "plural_definite": "publikerna", "english": "audience"},
    {"indefinite": "mål", "definite": "målet", "plural": "mål", "plural_definite": "målen", "english": "goal"},
]

verbs = [
    {"infinitive": "spela", "present": "spelar", "past": "spelade", "supine": "spelat", "english": "to play"},
    {"infinitive": "läsa", "present": "läser", "past": "läste", "supine": "läst", "english": "to read"},
    {"infinitive": "skriva", "present": "skriver", "past": "skrev", "supine": "skrivit", "english": "to write"},
    {"infinitive": "rita", "present": "ritar", "past": "ritade", "supine": "ritat", "english": "to draw"},
    {"infinitive": "måla", "present": "målar", "past": "målade", "supine": "målat", "english": "to paint"},
    {"infinitive": "sjunga", "present": "sjunger", "past": "sjöng", "supine": "sjungit", "english": "to sing"},
    {"infinitive": "dansa", "present": "dansar", "past": "dansade", "supine": "dansat", "english": "to dance"},
    {"infinitive": "titta", "present": "tittar", "past": "tittade", "supine": "tittat", "english": "to watch"},
    {"infinitive": "lyssna", "present": "lyssnar", "past": "lyssnade", "supine": "lyssnat", "english": "to listen"},
    {"infinitive": "springa", "present": "springer", "past": "sprang", "supine": "sprungit", "english": "to run"},
    {"infinitive": "simma", "present": "simmar", "past": "simmade", "supine": "simmat", "english": "to swim"},
    {"infinitive": "cykla", "present": "cyklar", "past": "cyklade", "supine": "cyklat", "english": "to cycle"},
    {"infinitive": "träna", "present": "tränar", "past": "tränade", "supine": "tränat", "english": "to exercise"},
    {"infinitive": "koppla av", "present": "kopplar av", "past": "kopplade av", "supine": "kopplat av", "english": "to relax"},
    {"infinitive": "resa", "present": "reser", "past": "reste", "supine": "rest", "english": "to travel"},
    {"infinitive": "besöka", "present": "besöker", "past": "besökte", "supine": "besökt", "english": "to visit"},
    {"infinitive": "träffas", "present": "träffas", "past": "träffades", "supine": "träffats", "english": "to meet (each other)"},
    {"infinitive": "njuta", "present": "njuter", "past": "njöt", "supine": "njutit", "english": "to enjoy"},
    {"infinitive": "delta", "present": "deltar", "past": "deltog", "supine": "deltagit", "english": "to participate"},
    {"infinitive": "vinna", "present": "vinner", "past": "vann", "supine": "vunnit", "english": "to win"},
]

misc = [
    {"swedish": "rolig", "english": "fun"},
    {"swedish": "intressant", "english": "interesting"},
    {"swedish": "avslappnande", "english": "relaxing"},
    {"swedish": "spännande", "english": "exciting"},
    {"swedish": "lugn", "english": "calm"},
    {"swedish": "social", "english": "social"},
    {"swedish": "aktiv", "english": "active"},
    {"swedish": "kreativ", "english": "creative"},
    {"swedish": "nyttig", "english": "beneficial"},
    {"swedish": "vanlig", "english": "common"},
    {"swedish": "sällsynt", "english": "rare"},
    {"swedish": "ibland", "english": "sometimes"},
    {"swedish": "ofta", "english": "often"},
    {"swedish": "sällan", "english": "rarely"},
    {"swedish": "aldrig", "english": "never"},
    {"swedish": "nästan alltid", "english": "almost always"},
    {"swedish": "på fritiden", "english": "in free time"},
    {"swedish": "tillsammans", "english": "together"},
    {"swedish": "ensam", "english": "alone"},
    {"swedish": "hellre", "english": "rather"},
    {"swedish": "gärna", "english": "gladly"},
    {"swedish": "mycket", "english": "a lot"},
    {"swedish": "lite", "english": "a little"},
    {"swedish": "till exempel", "english": "for example"},
    {"swedish": "för det mesta", "english": "for the most part"},
    {"swedish": "eftersom", "english": "because"},
    {"swedish": "så att", "english": "so that"},
]
