nouns = [
    {"indefinite": "lägenhet", "definite": "lägenheten", "plural": "lägenheter", "plural_definite": "lägenheterna", "english": "apartment"},
    {"indefinite": "villa", "definite": "villan", "plural": "villor", "plural_definite": "villorna", "english": "house, villa"},
    {"indefinite": "radhus", "definite": "radhuset", "plural": "radhus", "plural_definite": "radhusen", "english": "terraced house"},
    {"indefinite": "bostad", "definite": "bostaden", "plural": "bostäder", "plural_definite": "bostäderna", "english": "residence, dwelling"},
    {"indefinite": "hyra", "definite": "hyran", "plural": "hyror", "plural_definite": "hyrorna", "english": "rent"},
    {"indefinite": "hyresvärd", "definite": "hyresvärden", "plural": "hyresvärdar", "plural_definite": "hyresvärdarna", "english": "landlord"},
    {"indefinite": "hyresgäst", "definite": "hyresgästen", "plural": "hyresgäster", "plural_definite": "hyresgästerna", "english": "tenant"},
    {"indefinite": "granne", "definite": "grannen", "plural": "grannar", "plural_definite": "grannarna", "english": "neighbor"},
    {"indefinite": "område", "definite": "området", "plural": "områden", "plural_definite": "områdena", "english": "area, neighborhood"},
    {"indefinite": "adress", "definite": "adressen", "plural": "adresser", "plural_definite": "adresserna", "english": "address"},
    {"indefinite": "våning", "definite": "våningen", "plural": "våningar", "plural_definite": "våningarna", "english": "floor, level"},
    {"indefinite": "trappa", "definite": "trappan", "plural": "trappor", "plural_definite": "trapporna", "english": "staircase"},
    {"indefinite": "hiss", "definite": "hissen", "plural": "hissar", "plural_definite": "hissarna", "english": "elevator"},
    {"indefinite": "dörr", "definite": "dörren", "plural": "dörrar", "plural_definite": "dörrarna", "english": "door"},
    {"indefinite": "fönster", "definite": "fönstret", "plural": "fönster", "plural_definite": "fönstren", "english": "window"},
    {"indefinite": "tak", "definite": "taket", "plural": "tak", "plural_definite": "taken", "english": "roof, ceiling"},
    {"indefinite": "vägg", "definite": "väggen", "plural": "väggar", "plural_definite": "väggarna", "english": "wall"},
    {"indefinite": "golv", "definite": "golvet", "plural": "golv", "plural_definite": "golven", "english": "floor (surface)"},
    {"indefinite": "rum", "definite": "rummet", "plural": "rum", "plural_definite": "rummen", "english": "room"},
    {"indefinite": "vardagsrum", "definite": "vardagsrummet", "plural": "vardagsrum", "plural_definite": "vardagsrummen", "english": "living room"},
    {"indefinite": "sovrum", "definite": "sovrummet", "plural": "sovrum", "plural_definite": "sovrummen", "english": "bedroom"},
    {"indefinite": "kök", "definite": "köket", "plural": "kök", "plural_definite": "köken", "english": "kitchen"},
    {"indefinite": "badrum", "definite": "badrummet", "plural": "badrum", "plural_definite": "badrummen", "english": "bathroom"},
    {"indefinite": "toalett", "definite": "toaletten", "plural": "toaletter", "plural_definite": "toaletterna", "english": "toilet"},
    {"indefinite": "hall", "definite": "hallen", "plural": "hallar", "plural_definite": "hallarna", "english": "hall, entryway"},
    {"indefinite": "balkong", "definite": "balkongen", "plural": "balkonger", "plural_definite": "balkongerna", "english": "balcony"},
    {"indefinite": "trädgård", "definite": "trädgården", "plural": "trädgårdar", "plural_definite": "trädgårdarna", "english": "garden"},
    {"indefinite": "garage", "definite": "garaget", "plural": "garage", "plural_definite": "garagen", "english": "garage"},
    {"indefinite": "förråd", "definite": "förrådet", "plural": "förråd", "plural_definite": "förråden", "english": "storage room"},
    {"indefinite": "hylla", "definite": "hyllan", "plural": "hyllor", "plural_definite": "hyllorna", "english": "shelf"},
    {"indefinite": "soffa", "definite": "soffan", "plural": "soffor", "plural_definite": "sofforna", "english": "sofa"},
    {"indefinite": "stol", "definite": "stolen", "plural": "stolar", "plural_definite": "stolarna", "english": "chair"},
    {"indefinite": "bord", "definite": "bordet", "plural": "bord", "plural_definite": "borden", "english": "table"},
    {"indefinite": "säng", "definite": "sängen", "plural": "sängar", "plural_definite": "sängarna", "english": "bed"},
    {"indefinite": "matta", "definite": "mattan", "plural": "mattor", "plural_definite": "mattorna", "english": "rug"},
    {"indefinite": "lampa", "definite": "lampan", "plural": "lampor", "plural_definite": "lamporna", "english": "lamp"},
    {"indefinite": "gardin", "definite": "gardinen", "plural": "gardiner", "plural_definite": "gardinerna", "english": "curtain"},
    {"indefinite": "sopor", "definite": "soporna", "plural": "sopor", "plural_definite": "soporna", "english": "garbage"},
    {"indefinite": "tvättstuga", "definite": "tvättstugan", "plural": "tvättstugor", "plural_definite": "tvättstugorna", "english": "laundry room"},
    {"indefinite": "diskmaskin", "definite": "diskmaskinen", "plural": "diskmaskiner", "plural_definite": "diskmaskinerna", "english": "dishwasher"},
    {"indefinite": "ugn", "definite": "ugnen", "plural": "ugnar", "plural_definite": "ugnarna", "english": "oven"},
    {"indefinite": "spis", "definite": "spisen", "plural": "spisar", "plural_definite": "spisarna", "english": "stove"},
    {"indefinite": "kylskåp", "definite": "kylskåpet", "plural": "kylskåp", "plural_definite": "kylskåpen", "english": "fridge"},
    {"indefinite": "frys", "definite": "frysen", "plural": "frysar", "plural_definite": "frysarna", "english": "freezer"},
    {"indefinite": "tvättmaskin", "definite": "tvättmaskinen", "plural": "tvättmaskiner", "plural_definite": "tvättmaskinerna", "english": "washing machine"},
    {"indefinite": "torktumlare", "definite": "torktumlaren", "plural": "torktumlare", "plural_definite": "torktummarna", "english": "dryer"},
    {"indefinite": "elräkning", "definite": "elräkningen", "plural": "elräkningar", "plural_definite": "elräkningarna", "english": "electricity bill"},
    {"indefinite": "värme", "definite": "värmen", "plural": "värmar", "plural_definite": "värmarna", "english": "heat"},
    {"indefinite": "vatten", "definite": "vattnet", "plural": "vatten", "plural_definite": "vattnen", "english": "water"},
    {"indefinite": "luft", "definite": "luften", "plural": "lufter", "plural_definite": "lufterna", "english": "air"},
]

verbs = [
    {"infinitive": "städa", "present": "städar", "past": "städade", "supine": "städat", "english": "to clean"},
    {"infinitive": "diska", "present": "diskar", "past": "diskade", "supine": "diskat", "english": "to wash dishes"},
    {"infinitive": "tvätta", "present": "tvättar", "past": "tvättade", "supine": "tvättat", "english": "to wash (clothes)"},
    {"infinitive": "koka", "present": "kokar", "past": "kokade", "supine": "kokat", "english": "to boil"},
    {"infinitive": "baka", "present": "bakar", "past": "bakade", "supine": "bakat", "english": "to bake"},
    {"infinitive": "laga mat", "present": "lagar mat", "past": "lagade mat", "supine": "lagat mat", "english": "to cook"},
    {"infinitive": "bo", "present": "bor", "past": "bodde", "supine": "bott", "english": "to live (reside)"},
    {"infinitive": "flytta in", "present": "flyttar in", "past": "flyttade in", "supine": "flyttat in", "english": "to move in"},
    {"infinitive": "flytta ut", "present": "flyttar ut", "past": "flyttade ut", "supine": "flyttat ut", "english": "to move out"},
    {"infinitive": "renovera", "present": "renoverar", "past": "renoverade", "supine": "renoverat", "english": "to renovate"},
    {"infinitive": "måla", "present": "målar", "past": "målade", "supine": "målat", "english": "to paint"},
    {"infinitive": "bygga", "present": "bygger", "past": "byggde", "supine": "byggt", "english": "to build"},
    {"infinitive": "bo kvar", "present": "bor kvar", "past": "bodde kvar", "supine": "bott kvar", "english": "to remain living"},
    {"infinitive": "hyra", "present": "hyr", "past": "hyrde", "supine": "hyrt", "english": "to rent"},
    {"infinitive": "äga", "present": "äger", "past": "ägde", "supine": "ägt", "english": "to own"},
    {"infinitive": "sova", "present": "sover", "past": "sov", "supine": "sovit", "english": "to sleep"},
    {"infinitive": "vakna", "present": "vaknar", "past": "vaknade", "supine": "vaknat", "english": "to wake up"},
    {"infinitive": "släcka", "present": "släcker", "past": "släckte", "supine": "släckt", "english": "to turn off (light)"},
    {"infinitive": "tända", "present": "tänder", "past": "tände", "supine": "tänt", "english": "to light, turn on"},
    {"infinitive": "öppna", "present": "öppnar", "past": "öppnade", "supine": "öppnat", "english": "to open"},
    {"infinitive": "stänga", "present": "stänger", "past": "stängde", "supine": "stängt", "english": "to close"},
    {"infinitive": "vattna", "present": "vattnar", "past": "vattnade", "supine": "vattnat", "english": "to water (plants)"},
    {"infinitive": "slänga", "present": "slänger", "past": "slängde", "supine": "slängt", "english": "to throw away"},
    {"infinitive": "sopa", "present": "sopar", "past": "sopade", "supine": "sopat", "english": "to sweep"},
    {"infinitive": "torka", "present": "torkar", "past": "torkade", "supine": "torkat", "english": "to dry, wipe"},
    {"infinitive": "hänga", "present": "hänger", "past": "hängde", "supine": "hängt", "english": "to hang"},
    {"infinitive": "fixa", "present": "fixar", "past": "fixade", "supine": "fixat", "english": "to fix"},
    {"infinitive": "reparera", "present": "reparerar", "past": "reparerade", "supine": "reparerat", "english": "to repair"},
    {"infinitive": "låsa", "present": "låser", "past": "låsde", "supine": "låst", "english": "to lock"},
    {"infinitive": "byta", "present": "byter", "past": "bytte", "supine": "bytt", "english": "to change, replace"},
]

misc = [
    # Adjectives describing housing
    {"swedish": "bekväm", "english": "comfortable"},
    {"swedish": "rymlig", "english": "spacious"},
    {"swedish": "modern", "english": "modern"},
    {"swedish": "gammaldags", "english": "old-fashioned"},
    {"swedish": "ljus", "english": "bright"},
    {"swedish": "mörk", "english": "dark"},
    {"swedish": "tyst", "english": "quiet"},
    {"swedish": "bullrig", "english": "noisy"},
    {"swedish": "ren", "english": "clean"},
    {"swedish": "smutsig", "english": "dirty"},
    {"swedish": "trygg", "english": "safe"},
    {"swedish": "osäker", "english": "unsafe"},
    {"swedish": "billig", "english": "cheap"},
    {"swedish": "dyr", "english": "expensive"},
    {"swedish": "mysig", "english": "cozy"},
    {"swedish": "praktisk", "english": "practical"},
    {"swedish": "vacker", "english": "beautiful"},
    {"swedish": "hemtrevlig", "english": "homely, cozy"},
    {"swedish": "kall", "english": "cold"},
    {"swedish": "varm", "english": "warm"},

    # Adverbs / Connectors useful in describing housing
    {"swedish": "nära", "english": "near"},
    {"swedish": "långt bort", "english": "far away"},
    {"swedish": "inomhus", "english": "indoors"},
    {"swedish": "utomhus", "english": "outdoors"},
    {"swedish": "ovanpå", "english": "on top of"},
    {"swedish": "under", "english": "under"},
    {"swedish": "bredvid", "english": "next to"},
    {"swedish": "framför", "english": "in front of"},
    {"swedish": "bakom", "english": "behind"},
    {"swedish": "genom", "english": "through"},
    {"swedish": "mitt emot", "english": "opposite"},
    {"swedish": "på grund av", "english": "because of"},
    {"swedish": "trots", "english": "despite"},
    {"swedish": "eftersom", "english": "because"},
    {"swedish": "innan", "english": "before"},
    {"swedish": "efteråt", "english": "afterwards"},
]
