verbs = [
    {"english": "become", "infinitive": "bli", "present": "blir", "past": "blev", "supine": "blivit", "imperative": "bli", "cefr": 1, "frequency": 3293.35},
    {"english": "do/make", "infinitive": "göra", "present": "gör", "past": "gjorde", "supine": "gjort", "imperative": "gör", "cefr": 1, "frequency": 2942.04},
    {"english": "go", "infinitive": "gå", "present": "går", "past": "gick", "supine": "gått", "imperative": "gå", "cefr": 1, "frequency": 2001.14},
    {"english": "get/receive", "infinitive": "få", "present": "får", "past": "fick", "supine": "fått", "imperative": "få", "cefr": 1, "frequency": 4060.39},
    {"english": "give", "infinitive": "ge", "present": "ger", "past": "gav", "supine": "gett", "imperative": "ge", "cefr": 1, "frequency": 1208.51},
    {"english": "see", "infinitive": "se", "present": "ser", "past": "såg", "supine": "sett", "imperative": "se", "cefr": 1, "frequency": 2253.32},
    {"english": "sit", "infinitive": "sitta", "present": "sitter", "past": "satt", "supine": "suttit", "imperative": "sitt", "cefr": 1, "frequency": 280.32},
    {"english": "stand", "infinitive": "stå", "present": "står", "past": "stod", "supine": "stått", "imperative": "stå", "cefr": 1, "frequency": 761.80},
    {"english": "take", "infinitive": "ta", "present": "tar", "past": "tog", "supine": "tagit", "imperative": "ta", "cefr": 1, "frequency": 2452.40},
    {"english": "manage to", "infinitive": "lyckas", "present": "lyckas", "past": "lyckades", "supine": "lyckats", "imperative": "lyckas", "cefr": 1, "frequency": 384.14},
    {"english": "try", "infinitive": "försöka", "present": "försöker", "past": "försökte", "supine": "försökt", "imperative": "försök", "cefr": 1, "frequency": 859.72},
    {"english": "seem", "infinitive": "tyckas", "present": "tycks", "past": "tycktes", "supine": "tyckts", "imperative": "tyck", "cefr": 1, "frequency": None},
    {"english": "happen", "infinitive": "hända", "present": "händer", "past": "hände", "supine": "hänt", "imperative": "hända", "cefr": 1, "frequency": 307.66},
    {"english": "belong", "infinitive": "tillhöra", "present": "tillhör", "past": "tillhörde", "supine": "tillhört", "imperative": "tillhör", "cefr": 1, "frequency": 103.16},
    {"english": "seem", "infinitive": "synas", "present": "syns", "past": "syntes", "supine": "synts", "imperative": "syns", "cefr": 1, "frequency": 65.54},
    {"english": "know (a fact)", "infinitive": "veta", "present": "vet", "past": "visste", "supine": "vetat", "imperative": "veta", "cefr": 1, "frequency": 894.31},
    {"english": "buy", "infinitive": "köpa", "present": "köper", "past": "köpte", "supine": "köpt", "imperative": "köp", "cefr": 1, "frequency": 284.11},
    {"english": "sell", "infinitive": "sälja", "present": "säljer", "past": "sålde", "supine": "sålt", "imperative": "sälj", "cefr": 1, "frequency": 182.71},
    {"english": "lie (be lying)", "infinitive": "ligga", "present": "ligger", "past": "låg", "supine": "legat", "imperative": "ligg", "cefr": 1, "frequency": 566.60},
    {"english": "put/lay", "infinitive": "lägga", "present": "lägger", "past": "la", "supine": "lagt", "imperative": "lägg", "cefr": 1, "frequency": 545.17},
    {"english": "hold", "infinitive": "hålla", "present": "håller", "past": "höll", "supine": "hållit", "imperative": "håll", "cefr": 1, "frequency": 739.42},
    {"english": "meet", "infinitive": "träffa", "present": "träffar", "past": "träffade", "supine": "träffat", "imperative": "träffa", "cefr": 1, "frequency": 184.74},
    {"english": "help", "infinitive": "hjälpa", "present": "hjälper", "past": "hjälpte", "supine": "hjälpt", "imperative": "hjälp", "cefr": 1, "frequency": 238.92},
    {"english": "choose", "infinitive": "välja", "present": "väljer", "past": "valde", "supine": "valt", "imperative": "välj", "cefr": 1, "frequency": 403.72},
    {"english": "be able to / can", "infinitive": "kunna", "present": "kan", "past": "kunde", "supine": "kunnat", "imperative": "–", "cefr": 1, "frequency": 11119.08},
    {"english": "must / have to", "infinitive": "måste", "present": "måste", "past": "måste", "supine": "måst", "imperative": "–", "cefr": 1, "frequency": 2214.95},
    {"english": "want", "infinitive": "vilja", "present": "vill", "past": "ville", "supine": "velat", "imperative": "–", "cefr": 1, "frequency": 3004.91},
    {"english": "shall / will", "infinitive": "skola", "present": "ska", "past": "skulle", "supine": "skolat", "imperative": "–", "cefr": 1, "frequency": 10411.19},
    {"english": "need", "infinitive": "behöva", "present": "behöver", "past": "behövde", "supine": "behövt", "imperative": "behöv", "cefr": 1, "frequency": 858.16},
    {"english": "die", "infinitive": "dö", "present": "dör", "past": "dog", "supine": "dött", "imperative": "dö", "cefr": 1, "frequency": 164.30},
    {"english": "bring", "infinitive": "ta med", "present": "tar med", "past": "tog med", "supine": "tagit med", "imperative": "ta med", "cefr": 1, "frequency": None},
    {"english": "drive", "infinitive": "köra", "present": "kör", "past": "körde", "supine": "kört", "imperative": "kör", "cefr": 1, "frequency": 203.16},
    {"english": "send", "infinitive": "skicka", "present": "skickar", "past": "skickade", "supine": "skickat", "imperative": "skicka", "cefr": 1, "frequency": 192.84},
    {"english": "wait", "infinitive": "vänta", "present": "väntar", "past": "väntade", "supine": "väntat", "imperative": "vänta", "cefr": 1, "frequency": 225.55},
    {"english": "lose", "infinitive": "förlora", "present": "förlorar", "past": "förlorade", "supine": "förlorat", "imperative": "förlora", "cefr": 1, "frequency": 126.19},
    {"english": "think", "infinitive": "tänka", "present": "tänker", "past": "tänkte", "supine": "tänkt", "imperative": "tänk", "cefr": 1, "frequency": 666.70},
    {"english": "invite", "infinitive": "bjuda", "present": "bjuder", "past": "bjöd", "supine": "bjudit", "imperative": "bjud", "cefr": 1, "frequency": 139.86},
]
