verbs = [
    {"type": "verb", "english": "be", "infinitive": "vara", "present": "är", "past": "var", "supine": "varit", "imperative": "var"},
    {"type": "verb", "english": "become", "infinitive": "bli", "present": "blir", "past": "blev", "supine": "blivit", "imperative": "bli"},
    {"type": "verb", "english": "do/make", "infinitive": "göra", "present": "gör", "past": "gjorde", "supine": "gjort", "imperative": "gör"},
    {"type": "verb", "english": "go", "infinitive": "gå", "present": "går", "past": "gick", "supine": "gått", "imperative": "gå"},
    {"type": "verb", "english": "come", "infinitive": "komma", "present": "kommer", "past": "kom", "supine": "kommit", "imperative": "kom"},
    {"type": "verb", "english": "get/receive", "infinitive": "få", "present": "får", "past": "fick", "supine": "fått", "imperative": "få"},
    {"type": "verb", "english": "give", "infinitive": "ge", "present": "ger", "past": "gav", "supine": "gett", "imperative": "ge"},
    {"type": "verb", "english": "see", "infinitive": "se", "present": "ser", "past": "såg", "supine": "sett", "imperative": "se"},
    {"type": "verb", "english": "sit", "infinitive": "sitta", "present": "sitter", "past": "satt", "supine": "suttit", "imperative": "sitt"},
    {"type": "verb", "english": "stand", "infinitive": "stå", "present": "står", "past": "stod", "supine": "stått", "imperative": "stå"},
    {"type": "verb", "english": "take", "infinitive": "ta", "present": "tar", "past": "tog", "supine": "tagit", "imperative": "ta"},
    {"type": "verb", "english": "manage to", "infinitive": "lyckas", "present": "lyckas", "past": "lyckades", "supine": "lyckats", "imperative": "lyckas"},
    {"type": "verb", "english": "try", "infinitive": "försöka", "present": "försöker", "past": "försökte", "supine": "försökt", "imperative": "försök"},
    {"type": "verb", "english": "seem", "infinitive": "tyckas", "present": "tycks", "past": "tycktes", "supine": "tyckts", "imperative": "tyck"},
    {"type": "verb", "english": "breathe", "infinitive": "andas", "present": "andas", "past": "andades", "supine": "andats", "imperative": "andas"},
    {"type": "verb", "english": "happen", "infinitive": "hända", "present": "händer", "past": "hände", "supine": "hänt", "imperative": "hända"},
    {"type": "verb", "english": "belong", "infinitive": "tillhöra", "present": "tillhör", "past": "tillhörde", "supine": "tillhört", "imperative": "tillhör"},
    {"type": "verb", "english": "believe", "infinitive": "tro", "present": "tror", "past": "trodde", "supine": "trott", "imperative": "tro"},
    {"type": "verb", "english": "seem", "infinitive": "synas", "present": "syns", "past": "syntes", "supine": "synts", "imperative": "syns"},
    {"type": "verb", "english": "belong", "infinitive": "tillhöra", "present": "tillhör", "past": "tillhörde", "supine": "tillhört", "imperative": "tillhör"},
    {"type": "verb", "english": "succeed", "infinitive": "lyckas", "present": "lyckas", "past": "lyckades", "supine": "lyckats", "imperative": "lyckas"},
    {"type": "verb", "english": "know (a fact)", "infinitive": "veta", "present": "vet", "past": "visste", "supine": "vetat", "imperative": "veta"},
    {"type": "verb", "english": "know (be familiar with)", "infinitive": "känna", "present": "känner", "past": "kände", "supine": "känt", "imperative": "känn"},
    {"type": "verb", "english": "say", "infinitive": "säga", "present": "säger", "past": "sa", "supine": "sagt", "imperative": "säg"},
    {"type": "verb", "english": "write", "infinitive": "skriva", "present": "skriver", "past": "skrev", "supine": "skrivit", "imperative": "skriv"},
    {"type": "verb", "english": "eat", "infinitive": "äta", "present": "äter", "past": "åt", "supine": "ätit", "imperative": "ät"},
    {"type": "verb", "english": "drink", "infinitive": "dricka", "present": "dricker", "past": "drack", "supine": "druckit", "imperative": "drick"},
    {"type": "verb", "english": "sleep", "infinitive": "sova", "present": "sover", "past": "sov", "supine": "sovit", "imperative": "sov"},
    {"type": "verb", "english": "run", "infinitive": "springa", "present": "springer", "past": "sprang", "supine": "sprungit", "imperative": "spring"},
    {"type": "verb", "english": "understand", "infinitive": "förstå", "present": "förstår", "past": "förstod", "supine": "förstått", "imperative": "förstå"},
    {"type": "verb", "english": "buy", "infinitive": "köpa", "present": "köper", "past": "köpte", "supine": "köpt", "imperative": "köp"},
    {"type": "verb", "english": "sell", "infinitive": "sälja", "present": "säljer", "past": "sålde", "supine": "sålt", "imperative": "sälj"},
    {"type": "verb", "english": "read", "infinitive": "läsa", "present": "läser", "past": "läste", "supine": "läst", "imperative": "läs"},
    {"type": "verb", "english": "lie (be lying)", "infinitive": "ligga", "present": "ligger", "past": "låg", "supine": "legat", "imperative": "ligg"},
    {"type": "verb", "english": "put/lay", "infinitive": "lägga", "present": "lägger", "past": "la", "supine": "lagt", "imperative": "lägg"},
    {"type": "verb", "english": "hold", "infinitive": "hålla", "present": "håller", "past": "höll", "supine": "hållit", "imperative": "håll"},
    {"type": "verb", "english": "meet", "infinitive": "träffa", "present": "träffar", "past": "träffade", "supine": "träffat", "imperative": "träffa"},
    {"type": "verb", "english": "help", "infinitive": "hjälpa", "present": "hjälper", "past": "hjälpte", "supine": "hjälpt", "imperative": "hjälp"},
    {"type": "verb", "english": "choose", "infinitive": "välja", "present": "väljer", "past": "valde", "supine": "valt", "imperative": "välj"},
    {"type": "verb", "english": "be able to / can", "infinitive": "kunna", "present": "kan", "past": "kunde", "supine": "kunnat", "imperative": "–"},
    {"type": "verb", "english": "must / have to", "infinitive": "måste", "present": "måste", "past": "måste", "supine": "måst", "imperative": "–"},
    {"type": "verb", "english": "want", "infinitive": "vilja", "present": "vill", "past": "ville", "supine": "velat", "imperative": "–"},
    {"type": "verb", "english": "shall / will", "infinitive": "skola", "present": "ska", "past": "skulle", "supine": "skolat", "imperative": "–"},
    {"type": "verb", "english": "need", "infinitive": "behöva", "present": "behöver", "past": "behövde", "supine": "behövt", "imperative": "behöv"},
    {"type": "verb", "english": "die", "infinitive": "dö", "present": "dör", "past": "dog", "supine": "dött", "imperative": "dö"},
    {"type": "verb", "english": "live", "infinitive": "leva", "present": "lever", "past": "levde", "supine": "levt", "imperative": "lev"},
    {"type": "verb", "english": "bring", "infinitive": "ta med", "present": "tar med", "past": "tog med", "supine": "tagit med", "imperative": "ta med"},
    {"type": "verb", "english": "begin", "infinitive": "börja", "present": "börjar", "past": "började", "supine": "börjat", "imperative": "börja"},
    {"type": "verb", "english": "drive", "infinitive": "köra", "present": "kör", "past": "körde", "supine": "kört", "imperative": "kör"},
    {"type": "verb", "english": "send", "infinitive": "skicka", "present": "skickar", "past": "skickade", "supine": "skickat", "imperative": "skicka"},
    {"type": "verb", "english": "wait", "infinitive": "vänta", "present": "väntar", "past": "väntade", "supine": "väntat", "imperative": "vänta"},
    {"type": "verb", "english": "win", "infinitive": "vinna", "present": "vinner", "past": "vann", "supine": "vunnit", "imperative": "vinn"},
    {"type": "verb", "english": "lose", "infinitive": "förlora", "present": "förlorar", "past": "förlorade", "supine": "förlorat", "imperative": "förlora"},
    {"type": "verb", "english": "think", "infinitive": "tänka", "present": "tänker", "past": "tänkte", "supine": "tänkt", "imperative": "tänk"},
    {"type": "verb", "english": "believe", "infinitive": "tro", "present": "tror", "past": "trodde", "supine": "trott", "imperative": "tro"},
    {"type": "verb", "english": "feel", "infinitive": "må", "present": "mår", "past": "mådde", "supine": "mått", "imperative": "må"},
    {"type": "verb", "english": "invite", "infinitive": "bjuda", "present": "bjuder", "past": "bjöd", "supine": "bjudit", "imperative": "bjud"},
]