misc = [
    {"swedish": "jag", "english": "I"},
    {"swedish": "du", "english": "you (singular)"},
    {"swedish": "han", "english": "he"},
    {"swedish": "hon", "english": "she"},
    {"swedish": "hen", "english": "they (gender-neutral singular)"},
    {"swedish": "vi", "english": "we"},
    {"swedish": "ni", "english": "you (plural)"},
    {"swedish": "de", "english": "they"},
    {"swedish": "dem", "english": "them"},
    {"swedish": "den", "english": "it (common gender)"},
    {"swedish": "det", "english": "it (neuter)"},
    {"swedish": "mig", "english": "me / myself"},
    {"swedish": "dig", "english": "you / yourself"},
    {"swedish": "sig", "english": "himself / herself / itself / themselves"},
    {"swedish": "oss", "english": "us / ourselves"},
    {"swedish": "er", "english": "you (plural) / yourselves"},
    {"swedish": "min", "english": "my (en-word)"},
    {"swedish": "mitt", "english": "my (ett-word)"},
    {"swedish": "mina", "english": "my (plural)"},
    {"swedish": "din", "english": "your (en-word)"},
    {"swedish": "ditt", "english": "your (ett-word)"},
    {"swedish": "dina", "english": "your (plural)"},
    {"swedish": "sin", "english": "his/her/their own (en-word)"},
    {"swedish": "sitt", "english": "his/her/their own (ett-word)"},
    {"swedish": "sina", "english": "his/her/their own (plural)"},
    {"swedish": "hans", "english": "his"},
    {"swedish": "hennes", "english": "hers"},
    {"swedish": "deras", "english": "theirs"},
    {"swedish": "vår", "english": "our (en-word)"},
    {"swedish": "vårt", "english": "our (ett-word)"},
    {"swedish": "våra", "english": "our (plural)"},
    {"swedish": "er", "english": "your (plural, en-word)"},
    {"swedish": "ert", "english": "your (plural, ett-word)"},
    {"swedish": "era", "english": "your (plural, plural form)"},
    {"swedish": "den här", "english": "this (en-word)"},
    {"swedish": "det här", "english": "this (ett-word)"},
    {"swedish": "de här", "english": "these"},
    {"swedish": "den där", "english": "that (en-word)"},
    {"swedish": "det där", "english": "that (ett-word)"},
    {"swedish": "de där", "english": "those"},
    {"swedish": "denna", "english": "this (formal, en-word)"},
    {"swedish": "detta", "english": "this (formal, ett-word)"},
    {"swedish": "dessa", "english": "these (formal)"},
    {"swedish": "som", "english": "who / which / that"},
    {"swedish": "vars", "english": "whose"},
    {"swedish": "vad", "english": "what / that which"},
    {"swedish": "vem", "english": "who"},
    {"swedish": "vems", "english": "whose"},
    {"swedish": "vad", "english": "what"},
    {"swedish": "vilken", "english": "which (en-word)"},
    {"swedish": "vilket", "english": "which (ett-word)"},
    {"swedish": "vilka", "english": "which (plural)"},
    {"swedish": "någon", "english": "someone (en-word)"},
    {"swedish": "något", "english": "something (ett-word)"},
    {"swedish": "några", "english": "some (plural)"},
    {"swedish": "ingen", "english": "no one / nobody (en-word)"},
    {"swedish": "inget", "english": "nothing / not anything (ett-word)"},
    {"swedish": "inga", "english": "none / no (plural)"},
    {"swedish": "alla", "english": "everyone / all"},
    {"swedish": "allt", "english": "everything"},
    {"swedish": "man", "english": "one / you (generic)"},
    {"swedish": "varje", "english": "each / every"},
    {"swedish": "det är", "english": "it is / there is (identifying or describing)"},
    {"swedish": "det finns", "english": "there is / there are (existence)"},
    {"swedish": "det fanns", "english": "there was / there were"},
    {"swedish": "finns det", "english": "is there / are there"},
    {"swedish": "det där", "english": "that (neutral)"},
    {"swedish": "det här", "english": "this (neutral)"},
    {"swedish": "sig", "english": "oneself / himself / herself"},
    {"swedish": "som", "english": "that / who (relative connector)"},
]
