misc = [
    {"swedish": "jag", "english": "I", "cefr": 1, "frequency": 9390.67},
    {"swedish": "du", "english": "you (singular)", "cefr": 1, "frequency": 2581.46},
    {"swedish": "han", "english": "he", "cefr": 1, "frequency": 3380.88},
    {"swedish": "hon", "english": "she", "cefr": 1, "frequency": 1291.75},
    {"swedish": "hen", "english": "they (gender-neutral singular)", "cefr": 1, "frequency": None},
    {"swedish": "vi", "english": "we", "cefr": 1, "frequency": 4723.57},
    {"swedish": "ni", "english": "you (plural)", "cefr": 1, "frequency": 665.01},
    {"swedish": "de", "english": "they", "cefr": 1, "frequency": 4437.26},
    {"swedish": "dem", "english": "them", "cefr": 1, "frequency": 1341.39},
    {"swedish": "den", "english": "it (common gender)", "cefr": 1, "frequency": 6896.18},
    {"swedish": "det", "english": "it (neuter)", "cefr": 1, "frequency": 14582.21},
    {"swedish": "mig", "english": "me / myself", "cefr": 1, "frequency": 1622.70},
    {"swedish": "dig", "english": "you / yourself", "cefr": 1, "frequency": 590.81},
    {"swedish": "sig", "english": "himself / herself / itself / themselves", "cefr": 1, "frequency": 3469.03},
    {"swedish": "oss", "english": "us / ourselves", "cefr": 1, "frequency": 934.32},
    {"swedish": "er", "english": "you (plural) / yourselves", "cefr": 1, "frequency": 403.60},
    {"swedish": "min", "english": "my (en-word)", "cefr": 1, "frequency": 1757.18},
    {"swedish": "mitt", "english": "my (ett-word)", "cefr": 1, "frequency": 95.61},
    {"swedish": "mina", "english": "my (plural)", "cefr": 1, "frequency": None},
    {"swedish": "din", "english": "your (en-word)", "cefr": 1, "frequency": 771.62},
    {"swedish": "ditt", "english": "your (ett-word)", "cefr": 1, "frequency": None},
    {"swedish": "dina", "english": "your (plural)", "cefr": 1, "frequency": None},
    {"swedish": "sin", "english": "his/her/their own (en-word)", "cefr": 1, "frequency": 3217.30},
    {"swedish": "sitt", "english": "his/her/their own (ett-word)", "cefr": 1, "frequency": None},
    {"swedish": "sina", "english": "his/her/their own (plural)", "cefr": 1, "frequency": None},
    {"swedish": "hans", "english": "his", "cefr": 1, "frequency": 774.60},
    {"swedish": "hennes", "english": "hers", "cefr": 1, "frequency": 275.94},
    {"swedish": "deras", "english": "theirs", "cefr": 1, "frequency": 623.86},
    {"swedish": "vår", "english": "our (en-word)", "cefr": 1, "frequency": 1206.78},
    {"swedish": "vårt", "english": "our (ett-word)", "cefr": 1, "frequency": None},
    {"swedish": "våra", "english": "our (plural)", "cefr": 1, "frequency": None},
    {"swedish": "ert", "english": "your (plural, ett-word)", "cefr": 1, "frequency": None},
    {"swedish": "era", "english": "your (plural, plural form)", "cefr": 2, "frequency": 29.60},
    {"swedish": "den här", "english": "this (en-word)", "cefr": 1, "frequency": None},
    {"swedish": "det här", "english": "this (ett-word)", "cefr": 1, "frequency": None},
    {"swedish": "de här", "english": "these", "cefr": 1, "frequency": None},
    {"swedish": "den där", "english": "that (en-word)", "cefr": 1, "frequency": None},
    {"swedish": "det där", "english": "that (ett-word)", "cefr": 1, "frequency": None},
    {"swedish": "de där", "english": "those", "cefr": 1, "frequency": None},
    {"swedish": "denna", "english": "this (formal, en-word)", "cefr": 1, "frequency": 1279.97},
    {"swedish": "detta", "english": "this (formal, ett-word)", "cefr": 1, "frequency": 2200.74},
    {"swedish": "dessa", "english": "these (formal)", "cefr": 1, "frequency": None},
    {"swedish": "som", "english": "who / which / that", "cefr": 1, "frequency": 12734.70},
    {"swedish": "vars", "english": "whose", "cefr": 1, "frequency": None},
    {"swedish": "vad", "english": "what / that which", "cefr": 1, "frequency": 1911.20},
    {"swedish": "vem", "english": "who", "cefr": 1, "frequency": 243.27},
    {"swedish": "vems", "english": "whose", "cefr": 1, "frequency": None},
    {"swedish": "vilken", "english": "which (en-word)", "cefr": 1, "frequency": 1512.84},
    {"swedish": "vilka", "english": "which (plural)", "cefr": 1, "frequency": None},
    {"swedish": "någon", "english": "someone (en-word)", "cefr": 1, "frequency": 2565.69},
    {"swedish": "något", "english": "something (ett-word)", "cefr": 2, "frequency": 55.74},
    {"swedish": "några", "english": "some (plural)", "cefr": 1, "frequency": None},
    {"swedish": "ingen", "english": "no one / nobody (en-word)", "cefr": 1, "frequency": 1350.90},
    {"swedish": "inget", "english": "nothing / not anything (ett-word)", "cefr": 1, "frequency": None},
    {"swedish": "inga", "english": "none / no (plural)", "cefr": 1, "frequency": None},
    {"swedish": "alla", "english": "everyone / all", "cefr": 1, "frequency": None},
    {"swedish": "allt", "english": "everything", "cefr": 1, "frequency": 163.95},
    {"swedish": "man", "english": "one / you (generic)", "cefr": 1, "frequency": 4446.34},
    {"swedish": "det är", "english": "it is / there is (identifying or describing)", "cefr": 1, "frequency": None},
    {"swedish": "det finns", "english": "there is / there are (existence)", "cefr": 1, "frequency": None},
    {"swedish": "det fanns", "english": "there was / there were", "cefr": 1, "frequency": None},
    {"swedish": "finns det", "english": "is there / are there", "cefr": 1, "frequency": None},
]
