nouns = [
    {"indefinite": "affär", "definite": "affären", "plural": "affärer", "plural_definite": "affärerna", "english": "shop, store"},
    {"indefinite": "butik", "definite": "butiken", "plural": "butiker", "plural_definite": "butikerna", "english": "boutique, store"},
    {"indefinite": "stormarknad", "definite": "stormarknaden", "plural": "stormarknader", "plural_definite": "stormarknaderna", "english": "supermarket"},
    {"indefinite": "livsmedel", "definite": "livsmedlet", "plural": "livsmedel", "plural_definite": "livsmedlen", "english": "grocery, foodstuff"},
    {"indefinite": "kund", "definite": "kunden", "plural": "kunder", "plural_definite": "kunderna", "english": "customer"},
    {"indefinite": "kassa", "definite": "kassan", "plural": "kassor", "plural_definite": "kassorna", "english": "cash register, checkout"},
    {"indefinite": "kassör", "definite": "kassören", "plural": "kassörer", "plural_definite": "kassörerna", "english": "cashier"},
    {"indefinite": "pris", "definite": "priset", "plural": "priser", "plural_definite": "priserna", "english": "price"},
    {"indefinite": "rabatt", "definite": "rabatten", "plural": "rabatter", "plural_definite": "rabatterna", "english": "discount"},
    {"indefinite": "kvitto", "definite": "kvittot", "plural": "kvitton", "plural_definite": "kvittona", "english": "receipt"},
    {"indefinite": "vara", "definite": "varan", "plural": "varor", "plural_definite": "varorna", "english": "product, item"},
    {"indefinite": "påse", "definite": "påsen", "plural": "påsar", "plural_definite": "påsarna", "english": "bag"},
    {"indefinite": "korg", "definite": "korgen", "plural": "korgar", "plural_definite": "korgarna", "english": "basket"},
    {"indefinite": "vagn", "definite": "vagnen", "plural": "vagnar", "plural_definite": "vagnarna", "english": "shopping cart"},
    {"indefinite": "kö", "definite": "kön", "plural": "köer", "plural_definite": "köerna", "english": "queue, line"},
    {"indefinite": "bank", "definite": "banken", "plural": "banker", "plural_definite": "bankerna", "english": "bank"},
    {"indefinite": "konto", "definite": "kontot", "plural": "konton", "plural_definite": "kontona", "english": "account"},
    {"indefinite": "kort", "definite": "kortet", "plural": "kort", "plural_definite": "korten", "english": "card"},
    {"indefinite": "kontanter", "definite": "kontanterna", "plural": "kontanter", "plural_definite": "kontanterna", "english": "cash"},
    {"indefinite": "betalning", "definite": "betalningen", "plural": "betalningar", "plural_definite": "betalningarna", "english": "payment"},
    {"indefinite": "faktura", "definite": "fakturan", "plural": "fakturor", "plural_definite": "fakturorna", "english": "invoice"},
    {"indefinite": "tjänst", "definite": "tjänsten", "plural": "tjänster", "plural_definite": "tjänsterna", "english": "service"},
    {"indefinite": "kundservice", "definite": "kundservicen", "plural": "kundservicar", "plural_definite": "kundservicarna", "english": "customer service"},
    {"indefinite": "post", "definite": "posten", "plural": "poster", "plural_definite": "posterna", "english": "mail"},
    {"indefinite": "paket", "definite": "paketet", "plural": "paket", "plural_definite": "paketen", "english": "package"},
    {"indefinite": "brev", "definite": "brevet", "plural": "brev", "plural_definite": "breven", "english": "letter"},
    {"indefinite": "frimärke", "definite": "frimärket", "plural": "frimärken", "plural_definite": "frimärkena", "english": "stamp"},
    {"indefinite": "apotek", "definite": "apoteket", "plural": "apotek", "plural_definite": "apoteken", "english": "pharmacy"},
    {"indefinite": "present", "definite": "presenten", "plural": "presenter", "plural_definite": "presenterna", "english": "gift"},
    {"indefinite": "kläder", "definite": "kläderna", "plural": "kläder", "plural_definite": "kläderna", "english": "clothes"},
    {"indefinite": "skor", "definite": "skorna", "plural": "skor", "plural_definite": "skorna", "english": "shoes"},
    {"indefinite": "kvitto", "definite": "kvittot", "plural": "kvitton", "plural_definite": "kvittona", "english": "receipt"},
    {"indefinite": "prislista", "definite": "prislistan", "plural": "prislistor", "plural_definite": "prislistorna", "english": "price list"},
    {"indefinite": "kundkort", "definite": "kundkortet", "plural": "kundkort", "plural_definite": "kundkorten", "english": "loyalty card"},
    {"indefinite": "reklamation", "definite": "reklamationen", "plural": "reklamationer", "plural_definite": "reklamationerna", "english": "complaint, return"},
    {"indefinite": "utgift", "definite": "utgiften", "plural": "utgifter", "plural_definite": "utgifterna", "english": "expense"},
    {"indefinite": "inkomst", "definite": "inkomsten", "plural": "inkomster", "plural_definite": "inkomsterna", "english": "income"},
    {"indefinite": "försäkring", "definite": "försäkringen", "plural": "försäkringar", "plural_definite": "försäkringarna", "english": "insurance"},
    {"indefinite": "tillgång", "definite": "tillgången", "plural": "tillgångar", "plural_definite": "tillgångarna", "english": "asset"},
    {"indefinite": "reklam", "definite": "reklamen", "plural": "reklamer", "plural_definite": "reklamerna", "english": "advertisement"},
    {"indefinite": "erbjudande", "definite": "erbjudandet", "plural": "erbjudanden", "plural_definite": "erbjudandena", "english": "offer"},
    {"indefinite": "prisnivå", "definite": "prisnivån", "plural": "prisnivåer", "plural_definite": "prisnivåerna", "english": "price level"},
    {"indefinite": "butikskedja", "definite": "butikskedjan", "plural": "butikskedjor", "plural_definite": "butikskedjorna", "english": "store chain"},
    {"indefinite": "kundvagn", "definite": "kundvagnen", "plural": "kundvagnar", "plural_definite": "kundvagnarna", "english": "shopping cart"},
    {"indefinite": "färg", "definite": "färgen", "plural": "färger", "plural_definite": "färgerna", "english": "color"},
    {"indefinite": "storlek", "definite": "storleken", "plural": "storlekar", "plural_definite": "storlekarna", "english": "size"},
    {"indefinite": "vara", "definite": "varan", "plural": "varor", "plural_definite": "varorna", "english": "goods"},
    {"indefinite": "kundtjänst", "definite": "kundtjänsten", "plural": "kundtjänster", "plural_definite": "kundtjänsterna", "english": "customer support"},
]

verbs = [
    {"infinitive": "handla", "present": "handlar", "past": "handlade", "supine": "handlat", "english": "to shop"},
    {"infinitive": "betala", "present": "betalar", "past": "betalade", "supine": "betalat", "english": "to pay"},
    {"infinitive": "sälja", "present": "säljer", "past": "sålde", "supine": "sålt", "english": "to sell"},
    {"infinitive": "köpa", "present": "köper", "past": "köpte", "supine": "köpt", "english": "to buy"},
    {"infinitive": "returnera", "present": "returnerar", "past": "returnerade", "supine": "returnerat", "english": "to return (an item)"},
    {"infinitive": "prova", "present": "provar", "past": "provade", "supine": "provat", "english": "to try (clothes)"},
    {"infinitive": "välja", "present": "väljer", "past": "valde", "supine": "valt", "english": "to choose"},
    {"infinitive": "beställa", "present": "beställer", "past": "beställde", "supine": "beställt", "english": "to order"},
    {"infinitive": "skicka", "present": "skickar", "past": "skickade", "supine": "skickat", "english": "to send"},
    {"infinitive": "hämta", "present": "hämtar", "past": "hämtade", "supine": "hämtat", "english": "to pick up, fetch"},
    {"infinitive": "lämna", "present": "lämnar", "past": "lämnade", "supine": "lämnat", "english": "to leave, drop off"},
    {"infinitive": "reklamera", "present": "reklamerar", "past": "reklamerade", "supine": "reklamerat", "english": "to complain, make a claim"},
    {"infinitive": "fungera", "present": "fungerar", "past": "fungerade", "supine": "fungerat", "english": "to function, work"},
    {"infinitive": "låna", "present": "lånar", "past": "lånade", "supine": "lånat", "english": "to borrow"},
    {"infinitive": "växla", "present": "växlar", "past": "växlade", "supine": "växlat", "english": "to exchange (money)"},
    {"infinitive": "spara", "present": "sparar", "past": "sparade", "supine": "sparat", "english": "to save (money)"},
    {"infinitive": "spendera", "present": "spenderar", "past": "spenderade", "supine": "spenderat", "english": "to spend (money)"},
    {"infinitive": "använda", "present": "använder", "past": "använde", "supine": "använt", "english": "to use"},
    {"infinitive": "öppna", "present": "öppnar", "past": "öppnade", "supine": "öppnat", "english": "to open"},
    {"infinitive": "stänga", "present": "stänger", "past": "stängde", "supine": "stängt", "english": "to close"},
    {"infinitive": "packa", "present": "packar", "past": "packade", "supine": "packat", "english": "to pack"},
    {"infinitive": "reparera", "present": "reparerar", "past": "reparerade", "supine": "reparerat", "english": "to repair"},
]

misc = [
    {"swedish": "billig", "english": "cheap"},
    {"swedish": "dyr", "english": "expensive"},
    {"swedish": "nöjd", "english": "satisfied"},
    {"swedish": "missnöjd", "english": "dissatisfied"},
    {"swedish": "tillgänglig", "english": "available"},
    {"swedish": "upptagen", "english": "busy"},
    {"swedish": "stängd", "english": "closed"},
    {"swedish": "öppen", "english": "open"},
    {"swedish": "gratis", "english": "free (no cost)"},
    {"swedish": "snabb", "english": "fast"},
    {"swedish": "långsam", "english": "slow"},
    {"swedish": "bekväm", "english": "convenient"},
    {"swedish": "rättvis", "english": "fair"},
    {"swedish": "orättvis", "english": "unfair"},
    {"swedish": "direkt", "english": "directly"},
    {"swedish": "vanligtvis", "english": "usually"},
    {"swedish": "ibland", "english": "sometimes"},
    {"swedish": "ofta", "english": "often"},
    {"swedish": "sällan", "english": "rarely"},
    {"swedish": "snart", "english": "soon"},
    {"swedish": "redan", "english": "already"},
    {"swedish": "ännu inte", "english": "not yet"},
    {"swedish": "till exempel", "english": "for example"},
    {"swedish": "på grund av", "english": "because of"},
    {"swedish": "trots", "english": "despite"},
    {"swedish": "dessutom", "english": "in addition"},
    {"swedish": "därför", "english": "therefore"},
    {"swedish": "till slut", "english": "finally"},
]
