nouns = [
    {"indefinite": "affär", "definite": "affären", "plural": "affärer", "plural_definite": "affärerna", "english": "shop, store", "cefr": 2, "frequency": 63.08},
    {"indefinite": "butik", "definite": "butiken", "plural": "butiker", "plural_definite": "butikerna", "english": "boutique, store", "cefr": 2, "frequency": 47.83},
    {"indefinite": "stormarknad", "definite": "stormarknaden", "plural": "stormarknader", "plural_definite": "stormarknaderna", "english": "supermarket", "cefr": 1, "frequency": None},
    {"indefinite": "livsmedel", "definite": "livsmedlet", "plural": "livsmedel", "plural_definite": "livsmedlen", "english": "grocery, foodstuff", "cefr": 3, "frequency": 21.55},
    {"indefinite": "kund", "definite": "kunden", "plural": "kunder", "plural_definite": "kunderna", "english": "customer", "cefr": 1, "frequency": 112.31},
    {"indefinite": "kassa", "definite": "kassan", "plural": "kassor", "plural_definite": "kassorna", "english": "cash register, checkout", "cefr": 2, "frequency": 32.91},
    {"indefinite": "kassör", "definite": "kassören", "plural": "kassörer", "plural_definite": "kassörerna", "english": "cashier", "cefr": 1, "frequency": None},
    {"indefinite": "pris", "definite": "priset", "plural": "priser", "plural_definite": "priserna", "english": "price", "cefr": 1, "frequency": 172.92},
    {"indefinite": "rabatt", "definite": "rabatten", "plural": "rabatter", "plural_definite": "rabatterna", "english": "discount", "cefr": 1, "frequency": None},
    {"indefinite": "kvitto", "definite": "kvittot", "plural": "kvitton", "plural_definite": "kvittona", "english": "receipt", "cefr": 1, "frequency": None},
    {"indefinite": "vara", "definite": "varan", "plural": "varor", "plural_definite": "varorna", "english": "product, item", "cefr": 1, "frequency": 23017.26},
    {"indefinite": "påse", "definite": "påsen", "plural": "påsar", "plural_definite": "påsarna", "english": "bag", "cefr": 3, "frequency": 12.93},
    {"indefinite": "korg", "definite": "korgen", "plural": "korgar", "plural_definite": "korgarna", "english": "basket", "cefr": 1, "frequency": None},
    {"indefinite": "vagn", "definite": "vagnen", "plural": "vagnar", "plural_definite": "vagnarna", "english": "shopping cart", "cefr": 2, "frequency": 26.71},
    {"indefinite": "kö", "definite": "kön", "plural": "köer", "plural_definite": "köerna", "english": "queue, line", "cefr": 3, "frequency": 21.38},
    {"indefinite": "bank", "definite": "banken", "plural": "banker", "plural_definite": "bankerna", "english": "bank", "cefr": 1, "frequency": 105.47},
    {"indefinite": "konto", "definite": "kontot", "plural": "konton", "plural_definite": "kontona", "english": "account", "cefr": 2, "frequency": 25.67},
    {"indefinite": "kort", "definite": "kortet", "plural": "kort", "plural_definite": "korten", "english": "card", "cefr": 1, "frequency": 204.59},
    {"indefinite": "kontanter", "definite": "kontanterna", "plural": "kontanter", "plural_definite": "kontanterna", "english": "cash", "cefr": 1, "frequency": None},
    {"indefinite": "betalning", "definite": "betalningen", "plural": "betalningar", "plural_definite": "betalningarna", "english": "payment", "cefr": 2, "frequency": 26.52},
    {"indefinite": "faktura", "definite": "fakturan", "plural": "fakturor", "plural_definite": "fakturorna", "english": "invoice", "cefr": 1, "frequency": None},
    {"indefinite": "tjänst", "definite": "tjänsten", "plural": "tjänster", "plural_definite": "tjänsterna", "english": "service", "cefr": 1, "frequency": 170.63},
    {"indefinite": "kundservice", "definite": "kundservicen", "plural": "kundservicar", "plural_definite": "kundservicarna", "english": "customer service", "cefr": 1, "frequency": None},
    {"indefinite": "post", "definite": "posten", "plural": "poster", "plural_definite": "posterna", "english": "mail", "cefr": 1, "frequency": 67.02},
    {"indefinite": "paket", "definite": "paketet", "plural": "paket", "plural_definite": "paketen", "english": "package", "cefr": 2, "frequency": 25.51},
    {"indefinite": "brev", "definite": "brevet", "plural": "brev", "plural_definite": "breven", "english": "letter", "cefr": 1, "frequency": 80.95},
    {"indefinite": "frimärke", "definite": "frimärket", "plural": "frimärken", "plural_definite": "frimärkena", "english": "stamp", "cefr": 1, "frequency": None},
    {"indefinite": "kläder", "definite": "kläderna", "plural": "kläder", "plural_definite": "kläderna", "english": "clothes", "cefr": 1, "frequency": 69.00},
    {"indefinite": "skor", "definite": "skorna", "plural": "skor", "plural_definite": "skorna", "english": "shoes", "cefr": 1, "frequency": None},
    {"indefinite": "prislista", "definite": "prislistan", "plural": "prislistor", "plural_definite": "prislistorna", "english": "price list", "cefr": 1, "frequency": None},
    {"indefinite": "kundkort", "definite": "kundkortet", "plural": "kundkort", "plural_definite": "kundkorten", "english": "loyalty card", "cefr": 1, "frequency": None},
    {"indefinite": "reklamation", "definite": "reklamationen", "plural": "reklamationer", "plural_definite": "reklamationerna", "english": "complaint, return", "cefr": 1, "frequency": None},
    {"indefinite": "utgift", "definite": "utgiften", "plural": "utgifter", "plural_definite": "utgifterna", "english": "expense", "cefr": 2, "frequency": 30.88},
    {"indefinite": "inkomst", "definite": "inkomsten", "plural": "inkomster", "plural_definite": "inkomsterna", "english": "income", "cefr": 1, "frequency": 69.04},
    {"indefinite": "försäkring", "definite": "försäkringen", "plural": "försäkringar", "plural_definite": "försäkringarna", "english": "insurance", "cefr": 2, "frequency": 31.67},
    {"indefinite": "tillgång", "definite": "tillgången", "plural": "tillgångar", "plural_definite": "tillgångarna", "english": "asset", "cefr": 1, "frequency": 133.50},
    {"indefinite": "reklam", "definite": "reklamen", "plural": "reklamer", "plural_definite": "reklamerna", "english": "advertisement", "cefr": 2, "frequency": 48.04},
    {"indefinite": "erbjudande", "definite": "erbjudandet", "plural": "erbjudanden", "plural_definite": "erbjudandena", "english": "offer", "cefr": 3, "frequency": 21.68},
    {"indefinite": "prisnivå", "definite": "prisnivån", "plural": "prisnivåer", "plural_definite": "prisnivåerna", "english": "price level", "cefr": 1, "frequency": None},
    {"indefinite": "butikskedja", "definite": "butikskedjan", "plural": "butikskedjor", "plural_definite": "butikskedjorna", "english": "store chain", "cefr": 1, "frequency": None},
    {"indefinite": "kundvagn", "definite": "kundvagnen", "plural": "kundvagnar", "plural_definite": "kundvagnarna", "english": "shopping cart", "cefr": 1, "frequency": None},
    {"indefinite": "storlek", "definite": "storleken", "plural": "storlekar", "plural_definite": "storlekarna", "english": "size", "cefr": 2, "frequency": 49.07},
    {"indefinite": "kundtjänst", "definite": "kundtjänsten", "plural": "kundtjänster", "plural_definite": "kundtjänsterna", "english": "customer support", "cefr": 1, "frequency": None},
    {"indefinite": "ring", "definite": "ringen", "plural": "ringar", "plural_definite": "ringarna", "english": "ring", "cefr": 1, "frequency": 658.84},
    {"indefinite": "peng", "definite": "pengen", "plural": "pengar", "plural_definite": "pengarna", "english": "money", "cefr": 1, "frequency": 365.10},
    {"indefinite": "krona", "definite": "kronan", "plural": "kronor", "plural_definite": "kronorna", "english": "crown, Swedish krona", "cefr": 1, "frequency": 207.79},
    {"indefinite": "etikett", "definite": "etiketten", "plural": "etiketter", "plural_definite": "etiketterna", "english": "label, etiquette", "cefr": 1, "frequency": 202.31},
]

verbs = [
    {"infinitive": "handla", "present": "handlar", "past": "handlade", "supine": "handlat", "english": "to shop", "cefr": 1, "frequency": 475.07},
    {"infinitive": "betala", "present": "betalar", "past": "betalade", "supine": "betalat", "english": "to pay", "cefr": 1, "frequency": 242.04},
    {"infinitive": "returnera", "present": "returnerar", "past": "returnerade", "supine": "returnerat", "english": "to return (an item)", "cefr": 1, "frequency": None},
    {"infinitive": "prova", "present": "provar", "past": "provade", "supine": "provat", "english": "to try (clothes)", "cefr": 2, "frequency": 38.07},
    {"infinitive": "beställa", "present": "beställer", "past": "beställde", "supine": "beställt", "english": "to order", "cefr": 2, "frequency": 42.48},
    {"infinitive": "reklamera", "present": "reklamerar", "past": "reklamerade", "supine": "reklamerat", "english": "to complain, make a claim", "cefr": 1, "frequency": None},
    {"infinitive": "fungera", "present": "fungerar", "past": "fungerade", "supine": "fungerat", "english": "to function, work", "cefr": 1, "frequency": 287.40},
    {"infinitive": "låna", "present": "lånar", "past": "lånade", "supine": "lånat", "english": "to borrow", "cefr": 2, "frequency": 49.26},
    {"infinitive": "växla", "present": "växlar", "past": "växlade", "supine": "växlat", "english": "to exchange (money)", "cefr": 1, "frequency": None},
    {"infinitive": "spendera", "present": "spenderar", "past": "spenderade", "supine": "spenderat", "english": "to spend (money)", "cefr": 2, "frequency": 26.60},
    {"infinitive": "använda", "present": "använder", "past": "använde", "supine": "använt", "english": "to use", "cefr": 1, "frequency": 749.26},
    {"infinitive": "packa", "present": "packar", "past": "packade", "supine": "packat", "english": "to pack", "cefr": 3, "frequency": 18.38},
]

misc = [
    {"swedish": "missnöjd", "english": "dissatisfied", "cefr": 3, "frequency": 12.14},
    {"swedish": "tillgänglig", "english": "available", "cefr": 1, "frequency": 72.31},
    {"swedish": "upptagen", "english": "busy", "cefr": 3, "frequency": 17.39},
    {"swedish": "gratis", "english": "free (no cost)", "cefr": 2, "frequency": 57.31},
    {"swedish": "snabb", "english": "fast", "cefr": 1, "frequency": 110.80},
    {"swedish": "långsam", "english": "slow", "cefr": 3, "frequency": 18.86},
    {"swedish": "rättvis", "english": "fair", "cefr": 2, "frequency": 28.24},
    {"swedish": "orättvis", "english": "unfair", "cefr": 3, "frequency": 14.72},
    {"swedish": "direkt", "english": "directly", "cefr": 1, "frequency": 194.63},
    {"swedish": "ännu inte", "english": "not yet", "cefr": 1, "frequency": None},
]
