nouns = [
    {"type": "noun", "swedish": "samhället", "english": "society"},
    {"type": "noun", "swedish": "medborgare", "english": "citizen"},
    {"type": "noun", "swedish": "rättighet", "english": "right"},
    {"type": "noun", "swedish": "skyldighet", "english": "obligation"},
    {"type": "noun", "swedish": "regering", "english": "government"},
    {"type": "noun", "swedish": "riksdag", "english": "parliament"},
    {"type": "noun", "swedish": "lag", "english": "law"},
    {"type": "noun", "swedish": "regel", "english": "rule"},
    {"type": "noun", "swedish": "minister", "english": "minister"},
    {"type": "noun", "swedish": "politiker", "english": "politician"},
    {"type": "noun", "swedish": "parti", "english": "party (political)"},
    {"type": "noun", "swedish": "val", "english": "election"},
    {"type": "noun", "swedish": "omröstning", "english": "vote"},
    {"type": "noun", "swedish": "demokrati", "english": "democracy"},
    {"type": "noun", "swedish": "diktatur", "english": "dictatorship"},
    {"type": "noun", "swedish": "frihet", "english": "freedom"},
    {"type": "noun", "swedish": "jämlikhet", "english": "equality"},
    {"type": "noun", "swedish": "rättvisa", "english": "justice, fairness"},
    {"type": "noun", "swedish": "myndighet", "english": "authority, agency"},
    {"type": "noun", "swedish": "polis", "english": "police"},
    {"type": "noun", "swedish": "domstol", "english": "court"},
    {"type": "noun", "swedish": "brott", "english": "crime"},
    {"type": "noun", "swedish": "straff", "english": "punishment"},
    {"type": "noun", "swedish": "invånare", "english": "inhabitant, resident"},
    {"type": "noun", "swedish": "kommun", "english": "municipality"},
    {"type": "noun", "swedish": "stat", "english": "state"},
    {"type": "noun", "swedish": "skattebetalare", "english": "taxpayer"},
    {"type": "noun", "swedish": "socialt stöd", "english": "social support"},
    {"type": "noun", "swedish": "pension", "english": "pension"},
    {"type": "noun", "swedish": "arbetslöshet", "english": "unemployment"},
    {"type": "noun", "swedish": "ekonomi", "english": "economy"},
    {"type": "noun", "swedish": "inflation", "english": "inflation"},
    {"type": "noun", "swedish": "pris", "english": "price"},
    {"type": "noun", "swedish": "kostnad", "english": "cost"},
    {"type": "noun", "swedish": "lön", "english": "salary"},
    {"type": "noun", "swedish": "företag", "english": "company"},
    {"type": "noun", "swedish": "arbetsplats", "english": "workplace"},
    {"type": "noun", "swedish": "arbetstagare", "english": "employee"},
    {"type": "noun", "swedish": "arbetsgivare", "english": "employer"},
    {"type": "noun", "swedish": "produktion", "english": "production"},
    {"type": "noun", "swedish": "export", "english": "export"},
    {"type": "noun", "swedish": "import", "english": "import"},
    {"type": "noun", "swedish": "försäljning", "english": "sales"},
    {"type": "noun", "swedish": "handel", "english": "trade"},
    {"type": "noun", "swedish": "marknad", "english": "market"},
    {"type": "noun", "swedish": "investering", "english": "investment"},
    {"type": "noun", "swedish": "resurs", "english": "resource"},
    {"type": "noun", "swedish": "miljö", "english": "environment"},
    {"type": "noun", "swedish": "hållbarhet", "english": "sustainability"},
    {"type": "noun", "swedish": "energikälla", "english": "energy source"},
    {"type": "noun", "swedish": "nyhet", "english": "news"},
    {"type": "noun", "swedish": "media", "english": "media"},
    {"type": "noun", "swedish": "tidning", "english": "newspaper"},
    {"type": "noun", "swedish": "journalist", "english": "journalist"},
    {"type": "noun", "swedish": "rapport", "english": "report"},
    {"type": "noun", "swedish": "undersökning", "english": "survey, study"},
    {"type": "noun", "swedish": "forskning", "english": "research"},
    {"type": "noun", "swedish": "resultat", "english": "result"},
    {"type": "noun", "swedish": "förändring", "english": "change"},
    {"type": "noun", "swedish": "utveckling", "english": "development"},
    {"type": "noun", "swedish": "problem", "english": "problem"},
    {"type": "noun", "swedish": "lösning", "english": "solution"},
    {"type": "noun", "swedish": "orsak", "english": "cause"},
    {"type": "noun", "swedish": "följd", "english": "consequence"},
    {"type": "noun", "swedish": "debatt", "english": "debate"},
    {"type": "noun", "swedish": "opinion", "english": "opinion"},
    {"type": "noun", "swedish": "åsikt", "english": "point of view"},
    {"type": "noun", "swedish": "diskussion", "english": "discussion"},
    {"type": "noun", "swedish": "protest", "english": "protest"},
    {"type": "noun", "swedish": "demonstration", "english": "demonstration"},
    {"type": "noun", "swedish": "teknik", "english": "technology"},
    {"type": "noun", "swedish": "dator", "english": "computer"},
    {"type": "noun", "swedish": "mobil", "english": "mobile phone"},
    {"type": "noun", "swedish": "internet", "english": "internet"},
    {"type": "noun", "swedish": "app", "english": "app"},
    {"type": "noun", "swedish": "programvara", "english": "software"},
    {"type": "noun", "swedish": "hårdvara", "english": "hardware"},
    {"type": "noun", "swedish": "system", "english": "system"},
    {"type": "noun", "swedish": "nätverk", "english": "network"},
    {"type": "noun", "swedish": "data", "english": "data"},
    {"type": "noun", "swedish": "information", "english": "information"},
    {"type": "noun", "swedish": "säkerhet", "english": "security"},
    {"type": "noun", "swedish": "lösenord", "english": "password"},
    {"type": "noun", "swedish": "e-post", "english": "email"},
    {"type": "noun", "swedish": "meddelande", "english": "message"},
    {"type": "noun", "swedish": "hemsida", "english": "website"},
    {"type": "noun", "swedish": "sociala medier", "english": "social media"},
    {"type": "noun", "swedish": "robot", "english": "robot"},
    {"type": "noun", "swedish": "maskin", "english": "machine"},
    {"type": "noun", "swedish": "innovation", "english": "innovation"},
    {"type": "noun", "swedish": "uppfinning", "english": "invention"},
    {"type": "noun", "swedish": "artificiell intelligens", "english": "artificial intelligence"},
    {"type": "noun", "swedish": "algoritm", "english": "algorithm"},
    {"type": "noun", "swedish": "dataskydd", "english": "data protection"},
    {"type": "noun", "swedish": "digitalisering", "english": "digitalization"},
    {"type": "noun", "swedish": "cyberattack", "english": "cyberattack"},
    {"type": "noun", "swedish": "elnät", "english": "power grid"},
    {"type": "noun", "swedish": "elbil", "english": "electric car"},
    {"type": "noun", "swedish": "utvecklare", "english": "developer"},
    {"type": "noun", "swedish": "plattform", "english": "platform"},
    {"type": "noun", "swedish": "kris", "english": "crisis"},
    {"type": "noun", "swedish": "konflikt", "english": "conflict"},
    {"type": "noun", "swedish": "fred", "english": "peace"},
    {"type": "noun", "swedish": "krig", "english": "war"},
    {"type": "noun", "swedish": "flykting", "english": "refugee"},
    {"type": "noun", "swedish": "invandring", "english": "immigration"},
    {"type": "noun", "swedish": "integration", "english": "integration"},
    {"type": "noun", "swedish": "samhällsproblem", "english": "social issue"},
    {"type": "noun", "swedish": "lösning", "english": "solution"},
    {"type": "noun", "swedish": "framtid", "english": "future"},
    {"type": "noun", "swedish": "påverkan", "english": "impact"},
    {"type": "noun", "swedish": "lösning", "english": "solution"},
    {"type": "noun", "swedish": "omställning", "english": "transition/conversion"},
    {"type": "noun", "swedish": "utbildning", "english": "training"},
    {"type": "noun", "swedish": "yrkesverksamma", "english": "professionals"},
    {"type": "noun", "swedish": "subvention", "english": "subsidy"},
    {"type": "noun", "swedish": "satsning", "english": "investment"},
    {"type": "noun", "swedish": "mål", "english": "goal"},
    {"type": "noun", "swedish": "färdighet", "english": "skill"},
    {"type": "noun", "swedish": "förnybar", "english": "renewable"},
    {"type": "noun", "swedish": "på grund av", "english": "because of"},
]

verbs = [
    {"type": "verb", "infinitive": "påverka",
        "english": "affect",
        "present": "påverkar",
        "past": "påverkade",
        "supine": "påverkat",
        "imperative": "påverka",
        "passive": "påverkas",
        "adjective form": "påverkad"
    },
    {"type": "verb", "infinitive": "bestämma",
        "english": "decide/determine",
        "present": "bestämmer",
        "past": "bestämde",
        "supine": "bestämt",
        "imperative": "bestäm",
        "passive": "bestäms",
        "adjective form": "bestämd"
    },
    {"type": "verb", "infinitive": "styra",
        "english": "govern/control",
        "present": "styr",
        "past": "styrde",
        "supine": "styrt",
        "imperative": "styr",
        "passive": "styrs",
        "adjective form": "styrd"
    },
    {"type": "verb", "infinitive": "leda",
        "english": "lead",
        "present": "leder",
        "past": "ledde",
        "supine": "lett",
        "imperative": "led",
        "passive": "leds",
        "adjective form": "ledd"
    },
    {"type": "verb", "infinitive": "förändra",
        "english": "change",
        "present": "förändrar",
        "past": "förändrade",
        "supine": "förändrat",
        "imperative": "förändra",
        "passive": "förändras",
        "adjective form": "förändrad"
    },
    {"type": "verb", "infinitive": "utveckla",
        "english": "develop",
        "present": "utvecklar",
        "past": "utvecklade",
        "supine": "utvecklat",
        "imperative": "utveckla",
        "passive": "utvecklas",
        "adjective form": "utvecklad"
    },
    {"type": "verb", "infinitive": "bygga",
        "english": "build",
        "present": "bygger",
        "past": "byggde",
        "supine": "byggt",
        "imperative": "bygg",
        "passive": "byggs",
        "adjective form": "byggd"
    },
    {"type": "verb", "infinitive": "skapa",
        "english": "create",
        "present": "skapar",
        "past": "skapade",
        "supine": "skapat",
        "imperative": "skapa",
        "passive": "skapas",
        "adjective form": "skapad"
    },
    {"type": "verb", "infinitive": "förbättra",
        "english": "improve",
        "present": "förbättrar",
        "past": "förbättrade",
        "supine": "förbättrat",
        "imperative": "förbättra",
        "passive": "förbättras",
        "adjective form": "förbättrad"
    },
    {"type": "verb", "infinitive": "minska",
        "english": "reduce",
        "present": "minskar",
        "past": "minskade",
        "supine": "minskat",
        "imperative": "minska",
        "passive": "minskas",
        "adjective form": "minskad"
    },
    {"type": "verb", "infinitive": "öka",
        "english": "increase",
        "present": "ökar",
        "past": "ökade",
        "supine": "ökat",
        "imperative": "öka",
        "passive": "ökas",
        "adjective form": "ökad"
    },
    {"type": "verb", "infinitive": "använda",
        "english": "use",
        "present": "använder",
        "past": "använde",
        "supine": "använt",
        "imperative": "använd",
        "passive": "användes",
        "adjective form": "använd"
    },
    {"type": "verb", "infinitive": "producera",
        "english": "produce",
        "present": "producerar",
        "past": "producerade",
        "supine": "producerat",
        "imperative": "producera",
        "passive": "produceras",
        "adjective form": "producerad"
    },
    {"type": "verb", "infinitive": "förbjuda",
        "english": "prohibit",
        "present": "förbjuder",
        "past": "förbjöd",
        "supine": "förbjudit",
        "imperative": "förbjud",
        "passive": "förbjuds",
        "adjective form": "förbjuden"
    },
    {"type": "verb", "infinitive": "tillåta",
        "english": "allow/permit",
        "present": "tillåter",
        "past": "tillät",
        "supine": "tillåtit",
        "imperative": "tillåt",
        "passive": "tillåts",
        "adjective form": "tillåten"
    },
    {"type": "verb", "infinitive": "diskutera",
        "english": "discuss",
        "present": "diskuterar",
        "past": "diskuterade",
        "supine": "diskuterat",
        "imperative": "diskutera",
        "passive": "diskuteras",
        "adjective form": "diskuterad"
    },
    {"type": "verb", "infinitive": "besluta",
        "english": "decide",
        "present": "beslutar",
        "past": "beslutade",
        "supine": "beslutat",
        "imperative": "besluta",
        "passive": "beslutas",
        "adjective form": "beslutat"
    },
    {"type": "verb", "infinitive": "rösta",
        "english": "vote",
        "present": "röstar",
        "past": "röstade",
        "supine": "röstat",
        "imperative": "rösta",
        "passive": "röstas",
        "adjective form": "röstad"
    },
    {"type": "verb", "infinitive": "arbeta",
        "english": "work",
        "present": "arbetar",
        "past": "arbetade",
        "supine": "arbetat",
        "imperative": "arbeta",
        "passive": "arbetas",
        "adjective form": "arbetad"
    },
    {"type": "verb", "infinitive": "tjäna",
        "english": "earn (money)",
        "present": "tjänar",
        "past": "tjänade",
        "supine": "tjänat",
        "imperative": "tjäna",
        "passive": "tjänades",
        "adjective form": "intjänad"
    },
    {"type": "verb", "infinitive": "betala",
        "english": "pay",
        "present": "betalar",
        "past": "betalade",
        "supine": "betalat",
        "imperative": "betala",
        "passive": "betalades",
        "adjective form": "betalad"
    },
    {"type": "verb", "infinitive": "spara",
        "english": "save (money)",
        "present": "sparar",
        "past": "sparade",
        "supine": "sparat",
        "imperative": "spara",
        "passive": "sparades",
        "adjective form": "sparad"
    },
    {"type": "verb", "infinitive": "investera",
        "english": "invest",
        "present": "investerar",
        "past": "investerade",
        "supine": "investerat",
        "imperative": "investera",
        "passive": "investeras",
        "adjective form": "investerad"
    },
    {"type": "verb", "infinitive": "forska",
        "english": "research",
        "present": "forskar",
        "past": "forskade",
        "supine": "forskat",
        "imperative": "forska",
        "passive": "forskas",
        "adjective form": "forskad"
    },
    {"type": "verb", "infinitive": "uppfinna",
        "english": "invent",
        "present": "uppfinner",
        "past": "uppfann",
        "supine": "uppfunnit",
        "imperative": "uppfinn",
        "passive": "uppfinns",
        "adjective form": "uppfunnen"
    },
    {"type": "verb", "infinitive": "förklara",
        "english": "explain",
        "present": "förklarar",
        "past": "förklarade",
        "supine": "förklarat",
        "imperative": "förklara",
        "passive": "förklarades",
        "adjective form": "förklarad"
    },
    {"type": "verb", "infinitive": "informera",
        "english": "inform",
        "present": "informerar",
        "past": "informerade",
        "supine": "informerat",
        "imperative": "informera",
        "passive": "informeras",
        "adjective form": "informerad"
    },
    {"type": "verb", "infinitive": "rapportera",
        "english": "report",
        "present": "rapporterar",
        "past": "rapporterade",
        "supine": "rapporterat",
        "imperative": "rapportera",
        "passive": "rapporterades",
        "adjective form": "rapporterad"
    },
    {"type": "verb", "infinitive": "kontrollera",
        "english": "check/verify",
        "present": "kontrollerar",
        "past": "kontrollerade",
        "supine": "kontrollerat",
        "imperative": "kontrollera",
        "passive": "kontrollerades",
        "adjective form": "kontrollerad"
    },
    {"type": "verb", "infinitive": "övervaka",
        "english": "monitor/oversee",
        "present": "övervakar",
        "past": "övervakade",
        "supine": "övervakat",
        "imperative": "övervaka",
        "passive": "övervakades",
        "adjective form": "övervakad"
    },
    {"type": "verb", "infinitive": "försvara",
        "english": "defend/justify",
        "present": "försvarar",
        "past": "försvarade",
        "supine": "försvarat",
        "imperative": "försvara",
        "passive": "försvarades",
        "adjective form": "försvarad"
    },
    {"type": "verb", "infinitive": "skydda",
        "english": "protect",
        "present": "skyddar",
        "past": "skyddade",
        "supine": "skyddat",
        "imperative": "skydda",
        "passive": "skyddades",
        "adjective form": "skyddad"
    },
    {"type": "verb", "infinitive": "hjälpa",
        "english": "help",
        "present": "hjälper",
        "past": "hjälpte",
        "supine": "hjälpt",
        "imperative": "hjälp",
        "passive": "",
        "adjective form": "hjälpt"
    },
    {"type": "verb", "infinitive": "påminna",
        "english": "remind",
        "present": "påminner",
        "past": "påminde",
        "supine": "påmint",
        "imperative": "påminn",
        "passive": "påminns",
        "adjective form": "påmind"
    },
    {"type": "verb", "infinitive": "stöda",
        "english": "support",
        "present": "stöder",
        "past": "stödde",
        "supine": "stött",
        "imperative": "stöd",
        "passive": "stöds",
        "adjective form": "stödd"
    },
    {"type": "verb", "infinitive": "tillhöra",
        "english": "belong",
        "present": "tillhör",
        "past": "tillhörde",
        "supine": "tillhört",
        "imperative": "tillhör",
        "passive": "",
        "adjective form": "tillhörande"
    },
    {"type": "verb", "infinitive": "tro",
        "english": "believe",
        "present": "tror",
        "past": "trodde",
        "supine": "trott",
        "imperative": "tro",
        "passive": "tros",
        "adjective form": "trodd"
    },
    {"type": "verb", "infinitive": "tycka",
        "english": "think",
        "present": "tycker",
        "past": "tyckte",
        "supine": "tyckt",
        "imperative": "tyck",
        "passive": "tycks"
    },
    {"type": "verb", "infinitive": "anse",
        "english": "consider",
        "present": "anser",
        "past": "ansåg",
        "supine": "ansett",
        "imperative": "anse",
        "passive": "anses",
        "adjective form": ""
    },
    {"type": "verb", "infinitive": "hålla med",
        "english": "agree",
        "present": "håller",
        "past": "höll",
        "supine": "hållit",
        "imperative": "håll",
        "passive": "",
        "adjective form": ""
    },
    {"type": "verb", "infinitive": "försvinna",
        "english": "disappear",
        "present": "försvinner",
        "past": "försvann",
        "supine": "försvunnit",
        "imperative": "försvinna",
        "passive": "",
        "adjective form": "försvunnen"
    },
    {"type": "verb", "infinitive": "ersätta",
        "english": "replace",
        "present": "ersätter",
        "past": "ersatte",
        "supine": "ersatt",
        "imperative": "ersätt",
        "passive": "ersattes",
        "adjective form": "ersatt"
    },
    {"type": "verb", "infinitive": "påpeka",
        "english": "point out",
        "present": "påpekar",
        "past": "påpekade",
        "supine": "påpekat",
        "imperative": "påpeka",
        "passive": "påpekades",
        "adjective form": "påpekad"
    },
    {"type": "verb", "infinitive": "nå",
        "english": "reach/gain (business)",
        "present": "når",
        "past": "nådde",
        "supine": "nått",
        "imperative": "nå",
        "passive": "nås",
        "adjective form": "nådd"
    },
    {"type": "verb", "infinitive": "underlätta",
        "english": "facilitate",
        "present": "underlättar",
        "past": "underlätterade",
        "supine": "underlätt",
        "imperative": "underlätta",
        "passive": "underlättades",
        "adjective form": "underlättad"
    },
    {"type": "verb", "infinitive": "förbli",
        "english": "remain",
        "present": "förblir",
        "past": "förblev",
        "supine": "förblivit",
        "imperative": "förbliv",
        "passive": "",
        "adjective form": ""
    }
]