nouns = [
    {"indefinite": "samhälle", "definite": "samhället", "plural": "samhällen", "plural_definite": "samhällena", "english": "society"},
    {"indefinite": "medborgare", "definite": "medborgaren", "plural": "medborgare", "plural_definite": "medborgarna", "english": "citizen"},
    {"indefinite": "rättighet", "definite": "rättigheten", "plural": "rättigheter", "plural_definite": "rättigheterna", "english": "right"},
    {"indefinite": "skyldighet", "definite": "skyldigheten", "plural": "skyldigheter", "plural_definite": "skyldigheterna", "english": "obligation"},
    {"indefinite": "regering", "definite": "regeringen", "plural": "regeringar", "plural_definite": "regeringarna", "english": "government"},
    {"indefinite": "riksdag", "definite": "riksdagen", "plural": "riksdagar", "plural_definite": "riksdagarna", "english": "parliament"},
    {"indefinite": "lag", "definite": "lagen", "plural": "lagar", "plural_definite": "lagarna", "english": "law"},
    {"indefinite": "regel", "definite": "regeln", "plural": "regler", "plural_definite": "reglerna", "english": "rule"},
    {"indefinite": "minister", "definite": "ministern", "plural": "ministrar", "plural_definite": "ministrarna", "english": "minister"},
    {"indefinite": "politiker", "definite": "politikern", "plural": "politiker", "plural_definite": "politikerna", "english": "politician"},
    {"indefinite": "parti", "definite": "partiet", "plural": "partier", "plural_definite": "partierna", "english": "party (political)"},
    {"indefinite": "val", "definite": "valet", "plural": "val", "plural_definite": "valen", "english": "election"},
    {"indefinite": "omröstning", "definite": "omröstningen", "plural": "omröstningar", "plural_definite": "omröstningarna", "english": "vote"},
    {"indefinite": "demokrati", "definite": "demokratin", "plural": "demokratier", "plural_definite": "demokratierna", "english": "democracy"},
    {"indefinite": "diktatur", "definite": "diktaturen", "plural": "diktaturer", "plural_definite": "diktaturerna", "english": "dictatorship"},
    {"indefinite": "frihet", "definite": "friheten", "plural": "friheter", "plural_definite": "friheterna", "english": "freedom"},
    {"indefinite": "jämlikhet", "definite": "jämlikheten", "plural": "jämlikheter", "plural_definite": "jämlikheterna", "english": "equality"},
    {"indefinite": "rättvisa", "definite": "rättvisan", "plural": "rättvisor", "plural_definite": "rättvisorna", "english": "justice, fairness"},
    {"indefinite": "myndighet", "definite": "myndigheten", "plural": "myndigheter", "plural_definite": "myndigheterna", "english": "authority, agency"},
    {"indefinite": "polis", "definite": "polisen", "plural": "poliser", "plural_definite": "poliserna", "english": "police (officer)"},
    {"indefinite": "domstol", "definite": "domstolen", "plural": "domstolar", "plural_definite": "domstolarna", "english": "court"},
    {"indefinite": "brott", "definite": "brottet", "plural": "brott", "plural_definite": "brotten", "english": "crime"},
    {"indefinite": "straff", "definite": "straffet", "plural": "straff", "plural_definite": "straffen", "english": "punishment"},
    {"indefinite": "invånare", "definite": "invånaren", "plural": "invånare", "plural_definite": "invånarna", "english": "inhabitant, resident"},
    {"indefinite": "kommun", "definite": "kommunen", "plural": "kommuner", "plural_definite": "kommunerna", "english": "municipality"},
    {"indefinite": "stat", "definite": "staten", "plural": "stater", "plural_definite": "staterna", "english": "state"},
    {"indefinite": "skattebetalare", "definite": "skattebetalaren", "plural": "skattebetalare", "plural_definite": "skattebetalarna", "english": "taxpayer"},
    {"indefinite": "socialt stöd", "definite": "det sociala stödet", "plural": "sociala stöd", "plural_definite": "de sociala stöden", "english": "social support"},
    {"indefinite": "pension", "definite": "pensionen", "plural": "pensioner", "plural_definite": "pensionerna", "english": "pension"},
    {"indefinite": "arbetslöshet", "definite": "arbetslösheten", "plural": "arbetslösheter", "plural_definite": "arbetslösheterna", "english": "unemployment"},
    {"indefinite": "ekonomi", "definite": "ekonomin", "plural": "ekonomier", "plural_definite": "ekonomierna", "english": "economy"},
    {"indefinite": "inflation", "definite": "inflationen", "plural": "inflationer", "plural_definite": "inflationerna", "english": "inflation"},
    {"indefinite": "pris", "definite": "priset", "plural": "priser", "plural_definite": "priserna", "english": "price"},
    {"indefinite": "kostnad", "definite": "kostnaden", "plural": "kostnader", "plural_definite": "kostnaderna", "english": "cost"},
    {"indefinite": "lön", "definite": "lönen", "plural": "löner", "plural_definite": "lönerna", "english": "salary"},
    {"indefinite": "företag", "definite": "företaget", "plural": "företag", "plural_definite": "företagen", "english": "company"},
    {"indefinite": "arbetsplats", "definite": "arbetsplatsen", "plural": "arbetsplatser", "plural_definite": "arbetsplatserna", "english": "workplace"},
    {"indefinite": "arbetstagare", "definite": "arbetstagaren", "plural": "arbetstagare", "plural_definite": "arbetstagarna", "english": "employee"},
    {"indefinite": "arbetsgivare", "definite": "arbetsgivaren", "plural": "arbetsgivare", "plural_definite": "arbetsgivarna", "english": "employer"},
    {"indefinite": "produktion", "definite": "produktionen", "plural": "produktioner", "plural_definite": "produktionerna", "english": "production"},
    {"indefinite": "export", "definite": "exporten", "plural": "exporter", "plural_definite": "exporterna", "english": "export"},
    {"indefinite": "import", "definite": "importen", "plural": "importer", "plural_definite": "importerna", "english": "import"},
    {"indefinite": "försäljning", "definite": "försäljningen", "plural": "försäljningar", "plural_definite": "försäljningarna", "english": "sales"},
    {"indefinite": "handel", "definite": "handeln", "plural": "handlar", "plural_definite": "handlarna", "english": "trade"},
    {"indefinite": "marknad", "definite": "marknaden", "plural": "marknader", "plural_definite": "marknaderna", "english": "market"},
    {"indefinite": "investering", "definite": "investeringen", "plural": "investeringar", "plural_definite": "investeringarna", "english": "investment"},
    {"indefinite": "resurs", "definite": "resursen", "plural": "resurser", "plural_definite": "resurserna", "english": "resource"},
    {"indefinite": "miljö", "definite": "miljön", "plural": "miljöer", "plural_definite": "miljöerna", "english": "environment"},
    {"indefinite": "hållbarhet", "definite": "hållbarheten", "plural": "hållbarheter", "plural_definite": "hållbarheterna", "english": "sustainability"},
    {"indefinite": "energikälla", "definite": "energikällan", "plural": "energikällor", "plural_definite": "energikällorna", "english": "energy source"},
    {"indefinite": "nyhet", "definite": "nyheten", "plural": "nyheter", "plural_definite": "nyheterna", "english": "news (item)"},
    {"indefinite": "media", "definite": "median", "plural": "medier", "plural_definite": "medierna", "english": "media"},
    {"indefinite": "tidning", "definite": "tidningen", "plural": "tidningar", "plural_definite": "tidningarna", "english": "newspaper"},
    {"indefinite": "journalist", "definite": "journalisten", "plural": "journalister", "plural_definite": "journalisterna", "english": "journalist"},
    {"indefinite": "rapport", "definite": "rapporten", "plural": "rapporter", "plural_definite": "rapporterna", "english": "report"},
    {"indefinite": "undersökning", "definite": "undersökningen", "plural": "undersökningar", "plural_definite": "undersökningarna", "english": "survey, study"},
    {"indefinite": "forskning", "definite": "forskningen", "plural": "forskningar", "plural_definite": "forskningarna", "english": "research"},
    {"indefinite": "resultat", "definite": "resultatet", "plural": "resultat", "plural_definite": "resultaten", "english": "result"},
    {"indefinite": "förändring", "definite": "förändringen", "plural": "förändringar", "plural_definite": "förändringarna", "english": "change"},
    {"indefinite": "utveckling", "definite": "utvecklingen", "plural": "utvecklingar", "plural_definite": "utvecklingarna", "english": "development"},
    {"indefinite": "problem", "definite": "problemet", "plural": "problem", "plural_definite": "problemen", "english": "problem"},
    {"indefinite": "lösning", "definite": "lösningen", "plural": "lösningar", "plural_definite": "lösningarna", "english": "solution"},
    {"indefinite": "orsak", "definite": "orsaken", "plural": "orsaker", "plural_definite": "orsakerna", "english": "cause"},
    {"indefinite": "följd", "definite": "följden", "plural": "följder", "plural_definite": "följderna", "english": "consequence"},
    {"indefinite": "debatt", "definite": "debatten", "plural": "debatter", "plural_definite": "debatterna", "english": "debate"},
    {"indefinite": "opinion", "definite": "opinionen", "plural": "opinioner", "plural_definite": "opinionerna", "english": "opinion"},
    {"indefinite": "åsikt", "definite": "åsikten", "plural": "åsikter", "plural_definite": "åsikterna", "english": "point of view"},
    {"indefinite": "diskussion", "definite": "diskussionen", "plural": "diskussioner", "plural_definite": "diskussionerna", "english": "discussion"},
    {"indefinite": "protest", "definite": "protesten", "plural": "protester", "plural_definite": "protesterna", "english": "protest"},
    {"indefinite": "demonstration", "definite": "demonstrationen", "plural": "demonstrationer", "plural_definite": "demonstrationerna", "english": "demonstration"},
    {"indefinite": "teknik", "definite": "tekniken", "plural": "tekniker", "plural_definite": "teknikerna", "english": "technology"},
    {"indefinite": "dator", "definite": "datorn", "plural": "datorer", "plural_definite": "datorerna", "english": "computer"},
    {"indefinite": "mobil", "definite": "mobilen", "plural": "mobiler", "plural_definite": "mobilerna", "english": "mobile phone"},
    {"indefinite": "internet", "definite": "internetet", "plural": "internet", "plural_definite": "interneten", "english": "internet"},
    {"indefinite": "app", "definite": "appen", "plural": "appar", "plural_definite": "apparna", "english": "app"},
    {"indefinite": "programvara", "definite": "programvaran", "plural": "programvaror", "plural_definite": "programvarorna", "english": "software"},
    {"indefinite": "hårdvara", "definite": "hårdvaran", "plural": "hårdvaror", "plural_definite": "hårdvarorna", "english": "hardware"},
    {"indefinite": "system", "definite": "systemet", "plural": "system", "plural_definite": "systemen", "english": "system"},
    {"indefinite": "nätverk", "definite": "nätverket", "plural": "nätverk", "plural_definite": "nätverken", "english": "network"},
    {"indefinite": "data", "definite": "datan", "plural": "data", "plural_definite": "datorna", "english": "data"},
    {"indefinite": "information", "definite": "informationen", "plural": "informationer", "plural_definite": "informationerna", "english": "information"},
    {"indefinite": "säkerhet", "definite": "säkerheten", "plural": "säkerheter", "plural_definite": "säkerheterna", "english": "security"},
    {"indefinite": "lösenord", "definite": "lösenordet", "plural": "lösenord", "plural_definite": "lösenorden", "english": "password"},
    {"indefinite": "e-post", "definite": "e-posten", "plural": "e-post", "plural_definite": "e-posterna", "english": "email"},
    {"indefinite": "meddelande", "definite": "meddelandet", "plural": "meddelanden", "plural_definite": "meddelandena", "english": "message"},
    {"indefinite": "hemsida", "definite": "hemsidan", "plural": "hemsidor", "plural_definite": "hemsidorna", "english": "website"},
    {"indefinite": "sociala medier", "definite": "de sociala medierna", "plural": "sociala medier", "plural_definite": "de sociala medierna", "english": "social media"},
    {"indefinite": "robot", "definite": "roboten", "plural": "robotar", "plural_definite": "robotarna", "english": "robot"},
    {"indefinite": "maskin", "definite": "maskinen", "plural": "maskiner", "plural_definite": "maskinerna", "english": "machine"},
    {"indefinite": "innovation", "definite": "innovationen", "plural": "innovationer", "plural_definite": "innovationerna", "english": "innovation"},
    {"indefinite": "uppfinning", "definite": "uppfinningen", "plural": "uppfinningar", "plural_definite": "uppfinningarna", "english": "invention"},
    {"indefinite": "artificiell intelligens", "definite": "den artificiella intelligensen", "plural": "artificiella intelligenser", "plural_definite": "de artificiella intelligenserna", "english": "artificial intelligence"},
    {"indefinite": "algoritm", "definite": "algoritmen", "plural": "algoritmer", "plural_definite": "algoritmerna", "english": "algorithm"},
    {"indefinite": "dataskydd", "definite": "dataskyddet", "plural": "dataskydd", "plural_definite": "dataskydden", "english": "data protection"},
    {"indefinite": "digitalisering", "definite": "digitaliseringen", "plural": "digitaliseringar", "plural_definite": "digitaliseringarna", "english": "digitalization"},
    {"indefinite": "cyberattack", "definite": "cyberattacken", "plural": "cyberattacker", "plural_definite": "cyberattackerna", "english": "cyberattack"},
    {"indefinite": "elnät", "definite": "elnätet", "plural": "elnät", "plural_definite": "elnäten", "english": "power grid"},
    {"indefinite": "elbil", "definite": "elbilen", "plural": "elbilar", "plural_definite": "elbilarna", "english": "electric car"},
    {"indefinite": "utvecklare", "definite": "utvecklaren", "plural": "utvecklare", "plural_definite": "utvecklarna", "english": "developer"},
    {"indefinite": "plattform", "definite": "plattformen", "plural": "plattformar", "plural_definite": "plattformarna", "english": "platform"},
    {"indefinite": "kris", "definite": "krisen", "plural": "kriser", "plural_definite": "kriserna", "english": "crisis"},
    {"indefinite": "konflikt", "definite": "konflikten", "plural": "konflikter", "plural_definite": "konflikterna", "english": "conflict"},
    {"indefinite": "fred", "definite": "freden", "plural": "freder", "plural_definite": "frederna", "english": "peace"},
    {"indefinite": "krig", "definite": "kriget", "plural": "krig", "plural_definite": "krigen", "english": "war"},
    {"indefinite": "flykting", "definite": "flyktingen", "plural": "flyktingar", "plural_definite": "flyktingarna", "english": "refugee"},
    {"indefinite": "invandring", "definite": "invandringen", "plural": "invandringar", "plural_definite": "invandringarna", "english": "immigration"},
    {"indefinite": "integration", "definite": "integrationen", "plural": "integrationer", "plural_definite": "integrationerna", "english": "integration"},
    {"indefinite": "samhällsproblem", "definite": "samhällsproblemet", "plural": "samhällsproblem", "plural_definite": "samhällsproblemen", "english": "social issue"},
    {"indefinite": "framtid", "definite": "framtiden", "plural": "framtider", "plural_definite": "framtiderna", "english": "future"},
    {"indefinite": "påverkan", "definite": "påverkan", "plural": "påverkningar", "plural_definite": "påverkningarna", "english": "impact"},
    {"indefinite": "omställning", "definite": "omställningen", "plural": "omställningar", "plural_definite": "omställningarna", "english": "transition, conversion"},
    {"indefinite": "utbildning", "definite": "utbildningen", "plural": "utbildningar", "plural_definite": "utbildningarna", "english": "training, education"},
    {"indefinite": "yrkesverksam", "definite": "yrkesverksamma", "plural": "yrkesverksamma", "plural_definite": "yrkesverksamma", "english": "professional"},
    {"indefinite": "subvention", "definite": "subventionen", "plural": "subventioner", "plural_definite": "subventionerna", "english": "subsidy"},
    {"indefinite": "satsning", "definite": "satsningen", "plural": "satsningar", "plural_definite": "satsningarna", "english": "investment, initiative"},
    {"indefinite": "mål", "definite": "målet", "plural": "mål", "plural_definite": "målen", "english": "goal"},
    {"indefinite": "färdighet", "definite": "färdigheten", "plural": "färdigheter", "plural_definite": "färdigheterna", "english": "skill"},
]

misc = [
    {"swedish": "på grund av", "english": "because of"},
    {"swedish": "förnybar", "english": "renewable"},
        {"swedish": "rättvis", "english": "fair, just"},
    {"swedish": "orättvis", "english": "unfair, unjust"},
    {"swedish": "jämlik", "english": "equal (in rights)"},
    {"swedish": "ojämlik", "english": "unequal"},
    {"swedish": "fri", "english": "free"},
    {"swedish": "ofri", "english": "unfree, oppressed"},
    {"swedish": "demokratisk", "english": "democratic"},
    {"swedish": "odemokratisk", "english": "undemocratic"},
    {"swedish": "politisk", "english": "political"},
    {"swedish": "ekonomisk", "english": "economic"},
    {"swedish": "social", "english": "social"},
    {"swedish": "global", "english": "global"},
    {"swedish": "lokal", "english": "local"},
    {"swedish": "nationell", "english": "national"},
    {"swedish": "internationell", "english": "international"},
    {"swedish": "offentlig", "english": "public"},
    {"swedish": "privat", "english": "private"},
    {"swedish": "miljövänlig", "english": "environmentally friendly"},
    {"swedish": "hållbar", "english": "sustainable"},
    {"swedish": "ohållbar", "english": "unsustainable"},
    {"swedish": "klimatsmart", "english": "climate-smart"},
    {"swedish": "ekologisk", "english": "organic, ecological"},
    {"swedish": "teknisk", "english": "technical"},
    {"swedish": "digital", "english": "digital"},
    {"swedish": "modern", "english": "modern"},
    {"swedish": "traditionell", "english": "traditional"},
    {"swedish": "effektiv", "english": "efficient"},
    {"swedish": "ineffektiv", "english": "inefficient"},
    {"swedish": "säker", "english": "safe, secure"},
    {"swedish": "osäker", "english": "unsafe, uncertain"},
    {"swedish": "farlig", "english": "dangerous"},
    {"swedish": "trygg", "english": "secure, protected"},
    {"swedish": "billig", "english": "cheap"},
    {"swedish": "dyr", "english": "expensive"},
    {"swedish": "ekonomisk", "english": "financial, economical"},
    {"swedish": "lönsam", "english": "profitable"},
    {"swedish": "olönsam", "english": "unprofitable"},
    {"swedish": "framgångsrik", "english": "successful"},
    {"swedish": "misslyckad", "english": "failed, unsuccessful"},
    {"swedish": "viktig", "english": "important"},
    {"swedish": "avgörande", "english": "decisive, crucial"},
    {"swedish": "pålitlig", "english": "reliable"},
    {"swedish": "trovärdig", "english": "credible, trustworthy"},
    {"swedish": "opartisk", "english": "impartial"},
    {"swedish": "partisk", "english": "biased"},
    {"swedish": "aktiv", "english": "active"},
    {"swedish": "passiv", "english": "passive"},
    {"swedish": "ansvarig", "english": "responsible"},
    {"swedish": "engagerad", "english": "committed, involved"},
    {"swedish": "kritisk", "english": "critical"},
    {"swedish": "positiv", "english": "positive"},
    {"swedish": "negativ", "english": "negative"},
    {"swedish": "snabb", "english": "fast"},
    {"swedish": "långsam", "english": "slow"},
    {"swedish": "nära", "english": "close, nearby"},
    {"swedish": "långt borta", "english": "far away"},
    {"swedish": "ofta", "english": "often"},
    {"swedish": "sällan", "english": "rarely"},
    {"swedish": "ibland", "english": "sometimes"},
    {"swedish": "vanligtvis", "english": "usually"},
    {"swedish": "egentligen", "english": "actually, really"},
    {"swedish": "dessutom", "english": "in addition, moreover"},
    {"swedish": "däremot", "english": "on the other hand"},
    {"swedish": "därefter", "english": "after that, subsequently"},
    {"swedish": "tillsammans", "english": "together"},
    {"swedish": "ensam", "english": "alone"},
    {"swedish": "naturligtvis", "english": "of course, naturally"},
    {"swedish": "verkligen", "english": "really, truly"},
    {"swedish": "tydligen", "english": "apparently"},
    {"swedish": "ungefär", "english": "approximately"},
    {"swedish": "kanske", "english": "maybe, perhaps"},
    {"swedish": "sannolikt", "english": "likely"},
    {"swedish": "förmodligen", "english": "probably"},
    {"swedish": "eventuellt", "english": "possibly"},
    {"swedish": "antagligen", "english": "probably"},
    {"swedish": "redan", "english": "already"},
    {"swedish": "fortfarande", "english": "still"},
    {"swedish": "ännu", "english": "yet, still"},
    {"swedish": "nyligen", "english": "recently"},
    {"swedish": "snart", "english": "soon"},
    {"swedish": "plötsligt", "english": "suddenly"},
]

verbs = [
    {"infinitive": "påverka",
        "english": "affect",
        "present": "påverkar",
        "past": "påverkade",
        "supine": "påverkat",
        "imperative": "påverka",
        "passive": "påverkas",
        "adjective form": "påverkad"
    },
    {"infinitive": "bestämma",
        "english": "decide/determine",
        "present": "bestämmer",
        "past": "bestämde",
        "supine": "bestämt",
        "imperative": "bestäm",
        "passive": "bestäms",
        "adjective form": "bestämd"
    },
    {"infinitive": "styra",
        "english": "govern/control",
        "present": "styr",
        "past": "styrde",
        "supine": "styrt",
        "imperative": "styr",
        "passive": "styrs",
        "adjective form": "styrd"
    },
    {"infinitive": "leda",
        "english": "lead",
        "present": "leder",
        "past": "ledde",
        "supine": "lett",
        "imperative": "led",
        "passive": "leds",
        "adjective form": "ledd"
    },
    {"infinitive": "förändra",
        "english": "change",
        "present": "förändrar",
        "past": "förändrade",
        "supine": "förändrat",
        "imperative": "förändra",
        "passive": "förändras",
        "adjective form": "förändrad"
    },
    {"infinitive": "utveckla",
        "english": "develop",
        "present": "utvecklar",
        "past": "utvecklade",
        "supine": "utvecklat",
        "imperative": "utveckla",
        "passive": "utvecklas",
        "adjective form": "utvecklad"
    },
    {"infinitive": "bygga",
        "english": "build",
        "present": "bygger",
        "past": "byggde",
        "supine": "byggt",
        "imperative": "bygg",
        "passive": "byggs",
        "adjective form": "byggd"
    },
    {"infinitive": "skapa",
        "english": "create",
        "present": "skapar",
        "past": "skapade",
        "supine": "skapat",
        "imperative": "skapa",
        "passive": "skapas",
        "adjective form": "skapad"
    },
    {"infinitive": "förbättra",
        "english": "improve",
        "present": "förbättrar",
        "past": "förbättrade",
        "supine": "förbättrat",
        "imperative": "förbättra",
        "passive": "förbättras",
        "adjective form": "förbättrad"
    },
    {"infinitive": "minska",
        "english": "reduce",
        "present": "minskar",
        "past": "minskade",
        "supine": "minskat",
        "imperative": "minska",
        "passive": "minskas",
        "adjective form": "minskad"
    },
    {"infinitive": "öka",
        "english": "increase",
        "present": "ökar",
        "past": "ökade",
        "supine": "ökat",
        "imperative": "öka",
        "passive": "ökas",
        "adjective form": "ökad"
    },
    {"infinitive": "använda",
        "english": "use",
        "present": "använder",
        "past": "använde",
        "supine": "använt",
        "imperative": "använd",
        "passive": "användes",
        "adjective form": "använd"
    },
    {"infinitive": "producera",
        "english": "produce",
        "present": "producerar",
        "past": "producerade",
        "supine": "producerat",
        "imperative": "producera",
        "passive": "produceras",
        "adjective form": "producerad"
    },
    {"infinitive": "förbjuda",
        "english": "prohibit",
        "present": "förbjuder",
        "past": "förbjöd",
        "supine": "förbjudit",
        "imperative": "förbjud",
        "passive": "förbjuds",
        "adjective form": "förbjuden"
    },
    {"infinitive": "tillåta",
        "english": "allow/permit",
        "present": "tillåter",
        "past": "tillät",
        "supine": "tillåtit",
        "imperative": "tillåt",
        "passive": "tillåts",
        "adjective form": "tillåten"
    },
    {"infinitive": "diskutera",
        "english": "discuss",
        "present": "diskuterar",
        "past": "diskuterade",
        "supine": "diskuterat",
        "imperative": "diskutera",
        "passive": "diskuteras",
        "adjective form": "diskuterad"
    },
    {"infinitive": "besluta",
        "english": "decide",
        "present": "beslutar",
        "past": "beslutade",
        "supine": "beslutat",
        "imperative": "besluta",
        "passive": "beslutas",
        "adjective form": "beslutat"
    },
    {"infinitive": "rösta",
        "english": "vote",
        "present": "röstar",
        "past": "röstade",
        "supine": "röstat",
        "imperative": "rösta",
        "passive": "röstas",
        "adjective form": "röstad"
    },
    {"infinitive": "arbeta",
        "english": "work",
        "present": "arbetar",
        "past": "arbetade",
        "supine": "arbetat",
        "imperative": "arbeta",
        "passive": "arbetas",
        "adjective form": "arbetad"
    },
    {"infinitive": "tjäna",
        "english": "earn (money)",
        "present": "tjänar",
        "past": "tjänade",
        "supine": "tjänat",
        "imperative": "tjäna",
        "passive": "tjänades",
        "adjective form": "intjänad"
    },
    {"infinitive": "betala",
        "english": "pay",
        "present": "betalar",
        "past": "betalade",
        "supine": "betalat",
        "imperative": "betala",
        "passive": "betalades",
        "adjective form": "betalad"
    },
    {"infinitive": "spara",
        "english": "save (money)",
        "present": "sparar",
        "past": "sparade",
        "supine": "sparat",
        "imperative": "spara",
        "passive": "sparades",
        "adjective form": "sparad"
    },
    {"infinitive": "investera",
        "english": "invest",
        "present": "investerar",
        "past": "investerade",
        "supine": "investerat",
        "imperative": "investera",
        "passive": "investeras",
        "adjective form": "investerad"
    },
    {"infinitive": "forska",
        "english": "research",
        "present": "forskar",
        "past": "forskade",
        "supine": "forskat",
        "imperative": "forska",
        "passive": "forskas",
        "adjective form": "forskad"
    },
    {"infinitive": "uppfinna",
        "english": "invent",
        "present": "uppfinner",
        "past": "uppfann",
        "supine": "uppfunnit",
        "imperative": "uppfinn",
        "passive": "uppfinns",
        "adjective form": "uppfunnen"
    },
    {"infinitive": "förklara",
        "english": "explain",
        "present": "förklarar",
        "past": "förklarade",
        "supine": "förklarat",
        "imperative": "förklara",
        "passive": "förklarades",
        "adjective form": "förklarad"
    },
    {"infinitive": "informera",
        "english": "inform",
        "present": "informerar",
        "past": "informerade",
        "supine": "informerat",
        "imperative": "informera",
        "passive": "informeras",
        "adjective form": "informerad"
    },
    {"infinitive": "rapportera",
        "english": "report",
        "present": "rapporterar",
        "past": "rapporterade",
        "supine": "rapporterat",
        "imperative": "rapportera",
        "passive": "rapporterades",
        "adjective form": "rapporterad"
    },
    {"infinitive": "kontrollera",
        "english": "check/verify",
        "present": "kontrollerar",
        "past": "kontrollerade",
        "supine": "kontrollerat",
        "imperative": "kontrollera",
        "passive": "kontrollerades",
        "adjective form": "kontrollerad"
    },
    {"infinitive": "övervaka",
        "english": "monitor/oversee",
        "present": "övervakar",
        "past": "övervakade",
        "supine": "övervakat",
        "imperative": "övervaka",
        "passive": "övervakades",
        "adjective form": "övervakad"
    },
    {"infinitive": "försvara",
        "english": "defend/justify",
        "present": "försvarar",
        "past": "försvarade",
        "supine": "försvarat",
        "imperative": "försvara",
        "passive": "försvarades",
        "adjective form": "försvarad"
    },
    {"infinitive": "skydda",
        "english": "protect",
        "present": "skyddar",
        "past": "skyddade",
        "supine": "skyddat",
        "imperative": "skydda",
        "passive": "skyddades",
        "adjective form": "skyddad"
    },
    {"infinitive": "hjälpa",
        "english": "help",
        "present": "hjälper",
        "past": "hjälpte",
        "supine": "hjälpt",
        "imperative": "hjälp",
        "passive": "",
        "adjective form": "hjälpt"
    },
    {"infinitive": "påminna",
        "english": "remind",
        "present": "påminner",
        "past": "påminde",
        "supine": "påmint",
        "imperative": "påminn",
        "passive": "påminns",
        "adjective form": "påmind"
    },
    {"infinitive": "stöda",
        "english": "support",
        "present": "stöder",
        "past": "stödde",
        "supine": "stött",
        "imperative": "stöd",
        "passive": "stöds",
        "adjective form": "stödd"
    },
    {"infinitive": "tillhöra",
        "english": "belong",
        "present": "tillhör",
        "past": "tillhörde",
        "supine": "tillhört",
        "imperative": "tillhör",
        "passive": "",
        "adjective form": "tillhörande"
    },
    {"infinitive": "tro",
        "english": "believe",
        "present": "tror",
        "past": "trodde",
        "supine": "trott",
        "imperative": "tro",
        "passive": "tros",
        "adjective form": "trodd"
    },
    {"infinitive": "tycka",
        "english": "think",
        "present": "tycker",
        "past": "tyckte",
        "supine": "tyckt",
        "imperative": "tyck",
        "passive": "tycks"
    },
    {"infinitive": "anse",
        "english": "consider",
        "present": "anser",
        "past": "ansåg",
        "supine": "ansett",
        "imperative": "anse",
        "passive": "anses",
        "adjective form": ""
    },
    {"infinitive": "hålla med",
        "english": "agree",
        "present": "håller",
        "past": "höll",
        "supine": "hållit",
        "imperative": "håll",
        "passive": "",
        "adjective form": ""
    },
    {"infinitive": "försvinna",
        "english": "disappear",
        "present": "försvinner",
        "past": "försvann",
        "supine": "försvunnit",
        "imperative": "försvinna",
        "passive": "",
        "adjective form": "försvunnen"
    },
    {"infinitive": "ersätta",
        "english": "replace",
        "present": "ersätter",
        "past": "ersatte",
        "supine": "ersatt",
        "imperative": "ersätt",
        "passive": "ersattes",
        "adjective form": "ersatt"
    },
    {"infinitive": "påpeka",
        "english": "point out",
        "present": "påpekar",
        "past": "påpekade",
        "supine": "påpekat",
        "imperative": "påpeka",
        "passive": "påpekades",
        "adjective form": "påpekad"
    },
    {"infinitive": "nå",
        "english": "reach/gain (business)",
        "present": "når",
        "past": "nådde",
        "supine": "nått",
        "imperative": "nå",
        "passive": "nås",
        "adjective form": "nådd"
    },
    {"infinitive": "underlätta",
        "english": "facilitate",
        "present": "underlättar",
        "past": "underlätterade",
        "supine": "underlätt",
        "imperative": "underlätta",
        "passive": "underlättades",
        "adjective form": "underlättad"
    },
    {"infinitive": "förbli",
        "english": "remain",
        "present": "förblir",
        "past": "förblev",
        "supine": "förblivit",
        "imperative": "förbliv",
        "passive": "",
        "adjective form": ""
    }
]