nouns = [
    {"indefinite": "flygplats", "definite": "flygplatsen", "plural": "flygplatser", "plural_definite": "flygplatserna", "english": "airport", "cefr": 2, "frequency": 32.90},
    {"indefinite": "tågstation", "definite": "tågstationen", "plural": "tågstationer", "plural_definite": "tågstationerna", "english": "train station", "cefr": 1, "frequency": None},
    {"indefinite": "busshållplats", "definite": "busshållplatsen", "plural": "busshållplatser", "plural_definite": "busshållplatserna", "english": "bus stop", "cefr": 1, "frequency": None},
    {"indefinite": "hållplats", "definite": "hållplatsen", "plural": "hållplatser", "plural_definite": "hållplatserna", "english": "stop", "cefr": 1, "frequency": None},
    {"indefinite": "biljett", "definite": "biljetten", "plural": "biljetter", "plural_definite": "biljetterna", "english": "ticket", "cefr": 3, "frequency": 22.43},
    {"indefinite": "pass", "definite": "passet", "plural": "pass", "plural_definite": "passen", "english": "passport", "cefr": 2, "frequency": 30.20},
    {"indefinite": "visum", "definite": "visumet", "plural": "visum", "plural_definite": "visumen", "english": "visa", "cefr": 1, "frequency": None},
    {"indefinite": "flyg", "definite": "flyget", "plural": "flyg", "plural_definite": "flygen", "english": "flight", "cefr": 2, "frequency": 24.66},
    {"indefinite": "avgång", "definite": "avgången", "plural": "avgångar", "plural_definite": "avgångarna", "english": "departure", "cefr": 1, "frequency": None},
    {"indefinite": "ankomst", "definite": "ankomsten", "plural": "ankomster", "plural_definite": "ankomsterna", "english": "arrival", "cefr": 3, "frequency": 12.18},
    {"indefinite": "båt", "definite": "båten", "plural": "båtar", "plural_definite": "båtarna", "english": "boat", "cefr": 1, "frequency": 66.17},
    {"indefinite": "färja", "definite": "färjan", "plural": "färjor", "plural_definite": "färjorna", "english": "ferry", "cefr": 1, "frequency": None},
    {"indefinite": "väg", "definite": "vägen", "plural": "vägar", "plural_definite": "vägarna", "english": "road", "cefr": 1, "frequency": 420.51},
    {"indefinite": "gata", "definite": "gatan", "plural": "gator", "plural_definite": "gatorna", "english": "street", "cefr": 1, "frequency": 70.48},
    {"indefinite": "karta", "definite": "kartan", "plural": "kartor", "plural_definite": "kartorna", "english": "map", "cefr": 2, "frequency": 33.33},
    {"indefinite": "bagage", "definite": "bagaget", "plural": "bagage", "plural_definite": "bagagen", "english": "luggage", "cefr": 1, "frequency": None},
    {"indefinite": "väska", "definite": "väskan", "plural": "väskor", "plural_definite": "väskorna", "english": "bag, suitcase", "cefr": 3, "frequency": 17.78},
    {"indefinite": "ryggsäck", "definite": "ryggsäcken", "plural": "ryggsäckar", "plural_definite": "ryggsäckarna", "english": "backpack", "cefr": 1, "frequency": None},
    {"indefinite": "hotell", "definite": "hotellet", "plural": "hotell", "plural_definite": "hotellen", "english": "hotel", "cefr": 2, "frequency": 42.00},
    {"indefinite": "vandrarhem", "definite": "vandrarhemmet", "plural": "vandrarhem", "plural_definite": "vandrarhemmen", "english": "hostel", "cefr": 1, "frequency": None},
    {"indefinite": "campingplats", "definite": "campingplatsen", "plural": "campingplatser", "plural_definite": "campingplatserna", "english": "campground", "cefr": 1, "frequency": None},
    {"indefinite": "bokning", "definite": "bokningen", "plural": "bokningar", "plural_definite": "bokningarna", "english": "booking", "cefr": 1, "frequency": None},
    {"indefinite": "reservation", "definite": "reservationen", "plural": "reservationer", "plural_definite": "reservationerna", "english": "reservation", "cefr": 2, "frequency": 28.25},
    {"indefinite": "nyckel", "definite": "nyckeln", "plural": "nycklar", "plural_definite": "nycklarna", "english": "key", "cefr": 2, "frequency": 24.59},
    {"indefinite": "guide", "definite": "guiden", "plural": "guider", "plural_definite": "guiderna", "english": "guide", "cefr": 3, "frequency": 13.77},
    {"indefinite": "turist", "definite": "turisten", "plural": "turister", "plural_definite": "turisterna", "english": "tourist", "cefr": 3, "frequency": 18.67},
    {"indefinite": "turism", "definite": "turismen", "plural": "turismer", "plural_definite": "turismerna", "english": "tourism", "cefr": 1, "frequency": None},
    {"indefinite": "semesterort", "definite": "semesterorten", "plural": "semesterorter", "plural_definite": "semesterorterna", "english": "holiday resort", "cefr": 1, "frequency": None},
    {"indefinite": "utsikt", "definite": "utsikten", "plural": "utsikter", "plural_definite": "utsikterna", "english": "view", "cefr": 2, "frequency": 25.14},
    {"indefinite": "äventyr", "definite": "äventyret", "plural": "äventyr", "plural_definite": "äventyren", "english": "adventure", "cefr": 3, "frequency": 21.80},
    {"indefinite": "semesterresa", "definite": "semesterresan", "plural": "semesterresor", "plural_definite": "semesterresorna", "english": "holiday trip", "cefr": 1, "frequency": None},
]

verbs = [
    {"infinitive": "åka", "present": "åker", "past": "åkte", "supine": "åkt", "english": "to go (by vehicle)", "cefr": 1, "frequency": 243.14},
    {"infinitive": "flyga", "present": "flyger", "past": "flög", "supine": "flugit", "english": "to fly", "cefr": 2, "frequency": 47.45},
    {"infinitive": "vandra", "present": "vandrar", "past": "vandrade", "supine": "vandrat", "english": "to hike", "cefr": 2, "frequency": 31.46},
    {"infinitive": "boka", "present": "bokar", "past": "bokade", "supine": "bokat", "english": "to book", "cefr": 2, "frequency": 26.10},
    {"infinitive": "avboka", "present": "avbokar", "past": "avbokade", "supine": "avbokat", "english": "to cancel (booking)", "cefr": 1, "frequency": None},
    {"infinitive": "övernatta", "present": "övernattar", "past": "övernattade", "supine": "övernattat", "english": "to stay overnight", "cefr": 1, "frequency": None},
    {"infinitive": "upptäcka", "present": "upptäcker", "past": "upptäckte", "supine": "upptäckt", "english": "to discover", "cefr": 1, "frequency": 90.72},
    {"infinitive": "visa", "present": "visar", "past": "visade", "supine": "visat", "english": "to show", "cefr": 1, "frequency": 757.44},
    {"infinitive": "hitta", "present": "hittar", "past": "hittade", "supine": "hittat", "english": "to find", "cefr": 1, "frequency": 390.73},
    {"infinitive": "tappa bort", "present": "tappar bort", "past": "tappade bort", "supine": "tappat bort", "english": "to lose", "cefr": 1, "frequency": None},
    {"infinitive": "komma fram", "present": "kommer fram", "past": "kom fram", "supine": "kommit fram", "english": "to arrive", "cefr": 1, "frequency": None},
]

misc = [
    {"swedish": "långt", "english": "far", "cefr": 1, "frequency": None},
    {"swedish": "tidig", "english": "early", "cefr": 1, "frequency": 225.46},
    {"swedish": "sen", "english": "late", "cefr": 1, "frequency": 459.09},
    {"swedish": "obekväm", "english": "uncomfortable", "cefr": 1, "frequency": None},
    {"swedish": "avkopplande", "english": "relaxing", "cefr": 1, "frequency": None},
    {"swedish": "nästa", "english": "next", "cefr": 1, "frequency": 237.94},
    {"swedish": "förra", "english": "last (previous)", "cefr": 1, "frequency": 170.92},
    {"swedish": "äntligen", "english": "finally", "cefr": 1, "frequency": 69.88},
]
