nouns = [
    {"indefinite": "resa", "definite": "resan", "plural": "resor", "plural_definite": "resorna", "english": "trip, journey"},
    {"indefinite": "semester", "definite": "semestern", "plural": "semestrar", "plural_definite": "semestrarna", "english": "vacation"},
    {"indefinite": "flygplats", "definite": "flygplatsen", "plural": "flygplatser", "plural_definite": "flygplatserna", "english": "airport"},
    {"indefinite": "tågstation", "definite": "tågstationen", "plural": "tågstationer", "plural_definite": "tågstationerna", "english": "train station"},
    {"indefinite": "busshållplats", "definite": "busshållplatsen", "plural": "busshållplatser", "plural_definite": "busshållplatserna", "english": "bus stop"},
    {"indefinite": "hållplats", "definite": "hållplatsen", "plural": "hållplatser", "plural_definite": "hållplatserna", "english": "stop"},
    {"indefinite": "biljett", "definite": "biljetten", "plural": "biljetter", "plural_definite": "biljetterna", "english": "ticket"},
    {"indefinite": "pass", "definite": "passet", "plural": "pass", "plural_definite": "passen", "english": "passport"},
    {"indefinite": "visum", "definite": "visumet", "plural": "visum", "plural_definite": "visumen", "english": "visa"},
    {"indefinite": "resa", "definite": "resan", "plural": "resor", "plural_definite": "resorna", "english": "journey"},
    {"indefinite": "flyg", "definite": "flyget", "plural": "flyg", "plural_definite": "flygen", "english": "flight"},
    {"indefinite": "avgång", "definite": "avgången", "plural": "avgångar", "plural_definite": "avgångarna", "english": "departure"},
    {"indefinite": "ankomst", "definite": "ankomsten", "plural": "ankomster", "plural_definite": "ankomsterna", "english": "arrival"},
    {"indefinite": "tåg", "definite": "tåget", "plural": "tåg", "plural_definite": "tågen", "english": "train"},
    {"indefinite": "buss", "definite": "bussen", "plural": "bussar", "plural_definite": "bussarna", "english": "bus"},
    {"indefinite": "båt", "definite": "båten", "plural": "båtar", "plural_definite": "båtarna", "english": "boat"},
    {"indefinite": "färja", "definite": "färjan", "plural": "färjor", "plural_definite": "färjorna", "english": "ferry"},
    {"indefinite": "bil", "definite": "bilen", "plural": "bilar", "plural_definite": "bilarna", "english": "car"},
    {"indefinite": "cykel", "definite": "cykeln", "plural": "cyklar", "plural_definite": "cyklarna", "english": "bicycle"},
    {"indefinite": "väg", "definite": "vägen", "plural": "vägar", "plural_definite": "vägarna", "english": "road"},
    {"indefinite": "gata", "definite": "gatan", "plural": "gator", "plural_definite": "gatorna", "english": "street"},
    {"indefinite": "karta", "definite": "kartan", "plural": "kartor", "plural_definite": "kartorna", "english": "map"},
    {"indefinite": "bagage", "definite": "bagaget", "plural": "bagage", "plural_definite": "bagagen", "english": "luggage"},
    {"indefinite": "väska", "definite": "väskan", "plural": "väskor", "plural_definite": "väskorna", "english": "bag, suitcase"},
    {"indefinite": "ryggsäck", "definite": "ryggsäcken", "plural": "ryggsäckar", "plural_definite": "ryggsäckarna", "english": "backpack"},
    {"indefinite": "hotell", "definite": "hotellet", "plural": "hotell", "plural_definite": "hotellen", "english": "hotel"},
    {"indefinite": "vandrarhem", "definite": "vandrarhemmet", "plural": "vandrarhem", "plural_definite": "vandrarhemmen", "english": "hostel"},
    {"indefinite": "campingplats", "definite": "campingplatsen", "plural": "campingplatser", "plural_definite": "campingplatserna", "english": "campground"},
    {"indefinite": "rum", "definite": "rummet", "plural": "rum", "plural_definite": "rummen", "english": "room"},
    {"indefinite": "bokning", "definite": "bokningen", "plural": "bokningar", "plural_definite": "bokningarna", "english": "booking"},
    {"indefinite": "reservation", "definite": "reservationen", "plural": "reservationer", "plural_definite": "reservationerna", "english": "reservation"},
    {"indefinite": "nyckel", "definite": "nyckeln", "plural": "nycklar", "plural_definite": "nycklarna", "english": "key"},
    {"indefinite": "guide", "definite": "guiden", "plural": "guider", "plural_definite": "guiderna", "english": "guide"},
    {"indefinite": "turist", "definite": "turisten", "plural": "turister", "plural_definite": "turisterna", "english": "tourist"},
    {"indefinite": "turism", "definite": "turismen", "plural": "turismer", "plural_definite": "turismerna", "english": "tourism"},
    {"indefinite": "resa", "definite": "resan", "plural": "resor", "plural_definite": "resorna", "english": "travel"},
    {"indefinite": "semesterort", "definite": "semesterorten", "plural": "semesterorter", "plural_definite": "semesterorterna", "english": "holiday resort"},
    {"indefinite": "strand", "definite": "stranden", "plural": "stränder", "plural_definite": "stränderna", "english": "beach"},
    {"indefinite": "berg", "definite": "berget", "plural": "berg", "plural_definite": "bergen", "english": "mountain"},
    {"indefinite": "sjö", "definite": "sjön", "plural": "sjöar", "plural_definite": "sjöarna", "english": "lake"},
    {"indefinite": "hav", "definite": "havet", "plural": "hav", "plural_definite": "haven", "english": "sea"},
    {"indefinite": "utsikt", "definite": "utsikten", "plural": "utsikter", "plural_definite": "utsikterna", "english": "view"},
    {"indefinite": "äventyr", "definite": "äventyret", "plural": "äventyr", "plural_definite": "äventyren", "english": "adventure"},
    {"indefinite": "upplevelse", "definite": "upplevelsen", "plural": "upplevelser", "plural_definite": "upplevelserna", "english": "experience"},
    {"indefinite": "resa", "definite": "resan", "plural": "resor", "plural_definite": "resorna", "english": "trip"},
    {"indefinite": "resa", "definite": "resan", "plural": "resor", "plural_definite": "resorna", "english": "journey"},
    {"indefinite": "semesterresa", "definite": "semesterresan", "plural": "semesterresor", "plural_definite": "semesterresorna", "english": "holiday trip"},
]

verbs = [
    {"infinitive": "resa", "present": "reser", "past": "reste", "supine": "rest", "english": "to travel"},
    {"infinitive": "åka", "present": "åker", "past": "åkte", "supine": "åkt", "english": "to go (by vehicle)"},
    {"infinitive": "flyga", "present": "flyger", "past": "flög", "supine": "flugit", "english": "to fly"},
    {"infinitive": "köra", "present": "kör", "past": "körde", "supine": "kört", "english": "to drive"},
    {"infinitive": "gå", "present": "går", "past": "gick", "supine": "gått", "english": "to walk"},
    {"infinitive": "vandra", "present": "vandrar", "past": "vandrade", "supine": "vandrat", "english": "to hike"},
    {"infinitive": "cykla", "present": "cyklar", "past": "cyklade", "supine": "cyklat", "english": "to cycle"},
    {"infinitive": "boka", "present": "bokar", "past": "bokade", "supine": "bokat", "english": "to book"},
    {"infinitive": "avboka", "present": "avbokar", "past": "avbokade", "supine": "avbokat", "english": "to cancel (booking)"},
    {"infinitive": "packa", "present": "packar", "past": "packade", "supine": "packat", "english": "to pack"},
    {"infinitive": "stanna", "present": "stannar", "past": "stannade", "supine": "stannat", "english": "to stay, stop"},
    {"infinitive": "övernatta", "present": "övernattar", "past": "övernattade", "supine": "övernattat", "english": "to stay overnight"},
    {"infinitive": "besöka", "present": "besöker", "past": "besökte", "supine": "besökt", "english": "to visit"},
    {"infinitive": "upptäcka", "present": "upptäcker", "past": "upptäckte", "supine": "upptäckt", "english": "to discover"},
    {"infinitive": "glömma", "present": "glömmer", "past": "glömde", "supine": "glömt", "english": "to forget"},
    {"infinitive": "visa", "present": "visar", "past": "visade", "supine": "visat", "english": "to show"},
    {"infinitive": "hitta", "present": "hittar", "past": "hittade", "supine": "hittat", "english": "to find"},
    {"infinitive": "tappa bort", "present": "tappar bort", "past": "tappade bort", "supine": "tappat bort", "english": "to lose"},
    {"infinitive": "vänta", "present": "väntar", "past": "väntade", "supine": "väntat", "english": "to wait"},
    {"infinitive": "komma fram", "present": "kommer fram", "past": "kom fram", "supine": "kommit fram", "english": "to arrive"},
]

misc = [
    {"swedish": "borta", "english": "away"},
    {"swedish": "hemma", "english": "at home"},
    {"swedish": "nära", "english": "near"},
    {"swedish": "långt", "english": "far"},
    {"swedish": "tidig", "english": "early"},
    {"swedish": "sen", "english": "late"},
    {"swedish": "snabb", "english": "fast"},
    {"swedish": "bekväm", "english": "comfortable"},
    {"swedish": "obekväm", "english": "uncomfortable"},
    {"swedish": "säker", "english": "safe"},
    {"swedish": "osäker", "english": "unsafe"},
    {"swedish": "rolig", "english": "fun"},
    {"swedish": "tråkig", "english": "boring"},
    {"swedish": "intressant", "english": "interesting"},
    {"swedish": "spännande", "english": "exciting"},
    {"swedish": "avkopplande", "english": "relaxing"},
    {"swedish": "billig", "english": "cheap"},
    {"swedish": "dyr", "english": "expensive"},
    {"swedish": "nästa", "english": "next"},
    {"swedish": "förra", "english": "last (previous)"},
    {"swedish": "ofta", "english": "often"},
    {"swedish": "ibland", "english": "sometimes"},
    {"swedish": "sällan", "english": "rarely"},
    {"swedish": "aldrig", "english": "never"},
    {"swedish": "redan", "english": "already"},
    {"swedish": "snart", "english": "soon"},
    {"swedish": "äntligen", "english": "finally"},
    {"swedish": "trots", "english": "despite"},
    {"swedish": "på grund av", "english": "because of"},
    {"swedish": "för att", "english": "in order to"},
    {"swedish": "eftersom", "english": "because"},
    {"swedish": "innan", "english": "before"},
    {"swedish": "efteråt", "english": "afterwards"},
    {"swedish": "medan", "english": "while"},
    {"swedish": "så att", "english": "so that"},
]
