nouns = [
    {"indefinite": "arbete", "definite": "arbetet", "plural": "arbeten", "plural_definite": "arbetena", "english": "work, job", "cefr": 1, "frequency": 441.90},
    {"indefinite": "anställning", "definite": "anställningen", "plural": "anställningar", "plural_definite": "anställningarna", "english": "employment", "cefr": 2, "frequency": 34.72},
    {"indefinite": "kollega", "definite": "kollegan", "plural": "kollegor", "plural_definite": "kollegorna", "english": "colleague", "cefr": 2, "frequency": 49.68},
    {"indefinite": "chef", "definite": "chefen", "plural": "chefer", "plural_definite": "cheferna", "english": "manager, boss", "cefr": 1, "frequency": 79.17},
    {"indefinite": "anställd", "definite": "anställda", "plural": "anställda", "plural_definite": "anställda", "english": "employee (person)", "cefr": 2, "frequency": 57.15},
    {"indefinite": "praktik", "definite": "praktiken", "plural": "praktiker", "plural_definite": "praktikerna", "english": "internship", "cefr": 1, "frequency": 79.79},
    {"indefinite": "yrke", "definite": "yrket", "plural": "yrken", "plural_definite": "yrkena", "english": "profession, occupation", "cefr": 2, "frequency": 28.24},
    {"indefinite": "möte", "definite": "mötet", "plural": "möten", "plural_definite": "mötena", "english": "meeting", "cefr": 1, "frequency": 153.97},
    {"indefinite": "projekt", "definite": "projektet", "plural": "projekt", "plural_definite": "projekten", "english": "project", "cefr": 1, "frequency": 148.31},
    {"indefinite": "uppgift", "definite": "uppgiften", "plural": "uppgifter", "plural_definite": "uppgifterna", "english": "task, assignment", "cefr": 1, "frequency": 287.98},
    {"indefinite": "karriär", "definite": "karriären", "plural": "karriärer", "plural_definite": "karriärerna", "english": "career", "cefr": 2, "frequency": 37.72},
    {"indefinite": "förmån", "definite": "förmånen", "plural": "förmåner", "plural_definite": "förmånerna", "english": "benefit, perk", "cefr": 2, "frequency": 25.31},
    {"indefinite": "arbetstid", "definite": "arbetstiden", "plural": "arbetstider", "plural_definite": "arbetstiderna", "english": "working hours", "cefr": 3, "frequency": 19.81},
    {"indefinite": "ledig dag", "definite": "lediga dagen", "plural": "lediga dagar", "plural_definite": "lediga dagarna", "english": "day off", "cefr": 1, "frequency": None},
    {"indefinite": "övertid", "definite": "övertiden", "plural": "övertider", "plural_definite": "övertiderna", "english": "overtime", "cefr": 1, "frequency": None},
    {"indefinite": "arbetssökande", "definite": "arbetssökanden", "plural": "arbetssökande", "plural_definite": "arbetssökandena", "english": "job seeker", "cefr": 1, "frequency": None},
    {"indefinite": "anställningsintervju", "definite": "anställningsintervjun", "plural": "anställningsintervjuer", "plural_definite": "anställningsintervjuerna", "english": "job interview", "cefr": 1, "frequency": None},
    {"indefinite": "cv", "definite": "cv:t", "plural": "cv:n", "plural_definite": "cv:na", "english": "CV, résumé", "cefr": 1, "frequency": None},
    {"indefinite": "referens", "definite": "referensen", "plural": "referenser", "plural_definite": "referenserna", "english": "reference", "cefr": 2, "frequency": 27.39},
    {"indefinite": "kollektivavtal", "definite": "kollektivavtalet", "plural": "kollektivavtal", "plural_definite": "kollektivavtalen", "english": "collective agreement", "cefr": 3, "frequency": 18.16},
    {"indefinite": "fackförening", "definite": "fackföreningen", "plural": "fackföreningar", "plural_definite": "fackföreningarna", "english": "trade union", "cefr": 3, "frequency": 20.37},
    {"indefinite": "anställningsform", "definite": "anställningsformen", "plural": "anställningsformer", "plural_definite": "anställningsformerna", "english": "type of employment", "cefr": 1, "frequency": None},
    {"indefinite": "provanställning", "definite": "provanställningen", "plural": "provanställningar", "plural_definite": "provanställningarna", "english": "probationary employment", "cefr": 1, "frequency": None},
    {"indefinite": "fast anställning", "definite": "fasta anställningen", "plural": "fasta anställningar", "plural_definite": "fasta anställningarna", "english": "permanent job", "cefr": 1, "frequency": None},
    {"indefinite": "vikariat", "definite": "vikariatet", "plural": "vikariat", "plural_definite": "vikariaten", "english": "temporary position", "cefr": 1, "frequency": None},
    {"indefinite": "löneförhöjning", "definite": "löneförhöjningen", "plural": "löneförhöjningar", "plural_definite": "löneförhöjningarna", "english": "pay raise", "cefr": 1, "frequency": None},
    {"indefinite": "kontrakt", "definite": "kontraktet", "plural": "kontrakt", "plural_definite": "kontrakten", "english": "contract", "cefr": 2, "frequency": 29.78},
    {"indefinite": "arbetsuppgift", "definite": "arbetsuppgiften", "plural": "arbetsuppgifter", "plural_definite": "arbetsuppgifterna", "english": "work task", "cefr": 3, "frequency": 17.78},
    {"indefinite": "möjlighet", "definite": "möjligheten", "plural": "möjligheter", "plural_definite": "möjligheterna", "english": "opportunity", "cefr": 1, "frequency": 411.21},
    {"indefinite": "utmaning", "definite": "utmaningen", "plural": "utmaningar", "plural_definite": "utmaningarna", "english": "challenge", "cefr": 2, "frequency": 58.16},
    {"indefinite": "framgång", "definite": "framgången", "plural": "framgångar", "plural_definite": "framgångarna", "english": "success", "cefr": 1, "frequency": 73.07},
    {"indefinite": "misslyckande", "definite": "misslyckandet", "plural": "misslyckanden", "plural_definite": "misslyckandena", "english": "failure", "cefr": 3, "frequency": 15.72},
    {"indefinite": "fortbildning", "definite": "fortbildningen", "plural": "fortbildningar", "plural_definite": "fortbildningarna", "english": "further education", "cefr": 1, "frequency": None},
    {"indefinite": "karriärmöjlighet", "definite": "karriärmöjligheten", "plural": "karriärmöjligheter", "plural_definite": "karriärmöjligheterna", "english": "career opportunity", "cefr": 1, "frequency": None},
    {"indefinite": "arbetsmiljö", "definite": "arbetsmiljön", "plural": "arbetsmiljöer", "plural_definite": "arbetsmiljöerna", "english": "work environment", "cefr": 1, "frequency": None},
    {"indefinite": "konferens", "definite": "konferensen", "plural": "konferenser", "plural_definite": "konferenserna", "english": "conference", "cefr": 2, "frequency": 43.68},
    {"indefinite": "presentation", "definite": "presentationen", "plural": "presentationer", "plural_definite": "presentationerna", "english": "presentation", "cefr": 3, "frequency": 19.28},
    {"indefinite": "deadline", "definite": "deadlinen", "plural": "deadlines", "plural_definite": "deadlinesen", "english": "deadline", "cefr": 1, "frequency": None},
]

misc = [
    {"word": "flitig", "english": "hardworking, diligent", "cefr": 1, "frequency": None},
    {"word": "noggrann", "english": "thorough, meticulous", "cefr": 3, "frequency": 13.76},
    {"word": "flexibel", "english": "flexible", "cefr": 3, "frequency": 16.61},
    {"word": "ambitiös", "english": "ambitious", "cefr": 1, "frequency": None},
    {"word": "tålmodig", "english": "patient", "cefr": 1, "frequency": None},
    {"word": "ansvarsfull", "english": "responsible", "cefr": 1, "frequency": None},
    {"word": "ordentlig", "english": "organized, tidy", "cefr": 3, "frequency": 19.16},
    {"word": "ledig", "english": "free, off work", "cefr": 2, "frequency": 29.56},
    {"word": "meningsfull", "english": "meaningful", "cefr": 3, "frequency": 12.73},
    {"word": "krävande", "english": "demanding", "cefr": 1, "frequency": None},
    {"word": "utmanande", "english": "challenging", "cefr": 1, "frequency": None},
    {"word": "kompetent", "english": "competent", "cefr": 3, "frequency": 13.70},
    {"word": "erfaren", "english": "experienced", "cefr": 1, "frequency": None},
    {"word": "ny", "english": "new", "cefr": 1, "frequency": 1446.08},
    {"word": "nuvarande", "english": "current", "cefr": 1, "frequency": 126.21},
    {"word": "teoretisk", "english": "theoretical", "cefr": 3, "frequency": 20.09},
    {"word": "professionell", "english": "professional", "cefr": 3, "frequency": 22.20},
    {"word": "personlig", "english": "personal", "cefr": 1, "frequency": 143.81},
    {"word": "rimlig", "english": "reasonable, fair", "cefr": 1, "frequency": 70.42},
    {"word": "framgång", "english": "success (used adjectivally in phrases like framgångsrik)", "cefr": 1, "frequency": 73.07},
    {"word": "efter att", "english": "after", "cefr": 1, "frequency": 206.69},
    {"word": "både ... och", "english": "both ... and", "cefr": 1, "frequency": None},
    {"word": "antingen ... eller", "english": "either ... or", "cefr": 1, "frequency": None},
    {"word": "varken ... eller", "english": "neither ... nor", "cefr": 1, "frequency": None},
]

verbs = [
    {"infinitive": "anställa", "english": "to hire, employ", "present": "anställer", "past": "anställde", "supine": "anställt", "cefr": 2, "frequency": 30.69},
    {"infinitive": "avskeda", "english": "to fire, dismiss", "present": "avskedar", "past": "avskedade", "supine": "avskedat", "cefr": 1, "frequency": None},
    {"infinitive": "söka", "english": "to apply (for)", "present": "söker", "past": "sökte", "supine": "sökt", "cefr": 1, "frequency": 596.07},
    {"infinitive": "ha", "english": "to have", "present": "har", "past": "hade", "supine": "haft", "cefr": 1, "frequency": 15983.31},
    {"infinitive": "fortsätta", "english": "to continue", "present": "fortsätter", "past": "fortsatte", "supine": "fortsatt", "cefr": 1, "frequency": 337.29},
    {"infinitive": "arbeta över", "english": "to work overtime", "present": "arbetar över", "past": "arbetade över", "supine": "arbetat över", "cefr": 1, "frequency": None},
    {"infinitive": "pendla", "english": "to commute", "present": "pendlar", "past": "pendlade", "supine": "pendlat", "cefr": 1, "frequency": None},
    {"infinitive": "samarbeta", "english": "to cooperate, collaborate", "present": "samarbetar", "past": "samarbetade", "supine": "samarbetat", "cefr": 2, "frequency": 39.84},
    {"infinitive": "utbilda", "english": "to educate, train", "present": "utbildar", "past": "utbildade", "supine": "utbildat", "cefr": 2, "frequency": 24.39},
    {"infinitive": "forskа", "english": "to do research", "present": "forskar", "past": "forskade", "supine": "forskat", "cefr": 1, "frequency": None},
    {"infinitive": "stödja", "english": "to support", "present": "stödjer", "past": "stödde", "supine": "stött", "cefr": 1, "frequency": 123.76},
    {"infinitive": "hantera", "english": "to handle, manage", "present": "hanterar", "past": "hanterade", "supine": "hanterat", "cefr": 1, "frequency": 92.87},
    {"infinitive": "misslyckas", "english": "to fail", "present": "misslyckas", "past": "misslyckades", "supine": "misslyckats", "cefr": 2, "frequency": 42.04},
    {"infinitive": "leverera", "english": "to deliver", "present": "levererar", "past": "levererade", "supine": "levererat", "cefr": 2, "frequency": 45.14},
    {"infinitive": "ta emot", "english": "to receive", "present": "tar emot", "past": "tog emot", "supine": "tagit emot", "cefr": 1, "frequency": None},
]
