nouns = [
    {"indefinite": "arbete", "definite": "arbetet", "plural": "arbeten", "plural_definite": "arbetena", "english": "work, job"},
    {"indefinite": "arbetsplats", "definite": "arbetsplatsen", "plural": "arbetsplatser", "plural_definite": "arbetsplatserna", "english": "workplace"},
    {"indefinite": "arbetsgivare", "definite": "arbetsgivaren", "plural": "arbetsgivare", "plural_definite": "arbetsgivarna", "english": "employer"},
    {"indefinite": "arbetstagare", "definite": "arbetstagaren", "plural": "arbetstagare", "plural_definite": "arbetstagarna", "english": "employee"},
    {"indefinite": "anställning", "definite": "anställningen", "plural": "anställningar", "plural_definite": "anställningarna", "english": "employment"},
    {"indefinite": "kollega", "definite": "kollegan", "plural": "kollegor", "plural_definite": "kollegorna", "english": "colleague"},
    {"indefinite": "chef", "definite": "chefen", "plural": "chefer", "plural_definite": "cheferna", "english": "manager, boss"},
    {"indefinite": "anställd", "definite": "anställda", "plural": "anställda", "plural_definite": "anställda", "english": "employee (person)"},
    {"indefinite": "praktik", "definite": "praktiken", "plural": "praktiker", "plural_definite": "praktikerna", "english": "internship"},
    {"indefinite": "utbildning", "definite": "utbildningen", "plural": "utbildningar", "plural_definite": "utbildningarna", "english": "education, training"},
    {"indefinite": "yrke", "definite": "yrket", "plural": "yrken", "plural_definite": "yrkena", "english": "profession, occupation"},
    {"indefinite": "erfarenhet", "definite": "erfarenheten", "plural": "erfarenheter", "plural_definite": "erfarenheterna", "english": "experience"},
    {"indefinite": "kunskap", "definite": "kunskapen", "plural": "kunskaper", "plural_definite": "kunskaperna", "english": "knowledge"},
    {"indefinite": "färdighet", "definite": "färdigheten", "plural": "färdigheter", "plural_definite": "färdigheterna", "english": "skill"},
    {"indefinite": "möte", "definite": "mötet", "plural": "möten", "plural_definite": "mötena", "english": "meeting"},
    {"indefinite": "projekt", "definite": "projektet", "plural": "projekt", "plural_definite": "projekten", "english": "project"},
    {"indefinite": "uppgift", "definite": "uppgiften", "plural": "uppgifter", "plural_definite": "uppgifterna", "english": "task, assignment"},
    {"indefinite": "tjänst", "definite": "tjänsten", "plural": "tjänster", "plural_definite": "tjänsterna", "english": "position, service"},
    {"indefinite": "karriär", "definite": "karriären", "plural": "karriärer", "plural_definite": "karriärerna", "english": "career"},
    {"indefinite": "lön", "definite": "lönen", "plural": "löner", "plural_definite": "lönerna", "english": "salary"},
    {"indefinite": "förmån", "definite": "förmånen", "plural": "förmåner", "plural_definite": "förmånerna", "english": "benefit, perk"},
    {"indefinite": "arbetstid", "definite": "arbetstiden", "plural": "arbetstider", "plural_definite": "arbetstiderna", "english": "working hours"},
    {"indefinite": "semester", "definite": "semestern", "plural": "semestrar", "plural_definite": "semestrarna", "english": "vacation"},
    {"indefinite": "ledig dag", "definite": "lediga dagen", "plural": "lediga dagar", "plural_definite": "lediga dagarna", "english": "day off"},
    {"indefinite": "övertid", "definite": "övertiden", "plural": "övertider", "plural_definite": "övertiderna", "english": "overtime"},
    {"indefinite": "arbetssökande", "definite": "arbetssökanden", "plural": "arbetssökande", "plural_definite": "arbetssökandena", "english": "job seeker"},
    {"indefinite": "anställningsintervju", "definite": "anställningsintervjun", "plural": "anställningsintervjuer", "plural_definite": "anställningsintervjuerna", "english": "job interview"},
    {"indefinite": "cv", "definite": "cv:t", "plural": "cv:n", "plural_definite": "cv:na", "english": "CV, résumé"},
    {"indefinite": "referens", "definite": "referensen", "plural": "referenser", "plural_definite": "referenserna", "english": "reference"},
    {"indefinite": "kollektivavtal", "definite": "kollektivavtalet", "plural": "kollektivavtal", "plural_definite": "kollektivavtalen", "english": "collective agreement"},
    {"indefinite": "fackförening", "definite": "fackföreningen", "plural": "fackföreningar", "plural_definite": "fackföreningarna", "english": "trade union"},
    {"indefinite": "anställningsform", "definite": "anställningsformen", "plural": "anställningsformer", "plural_definite": "anställningsformerna", "english": "type of employment"},
    {"indefinite": "provanställning", "definite": "provanställningen", "plural": "provanställningar", "plural_definite": "provanställningarna", "english": "probationary employment"},
    {"indefinite": "fast anställning", "definite": "fasta anställningen", "plural": "fasta anställningar", "plural_definite": "fasta anställningarna", "english": "permanent job"},
    {"indefinite": "vikariat", "definite": "vikariatet", "plural": "vikariat", "plural_definite": "vikariaten", "english": "temporary position"},
    {"indefinite": "löneförhöjning", "definite": "löneförhöjningen", "plural": "löneförhöjningar", "plural_definite": "löneförhöjningarna", "english": "pay raise"},
    {"indefinite": "kontrakt", "definite": "kontraktet", "plural": "kontrakt", "plural_definite": "kontrakten", "english": "contract"},
    {"indefinite": "arbetsuppgift", "definite": "arbetsuppgiften", "plural": "arbetsuppgifter", "plural_definite": "arbetsuppgifterna", "english": "work task"},
    {"indefinite": "ansvar", "definite": "ansvaret", "plural": "ansvar", "plural_definite": "ansvaren", "english": "responsibility"},
    {"indefinite": "möjlighet", "definite": "möjligheten", "plural": "möjligheter", "plural_definite": "möjligheterna", "english": "opportunity"},
    {"indefinite": "utmaning", "definite": "utmaningen", "plural": "utmaningar", "plural_definite": "utmaningarna", "english": "challenge"},
    {"indefinite": "framgång", "definite": "framgången", "plural": "framgångar", "plural_definite": "framgångarna", "english": "success"},
    {"indefinite": "misslyckande", "definite": "misslyckandet", "plural": "misslyckanden", "plural_definite": "misslyckandena", "english": "failure"},
    {"indefinite": "möjlighet", "definite": "möjligheten", "plural": "möjligheter", "plural_definite": "möjligheterna", "english": "opportunity"},
    {"indefinite": "utveckling", "definite": "utvecklingen", "plural": "utvecklingar", "plural_definite": "utvecklingarna", "english": "development"},
    {"indefinite": "fortbildning", "definite": "fortbildningen", "plural": "fortbildningar", "plural_definite": "fortbildningarna", "english": "further education"},
    {"indefinite": "karriärmöjlighet", "definite": "karriärmöjligheten", "plural": "karriärmöjligheter", "plural_definite": "karriärmöjligheterna", "english": "career opportunity"},
    {"indefinite": "arbetsmiljö", "definite": "arbetsmiljön", "plural": "arbetsmiljöer", "plural_definite": "arbetsmiljöerna", "english": "work environment"},
    {"indefinite": "konferens", "definite": "konferensen", "plural": "konferenser", "plural_definite": "konferenserna", "english": "conference"},
    {"indefinite": "presentation", "definite": "presentationen", "plural": "presentationer", "plural_definite": "presentationerna", "english": "presentation"},
    {"indefinite": "rapport", "definite": "rapporten", "plural": "rapporter", "plural_definite": "rapporterna", "english": "report"},
    {"indefinite": "deadline", "definite": "deadlinen", "plural": "deadlines", "plural_definite": "deadlinesen", "english": "deadline"},
    {"indefinite": "möjlighet", "definite": "möjligheten", "plural": "möjligheter", "plural_definite": "möjligheterna", "english": "possibility"},
]

misc = [
    {"word": "flitig", "english": "hardworking, diligent"},
    {"word": "pålitlig", "english": "reliable"},
    {"word": "noggrann", "english": "thorough, meticulous"},
    {"word": "självständig", "english": "independent"},
    {"word": "flexibel", "english": "flexible"},
    {"word": "effektiv", "english": "efficient"},
    {"word": "positiv", "english": "positive"},
    {"word": "ambitiös", "english": "ambitious"},
    {"word": "tålmodig", "english": "patient"},
    {"word": "kreativ", "english": "creative"},
    {"word": "ansvarsfull", "english": "responsible"},
    {"word": "ordentlig", "english": "organized, tidy"},
    {"word": "stressad", "english": "stressed"},
    {"word": "nöjd", "english": "satisfied"},
    {"word": "missnöjd", "english": "dissatisfied"},
    {"word": "upptagen", "english": "busy"},
    {"word": "ledig", "english": "free, off work"},
    {"word": "viktig", "english": "important"},
    {"word": "meningsfull", "english": "meaningful"},
    {"word": "krävande", "english": "demanding"},
    {"word": "utmanande", "english": "challenging"},
    {"word": "framgångsrik", "english": "successful"},
    {"word": "kompetent", "english": "competent"},
    {"word": "erfaren", "english": "experienced"},
    {"word": "ny", "english": "new"},
    {"word": "tidigare", "english": "previous, former"},
    {"word": "nuvarande", "english": "current"},
    {"word": "gemensam", "english": "shared, common"},
    {"word": "praktisk", "english": "practical"},
    {"word": "teoretisk", "english": "theoretical"},
    {"word": "professionell", "english": "professional"},
    {"word": "personlig", "english": "personal"},
    {"word": "rimlig", "english": "reasonable, fair"},
    {"word": "lönsam", "english": "profitable"},
    {"word": "framgång", "english": "success (used adjectivally in phrases like framgångsrik)"},
    {"word": "tillsammans", "english": "together"},
    {"word": "ofta", "english": "often"},
    {"word": "sällan", "english": "rarely"},
    {"word": "ibland", "english": "sometimes"},
    {"word": "alltid", "english": "always"},
    {"word": "vanligtvis", "english": "usually"},
    {"word": "redan", "english": "already"},
    {"word": "snart", "english": "soon"},
    {"word": "äntligen", "english": "finally"},
    {"word": "dessutom", "english": "in addition"},
    {"word": "trots", "english": "despite"},
    {"word": "på grund av", "english": "because of"},
    {"word": "eftersom", "english": "because"},
    {"word": "även om", "english": "even though"},
    {"word": "därför att", "english": "because (for giving reasons)"},
    {"word": "så att", "english": "so that"},
    {"word": "fastän", "english": "although"},
    {"word": "medan", "english": "while"},
    {"word": "när", "english": "when"},
    {"word": "innan", "english": "before"},
    {"word": "efter att", "english": "after"},
    {"word": "både ... och", "english": "both ... and"},
    {"word": "antingen ... eller", "english": "either ... or"},
    {"word": "varken ... eller", "english": "neither ... nor"},
    {"word": "dessutom", "english": "furthermore"},
    {"word": "slutligen", "english": "finally"},
    {"word": "till exempel", "english": "for example"},
    {"word": "alltså", "english": "therefore, that is to say"},
]

verbs = [
    {"infinitive": "arbeta", "english": "to work", "present": "arbetar", "past": "arbetade", "supine": "arbetat"},
    {"infinitive": "anställa", "english": "to hire, employ", "present": "anställer", "past": "anställde", "supine": "anställt"},
    {"infinitive": "avskeda", "english": "to fire, dismiss", "present": "avskedar", "past": "avskedade", "supine": "avskedat"},
    {"infinitive": "söka", "english": "to apply (for)", "present": "söker", "past": "sökte", "supine": "sökt"},
    {"infinitive": "ha", "english": "to have", "present": "har", "past": "hade", "supine": "haft"},
    {"infinitive": "börja", "english": "to start, begin", "present": "börjar", "past": "började", "supine": "börjat"},
    {"infinitive": "sluta", "english": "to stop, quit", "present": "slutar", "past": "slutade", "supine": "slutat"},
    {"infinitive": "fortsätta", "english": "to continue", "present": "fortsätter", "past": "fortsatte", "supine": "fortsatt"},
    {"infinitive": "arbeta över", "english": "to work overtime", "present": "arbetar över", "past": "arbetade över", "supine": "arbetat över"},
    {"infinitive": "pendla", "english": "to commute", "present": "pendlar", "past": "pendlade", "supine": "pendlat"},
    {"infinitive": "delta", "english": "to participate", "present": "deltar", "past": "deltog", "supine": "deltagit"},
    {"infinitive": "samarbeta", "english": "to cooperate, collaborate", "present": "samarbetar", "past": "samarbetade", "supine": "samarbetat"},
    {"infinitive": "utbilda", "english": "to educate, train", "present": "utbildar", "past": "utbildade", "supine": "utbildat"},
    {"infinitive": "lära", "english": "to teach, learn", "present": "lär", "past": "lärde", "supine": "lärt"},
    {"infinitive": "studera", "english": "to study", "present": "studerar", "past": "studerade", "supine": "studerat"},
    {"infinitive": "forskа", "english": "to do research", "present": "forskar", "past": "forskade", "supine": "forskat"},
    {"infinitive": "förklara", "english": "to explain", "present": "förklarar", "past": "förklarade", "supine": "förklarat"},
    {"infinitive": "diskutera", "english": "to discuss", "present": "diskuterar", "past": "diskuterade", "supine": "diskuterat"},
    {"infinitive": "samarbeta", "english": "to cooperate", "present": "samarbetar", "past": "samarbetade", "supine": "samarbetat"},
    {"infinitive": "hjälpa", "english": "to help", "present": "hjälper", "past": "hjälpte", "supine": "hjälpt"},
    {"infinitive": "stödja", "english": "to support", "present": "stödjer", "past": "stödde", "supine": "stött"},
    {"infinitive": "hantera", "english": "to handle, manage", "present": "hanterar", "past": "hanterade", "supine": "hanterat"},
    {"infinitive": "ansvara", "english": "to be responsible (for)", "present": "ansvarar", "past": "ansvarade", "supine": "ansvarat"},
    {"infinitive": "försöka", "english": "to try", "present": "försöker", "past": "försökte", "supine": "försökt"},
    {"infinitive": "lyckas", "english": "to succeed", "present": "lyckas", "past": "lyckades", "supine": "lyckats"},
    {"infinitive": "misslyckas", "english": "to fail", "present": "misslyckas", "past": "misslyckades", "supine": "misslyckats"},
    {"infinitive": "tjäna", "english": "to earn", "present": "tjänar", "past": "tjänade", "supine": "tjänat"},
    {"infinitive": "spara", "english": "to save (money)", "present": "sparar", "past": "sparade", "supine": "sparat"},
    {"infinitive": "investera", "english": "to invest", "present": "investerar", "past": "investerade", "supine": "investerat"},
    {"infinitive": "låna", "english": "to borrow, lend", "present": "lånar", "past": "lånade", "supine": "lånat"},
    {"infinitive": "leverera", "english": "to deliver", "present": "levererar", "past": "levererade", "supine": "levererat"},
    {"infinitive": "kontakta", "english": "to contact", "present": "kontaktar", "past": "kontaktade", "supine": "kontakta"},
    {"infinitive": "skicka", "english": "to send", "present": "skickar", "past": "skickade", "supine": "skickat"},
    {"infinitive": "ta emot", "english": "to receive", "present": "tar emot", "past": "tog emot", "supine": "tagit emot"},
    {"infinitive": "hålla", "english": "to hold, keep", "present": "håller", "past": "höll", "supine": "hållit"},
    {"infinitive": "träffa", "english": "to meet", "present": "träffar", "past": "träffade", "supine": "träffat"},
    {"infinitive": "delta", "english": "to participate", "present": "deltar", "past": "deltog", "supine": "deltagit"},
]
