nouns = [
    {"indefinite": "fråga", "definite": "frågan", "plural": "frågor", "plural_definite": "frågorna", "english": "question", "cefr": 1, "frequency": 938.78},
    {"indefinite": "sätt", "definite": "sättet", "plural": "sätt", "plural_definite": "sätten", "english": "way, manner", "cefr": 1, "frequency": 784.91},
    {"indefinite": "gång", "definite": "gången", "plural": "gånger", "plural_definite": "gångerna", "english": "time (occurrence), walk", "cefr": 1, "frequency": 763.39},
    {"indefinite": "sak", "definite": "saken", "plural": "saker", "plural_definite": "sakerna", "english": "thing, matter", "cefr": 1, "frequency": 581.51},
    {"indefinite": "antal", "definite": "antalet", "plural": "antal", "plural_definite": "antalen", "english": "number, quantity", "cefr": 1, "frequency": 542.86},
    {"indefinite": "fall", "definite": "fallet", "plural": "fall", "plural_definite": "fallen", "english": "case, fall", "cefr": 1, "frequency": 520.07},
    {"indefinite": "slag", "definite": "slaget", "plural": "slag", "plural_definite": "slagen", "english": "kind, type, blow", "cefr": 1, "frequency": 487.59},
    {"indefinite": "tal", "definite": "talet", "plural": "tal", "plural_definite": "talen", "english": "number, speech", "cefr": 1, "frequency": 485.93},
    {"indefinite": "sida", "definite": "sidan", "plural": "sidor", "plural_definite": "sidorna", "english": "side, page", "cefr": 1, "frequency": 466.09},
    {"indefinite": "ord", "definite": "ordet", "plural": "ord", "plural_definite": "orden", "english": "word", "cefr": 1, "frequency": 410.30},
    {"indefinite": "tag", "definite": "taget", "plural": "tag", "plural_definite": "tagen", "english": "grip, hold, moment", "cefr": 1, "frequency": 390.12},
    {"indefinite": "förslag", "definite": "förslaget", "plural": "förslag", "plural_definite": "förslagen", "english": "suggestion, proposal", "cefr": 1, "frequency": 385.31},
    {"indefinite": "par", "definite": "paret", "plural": "par", "plural_definite": "paren", "english": "pair, couple", "cefr": 1, "frequency": 331.61},
    {"indefinite": "miljon", "definite": "miljonen", "plural": "miljoner", "plural_definite": "miljonerna", "english": "million", "cefr": 1, "frequency": 301.59},
    {"indefinite": "svar", "definite": "svaret", "plural": "svar", "plural_definite": "svaren", "english": "answer, reply", "cefr": 1, "frequency": 291.65},
    {"indefinite": "slut", "definite": "slutet", "plural": "slut", "plural_definite": "sluten", "english": "end", "cefr": 1, "frequency": 256.60},
    {"indefinite": "massa", "definite": "massan", "plural": "massor", "plural_definite": "massorna", "english": "mass, lot", "cefr": 1, "frequency": 255.87},
    {"indefinite": "tanke", "definite": "tanken", "plural": "tankar", "plural_definite": "tankarna", "english": "thought", "cefr": 1, "frequency": 251.61},
    {"indefinite": "akt", "definite": "akten", "plural": "akter", "plural_definite": "akterna", "english": "act", "cefr": 1, "frequency": 251.45},
    {"indefinite": "procent", "definite": "procenten", "plural": "procent", "plural_definite": "procenten", "english": "percent", "cefr": 1, "frequency": 251.21},
    {"indefinite": "exempel", "definite": "exemplet", "plural": "exempel", "plural_definite": "exemplen", "english": "example", "cefr": 1, "frequency": 232.43},
    {"indefinite": "situation", "definite": "situationen", "plural": "situationer", "plural_definite": "situationerna", "english": "situation", "cefr": 1, "frequency": 229.02},
    {"indefinite": "form", "definite": "formen", "plural": "former", "plural_definite": "formerna", "english": "form, shape", "cefr": 1, "frequency": 228.11},
    {"indefinite": "råd", "definite": "rådet", "plural": "råd", "plural_definite": "råden", "english": "advice, council", "cefr": 1, "frequency": 228.07},
    {"indefinite": "skillnad", "definite": "skillnaden", "plural": "skillnader", "plural_definite": "skillnaderna", "english": "difference", "cefr": 1, "frequency": 223.65},
    {"indefinite": "typ", "definite": "typen", "plural": "typer", "plural_definite": "typerna", "english": "type", "cefr": 1, "frequency": 217.75},
    {"indefinite": "tur", "definite": "turen", "plural": "turer", "plural_definite": "turerna", "english": "luck, turn, trip", "cefr": 1, "frequency": 216.52},
    {"indefinite": "grund", "definite": "grunden", "plural": "grunder", "plural_definite": "grunderna", "english": "ground, basis, reason", "cefr": 1, "frequency": 204.34},
    {"indefinite": "behov", "definite": "behovet", "plural": "behov", "plural_definite": "behoven", "english": "need", "cefr": 1, "frequency": 201.71},
    {"indefinite": "anledning", "definite": "anledningen", "plural": "anledningar", "plural_definite": "anledningarna", "english": "reason, cause", "cefr": 1, "frequency": 195.88},
    {"indefinite": "rad", "definite": "raden", "plural": "rader", "plural_definite": "raderna", "english": "row, line", "cefr": 1, "frequency": 192.14},
    {"indefinite": "faktum", "definite": "faktumet", "plural": "fakta", "plural_definite": "fakta", "english": "fact", "cefr": 1, "frequency": 192.11},
    {"indefinite": "mening", "definite": "meningen", "plural": "meningar", "plural_definite": "meningarna", "english": "meaning, sentence, opinion", "cefr": 1, "frequency": 191.16},
    {"indefinite": "nummer", "definite": "numret", "plural": "nummer", "plural_definite": "numren", "english": "number", "cefr": 1, "frequency": 186.00},
    {"indefinite": "skäl", "definite": "skälet", "plural": "skäl", "plural_definite": "skälen", "english": "reason", "cefr": 1, "frequency": 175.99},
    {"indefinite": "idé", "definite": "idén", "plural": "idéer", "plural_definite": "idéerna", "english": "idea", "cefr": 1, "frequency": 171.57},
    {"indefinite": "syfte", "definite": "syftet", "plural": "syften", "plural_definite": "syftena", "english": "purpose, aim", "cefr": 1, "frequency": 168.82},
    {"indefinite": "princip", "definite": "principen", "plural": "principer", "plural_definite": "principerna", "english": "principle", "cefr": 1, "frequency": 167.86},
    {"indefinite": "nivå", "definite": "nivån", "plural": "nivåer", "plural_definite": "nivåerna", "english": "level", "cefr": 1, "frequency": 165.64},
    {"indefinite": "mängd", "definite": "mängden", "plural": "mängder", "plural_definite": "mängderna", "english": "amount, quantity", "cefr": 1, "frequency": 165.27},
    {"indefinite": "betydelse", "definite": "betydelsen", "plural": "betydelser", "plural_definite": "betydelserna", "english": "meaning, significance", "cefr": 1, "frequency": 165.20},
]

misc = [
    {"swedish": "och", "english": "and", "cefr": 1, "frequency": 26019.68},
    {"swedish": "eller", "english": "or", "cefr": 1, "frequency": 3138.92},
    {"swedish": "så att", "english": "so that", "cefr": 1, "frequency": 400.31},
    {"swedish": "så", "english": "so / then", "cefr": 1, "frequency": 4004.97},
    {"swedish": "därför", "english": "therefore", "cefr": 1, "frequency": 461.58},
    {"swedish": "runt", "english": "around", "cefr": 1, "frequency": 203.50},
    {"swedish": "dock", "english": "however", "cefr": 1, "frequency": 614.54},
    {"swedish": "också", "english": "also", "cefr": 1, "frequency": 1797.39},
    {"swedish": "bara", "english": "only / just", "cefr": 1, "frequency": 1582.15},
    {"swedish": "mycket", "english": "much / very", "cefr": 1, "frequency": 3112.13},
    {"swedish": "under", "english": "under / during", "cefr": 1, "frequency": 1851.63},
    {"swedish": "över", "english": "over / above", "cefr": 1, "frequency": 1267.18},
    {"swedish": "framför", "english": "in front of", "cefr": 1, "frequency": 110.51},
    {"swedish": "bakom", "english": "behind", "cefr": 1, "frequency": 206.72},
    {"swedish": "mellan", "english": "between", "cefr": 1, "frequency": 841.51},
    {"swedish": "utan", "english": "without / but (after negative)", "cefr": 1, "frequency": 707.53},
    {"swedish": "hos", "english": "at (someone’s place)", "cefr": 1, "frequency": 453.15},
    {"swedish": "genom", "english": "through", "cefr": 1, "frequency": 733.74},
    {"swedish": "innan", "english": "before", "cefr": 1, "frequency": 429.65},
    {"swedish": "efter", "english": "after", "cefr": 1, "frequency": 1323.97},
    {"swedish": "på", "english": "on / at", "cefr": 1, "frequency": 12591.15},
    {"swedish": "i", "english": "in / inside", "cefr": 1, "frequency": 19272.89},
    {"swedish": "av", "english": "of / by", "cefr": 1, "frequency": 11540.13},
    {"swedish": "till", "english": "to / until", "cefr": 1, "frequency": 8662.68},
    {"swedish": "från", "english": "from", "cefr": 1, "frequency": 3117.46},
    {"swedish": "när", "english": "when", "cefr": 1, "frequency": 2386.89},
    {"swedish": "om", "english": "if / about", "cefr": 1, "frequency": 5278.24},
    {"swedish": "för", "english": "for / to", "cefr": 1, "frequency": 11408.82},
    {"swedish": "mot", "english": "against / toward", "cefr": 1, "frequency": 1592.42},
    {"swedish": "bland", "english": "among", "cefr": 1, "frequency": 282.47},
    {"swedish": "trots", "english": "despite", "cefr": 1, "frequency": 192.43},
    {"swedish": "snart", "english": "soon", "cefr": 1, "frequency": 199.90},
    {"swedish": "kanske", "english": "maybe / perhaps", "cefr": 1, "frequency": 809.75},
    {"swedish": "nästan", "english": "almost/next", "cefr": 1, "frequency": 284.00},
    {"swedish": "fortfarande", "english": "still", "cefr": 1, "frequency": 319.39},
    {"swedish": "här", "english": "here", "cefr": 1, "frequency": 1194.91},
    {"swedish": "där", "english": "there", "cefr": 1, "frequency": 1790.68},
    {"swedish": "hit", "english": "to here", "cefr": 1, "frequency": 78.19},
    {"swedish": "dit", "english": "to there", "cefr": 1, "frequency": 126.29},
    {"swedish": "hem", "english": "home (motion)", "cefr": 1, "frequency": 172.22},
    {"swedish": "hemma", "english": "at home", "cefr": 1, "frequency": 129.59},
    {"swedish": "borta", "english": "away / gone", "cefr": 1, "frequency": 66.14},
    {"swedish": "inne", "english": "inside", "cefr": 1, "frequency": 85.10},
    {"swedish": "ute", "english": "outside", "cefr": 1, "frequency": 167.61},
    {"swedish": "finns", "english": "there is / there are", "cefr": 1, "frequency": None},
    {"swedish": "än", "english": "yet / than", "cefr": 1, "frequency": 1428.89},
    {"swedish": "igen", "english": "again", "cefr": 1, "frequency": 321.76},
    {"swedish": "tillsammans", "english": "together", "cefr": 1, "frequency": 274.88},
    {"swedish": "ensam", "english": "alone", "cefr": 1, "frequency": 200.63},
    {"swedish": "däremot", "english": "on the other hand", "cefr": 1, "frequency": 194.90},
    {"swedish": "även om", "english": "even though", "cefr": 1, "frequency": 314.71},
    {"swedish": "således", "english": "thus", "cefr": 1, "frequency": 87.49},
    {"swedish": "nämligen", "english": "namely / that is", "cefr": 1, "frequency": 165.98},
    {"swedish": "till exempel", "english": "for example", "cefr": 1, "frequency": 274.97},
    {"swedish": "alltså", "english": "so / that means", "cefr": 1, "frequency": 419.06},
    {"swedish": "väl", "english": "surely / well", "cefr": 1, "frequency": 705.75},
    {"swedish": "precis", "english": "exactly", "cefr": 1, "frequency": 277.18},
    {"swedish": "liksom", "english": "like / sort of", "cefr": 1, "frequency": 174.75},
    {"swedish": "nyss", "english": "just (recently)", "cefr": 2, "frequency": 33.64},
    {"swedish": "nära", "english": "near", "cefr": 1, "frequency": 237.62},
    {"swedish": "vanligt", "english": "usual", "cefr": 2, "frequency": 23.67},
    {"swedish": "ovanligt", "english": "unusual", "cefr": 2, "frequency": 23.67},
    {"swedish": "plötsligt", "english": "suddenly", "cefr": 1, "frequency": 93.95},
    {"swedish": "lyckligtvis", "english": "luckily", "cefr": 1, "frequency": None},
    {"swedish": "särskilt", "english": "particularly/ especially", "cefr": 1, "frequency": 232.35},
    {"swedish": "i närheten", "english": "nearby", "cefr": 1, "frequency": None},
    {"swedish": "illa", "english": "badly", "cefr": 1, "frequency": 80.73},
    {"swedish": "senaste", "english": "recent/latest", "cefr": 1, "frequency": None},
    {"swedish": "istället", "english": "instead", "cefr": 1, "frequency": 291.38},
    {"swedish": "vilket", "english": "which", "cefr": 1, "frequency": None},
    {"swedish": "både", "english": "both", "cefr": 1, "frequency": 554.95},
    {"swedish": "fler", "english": "more", "cefr": 1, "frequency": 717.99},
    {"swedish": "viktig", "english": "important", "cefr": 1, "frequency": 662.11},
    {"swedish": "samtidigt", "english": "simultaneously/at the same time", "cefr": 1, "frequency": 247.54},
    {"swedish": "flera", "english": "several", "cefr": 1, "frequency": 94.49},
    {"swedish": "nedan", "english": "below", "cefr": 2, "frequency": 57.98},
    {"swedish": "endast", "english": "only", "cefr": 1, "frequency": 302.17},
    {"swedish": "sådant", "english": "such", "cefr": 1, "frequency": None},
    {"swedish": "hela", "english": "whole/all", "cefr": 1, "frequency": None},
    {"swedish": "tidigt", "english": "early", "cefr": 2, "frequency": 62.99},
    {"swedish": "någonstans", "english": "anywhere", "cefr": 2, "frequency": 62.31},
    {"swedish": "tillräckligt med", "english": "enough", "cefr": 1, "frequency": None},
    {"swedish": "förmodligen", "english": "probably", "cefr": 1, "frequency": 79.75},
    {"swedish": "medan", "english": "while", "cefr": 1, "frequency": 257.43},
    {"swedish": "varje", "english": "every/each", "cefr": 1, "frequency": 501.70},
    {"swedish": "annan", "english": "other", "cefr": 1, "frequency": 2624.20},
    {"swedish": "imorse", "english": "this morning", "cefr": 1, "frequency": None},
    {"swedish": "del", "english": "part/portion", "cefr": 1, "frequency": 1202.45},
    {"swedish": "helt", "english": "completely", "cefr": 1, "frequency": 721.67},
    {"swedish": "inom", "english": "within", "cefr": 1, "frequency": 758.15},
    {"swedish": "fram", "english": "up/forward", "cefr": 1, "frequency": 600.53},
    {"swedish": "enligt", "english": "according to", "cefr": 1, "frequency": 680.22},
    {"swedish": "utom", "english": "except", "cefr": 1, "frequency": 122.27},
    {"swedish": "sedan dess", "english": "since then", "cefr": 1, "frequency": None},
    {"swedish": "under tiden", "english": "in the meantime", "cefr": 1, "frequency": None},
    {"swedish": "däri", "english": "in that / therein", "cefr": 1, "frequency": None},
    {"swedish": "därmed", "english": "thereby / with that", "cefr": 1, "frequency": 206.58},
    {"swedish": "däreför", "english": "for that reason", "cefr": 1, "frequency": None},
    {"swedish": "dessförinnan", "english": "before that / previously", "cefr": 1, "frequency": None},
    {"swedish": "därefteråt", "english": "afterwards", "cefr": 1, "frequency": None},
    {"swedish": "först och främst", "english": "first and foremost", "cefr": 3, "frequency": 18.98},
    {"swedish": "slutligen", "english": "finally / ultimately", "cefr": 1, "frequency": 68.46},
    {"swedish": "sammanfattningsvis", "english": "in summary / to sum up", "cefr": 1, "frequency": None},
    {"swedish": "avslutningsvis", "english": "in conclusion", "cefr": 1, "frequency": None},
    {"swedish": "kort sagt", "english": "in short / briefly", "cefr": 1, "frequency": None},
    {"swedish": "å ena sidan", "english": "on one hand", "cefr": 1, "frequency": None},
    {"swedish": "å andra sidan", "english": "on the other hand", "cefr": 1, "frequency": None},
    {"swedish": "med andra ord", "english": "in other words", "cefr": 2, "frequency": 44.51},
    {"swedish": "i själva verket", "english": "in fact / actually", "cefr": 2, "frequency": 40.15},
    {"swedish": "verkligen", "english": "really / truly", "cefr": 1, "frequency": 321.76},
    {"swedish": "troligen", "english": "likely / probably", "cefr": 2, "frequency": 54.11},
    {"swedish": "antagligen", "english": "probably / presumably", "cefr": 2, "frequency": 52.05},
    {"swedish": "möjligen", "english": "possibly", "cefr": 2, "frequency": 49.17},
    {"swedish": "eventuellt", "english": "possibly / potentially", "cefr": 2, "frequency": 36.69},
    {"swedish": "sannolikt", "english": "likely", "cefr": 2, "frequency": 49.49},
    {"swedish": "för det mesta", "english": "for the most part / usually", "cefr": 1, "frequency": None},
    {"swedish": "i allmänhet", "english": "in general", "cefr": 2, "frequency": 46.20},
    {"swedish": "generellt sett", "english": "generally speaking", "cefr": 1, "frequency": None},
    {"swedish": "till viss del", "english": "to some extent", "cefr": 1, "frequency": None},
    {"swedish": "för det första", "english": "first of all", "cefr": 1, "frequency": None},
    {"swedish": "för det andra", "english": "secondly", "cefr": 1, "frequency": None},
    {"swedish": "för det tredje", "english": "thirdly", "cefr": 1, "frequency": None},
    {"swedish": "dels", "english": "partly / in part", "cefr": 1, "frequency": 148.09},
    {"swedish": "så småningom", "english": "eventually", "cefr": 2, "frequency": 40.70},
    {"swedish": "däremellan", "english": "in between", "cefr": 1, "frequency": None},
    {"swedish": "förutom att", "english": "besides / apart from", "cefr": 1, "frequency": None},
    {"swedish": "så länge", "english": "as long as", "cefr": 1, "frequency": None},
    {"swedish": "så snart", "english": "as soon as", "cefr": 1, "frequency": None},
    {"swedish": "innan dess", "english": "before that", "cefr": 1, "frequency": None},
    {"swedish": "därigenom", "english": "thereby / through that", "cefr": 2, "frequency": 32.50},
    {"swedish": "i stället för", "english": "instead of", "cefr": 1, "frequency": None},
    {"swedish": "utan att", "english": "without (doing something)", "cefr": 1, "frequency": None},
    {"swedish": "på grund av", "english": "because of / due to", "cefr": 1, "frequency": 229.03},
    {"swedish": "i synnerhet", "english": "especially / particularly", "cefr": 2, "frequency": 48.31},
    {"swedish": "bland annat", "english": "among other things", "cefr": 1, "frequency": 275.20},
    {"swedish": "till skillnad från", "english": "in contrast to / unlike", "cefr": 1, "frequency": None},
    {"swedish": "i jämförelse med", "english": "in comparison with", "cefr": 3, "frequency": 13.07},
    {"swedish": "jämfört med", "english": "compared with", "cefr": 1, "frequency": None},
    {"swedish": "förr eller senare", "english": "sooner or later", "cefr": 1, "frequency": None},
    {"swedish": "för närvarande", "english": "at present / currently", "cefr": 2, "frequency": 34.84},
    {"swedish": "nuförtiden", "english": "these days / nowadays", "cefr": 1, "frequency": None},
    {"swedish": "tidvis", "english": "at times / occasionally", "cefr": 1, "frequency": None},
    {"swedish": "emellanåt", "english": "now and then", "cefr": 1, "frequency": None},
    {"swedish": "vanligen", "english": "commonly / usually", "cefr": 3, "frequency": 20.88},
    {"swedish": "plötsligen", "english": "suddenly", "cefr": 1, "frequency": None},
    {"swedish": "dessvärre", "english": "unfortunately", "cefr": 3, "frequency": 21.51},
    {"swedish": "tyvärr", "english": "unfortunately", "cefr": 1, "frequency": 159.15},
    {"swedish": "förhoppningsvis", "english": "hopefully", "cefr": 2, "frequency": 41.58},
    {"swedish": "lyckligt nog", "english": "luckily enough", "cefr": 1, "frequency": None},
    {"swedish": "tvärtom", "english": "on the contrary", "cefr": 1, "frequency": 71.67},
    {"swedish": "därutöver", "english": "besides that / moreover", "cefr": 1, "frequency": None},
    {"swedish": "i tillägg", "english": "in addition", "cefr": 1, "frequency": None},
    {"swedish": "för övrigt", "english": "by the way / incidentally", "cefr": 1, "frequency": 70.76},
    {"swedish": "desslike", "english": "the like / of the same kind", "cefr": 1, "frequency": None},
    {"swedish": "utan vidare", "english": "without further ado", "cefr": 1, "frequency": None},
    {"swedish": "förresten", "english": "by the way", "cefr": 2, "frequency": 39.86},
    {"swedish": "kort därefter", "english": "shortly after", "cefr": 1, "frequency": None},
    {"swedish": "strax efter", "english": "just after", "cefr": 3, "frequency": 13.01},
    {"swedish": "strax före", "english": "just before", "cefr": 1, "frequency": None},
    {"swedish": "i samband med", "english": "in connection with", "cefr": 1, "frequency": 106.30},
    {"swedish": "med hjälp av", "english": "with the help of", "cefr": 1, "frequency": 71.84},
    {"swedish": "i fråga om", "english": "regarding / concerning", "cefr": 2, "frequency": 54.28},
    {"swedish": "beträffande", "english": "regarding / concerning", "cefr": 2, "frequency": 47.59},
    {"swedish": "angående", "english": "regarding / concerning", "cefr": 2, "frequency": 57.49},
    {"swedish": "på så sätt", "english": "in that way / thus", "cefr": 2, "frequency": 39.33},
    {"swedish": "på samma sätt", "english": "in the same way", "cefr": 1, "frequency": None},
    {"swedish": "till följd av", "english": "as a result of", "cefr": 2, "frequency": 34.39},
    {"swedish": "som ett resultat av", "english": "as a result of", "cefr": 1, "frequency": None},
    {"swedish": "med anledning av", "english": "due to / because of", "cefr": 2, "frequency": 28.44},
    {"swedish": "i och med", "english": "as a result of / in connection with", "cefr": 3, "frequency": 21.81},
    {"swedish": "så fort", "english": "as soon as", "cefr": 1, "frequency": None},
    {"swedish": "eftersom att", "english": "because (colloquial)", "cefr": 1, "frequency": None},
    {"swedish": "i alla fall", "english": "in any case / anyway", "cefr": 1, "frequency": 195.28},
    {"swedish": "hur som helst", "english": "anyhow / anyway", "cefr": 2, "frequency": 35.69},
    {"swedish": "på något sätt", "english": "somehow", "cefr": 1, "frequency": None},
    {"swedish": "på grund därav", "english": "because of that", "cefr": 1, "frequency": None},
    {"swedish": "för det syftet", "english": "for that purpose", "cefr": 1, "frequency": None},
    {"swedish": "till exempelvis", "english": "for example (formal)", "cefr": 1, "frequency": None},
    {"swedish": "i synnerhet när", "english": "especially when", "cefr": 1, "frequency": None},
    {"swedish": "särskilt om", "english": "especially if", "cefr": 1, "frequency": None},
    {"swedish": "för att inte tala om", "english": "not to mention", "cefr": 1, "frequency": None},
    {"swedish": "i likhet med", "english": "similar to", "cefr": 3, "frequency": 17.46},
    {"swedish": "till och med", "english": "even", "cefr": 1, "frequency": 139.70},
    {"swedish": "fram tills", "english": "until / up to", "cefr": 1, "frequency": None},
    {"swedish": "utan tvekan", "english": "without a doubt", "cefr": 1, "frequency": None},
    {"swedish": "av den anledningen", "english": "for that reason", "cefr": 1, "frequency": None},
    {"swedish": "såvitt jag vet", "english": "as far as I know", "cefr": 1, "frequency": None},
    {"swedish": "så länge som", "english": "as long as", "cefr": 1, "frequency": None},
    {"swedish": "allt eftersom", "english": "gradually / as", "cefr": 1, "frequency": None},
    {"swedish": "hellre än", "english": "rather than", "cefr": 1, "frequency": None},
    {"swedish": "å", "english": "on", "cefr": 1, "frequency": 12462.73},
    {"swedish": "att", "english": "to, that", "cefr": 1, "frequency": 11271.57},
    {"swedish": "inte", "english": "not", "cefr": 1, "frequency": 9073.55},
    {"swedish": "med", "english": "with", "cefr": 1, "frequency": 8790.85},
    {"swedish": "liten", "english": "small, little", "cefr": 1, "frequency": 8654.67},
    {"swedish": "analog", "english": "analog", "cefr": 1, "frequency": 5649.00},
    {"swedish": "stor", "english": "big, large", "cefr": 1, "frequency": 2046.73},
    {"swedish": "nu", "english": "now", "cefr": 1, "frequency": 2033.06},
    {"swedish": "då", "english": "then", "cefr": 1, "frequency": 1788.93},
    {"swedish": "hur", "english": "how", "cefr": 1, "frequency": 1690.32},
    {"swedish": "vid", "english": "at, by", "cefr": 1, "frequency": 1439.02},
    {"swedish": "bra", "english": "good, well", "cefr": 1, "frequency": 1428.27},
    {"swedish": "även", "english": "also, even", "cefr": 1, "frequency": 1191.77},
    {"swedish": "ju", "english": "you know, of course", "cefr": 1, "frequency": 1119.58},
    {"swedish": "hel", "english": "whole, entire", "cefr": 1, "frequency": 1034.76},
    {"swedish": "idag", "english": "today", "cefr": 1, "frequency": 865.13},
    {"swedish": "lik", "english": "similar, alike", "cefr": 1, "frequency": 808.09},
    {"swedish": "olik", "english": "different, unlike", "cefr": 1, "frequency": 790.47},
    {"swedish": "viss", "english": "certain", "cefr": 1, "frequency": 614.61},
    {"swedish": "egen", "english": "own", "cefr": 1, "frequency": 612.48},
    {"swedish": "hög", "english": "high, tall", "cefr": 1, "frequency": 578.03},
    {"swedish": "länge", "english": "for a long time", "cefr": 1, "frequency": 568.83},
    {"swedish": "just", "english": "just, exactly", "cefr": 1, "frequency": 545.57},
    {"swedish": "åt", "english": "to, for", "cefr": 1, "frequency": 484.56},
    {"swedish": "nog", "english": "enough, probably", "cefr": 1, "frequency": 482.60},
    {"swedish": "varför", "english": "why", "cefr": 1, "frequency": 475.84},
    {"swedish": "god", "english": "good", "cefr": 1, "frequency": 453.87},
    {"swedish": "samt", "english": "and, as well as", "cefr": 1, "frequency": 435.23},
    {"swedish": "ur", "english": "out of, from", "cefr": 1, "frequency": 427.00},
    {"swedish": "genom att", "english": "by (doing)", "cefr": 1, "frequency": 412.39},
    {"swedish": "lika", "english": "equally, alike", "cefr": 1, "frequency": 394.25},
    {"swedish": "ändå", "english": "still, yet, anyway", "cefr": 1, "frequency": 386.11},
    {"swedish": "svår", "english": "difficult, hard", "cefr": 1, "frequency": 379.67},
    {"swedish": "lång", "english": "long, tall", "cefr": 1, "frequency": 372.00},
    {"swedish": "väldigt", "english": "very", "cefr": 1, "frequency": 363.60},
    {"swedish": "ja", "english": "yes", "cefr": 1, "frequency": 353.15},
    {"swedish": "faktiskt", "english": "actually, in fact", "cefr": 1, "frequency": 341.44},
    {"swedish": "sent", "english": "late", "cefr": 1, "frequency": 330.39},
    {"swedish": "dålig", "english": "bad", "cefr": 1, "frequency": 323.94},
    {"swedish": "enda", "english": "only, single", "cefr": 1, "frequency": 314.53},
    {"swedish": "möjlig", "english": "possible", "cefr": 1, "frequency": 310.72},
    {"swedish": "ganska", "english": "quite, rather", "cefr": 1, "frequency": 295.35},
    {"swedish": "heller", "english": "either, neither", "cefr": 1, "frequency": 288.81},
    {"swedish": "riktigt", "english": "really, properly", "cefr": 1, "frequency": 288.62},
    {"swedish": "inför", "english": "before, ahead of", "cefr": 1, "frequency": 267.33},
    {"swedish": "flest", "english": "most (quantity)", "cefr": 1, "frequency": 262.77},
    {"swedish": "sista", "english": "last, final", "cefr": 1, "frequency": 250.04},
    {"swedish": "emot", "english": "against", "cefr": 1, "frequency": 247.28},
    {"swedish": "nej", "english": "no", "cefr": 1, "frequency": 237.61},
    {"swedish": "när det gäller", "english": "regarding, when it comes to", "cefr": 1, "frequency": 230.03},
    {"swedish": "kvar", "english": "remaining, left", "cefr": 1, "frequency": 226.35},
    {"swedish": "kring", "english": "around", "cefr": 1, "frequency": 217.05},
    {"swedish": "cirka", "english": "approximately", "cefr": 1, "frequency": 216.97},
    {"swedish": "låg", "english": "low", "cefr": 1, "frequency": 214.24},
    {"swedish": "rätt", "english": "right, quite, fairly", "cefr": 1, "frequency": 198.64},
    {"swedish": "utanför", "english": "outside", "cefr": 1, "frequency": 190.63},
    {"swedish": "klar", "english": "clear, ready", "cefr": 1, "frequency": 187.90},
    {"swedish": "ihop", "english": "together", "cefr": 1, "frequency": 183.73},
    {"swedish": "ifrån", "english": "from", "cefr": 1, "frequency": 181.44},
    {"swedish": "snabbt", "english": "quickly, fast", "cefr": 1, "frequency": 178.68},
    {"swedish": "fin", "english": "fine, nice", "cefr": 1, "frequency": 174.99},
    {"swedish": "via", "english": "via, through", "cefr": 1, "frequency": 174.12},
    {"swedish": "före", "english": "before", "cefr": 1, "frequency": 173.85},
    {"swedish": "enkel", "english": "simple, easy", "cefr": 1, "frequency": 173.10},
    {"swedish": "alls", "english": "at all", "cefr": 1, "frequency": 173.06},
    {"swedish": "såsom", "english": "such as, as", "cefr": 1, "frequency": 171.86},
    {"swedish": "lätt", "english": "easy, light", "cefr": 1, "frequency": 167.41},
    {"swedish": "tydlig", "english": "clear, obvious", "cefr": 1, "frequency": 165.93},
    {"swedish": "per", "english": "per", "cefr": 1, "frequency": 162.15},
    {"swedish": "såväl", "english": "as well", "cefr": 1, "frequency": 161.72},
    {"swedish": "enskild", "english": "individual, private", "cefr": 1, "frequency": 159.02},
    {"swedish": "igår", "english": "yesterday", "cefr": 1, "frequency": 157.53},
    {"swedish": "igenom", "english": "through", "cefr": 1, "frequency": 154.93},
    {"swedish": "eget", "english": "own (neuter)", "cefr": 1, "frequency": 154.19},
    {"swedish": "annars", "english": "otherwise", "cefr": 1, "frequency": 152.60},
    {"swedish": "säkert", "english": "surely, probably", "cefr": 1, "frequency": 149.46},
    {"swedish": "övrig", "english": "remaining, other", "cefr": 1, "frequency": 148.21},
    {"swedish": "framför allt", "english": "above all", "cefr": 1, "frequency": 147.43},
    {"swedish": "riktig", "english": "real, proper", "cefr": 1, "frequency": 144.98},
    {"swedish": "som att", "english": "as if", "cefr": 1, "frequency": 142.78},
    {"swedish": "liknande", "english": "similar", "cefr": 1, "frequency": 140.93},
    {"swedish": "inte ens", "english": "not even", "cefr": 1, "frequency": 140.79},
    {"swedish": "helt enkelt", "english": "simply, quite simply", "cefr": 1, "frequency": 140.11},
    {"swedish": "exempelvis", "english": "for example", "cefr": 1, "frequency": 139.94},
    {"swedish": "det vill säga", "english": "that is to say", "cefr": 1, "frequency": 138.07},
    {"swedish": "enbart", "english": "only, solely", "cefr": 1, "frequency": 134.15},
    {"swedish": "full", "english": "full", "cefr": 1, "frequency": 133.12},
    {"swedish": "ytterligare", "english": "further, additional", "cefr": 1, "frequency": 131.58},
    {"swedish": "alldeles", "english": "quite, completely", "cefr": 1, "frequency": 128.37},
    {"swedish": "sann", "english": "true", "cefr": 1, "frequency": 128.33},
    {"swedish": "klart", "english": "clearly, of course", "cefr": 1, "frequency": 126.22},
    {"swedish": "vit", "english": "white", "cefr": 1, "frequency": 126.15},
    {"swedish": "ond", "english": "evil, angry", "cefr": 1, "frequency": 123.18},
    {"swedish": "förstås", "english": "of course", "cefr": 1, "frequency": 121.03},
    {"swedish": "åtminstone", "english": "at least", "cefr": 1, "frequency": 119.86},
    {"swedish": "svart", "english": "black", "cefr": 1, "frequency": 118.26},
    {"swedish": "istället för", "english": "instead of", "cefr": 1, "frequency": 113.32},
    {"swedish": "främst", "english": "primarily, mainly", "cefr": 1, "frequency": 112.96},
    {"swedish": "bättre", "english": "better", "cefr": 1, "frequency": 112.92},
    {"swedish": "visst", "english": "certainly, sure", "cefr": 1, "frequency": 112.62},
    {"swedish": "högt", "english": "highly, loudly", "cefr": 1, "frequency": 112.04},
    {"swedish": "emellertid", "english": "however", "cefr": 1, "frequency": 111.59},
    {"swedish": "så kallad", "english": "so-called", "cefr": 1, "frequency": 110.51},
    {"swedish": "tack", "english": "thanks, thank you", "cefr": 1, "frequency": 108.87},
    {"swedish": "samtidigt som", "english": "while, at the same time as", "cefr": 1, "frequency": 108.12},
    {"swedish": "fel", "english": "wrong, incorrectly", "cefr": 1, "frequency": 107.80},
    {"swedish": "förutom", "english": "besides, apart from", "cefr": 1, "frequency": 106.41},
    {"swedish": "givetvis", "english": "of course, naturally", "cefr": 1, "frequency": 105.17},
    {"swedish": "speciellt", "english": "especially", "cefr": 1, "frequency": 104.35},
    {"swedish": "röd", "english": "red", "cefr": 1, "frequency": 104.34},
    {"swedish": "knappast", "english": "hardly, scarcely", "cefr": 1, "frequency": 102.76},
    {"swedish": "ens", "english": "even (in negation)", "cefr": 1, "frequency": 102.09},
    {"swedish": "utifrån", "english": "from outside, based on", "cefr": 1, "frequency": 100.69},
    {"swedish": "tillräckligt", "english": "sufficiently, enough", "cefr": 1, "frequency": 100.40},
    {"swedish": "aktuell", "english": "current, relevant", "cefr": 1, "frequency": 99.75},
    {"swedish": "någonsin", "english": "ever", "cefr": 1, "frequency": 99.71},
    {"swedish": "hård", "english": "hard, tough", "cefr": 1, "frequency": 98.66},
    {"swedish": "betydligt", "english": "considerably", "cefr": 1, "frequency": 97.40},
    {"swedish": "värd", "english": "worth", "cefr": 1, "frequency": 97.06},
    {"swedish": "imorgon", "english": "tomorrow", "cefr": 1, "frequency": 96.53},
    {"swedish": "central", "english": "central", "cefr": 1, "frequency": 94.56},
    {"swedish": "allra", "english": "very (superlative intensifier)", "cefr": 1, "frequency": 93.57},
    {"swedish": "tills", "english": "until", "cefr": 1, "frequency": 93.48},
    {"swedish": "totalt", "english": "totally", "cefr": 1, "frequency": 92.97},
    {"swedish": "varken...eller", "english": "neither...nor", "cefr": 1, "frequency": 91.32},
    {"swedish": "verklig", "english": "real, actual", "cefr": 1, "frequency": 90.87},
    {"swedish": "rent", "english": "purely, downright", "cefr": 1, "frequency": 90.85},
    {"swedish": "fantastisk", "english": "fantastic, wonderful", "cefr": 1, "frequency": 90.78},
    {"swedish": "grundläggande", "english": "fundamental, basic", "cefr": 1, "frequency": 90.73},
    {"swedish": "halv", "english": "half", "cefr": 1, "frequency": 90.13},
    {"swedish": "inte minst", "english": "not least", "cefr": 1, "frequency": 89.08},
    {"swedish": "ovan", "english": "above", "cefr": 1, "frequency": 88.85},
    {"swedish": "snarare", "english": "rather", "cefr": 1, "frequency": 87.88},
    {"swedish": "skön", "english": "comfortable, nice", "cefr": 1, "frequency": 87.52},
    {"swedish": "fast", "english": "although, even though", "cefr": 1, "frequency": 87.09},
    {"swedish": "fullt", "english": "fully, completely", "cefr": 1, "frequency": 86.40},
    {"swedish": "oavsett", "english": "regardless of", "cefr": 1, "frequency": 86.16},
    {"swedish": "jo", "english": "yes (in response to negative)", "cefr": 1, "frequency": 85.95},
    {"swedish": "allmänt", "english": "generally", "cefr": 1, "frequency": 85.48},
    {"swedish": "total", "english": "total", "cefr": 1, "frequency": 84.78},
    {"swedish": "i form av", "english": "in the form of", "cefr": 1, "frequency": 84.01},
    {"swedish": "rik", "english": "rich", "cefr": 1, "frequency": 83.80},
    {"swedish": "i år", "english": "this year", "cefr": 1, "frequency": 83.52},
    {"swedish": "igång", "english": "going, started", "cefr": 1, "frequency": 83.49},
    {"swedish": "antingen...eller", "english": "either...or", "cefr": 1, "frequency": 83.19},
    {"swedish": "åter", "english": "again, back", "cefr": 1, "frequency": 83.06},
    {"swedish": "bred", "english": "wide, broad", "cefr": 1, "frequency": 82.28},
    {"swedish": "vad gäller", "english": "regarding, as for", "cefr": 1, "frequency": 82.23},
    {"swedish": "samtlig", "english": "all, every", "cefr": 1, "frequency": 81.95},
    {"swedish": "hej", "english": "hello, hi", "cefr": 1, "frequency": 81.45},
    {"swedish": "fort", "english": "quickly, fast", "cefr": 1, "frequency": 81.07},
    {"swedish": "alltför", "english": "too (much)", "cefr": 1, "frequency": 80.65},
    {"swedish": "tydligt", "english": "clearly", "cefr": 1, "frequency": 80.52},
    {"swedish": "hårt", "english": "hard, harshly", "cefr": 1, "frequency": 80.46},
    {"swedish": "absolut", "english": "absolutely", "cefr": 1, "frequency": 80.27},
    {"swedish": "konstig", "english": "strange, weird", "cefr": 1, "frequency": 79.43},
    {"swedish": "kommande", "english": "coming, upcoming", "cefr": 1, "frequency": 79.27},
    {"swedish": "speciell", "english": "special", "cefr": 1, "frequency": 77.45},
    {"swedish": "omöjlig", "english": "impossible", "cefr": 1, "frequency": 77.05},
    {"swedish": "hittills", "english": "so far, until now", "cefr": 1, "frequency": 76.96},
    {"swedish": "omfattande", "english": "extensive, comprehensive", "cefr": 1, "frequency": 76.54},
    {"swedish": "oerhört", "english": "enormously, extremely", "cefr": 1, "frequency": 76.26},
    {"swedish": "självklart", "english": "obviously, of course", "cefr": 1, "frequency": 75.31},
    {"swedish": "lämplig", "english": "suitable, appropriate", "cefr": 1, "frequency": 75.27},
    {"swedish": "ständigt", "english": "constantly", "cefr": 1, "frequency": 74.22},
    {"swedish": "och så vidare", "english": "and so on", "cefr": 1, "frequency": 72.62},
    {"swedish": "visserligen", "english": "admittedly, certainly", "cefr": 1, "frequency": 72.58},
    {"swedish": "enorm", "english": "enormous", "cefr": 1, "frequency": 72.24},
    {"swedish": "relativt", "english": "relatively", "cefr": 1, "frequency": 72.06},
    {"swedish": "tung", "english": "heavy", "cefr": 1, "frequency": 72.04},
    {"swedish": "delvis", "english": "partly, partially", "cefr": 1, "frequency": 70.94},
    {"swedish": "medveten", "english": "conscious, aware", "cefr": 1, "frequency": 70.44},
    {"swedish": "ty", "english": "for, because", "cefr": 1, "frequency": 70.38},
    {"swedish": "begränsad", "english": "limited", "cefr": 1, "frequency": 69.90},
    {"swedish": "vag", "english": "vague", "cefr": 1, "frequency": 69.88},
    {"swedish": "starkt", "english": "strongly", "cefr": 1, "frequency": 68.69},
    {"swedish": "överens", "english": "in agreement", "cefr": 1, "frequency": 67.86},
    {"swedish": "framtida", "english": "future", "cefr": 1, "frequency": 67.84},
    {"swedish": "exakt", "english": "exactly", "cefr": 1, "frequency": 67.27},
    {"swedish": "underbar", "english": "wonderful", "cefr": 1, "frequency": 67.23},
    {"swedish": "extra", "english": "extra", "cefr": 1, "frequency": 66.90},
    {"swedish": "med tanke på", "english": "considering", "cefr": 1, "frequency": 66.31},
    {"swedish": "självklar", "english": "obvious, self-evident", "cefr": 1, "frequency": 66.24},
    {"swedish": "omkring", "english": "around, about", "cefr": 1, "frequency": 65.97},
    {"swedish": "i början", "english": "in the beginning", "cefr": 1, "frequency": 65.88},
    {"swedish": "motsvarande", "english": "corresponding, equivalent", "cefr": 1, "frequency": 65.56},
    {"swedish": "an", "english": "on (particle)", "cefr": 1, "frequency": 65.44},
    {"swedish": "samman", "english": "together", "cefr": 1, "frequency": 65.44},
    {"swedish": "ända", "english": "all the way", "cefr": 1, "frequency": 65.38},
    {"swedish": "i enlighet med", "english": "in accordance with", "cefr": 1, "frequency": 65.20},
    {"swedish": "uppenbar", "english": "obvious, evident", "cefr": 1, "frequency": 65.12},
    {"swedish": "återigen", "english": "once again", "cefr": 1, "frequency": 64.84},
    {"swedish": "levande", "english": "alive, living", "cefr": 1, "frequency": 64.27},
    {"swedish": "tusentals", "english": "thousands of", "cefr": 1, "frequency": 64.02},
    {"swedish": "eventuell", "english": "possible, potential", "cefr": 1, "frequency": 64.00},
    {"swedish": "normal", "english": "normal", "cefr": 2, "frequency": 63.27},
    {"swedish": "märklig", "english": "strange, remarkable", "cefr": 2, "frequency": 63.17},
    {"swedish": "respektive", "english": "respectively", "cefr": 2, "frequency": 62.53},
    {"swedish": "ihåg", "english": "in mind (komma ihåg = remember)", "cefr": 2, "frequency": 62.40},
    {"swedish": "knappt", "english": "barely, hardly", "cefr": 2, "frequency": 62.21},
    {"swedish": "enkelt", "english": "simply, easily", "cefr": 2, "frequency": 62.17},
    {"swedish": "ikväll", "english": "tonight, this evening", "cefr": 2, "frequency": 62.03},
    {"swedish": "anonym", "english": "anonymous", "cefr": 2, "frequency": 61.81},
    {"swedish": "bar", "english": "bare, naked", "cefr": 2, "frequency": 61.59},
    {"swedish": "i slutet", "english": "at the end", "cefr": 2, "frequency": 60.23},
    {"swedish": "drygt", "english": "just over, slightly more than", "cefr": 2, "frequency": 60.10},
    {"swedish": "otroligt", "english": "incredibly", "cefr": 2, "frequency": 59.42},
    {"swedish": "roligt", "english": "fun, funny", "cefr": 2, "frequency": 59.42},
    {"swedish": "förrän", "english": "until, before", "cefr": 2, "frequency": 59.06},
    {"swedish": "lös", "english": "loose", "cefr": 2, "frequency": 57.71},
    {"swedish": "unik", "english": "unique", "cefr": 2, "frequency": 57.46},
    {"swedish": "förr", "english": "before, formerly", "cefr": 2, "frequency": 56.75},
    {"swedish": "svårt", "english": "with difficulty", "cefr": 2, "frequency": 56.72},
    {"swedish": "relevant", "english": "relevant", "cefr": 2, "frequency": 56.02},
    {"swedish": "som vanligt", "english": "as usual", "cefr": 2, "frequency": 55.42},
    {"swedish": "betydande", "english": "significant, considerable", "cefr": 2, "frequency": 55.32},
    {"swedish": "i övrigt", "english": "otherwise, apart from that", "cefr": 2, "frequency": 55.30},
    {"swedish": "dåligt", "english": "badly", "cefr": 2, "frequency": 54.56},
    {"swedish": "konkret", "english": "concrete, specific", "cefr": 2, "frequency": 53.61},
    {"swedish": "rakt", "english": "straight", "cefr": 2, "frequency": 53.53},
    {"swedish": "uppenbarligen", "english": "obviously, apparently", "cefr": 2, "frequency": 53.53},
    {"swedish": "desto", "english": "the (in comparisons)", "cefr": 2, "frequency": 53.50},
    {"swedish": "vart", "english": "where (to)", "cefr": 2, "frequency": 53.43},
    {"swedish": "kraftigt", "english": "strongly, heavily", "cefr": 2, "frequency": 53.14},
    {"swedish": "inklusive", "english": "including", "cefr": 2, "frequency": 52.53},
    {"swedish": "fullständigt", "english": "completely", "cefr": 2, "frequency": 52.21},
    {"swedish": "utöver", "english": "beyond, in addition to", "cefr": 2, "frequency": 51.60},
    {"swedish": "vare sig", "english": "whether...or", "cefr": 2, "frequency": 51.25},
    {"swedish": "grov", "english": "coarse, rough", "cefr": 2, "frequency": 51.04},
    {"swedish": "tom", "english": "empty", "cefr": 2, "frequency": 50.74},
    {"swedish": "mer eller mindre", "english": "more or less", "cefr": 2, "frequency": 50.50},
    {"swedish": "främsta", "english": "foremost, main", "cefr": 2, "frequency": 50.47},
    {"swedish": "djupt", "english": "deeply", "cefr": 2, "frequency": 50.43},
    {"swedish": "korrekt", "english": "correct", "cefr": 2, "frequency": 50.24},
    {"swedish": "bäst", "english": "best", "cefr": 2, "frequency": 50.24},
    {"swedish": "gentemot", "english": "towards, in relation to", "cefr": 2, "frequency": 50.23},
    {"swedish": "felaktig", "english": "incorrect, faulty", "cefr": 2, "frequency": 50.17},
    {"swedish": "ständig", "english": "constant, permanent", "cefr": 2, "frequency": 50.11},
    {"swedish": "längs", "english": "along", "cefr": 2, "frequency": 49.80},
    {"swedish": "i första hand", "english": "primarily, in the first place", "cefr": 2, "frequency": 49.48},
    {"swedish": "slut", "english": "finished, over", "cefr": 2, "frequency": 48.93},
    {"swedish": "övertygad", "english": "convinced", "cefr": 2, "frequency": 48.55},
    {"swedish": "förut", "english": "before, previously", "cefr": 2, "frequency": 48.23},
    {"swedish": "personligen", "english": "personally", "cefr": 2, "frequency": 48.21},
    {"swedish": "huruvida", "english": "whether", "cefr": 2, "frequency": 47.92},
    {"swedish": "ytterst", "english": "extremely, ultimately", "cefr": 2, "frequency": 47.74},
    {"swedish": "hemlig", "english": "secret", "cefr": 2, "frequency": 47.62},
    {"swedish": "berörd", "english": "affected, concerned", "cefr": 2, "frequency": 47.13},
    {"swedish": "härlig", "english": "lovely, wonderful", "cefr": 2, "frequency": 47.10},
    {"swedish": "bekant", "english": "familiar, known", "cefr": 2, "frequency": 46.60},
    {"swedish": "överallt", "english": "everywhere", "cefr": 2, "frequency": 46.57},
    {"swedish": "falsk", "english": "false, fake", "cefr": 2, "frequency": 46.49},
    {"swedish": "normalt", "english": "normally", "cefr": 2, "frequency": 46.36},
    {"swedish": "seriös", "english": "serious", "cefr": 2, "frequency": 46.16},
    {"swedish": "omedelbart", "english": "immediately", "cefr": 2, "frequency": 46.15},
    {"swedish": "kraftig", "english": "strong, powerful", "cefr": 2, "frequency": 46.13},
    {"swedish": "fritt", "english": "freely", "cefr": 2, "frequency": 45.90},
    {"swedish": "perfekt", "english": "perfect", "cefr": 2, "frequency": 45.65},
    {"swedish": "gott", "english": "well, good", "cefr": 2, "frequency": 45.50},
    {"swedish": "beroende på", "english": "depending on", "cefr": 2, "frequency": 45.39},
    {"swedish": "långsiktig", "english": "long-term", "cefr": 2, "frequency": 44.96},
    {"swedish": "evig", "english": "eternal", "cefr": 2, "frequency": 44.78},
    {"swedish": "specifik", "english": "specific", "cefr": 2, "frequency": 43.64},
    {"swedish": "färdig", "english": "finished, ready", "cefr": 2, "frequency": 43.33},
    {"swedish": "bestämd", "english": "determined, definite", "cefr": 2, "frequency": 43.06},
    {"swedish": "annorlunda", "english": "different", "cefr": 2, "frequency": 42.85},
    {"swedish": "definitivt", "english": "definitely", "cefr": 2, "frequency": 42.38},
    {"swedish": "i stort sett", "english": "largely, mostly", "cefr": 2, "frequency": 42.10},
    {"swedish": "i förhållande till", "english": "in relation to", "cefr": 2, "frequency": 41.87},
    {"swedish": "ifall", "english": "in case, if", "cefr": 2, "frequency": 41.43},
    {"swedish": "oberoende", "english": "independent", "cefr": 2, "frequency": 41.42},
    {"swedish": "överhuvudtaget", "english": "at all", "cefr": 2, "frequency": 41.00},
    {"swedish": "synd", "english": "a pity, too bad", "cefr": 2, "frequency": 40.74},
    {"swedish": "genast", "english": "immediately, at once", "cefr": 2, "frequency": 40.70},
    {"swedish": "logisk", "english": "logical", "cefr": 2, "frequency": 40.69},
    {"swedish": "inom ramen för", "english": "within the framework of", "cefr": 2, "frequency": 40.67},
    {"swedish": "i fråga", "english": "in question", "cefr": 2, "frequency": 40.14},
    {"swedish": "blå", "english": "blue", "cefr": 2, "frequency": 40.00},
    {"swedish": "extremt", "english": "extremely", "cefr": 2, "frequency": 39.25},
    {"swedish": "individuell", "english": "individual", "cefr": 2, "frequency": 38.72},
]
