nouns = [
    {"indefinite": "fritid", "definite": "fritiden", "plural": "fritider", "plural_definite": "fritiderna", "english": "free time", "cefr": 3, "frequency": 15.60},
    {"indefinite": "sport", "definite": "sporten", "plural": "sporter", "plural_definite": "sporterna", "english": "sport", "cefr": 2, "frequency": 38.76},
    {"indefinite": "gym", "definite": "gymmet", "plural": "gym", "plural_definite": "gymmen", "english": "gym", "cefr": 1, "frequency": None},
    {"indefinite": "löpning", "definite": "löpningen", "plural": "löpningar", "plural_definite": "löpningarna", "english": "running", "cefr": 1, "frequency": None},
    {"indefinite": "cykling", "definite": "cyklingen", "plural": "cyklingar", "plural_definite": "cyklingarna", "english": "cycling", "cefr": 1, "frequency": None},
    {"indefinite": "simning", "definite": "simningen", "plural": "simningar", "plural_definite": "simningarna", "english": "swimming", "cefr": 1, "frequency": None},
    {"indefinite": "promenad", "definite": "promenaden", "plural": "promenader", "plural_definite": "promenaderna", "english": "walk", "cefr": 2, "frequency": 25.00},
    {"indefinite": "vandring", "definite": "vandringen", "plural": "vandringar", "plural_definite": "vandringarna", "english": "hike", "cefr": 2, "frequency": 36.83},
    {"indefinite": "spel", "definite": "spelet", "plural": "spel", "plural_definite": "spelen", "english": "game", "cefr": 1, "frequency": 156.33},
    {"indefinite": "brädspel", "definite": "brädspelet", "plural": "brädspel", "plural_definite": "brädspelen", "english": "board game", "cefr": 1, "frequency": None},
    {"indefinite": "datorspel", "definite": "datorspelet", "plural": "datorspel", "plural_definite": "datorspelen", "english": "computer game", "cefr": 1, "frequency": None},
    {"indefinite": "gitarr", "definite": "gitarren", "plural": "gitarrer", "plural_definite": "gitarrerna", "english": "guitar", "cefr": 3, "frequency": 15.21},
    {"indefinite": "piano", "definite": "pianot", "plural": "pianon", "plural_definite": "pianona", "english": "piano", "cefr": 1, "frequency": None},
    {"indefinite": "roman", "definite": "romanen", "plural": "romaner", "plural_definite": "romanerna", "english": "novel", "cefr": 2, "frequency": 48.70},
    {"indefinite": "teckning", "definite": "teckningen", "plural": "teckningar", "plural_definite": "teckningarna", "english": "drawing", "cefr": 3, "frequency": 23.51},
    {"indefinite": "fotografi", "definite": "fotografiet", "plural": "fotografier", "plural_definite": "fotografierna", "english": "photograph", "cefr": 3, "frequency": 15.74},
    {"indefinite": "kamera", "definite": "kameran", "plural": "kameror", "plural_definite": "kamerorna", "english": "camera", "cefr": 2, "frequency": 39.24},
    {"indefinite": "resa", "definite": "resan", "plural": "resor", "plural_definite": "resorna", "english": "trip", "cefr": 1, "frequency": 122.43},
    {"indefinite": "semester", "definite": "semestern", "plural": "semestrar", "plural_definite": "semestrarna", "english": "vacation", "cefr": 2, "frequency": 32.51},
    {"indefinite": "strand", "definite": "stranden", "plural": "stränder", "plural_definite": "stränderna", "english": "beach", "cefr": 2, "frequency": 38.97},
    {"indefinite": "fjäll", "definite": "fjället", "plural": "fjäll", "plural_definite": "fjällen", "english": "mountain area", "cefr": 1, "frequency": None},
    {"indefinite": "park", "definite": "parken", "plural": "parker", "plural_definite": "parkerna", "english": "park", "cefr": 2, "frequency": 26.25},
    {"indefinite": "bibliotek", "definite": "biblioteket", "plural": "bibliotek", "plural_definite": "biblioteken", "english": "library", "cefr": 2, "frequency": 35.39},
    {"indefinite": "dans", "definite": "dansen", "plural": "danser", "plural_definite": "danserna", "english": "dance", "cefr": 2, "frequency": 24.70},
    {"indefinite": "lektion", "definite": "lektionen", "plural": "lektioner", "plural_definite": "lektionerna", "english": "lesson", "cefr": 3, "frequency": 22.89},
    {"indefinite": "kurs", "definite": "kursen", "plural": "kurser", "plural_definite": "kurserna", "english": "course", "cefr": 2, "frequency": 63.24},
    {"indefinite": "aktivitet", "definite": "aktiviteten", "plural": "aktiviteter", "plural_definite": "aktiviteterna", "english": "activity", "cefr": 1, "frequency": 65.76},
    {"indefinite": "föreningsliv", "definite": "föreningslivet", "plural": "föreningsliv", "plural_definite": "föreningsliven", "english": "association life", "cefr": 1, "frequency": None},
    {"indefinite": "spelare", "definite": "spelaren", "plural": "spelare", "plural_definite": "spelarna", "english": "player", "cefr": 1, "frequency": 127.02},
]

verbs = [
    {"infinitive": "springa", "present": "springer", "past": "sprang", "supine": "sprungit", "english": "to run", "cefr": 1, "frequency": 76.39},
    {"infinitive": "simma", "present": "simmar", "past": "simmade", "supine": "simmat", "english": "to swim", "cefr": 3, "frequency": 13.60},
    {"infinitive": "cykla", "present": "cyklar", "past": "cyklade", "supine": "cyklat", "english": "to cycle", "cefr": 3, "frequency": 21.54},
    {"infinitive": "koppla av", "present": "kopplar av", "past": "kopplade av", "supine": "kopplat av", "english": "to relax", "cefr": 1, "frequency": None},
    {"infinitive": "träffas", "present": "träffas", "past": "träffades", "supine": "träffats", "english": "to meet (each other)", "cefr": 1, "frequency": None},
    {"infinitive": "njuta", "present": "njuter", "past": "njöt", "supine": "njutit", "english": "to enjoy", "cefr": 2, "frequency": 44.46},
    {"infinitive": "vinna", "present": "vinner", "past": "vann", "supine": "vunnit", "english": "to win", "cefr": 1, "frequency": 226.63},
    {"infinitive": "ro", "present": "ror", "past": "rodde", "supine": "rott", "english": "to row", "cefr": 1, "frequency": 816.02},
    {"infinitive": "öva", "present": "övar", "past": "övade", "supine": "övat", "english": "to practice", "cefr": 1, "frequency": 496.12},
    {"infinitive": "kommentera", "present": "kommenterar", "past": "kommenterade", "supine": "kommenterat", "english": "to comment", "cefr": 1, "frequency": 142.95},
    {"infinitive": "gilla", "present": "gillar", "past": "gillade", "supine": "gillat", "english": "to like", "cefr": 1, "frequency": 142.42},
    {"infinitive": "samla", "present": "samlar", "past": "samlade", "supine": "samlat", "english": "to collect/gather", "cefr": 1, "frequency": 118.53},
    {"infinitive": "kolla", "present": "kollar", "past": "kollade", "supine": "kollat", "english": "to check", "cefr": 1, "frequency": 116.13},
]

misc = [
    {"swedish": "avslappnande", "english": "relaxing", "cefr": 1, "frequency": None},
    {"swedish": "kreativ", "english": "creative", "cefr": 2, "frequency": 26.92},
    {"swedish": "sällsynt", "english": "rare", "cefr": 3, "frequency": 13.10},
    {"swedish": "på fritiden", "english": "in free time", "cefr": 1, "frequency": None},
    {"swedish": "hellre", "english": "rather", "cefr": 1, "frequency": None},
    {"swedish": "gärna", "english": "gladly", "cefr": 1, "frequency": 387.27},
    {"swedish": "lite", "english": "a little", "cefr": 1, "frequency": 1288.09},
    {"swedish": "kul", "english": "fun", "cefr": 1, "frequency": 121.60},
]
