nouns = [
    {"indefinite": "lägenhet", "definite": "lägenheten", "plural": "lägenheter", "plural_definite": "lägenheterna", "english": "apartment", "cefr": 2, "frequency": 58.56},
    {"indefinite": "villa", "definite": "villan", "plural": "villor", "plural_definite": "villorna", "english": "house, villa", "cefr": 3, "frequency": 14.78},
    {"indefinite": "radhus", "definite": "radhuset", "plural": "radhus", "plural_definite": "radhusen", "english": "terraced house", "cefr": 1, "frequency": None},
    {"indefinite": "bostad", "definite": "bostaden", "plural": "bostäder", "plural_definite": "bostäderna", "english": "residence, dwelling", "cefr": 2, "frequency": 57.37},
    {"indefinite": "hyra", "definite": "hyran", "plural": "hyror", "plural_definite": "hyrorna", "english": "rent", "cefr": 2, "frequency": 24.80},
    {"indefinite": "hyresvärd", "definite": "hyresvärden", "plural": "hyresvärdar", "plural_definite": "hyresvärdarna", "english": "landlord", "cefr": 1, "frequency": None},
    {"indefinite": "hyresgäst", "definite": "hyresgästen", "plural": "hyresgäster", "plural_definite": "hyresgästerna", "english": "tenant", "cefr": 1, "frequency": None},
    {"indefinite": "våning", "definite": "våningen", "plural": "våningar", "plural_definite": "våningarna", "english": "floor, level", "cefr": 3, "frequency": 23.11},
    {"indefinite": "trappa", "definite": "trappan", "plural": "trappor", "plural_definite": "trapporna", "english": "staircase", "cefr": 3, "frequency": 19.22},
    {"indefinite": "hiss", "definite": "hissen", "plural": "hissar", "plural_definite": "hissarna", "english": "elevator", "cefr": 1, "frequency": None},
    {"indefinite": "dörr", "definite": "dörren", "plural": "dörrar", "plural_definite": "dörrarna", "english": "door", "cefr": 1, "frequency": 70.02},
    {"indefinite": "fönster", "definite": "fönstret", "plural": "fönster", "plural_definite": "fönstren", "english": "window", "cefr": 2, "frequency": 42.75},
    {"indefinite": "tak", "definite": "taket", "plural": "tak", "plural_definite": "taken", "english": "roof, ceiling", "cefr": 2, "frequency": 45.67},
    {"indefinite": "vägg", "definite": "väggen", "plural": "väggar", "plural_definite": "väggarna", "english": "wall", "cefr": 2, "frequency": 50.14},
    {"indefinite": "golv", "definite": "golvet", "plural": "golv", "plural_definite": "golven", "english": "floor (surface)", "cefr": 2, "frequency": 32.64},
    {"indefinite": "rum", "definite": "rummet", "plural": "rum", "plural_definite": "rummen", "english": "room", "cefr": 1, "frequency": 152.07},
    {"indefinite": "vardagsrum", "definite": "vardagsrummet", "plural": "vardagsrum", "plural_definite": "vardagsrummen", "english": "living room", "cefr": 1, "frequency": None},
    {"indefinite": "sovrum", "definite": "sovrummet", "plural": "sovrum", "plural_definite": "sovrummen", "english": "bedroom", "cefr": 1, "frequency": None},
    {"indefinite": "kök", "definite": "köket", "plural": "kök", "plural_definite": "köken", "english": "kitchen", "cefr": 2, "frequency": 31.43},
    {"indefinite": "badrum", "definite": "badrummet", "plural": "badrum", "plural_definite": "badrummen", "english": "bathroom", "cefr": 1, "frequency": None},
    {"indefinite": "toalett", "definite": "toaletten", "plural": "toaletter", "plural_definite": "toaletterna", "english": "toilet", "cefr": 3, "frequency": 14.75},
    {"indefinite": "hall", "definite": "hallen", "plural": "hallar", "plural_definite": "hallarna", "english": "hall, entryway", "cefr": 3, "frequency": 12.29},
    {"indefinite": "balkong", "definite": "balkongen", "plural": "balkonger", "plural_definite": "balkongerna", "english": "balcony", "cefr": 1, "frequency": None},
    {"indefinite": "trädgård", "definite": "trädgården", "plural": "trädgårdar", "plural_definite": "trädgårdarna", "english": "garden", "cefr": 2, "frequency": 29.17},
    {"indefinite": "garage", "definite": "garaget", "plural": "garage", "plural_definite": "garagen", "english": "garage", "cefr": 1, "frequency": None},
    {"indefinite": "förråd", "definite": "förrådet", "plural": "förråd", "plural_definite": "förråden", "english": "storage room", "cefr": 1, "frequency": None},
    {"indefinite": "hylla", "definite": "hyllan", "plural": "hyllor", "plural_definite": "hyllorna", "english": "shelf", "cefr": 2, "frequency": 25.98},
    {"indefinite": "soffa", "definite": "soffan", "plural": "soffor", "plural_definite": "sofforna", "english": "sofa", "cefr": 3, "frequency": 23.32},
    {"indefinite": "stol", "definite": "stolen", "plural": "stolar", "plural_definite": "stolarna", "english": "chair", "cefr": 1, "frequency": 95.52},
    {"indefinite": "bord", "definite": "bordet", "plural": "bord", "plural_definite": "borden", "english": "table", "cefr": 2, "frequency": 59.07},
    {"indefinite": "säng", "definite": "sängen", "plural": "sängar", "plural_definite": "sängarna", "english": "bed", "cefr": 2, "frequency": 48.59},
    {"indefinite": "matta", "definite": "mattan", "plural": "mattor", "plural_definite": "mattorna", "english": "rug", "cefr": 3, "frequency": 11.96},
    {"indefinite": "lampa", "definite": "lampan", "plural": "lampor", "plural_definite": "lamporna", "english": "lamp", "cefr": 3, "frequency": 14.77},
    {"indefinite": "gardin", "definite": "gardinen", "plural": "gardiner", "plural_definite": "gardinerna", "english": "curtain", "cefr": 1, "frequency": None},
    {"indefinite": "tvättstuga", "definite": "tvättstugan", "plural": "tvättstugor", "plural_definite": "tvättstugorna", "english": "laundry room", "cefr": 1, "frequency": None},
    {"indefinite": "diskmaskin", "definite": "diskmaskinen", "plural": "diskmaskiner", "plural_definite": "diskmaskinerna", "english": "dishwasher", "cefr": 1, "frequency": None},
    {"indefinite": "ugn", "definite": "ugnen", "plural": "ugnar", "plural_definite": "ugnarna", "english": "oven", "cefr": 1, "frequency": None},
    {"indefinite": "spis", "definite": "spisen", "plural": "spisar", "plural_definite": "spisarna", "english": "stove", "cefr": 1, "frequency": None},
    {"indefinite": "kylskåp", "definite": "kylskåpet", "plural": "kylskåp", "plural_definite": "kylskåpen", "english": "fridge", "cefr": 1, "frequency": None},
    {"indefinite": "frys", "definite": "frysen", "plural": "frysar", "plural_definite": "frysarna", "english": "freezer", "cefr": 1, "frequency": None},
    {"indefinite": "tvättmaskin", "definite": "tvättmaskinen", "plural": "tvättmaskiner", "plural_definite": "tvättmaskinerna", "english": "washing machine", "cefr": 1, "frequency": None},
    {"indefinite": "torktumlare", "definite": "torktumlaren", "plural": "torktumlare", "plural_definite": "torktummarna", "english": "dryer", "cefr": 1, "frequency": None},
    {"indefinite": "elräkning", "definite": "elräkningen", "plural": "elräkningar", "plural_definite": "elräkningarna", "english": "electricity bill", "cefr": 1, "frequency": None},
    {"indefinite": "värme", "definite": "värmen", "plural": "värmar", "plural_definite": "värmarna", "english": "heat", "cefr": 2, "frequency": 34.25},
    {"indefinite": "hus", "definite": "huset", "plural": "hus", "plural_definite": "husen", "english": "house", "cefr": 1, "frequency": 206.57},
]

verbs = [
    {"infinitive": "städa", "present": "städar", "past": "städade", "supine": "städat", "english": "to clean", "cefr": 3, "frequency": 17.78},
    {"infinitive": "diska", "present": "diskar", "past": "diskade", "supine": "diskat", "english": "to wash dishes", "cefr": 1, "frequency": None},
    {"infinitive": "tvätta", "present": "tvättar", "past": "tvättade", "supine": "tvättat", "english": "to wash (clothes)", "cefr": 3, "frequency": 19.45},
    {"infinitive": "koka", "present": "kokar", "past": "kokade", "supine": "kokat", "english": "to boil", "cefr": 3, "frequency": 15.27},
    {"infinitive": "baka", "present": "bakar", "past": "bakade", "supine": "bakat", "english": "to bake", "cefr": 1, "frequency": None},
    {"infinitive": "laga mat", "present": "lagar mat", "past": "lagade mat", "supine": "lagat mat", "english": "to cook", "cefr": 1, "frequency": None},
    {"infinitive": "flytta in", "present": "flyttar in", "past": "flyttade in", "supine": "flyttat in", "english": "to move in", "cefr": 1, "frequency": None},
    {"infinitive": "flytta ut", "present": "flyttar ut", "past": "flyttade ut", "supine": "flyttat ut", "english": "to move out", "cefr": 1, "frequency": None},
    {"infinitive": "renovera", "present": "renoverar", "past": "renoverade", "supine": "renoverat", "english": "to renovate", "cefr": 1, "frequency": None},
    {"infinitive": "bygga", "present": "bygger", "past": "byggde", "supine": "byggt", "english": "to build", "cefr": 1, "frequency": 368.34},
    {"infinitive": "hyra", "present": "hyr", "past": "hyrde", "supine": "hyrt", "english": "to rent", "cefr": 2, "frequency": 24.80},
    {"infinitive": "äga", "present": "äger", "past": "ägde", "supine": "ägt", "english": "to own", "cefr": 1, "frequency": 1867.88},
    {"infinitive": "släcka", "present": "släcker", "past": "släckte", "supine": "släckt", "english": "to turn off (light)", "cefr": 1, "frequency": None},
    {"infinitive": "tända", "present": "tänder", "past": "tände", "supine": "tänt", "english": "to light, turn on", "cefr": 3, "frequency": 19.10},
    {"infinitive": "öppna", "present": "öppnar", "past": "öppnade", "supine": "öppnat", "english": "to open", "cefr": 1, "frequency": 131.53},
    {"infinitive": "stänga", "present": "stänger", "past": "stängde", "supine": "stängt", "english": "to close", "cefr": 1, "frequency": 76.10},
    {"infinitive": "vattna", "present": "vattnar", "past": "vattnade", "supine": "vattnat", "english": "to water (plants)", "cefr": 1, "frequency": None},
    {"infinitive": "slänga", "present": "slänger", "past": "slängde", "supine": "slängt", "english": "to throw away", "cefr": 2, "frequency": 39.82},
    {"infinitive": "sopa", "present": "sopar", "past": "sopade", "supine": "sopat", "english": "to sweep", "cefr": 1, "frequency": None},
    {"infinitive": "torka", "present": "torkar", "past": "torkade", "supine": "torkat", "english": "to dry, wipe", "cefr": 3, "frequency": 13.41},
    {"infinitive": "hänga", "present": "hänger", "past": "hängde", "supine": "hängt", "english": "to hang", "cefr": 1, "frequency": 100.43},
    {"infinitive": "fixa", "present": "fixar", "past": "fixade", "supine": "fixat", "english": "to fix", "cefr": 2, "frequency": 49.79},
    {"infinitive": "reparera", "present": "reparerar", "past": "reparerade", "supine": "reparerat", "english": "to repair", "cefr": 1, "frequency": None},
    {"infinitive": "låsa", "present": "låser", "past": "låsde", "supine": "låst", "english": "to lock", "cefr": 2, "frequency": 30.76},
    {"infinitive": "byta", "present": "byter", "past": "bytte", "supine": "bytt", "english": "to change, replace", "cefr": 1, "frequency": 119.29},
    {"infinitive": "riva", "present": "river", "past": "rev", "supine": "rivit", "english": "to tear/demolish", "cefr": 1, "frequency": 1088.02},
    {"infinitive": "sätta", "present": "sätter", "past": "satte", "supine": "satt", "english": "to put/set", "cefr": 1, "frequency": 375.30},
    {"infinitive": "ställa", "present": "ställer", "past": "ställde", "supine": "ställt", "english": "to place/put", "cefr": 1, "frequency": 361.06},
    {"infinitive": "fylla", "present": "fyller", "past": "fyllde", "supine": "fyllt", "english": "to fill", "cefr": 1, "frequency": 116.00},
]

misc = [
    {"swedish": "bekväm", "english": "comfortable", "cefr": 1, "frequency": None},
    {"swedish": "rymlig", "english": "spacious", "cefr": 1, "frequency": None},
    {"swedish": "gammaldags", "english": "old-fashioned", "cefr": 1, "frequency": None},
    {"swedish": "ljus", "english": "bright", "cefr": 1, "frequency": 84.31},
    {"swedish": "mörk", "english": "dark", "cefr": 2, "frequency": 59.31},
    {"swedish": "bullrig", "english": "noisy", "cefr": 1, "frequency": None},
    {"swedish": "trygg", "english": "safe", "cefr": 2, "frequency": 30.29},
    {"swedish": "osäker", "english": "unsafe", "cefr": 2, "frequency": 35.63},
    {"swedish": "mysig", "english": "cozy", "cefr": 3, "frequency": 19.70},
    {"swedish": "praktisk", "english": "practical", "cefr": 2, "frequency": 51.45},
    {"swedish": "vacker", "english": "beautiful", "cefr": 1, "frequency": 127.57},
    {"swedish": "hemtrevlig", "english": "homely, cozy", "cefr": 1, "frequency": None},
    {"swedish": "kall", "english": "cold", "cefr": 1, "frequency": 74.14},
    {"swedish": "varm", "english": "warm", "cefr": 1, "frequency": 78.22},
    {"swedish": "långt bort", "english": "far away", "cefr": 1, "frequency": None},
    {"swedish": "inomhus", "english": "indoors", "cefr": 1, "frequency": None},
    {"swedish": "utomhus", "english": "outdoors", "cefr": 1, "frequency": None},
    {"swedish": "ovanpå", "english": "on top of", "cefr": 1, "frequency": None},
    {"swedish": "bredvid", "english": "next to", "cefr": 2, "frequency": 30.67},
    {"swedish": "mitt emot", "english": "opposite", "cefr": 1, "frequency": None},
    {"swedish": "efteråt", "english": "afterwards", "cefr": 2, "frequency": 31.67},
]
