nouns = [
    {"indefinite": "medborgare", "definite": "medborgaren", "plural": "medborgare", "plural_definite": "medborgarna", "english": "citizen", "cefr": 1, "frequency": 135.65},
    {"indefinite": "rättighet", "definite": "rättigheten", "plural": "rättigheter", "plural_definite": "rättigheterna", "english": "right", "cefr": 1, "frequency": 207.42},
    {"indefinite": "skyldighet", "definite": "skyldigheten", "plural": "skyldigheter", "plural_definite": "skyldigheterna", "english": "obligation", "cefr": 2, "frequency": 44.81},
    {"indefinite": "regering", "definite": "regeringen", "plural": "regeringar", "plural_definite": "regeringarna", "english": "government", "cefr": 1, "frequency": 603.37},
    {"indefinite": "riksdag", "definite": "riksdagen", "plural": "riksdagar", "plural_definite": "riksdagarna", "english": "parliament", "cefr": 1, "frequency": 223.14},
    {"indefinite": "lag", "definite": "lagen", "plural": "lagar", "plural_definite": "lagarna", "english": "law", "cefr": 1, "frequency": 489.85},
    {"indefinite": "regel", "definite": "regeln", "plural": "regler", "plural_definite": "reglerna", "english": "rule", "cefr": 1, "frequency": 211.92},
    {"indefinite": "minister", "definite": "ministern", "plural": "ministrar", "plural_definite": "ministrarna", "english": "minister", "cefr": 2, "frequency": 55.85},
    {"indefinite": "politiker", "definite": "politikern", "plural": "politiker", "plural_definite": "politikerna", "english": "politician", "cefr": 1, "frequency": 167.43},
    {"indefinite": "parti", "definite": "partiet", "plural": "partier", "plural_definite": "partierna", "english": "party (political)", "cefr": 1, "frequency": 348.11},
    {"indefinite": "val", "definite": "valet", "plural": "val", "plural_definite": "valen", "english": "election", "cefr": 1, "frequency": 269.93},
    {"indefinite": "omröstning", "definite": "omröstningen", "plural": "omröstningar", "plural_definite": "omröstningarna", "english": "vote", "cefr": 2, "frequency": 30.56},
    {"indefinite": "demokrati", "definite": "demokratin", "plural": "demokratier", "plural_definite": "demokratierna", "english": "democracy", "cefr": 1, "frequency": 160.56},
    {"indefinite": "diktatur", "definite": "diktaturen", "plural": "diktaturer", "plural_definite": "diktaturerna", "english": "dictatorship", "cefr": 2, "frequency": 35.37},
    {"indefinite": "frihet", "definite": "friheten", "plural": "friheter", "plural_definite": "friheterna", "english": "freedom", "cefr": 1, "frequency": 132.47},
    {"indefinite": "jämlikhet", "definite": "jämlikheten", "plural": "jämlikheter", "plural_definite": "jämlikheterna", "english": "equality", "cefr": 3, "frequency": 15.42},
    {"indefinite": "rättvisa", "definite": "rättvisan", "plural": "rättvisor", "plural_definite": "rättvisorna", "english": "justice, fairness", "cefr": 2, "frequency": 38.74},
    {"indefinite": "myndighet", "definite": "myndigheten", "plural": "myndigheter", "plural_definite": "myndigheterna", "english": "authority, agency", "cefr": 1, "frequency": 186.22},
    {"indefinite": "polis", "definite": "polisen", "plural": "poliser", "plural_definite": "poliserna", "english": "police (officer)", "cefr": 1, "frequency": 216.42},
    {"indefinite": "domstol", "definite": "domstolen", "plural": "domstolar", "plural_definite": "domstolarna", "english": "court", "cefr": 1, "frequency": 98.49},
    {"indefinite": "brott", "definite": "brottet", "plural": "brott", "plural_definite": "brotten", "english": "crime", "cefr": 1, "frequency": 139.94},
    {"indefinite": "straff", "definite": "straffet", "plural": "straff", "plural_definite": "straffen", "english": "punishment", "cefr": 2, "frequency": 45.66},
    {"indefinite": "invånare", "definite": "invånaren", "plural": "invånare", "plural_definite": "invånarna", "english": "inhabitant, resident", "cefr": 2, "frequency": 50.64},
    {"indefinite": "kommun", "definite": "kommunen", "plural": "kommuner", "plural_definite": "kommunerna", "english": "municipality", "cefr": 1, "frequency": 242.01},
    {"indefinite": "stat", "definite": "staten", "plural": "stater", "plural_definite": "staterna", "english": "state", "cefr": 1, "frequency": 416.16},
    {"indefinite": "skattebetalare", "definite": "skattebetalaren", "plural": "skattebetalare", "plural_definite": "skattebetalarna", "english": "taxpayer", "cefr": 3, "frequency": 19.78},
    {"indefinite": "socialt stöd", "definite": "det sociala stödet", "plural": "sociala stöd", "plural_definite": "de sociala stöden", "english": "social support", "cefr": 1, "frequency": None},
    {"indefinite": "pension", "definite": "pensionen", "plural": "pensioner", "plural_definite": "pensionerna", "english": "pension", "cefr": 2, "frequency": 38.96},
    {"indefinite": "arbetslöshet", "definite": "arbetslösheten", "plural": "arbetslösheter", "plural_definite": "arbetslösheterna", "english": "unemployment", "cefr": 1, "frequency": 65.00},
    {"indefinite": "ekonomi", "definite": "ekonomin", "plural": "ekonomier", "plural_definite": "ekonomierna", "english": "economy", "cefr": 1, "frequency": 194.28},
    {"indefinite": "inflation", "definite": "inflationen", "plural": "inflationer", "plural_definite": "inflationerna", "english": "inflation", "cefr": 2, "frequency": 55.13},
    {"indefinite": "kostnad", "definite": "kostnaden", "plural": "kostnader", "plural_definite": "kostnaderna", "english": "cost", "cefr": 1, "frequency": 135.72},
    {"indefinite": "lön", "definite": "lönen", "plural": "löner", "plural_definite": "lönerna", "english": "salary", "cefr": 1, "frequency": 90.42},
    {"indefinite": "företag", "definite": "företaget", "plural": "företag", "plural_definite": "företagen", "english": "company", "cefr": 1, "frequency": 412.18},
    {"indefinite": "arbetsplats", "definite": "arbetsplatsen", "plural": "arbetsplatser", "plural_definite": "arbetsplatserna", "english": "workplace", "cefr": 2, "frequency": 39.66},
    {"indefinite": "arbetstagare", "definite": "arbetstagaren", "plural": "arbetstagare", "plural_definite": "arbetstagarna", "english": "employee", "cefr": 2, "frequency": 38.17},
    {"indefinite": "arbetsgivare", "definite": "arbetsgivaren", "plural": "arbetsgivare", "plural_definite": "arbetsgivarna", "english": "employer", "cefr": 1, "frequency": 71.89},
    {"indefinite": "produktion", "definite": "produktionen", "plural": "produktioner", "plural_definite": "produktionerna", "english": "production", "cefr": 1, "frequency": 77.86},
    {"indefinite": "export", "definite": "exporten", "plural": "exporter", "plural_definite": "exporterna", "english": "export", "cefr": 3, "frequency": 19.85},
    {"indefinite": "import", "definite": "importen", "plural": "importer", "plural_definite": "importerna", "english": "import", "cefr": 3, "frequency": 15.18},
    {"indefinite": "försäljning", "definite": "försäljningen", "plural": "försäljningar", "plural_definite": "försäljningarna", "english": "sales", "cefr": 2, "frequency": 56.93},
    {"indefinite": "handel", "definite": "handeln", "plural": "handlar", "plural_definite": "handlarna", "english": "trade", "cefr": 2, "frequency": 62.81},
    {"indefinite": "marknad", "definite": "marknaden", "plural": "marknader", "plural_definite": "marknaderna", "english": "market", "cefr": 1, "frequency": 166.13},
    {"indefinite": "investering", "definite": "investeringen", "plural": "investeringar", "plural_definite": "investeringarna", "english": "investment", "cefr": 2, "frequency": 57.01},
    {"indefinite": "hållbarhet", "definite": "hållbarheten", "plural": "hållbarheter", "plural_definite": "hållbarheterna", "english": "sustainability", "cefr": 1, "frequency": None},
    {"indefinite": "energikälla", "definite": "energikällan", "plural": "energikällor", "plural_definite": "energikällorna", "english": "energy source", "cefr": 1, "frequency": None},
    {"indefinite": "nyhet", "definite": "nyheten", "plural": "nyheter", "plural_definite": "nyheterna", "english": "news (item)", "cefr": 1, "frequency": 97.80},
    {"indefinite": "media", "definite": "median", "plural": "medier", "plural_definite": "medierna", "english": "media", "cefr": 1, "frequency": None},
    {"indefinite": "journalist", "definite": "journalisten", "plural": "journalister", "plural_definite": "journalisterna", "english": "journalist", "cefr": 1, "frequency": 97.73},
    {"indefinite": "rapport", "definite": "rapporten", "plural": "rapporter", "plural_definite": "rapporterna", "english": "report", "cefr": 1, "frequency": 144.86},
    {"indefinite": "forskning", "definite": "forskningen", "plural": "forskningar", "plural_definite": "forskningarna", "english": "research", "cefr": 1, "frequency": 140.49},
    {"indefinite": "resultat", "definite": "resultatet", "plural": "resultat", "plural_definite": "resultaten", "english": "result", "cefr": 1, "frequency": 241.96},
    {"indefinite": "förändring", "definite": "förändringen", "plural": "förändringar", "plural_definite": "förändringarna", "english": "change", "cefr": 1, "frequency": 159.43},
    {"indefinite": "utveckling", "definite": "utvecklingen", "plural": "utvecklingar", "plural_definite": "utvecklingarna", "english": "development", "cefr": 1, "frequency": 341.81},
    {"indefinite": "orsak", "definite": "orsaken", "plural": "orsaker", "plural_definite": "orsakerna", "english": "cause", "cefr": 1, "frequency": 110.42},
    {"indefinite": "följd", "definite": "följden", "plural": "följder", "plural_definite": "följderna", "english": "consequence", "cefr": 1, "frequency": 69.24},
    {"indefinite": "debatt", "definite": "debatten", "plural": "debatter", "plural_definite": "debatterna", "english": "debate", "cefr": 1, "frequency": 232.07},
    {"indefinite": "opinion", "definite": "opinionen", "plural": "opinioner", "plural_definite": "opinionerna", "english": "opinion", "cefr": 2, "frequency": 23.75},
    {"indefinite": "åsikt", "definite": "åsikten", "plural": "åsikter", "plural_definite": "åsikterna", "english": "point of view", "cefr": 1, "frequency": 192.30},
    {"indefinite": "diskussion", "definite": "diskussionen", "plural": "diskussioner", "plural_definite": "diskussionerna", "english": "discussion", "cefr": 1, "frequency": 192.14},
    {"indefinite": "protest", "definite": "protesten", "plural": "protester", "plural_definite": "protesterna", "english": "protest", "cefr": 2, "frequency": 34.62},
    {"indefinite": "demonstration", "definite": "demonstrationen", "plural": "demonstrationer", "plural_definite": "demonstrationerna", "english": "demonstration", "cefr": 2, "frequency": 37.37},
    {"indefinite": "teknik", "definite": "tekniken", "plural": "tekniker", "plural_definite": "teknikerna", "english": "technology", "cefr": 1, "frequency": 115.08},
    {"indefinite": "dator", "definite": "datorn", "plural": "datorer", "plural_definite": "datorerna", "english": "computer", "cefr": 1, "frequency": 120.28},
    {"indefinite": "mobil", "definite": "mobilen", "plural": "mobiler", "plural_definite": "mobilerna", "english": "mobile phone", "cefr": 3, "frequency": 16.93},
    {"indefinite": "internet", "definite": "internetet", "plural": "internet", "plural_definite": "interneten", "english": "internet", "cefr": 1, "frequency": 151.38},
    {"indefinite": "app", "definite": "appen", "plural": "appar", "plural_definite": "apparna", "english": "app", "cefr": 1, "frequency": None},
    {"indefinite": "programvara", "definite": "programvaran", "plural": "programvaror", "plural_definite": "programvarorna", "english": "software", "cefr": 3, "frequency": 15.43},
    {"indefinite": "hårdvara", "definite": "hårdvaran", "plural": "hårdvaror", "plural_definite": "hårdvarorna", "english": "hardware", "cefr": 1, "frequency": None},
    {"indefinite": "system", "definite": "systemet", "plural": "system", "plural_definite": "systemen", "english": "system", "cefr": 1, "frequency": 225.72},
    {"indefinite": "nätverk", "definite": "nätverket", "plural": "nätverk", "plural_definite": "nätverken", "english": "network", "cefr": 2, "frequency": 55.73},
    {"indefinite": "data", "definite": "datan", "plural": "data", "plural_definite": "datorna", "english": "data", "cefr": 2, "frequency": 26.32},
    {"indefinite": "information", "definite": "informationen", "plural": "informationer", "plural_definite": "informationerna", "english": "information", "cefr": 1, "frequency": 264.14},
    {"indefinite": "säkerhet", "definite": "säkerheten", "plural": "säkerheter", "plural_definite": "säkerheterna", "english": "security", "cefr": 1, "frequency": 105.63},
    {"indefinite": "lösenord", "definite": "lösenordet", "plural": "lösenord", "plural_definite": "lösenorden", "english": "password", "cefr": 1, "frequency": None},
    {"indefinite": "e-post", "definite": "e-posten", "plural": "e-post", "plural_definite": "e-posterna", "english": "email", "cefr": 1, "frequency": None},
    {"indefinite": "meddelande", "definite": "meddelandet", "plural": "meddelanden", "plural_definite": "meddelandena", "english": "message", "cefr": 2, "frequency": 49.48},
    {"indefinite": "hemsida", "definite": "hemsidan", "plural": "hemsidor", "plural_definite": "hemsidorna", "english": "website", "cefr": 1, "frequency": 89.75},
    {"indefinite": "sociala medier", "definite": "de sociala medierna", "plural": "sociala medier", "plural_definite": "de sociala medierna", "english": "social media", "cefr": 1, "frequency": None},
    {"indefinite": "robot", "definite": "roboten", "plural": "robotar", "plural_definite": "robotarna", "english": "robot", "cefr": 1, "frequency": None},
    {"indefinite": "maskin", "definite": "maskinen", "plural": "maskiner", "plural_definite": "maskinerna", "english": "machine", "cefr": 2, "frequency": 32.70},
    {"indefinite": "innovation", "definite": "innovationen", "plural": "innovationer", "plural_definite": "innovationerna", "english": "innovation", "cefr": 3, "frequency": 17.23},
    {"indefinite": "uppfinning", "definite": "uppfinningen", "plural": "uppfinningar", "plural_definite": "uppfinningarna", "english": "invention", "cefr": 3, "frequency": 12.11},
    {"indefinite": "artificiell intelligens", "definite": "den artificiella intelligensen", "plural": "artificiella intelligenser", "plural_definite": "de artificiella intelligenserna", "english": "artificial intelligence", "cefr": 1, "frequency": None},
    {"indefinite": "algoritm", "definite": "algoritmen", "plural": "algoritmer", "plural_definite": "algoritmerna", "english": "algorithm", "cefr": 1, "frequency": None},
    {"indefinite": "dataskydd", "definite": "dataskyddet", "plural": "dataskydd", "plural_definite": "dataskydden", "english": "data protection", "cefr": 1, "frequency": None},
    {"indefinite": "digitalisering", "definite": "digitaliseringen", "plural": "digitaliseringar", "plural_definite": "digitaliseringarna", "english": "digitalization", "cefr": 1, "frequency": None},
    {"indefinite": "cyberattack", "definite": "cyberattacken", "plural": "cyberattacker", "plural_definite": "cyberattackerna", "english": "cyberattack", "cefr": 1, "frequency": None},
    {"indefinite": "elnät", "definite": "elnätet", "plural": "elnät", "plural_definite": "elnäten", "english": "power grid", "cefr": 1, "frequency": None},
    {"indefinite": "elbil", "definite": "elbilen", "plural": "elbilar", "plural_definite": "elbilarna", "english": "electric car", "cefr": 1, "frequency": None},
    {"indefinite": "utvecklare", "definite": "utvecklaren", "plural": "utvecklare", "plural_definite": "utvecklarna", "english": "developer", "cefr": 1, "frequency": None},
    {"indefinite": "plattform", "definite": "plattformen", "plural": "plattformar", "plural_definite": "plattformarna", "english": "platform", "cefr": 3, "frequency": 18.51},
    {"indefinite": "kris", "definite": "krisen", "plural": "kriser", "plural_definite": "kriserna", "english": "crisis", "cefr": 1, "frequency": 97.59},
    {"indefinite": "konflikt", "definite": "konflikten", "plural": "konflikter", "plural_definite": "konflikterna", "english": "conflict", "cefr": 1, "frequency": 109.19},
    {"indefinite": "fred", "definite": "freden", "plural": "freder", "plural_definite": "frederna", "english": "peace", "cefr": 1, "frequency": 69.22},
    {"indefinite": "krig", "definite": "kriget", "plural": "krig", "plural_definite": "krigen", "english": "war", "cefr": 1, "frequency": 275.09},
    {"indefinite": "flykting", "definite": "flyktingen", "plural": "flyktingar", "plural_definite": "flyktingarna", "english": "refugee", "cefr": 2, "frequency": 39.98},
    {"indefinite": "invandring", "definite": "invandringen", "plural": "invandringar", "plural_definite": "invandringarna", "english": "immigration", "cefr": 2, "frequency": 36.54},
    {"indefinite": "integration", "definite": "integrationen", "plural": "integrationer", "plural_definite": "integrationerna", "english": "integration", "cefr": 2, "frequency": 25.74},
    {"indefinite": "samhällsproblem", "definite": "samhällsproblemet", "plural": "samhällsproblem", "plural_definite": "samhällsproblemen", "english": "social issue", "cefr": 1, "frequency": None},
    {"indefinite": "påverkan", "definite": "påverkan", "plural": "påverkningar", "plural_definite": "påverkningarna", "english": "impact", "cefr": 2, "frequency": 28.40},
    {"indefinite": "omställning", "definite": "omställningen", "plural": "omställningar", "plural_definite": "omställningarna", "english": "transition, conversion", "cefr": 1, "frequency": None},
    {"indefinite": "yrkesverksam", "definite": "yrkesverksamma", "plural": "yrkesverksamma", "plural_definite": "yrkesverksamma", "english": "professional", "cefr": 1, "frequency": None},
    {"indefinite": "subvention", "definite": "subventionen", "plural": "subventioner", "plural_definite": "subventionerna", "english": "subsidy", "cefr": 1, "frequency": None},
    {"indefinite": "satsning", "definite": "satsningen", "plural": "satsningar", "plural_definite": "satsningarna", "english": "investment, initiative", "cefr": 2, "frequency": 50.02},
    {"indefinite": "färdighet", "definite": "färdigheten", "plural": "färdigheter", "plural_definite": "färdigheterna", "english": "skill", "cefr": 3, "frequency": 15.05},
    {"indefinite": "människa", "definite": "människan", "plural": "människor", "plural_definite": "människorna", "english": "human, person", "cefr": 1, "frequency": 1030.33},
    {"indefinite": "kommentar", "definite": "kommentaren", "plural": "kommentarer", "plural_definite": "kommentarerna", "english": "comment", "cefr": 1, "frequency": 924.68},
    {"indefinite": "värld", "definite": "världen", "plural": "världar", "plural_definite": "världarna", "english": "world", "cefr": 1, "frequency": 617.89},
    {"indefinite": "folk", "definite": "folket", "plural": "folk", "plural_definite": "folken", "english": "people, folk", "cefr": 1, "frequency": 606.98},
    {"indefinite": "blogg", "definite": "bloggen", "plural": "bloggar", "plural_definite": "bloggarna", "english": "blog", "cefr": 1, "frequency": 430.91},
    {"indefinite": "inlägg", "definite": "inlägget", "plural": "inlägg", "plural_definite": "inläggen", "english": "post, contribution", "cefr": 1, "frequency": 403.03},
    {"indefinite": "politik", "definite": "politiken", "plural": "", "plural_definite": "", "english": "politics, policy", "cefr": 1, "frequency": 367.14},
    {"indefinite": "grupp", "definite": "gruppen", "plural": "grupper", "plural_definite": "grupperna", "english": "group", "cefr": 1, "frequency": 315.91},
    {"indefinite": "beslut", "definite": "beslutet", "plural": "beslut", "plural_definite": "besluten", "english": "decision", "cefr": 1, "frequency": 315.74},
    {"indefinite": "rätt", "definite": "rätten", "plural": "rätter", "plural_definite": "rätterna", "english": "right, court, dish", "cefr": 1, "frequency": 249.15},
    {"indefinite": "stöd", "definite": "stödet", "plural": "stöd", "plural_definite": "stöden", "english": "support", "cefr": 1, "frequency": 244.26},
    {"indefinite": "makt", "definite": "makten", "plural": "makter", "plural_definite": "makterna", "english": "power", "cefr": 1, "frequency": 228.02},
    {"indefinite": "åtgärd", "definite": "åtgärden", "plural": "åtgärder", "plural_definite": "åtgärderna", "english": "measure, action", "cefr": 1, "frequency": 223.86},
    {"indefinite": "medium", "definite": "mediet", "plural": "medier", "plural_definite": "medierna", "english": "medium, media", "cefr": 1, "frequency": 215.79},
    {"indefinite": "organisation", "definite": "organisationen", "plural": "organisationer", "plural_definite": "organisationerna", "english": "organization", "cefr": 1, "frequency": 210.61},
    {"indefinite": "medlem", "definite": "medlemmen", "plural": "medlemmar", "plural_definite": "medlemmarna", "english": "member", "cefr": 1, "frequency": 210.54},
    {"indefinite": "dom", "definite": "domen", "plural": "domar", "plural_definite": "domarna", "english": "judgment, verdict", "cefr": 1, "frequency": 173.60},
    {"indefinite": "risk", "definite": "risken", "plural": "risker", "plural_definite": "riskerna", "english": "risk", "cefr": 1, "frequency": 173.27},
    {"indefinite": "program", "definite": "programmet", "plural": "program", "plural_definite": "programmen", "english": "program, programme", "cefr": 1, "frequency": 182.39},
]

misc = [
    {"swedish": "jämlik", "english": "equal (in rights)", "cefr": 1, "frequency": None},
    {"swedish": "ojämlik", "english": "unequal", "cefr": 1, "frequency": None},
    {"swedish": "fri", "english": "free", "cefr": 1, "frequency": 201.84},
    {"swedish": "ofri", "english": "unfree, oppressed", "cefr": 1, "frequency": None},
    {"swedish": "demokratisk", "english": "democratic", "cefr": 1, "frequency": 107.94},
    {"swedish": "odemokratisk", "english": "undemocratic", "cefr": 1, "frequency": None},
    {"swedish": "politisk", "english": "political", "cefr": 1, "frequency": 409.23},
    {"swedish": "ekonomisk", "english": "economic", "cefr": 1, "frequency": 327.88},
    {"swedish": "nationell", "english": "national", "cefr": 1, "frequency": 222.66},
    {"swedish": "internationell", "english": "international", "cefr": 1, "frequency": 222.66},
    {"swedish": "offentlig", "english": "public", "cefr": 1, "frequency": 161.83},
    {"swedish": "privat", "english": "private", "cefr": 1, "frequency": 124.48},
    {"swedish": "ohållbar", "english": "unsustainable", "cefr": 1, "frequency": None},
    {"swedish": "klimatsmart", "english": "climate-smart", "cefr": 1, "frequency": None},
    {"swedish": "teknisk", "english": "technical", "cefr": 1, "frequency": 90.04},
    {"swedish": "digital", "english": "digital", "cefr": 2, "frequency": 45.42},
    {"swedish": "effektiv", "english": "efficient", "cefr": 1, "frequency": 95.24},
    {"swedish": "ineffektiv", "english": "inefficient", "cefr": 1, "frequency": None},
    {"swedish": "säker", "english": "safe, secure", "cefr": 1, "frequency": 117.08},
    {"swedish": "lönsam", "english": "profitable", "cefr": 3, "frequency": 15.11},
    {"swedish": "olönsam", "english": "unprofitable", "cefr": 1, "frequency": None},
    {"swedish": "framgångsrik", "english": "successful", "cefr": 2, "frequency": 43.21},
    {"swedish": "misslyckad", "english": "failed, unsuccessful", "cefr": 1, "frequency": None},
    {"swedish": "avgörande", "english": "decisive, crucial", "cefr": 1, "frequency": None},
    {"swedish": "pålitlig", "english": "reliable", "cefr": 1, "frequency": None},
    {"swedish": "trovärdig", "english": "credible, trustworthy", "cefr": 3, "frequency": 23.26},
    {"swedish": "opartisk", "english": "impartial", "cefr": 1, "frequency": None},
    {"swedish": "partisk", "english": "biased", "cefr": 1, "frequency": None},
    {"swedish": "ansvarig", "english": "responsible", "cefr": 2, "frequency": 60.34},
    {"swedish": "kritisk", "english": "critical", "cefr": 2, "frequency": 59.66},
    {"swedish": "långt borta", "english": "far away", "cefr": 1, "frequency": None},
    {"swedish": "egentligen", "english": "actually, really", "cefr": 1, "frequency": 267.44},
    {"swedish": "naturligtvis", "english": "of course, naturally", "cefr": 1, "frequency": 176.31},
    {"swedish": "tydligen", "english": "apparently", "cefr": 1, "frequency": 91.69},
    {"swedish": "ungefär", "english": "approximately", "cefr": 1, "frequency": 151.93},
    {"swedish": "svensk", "english": "Swedish", "cefr": 1, "frequency": 948.52},
    {"swedish": "europeisk", "english": "European", "cefr": 1, "frequency": 228.56},
    {"swedish": "allmän", "english": "general, public", "cefr": 1, "frequency": 185.28},
    {"swedish": "amerikansk", "english": "American", "cefr": 1, "frequency": 177.66},
    {"swedish": "mänsklig", "english": "human", "cefr": 1, "frequency": 160.58},
    {"swedish": "tysk", "english": "German", "cefr": 1, "frequency": 116.47},
    {"swedish": "statlig", "english": "state, governmental", "cefr": 1, "frequency": 104.45},
    {"swedish": "rysk", "english": "Russian", "cefr": 1, "frequency": 93.55},
    {"swedish": "borgerlig", "english": "bourgeois, conservative", "cefr": 1, "frequency": 92.09},
    {"swedish": "militär", "english": "military", "cefr": 1, "frequency": 88.82},
    {"swedish": "fransk", "english": "French", "cefr": 1, "frequency": 88.02},
    {"swedish": "fattig", "english": "poor", "cefr": 1, "frequency": 81.56},
    {"swedish": "engelsk", "english": "English", "cefr": 1, "frequency": 80.20},
    {"swedish": "finansiell", "english": "financial", "cefr": 1, "frequency": 74.34},
    {"swedish": "utländsk", "english": "foreign", "cefr": 1, "frequency": 73.89},
    {"swedish": "brittisk", "english": "British", "cefr": 1, "frequency": 69.43},
    {"swedish": "vetenskaplig", "english": "scientific", "cefr": 1, "frequency": 68.23},
    {"swedish": "England", "english": "England", "cefr": 1, "frequency": 66.60},
    {"swedish": "regional", "english": "regional", "cefr": 1, "frequency": 66.06},
    {"swedish": "civil", "english": "civil, civilian", "cefr": 1, "frequency": 65.17},
    {"swedish": "nordisk", "english": "Nordic", "cefr": 2, "frequency": 60.93},
    {"swedish": "israelisk", "english": "Israeli", "cefr": 2, "frequency": 60.20},
    {"swedish": "dansk", "english": "Danish", "cefr": 2, "frequency": 59.05},
    {"swedish": "liberal", "english": "liberal", "cefr": 2, "frequency": 57.58},
    {"swedish": "officiell", "english": "official", "cefr": 2, "frequency": 56.31},
    {"swedish": "palestinsk", "english": "Palestinian", "cefr": 2, "frequency": 56.26},
    {"swedish": "kvinnlig", "english": "female", "cefr": 2, "frequency": 55.42},
    {"swedish": "skyldig", "english": "guilty, owing", "cefr": 2, "frequency": 55.31},
    {"swedish": "kommunal", "english": "municipal", "cefr": 2, "frequency": 54.45},
    {"swedish": "socialdemokratisk", "english": "Social Democratic", "cefr": 2, "frequency": 53.50},
    {"swedish": "politiskt", "english": "politically", "cefr": 2, "frequency": 50.53},
    {"swedish": "kinesisk", "english": "Chinese", "cefr": 2, "frequency": 50.13},
    {"swedish": "utsatt", "english": "exposed, vulnerable", "cefr": 2, "frequency": 47.92},
    {"swedish": "finsk", "english": "Finnish", "cefr": 2, "frequency": 46.66},
    {"swedish": "etnisk", "english": "ethnic", "cefr": 2, "frequency": 44.59},
    {"swedish": "norsk", "english": "Norwegian", "cefr": 2, "frequency": 40.15},
    {"swedish": "socialistisk", "english": "socialist", "cefr": 2, "frequency": 39.15},
]

verbs = [
    {"infinitive": "bestämma", "english": "decide/determine", "present": "bestämmer", "past": "bestämde", "supine": "bestämt", "imperative": "bestäm", "passive": "bestäms", "adjective form": "bestämd", "cefr": 1, "frequency": 192.88},
    {"infinitive": "styra", "english": "govern/control", "present": "styr", "past": "styrde", "supine": "styrt", "imperative": "styr", "passive": "styrs", "adjective form": "styrd", "cefr": 1, "frequency": 126.20},
    {"infinitive": "leda", "english": "lead", "present": "leder", "past": "ledde", "supine": "lett", "imperative": "led", "passive": "leds", "adjective form": "ledd", "cefr": 1, "frequency": 388.53},
    {"infinitive": "producera", "english": "produce", "present": "producerar", "past": "producerade", "supine": "producerat", "imperative": "producera", "passive": "produceras", "adjective form": "producerad", "cefr": 2, "frequency": 61.86},
    {"infinitive": "förbjuda", "english": "prohibit", "present": "förbjuder", "past": "förbjöd", "supine": "förbjudit", "imperative": "förbjud", "passive": "förbjuds", "adjective form": "förbjuden", "cefr": 2, "frequency": 57.13},
    {"infinitive": "tillåta", "english": "allow/permit", "present": "tillåter", "past": "tillät", "supine": "tillåtit", "imperative": "tillåt", "passive": "tillåts", "adjective form": "tillåten", "cefr": 1, "frequency": 99.66},
    {"infinitive": "besluta", "english": "decide", "present": "beslutar", "past": "beslutade", "supine": "beslutat", "imperative": "besluta", "passive": "beslutas", "adjective form": "beslutat", "cefr": 1, "frequency": 125.13},
    {"infinitive": "rösta", "english": "vote", "present": "röstar", "past": "röstade", "supine": "röstat", "imperative": "rösta", "passive": "röstas", "adjective form": "röstad", "cefr": 1, "frequency": 145.06},
    {"infinitive": "arbeta", "english": "work", "present": "arbetar", "past": "arbetade", "supine": "arbetat", "imperative": "arbeta", "passive": "arbetas", "adjective form": "arbetad", "cefr": 1, "frequency": 289.93},
    {"infinitive": "tjäna", "english": "earn (money)", "present": "tjänar", "past": "tjänade", "supine": "tjänat", "imperative": "tjäna", "passive": "tjänades", "adjective form": "intjänad", "cefr": 1, "frequency": 114.80},
    {"infinitive": "investera", "english": "invest", "present": "investerar", "past": "investerade", "supine": "investerat", "imperative": "investera", "passive": "investeras", "adjective form": "investerad", "cefr": 2, "frequency": 27.72},
    {"infinitive": "forska", "english": "research", "present": "forskar", "past": "forskade", "supine": "forskat", "imperative": "forska", "passive": "forskas", "adjective form": "forskad", "cefr": 3, "frequency": 16.10},
    {"infinitive": "uppfinna", "english": "invent", "present": "uppfinner", "past": "uppfann", "supine": "uppfunnit", "imperative": "uppfinn", "passive": "uppfinns", "adjective form": "uppfunnen", "cefr": 1, "frequency": None},
    {"infinitive": "informera", "english": "inform", "present": "informerar", "past": "informerade", "supine": "informerat", "imperative": "informera", "passive": "informeras", "adjective form": "informerad", "cefr": 2, "frequency": 33.33},
    {"infinitive": "rapportera", "english": "report", "present": "rapporterar", "past": "rapporterade", "supine": "rapporterat", "imperative": "rapportera", "passive": "rapporterades", "adjective form": "rapporterad", "cefr": 2, "frequency": 62.23},
    {"infinitive": "övervaka", "english": "monitor/oversee", "present": "övervakar", "past": "övervakade", "supine": "övervakat", "imperative": "övervaka", "passive": "övervakades", "adjective form": "övervakad", "cefr": 3, "frequency": 19.98},
    {"infinitive": "försvara", "english": "defend/justify", "present": "försvarar", "past": "försvarade", "supine": "försvarat", "imperative": "försvara", "passive": "försvarades", "adjective form": "försvarad", "cefr": 1, "frequency": 87.72},
    {"infinitive": "stöda", "english": "support", "present": "stöder", "past": "stödde", "supine": "stött", "imperative": "stöd", "passive": "stöds", "adjective form": "stödd", "cefr": 1, "frequency": None},
    {"infinitive": "anse", "english": "consider", "present": "anser", "past": "ansåg", "supine": "ansett", "imperative": "anse", "passive": "anses", "adjective form": "", "cefr": 1, "frequency": 500.58},
    {"infinitive": "hålla med", "english": "agree", "present": "håller", "past": "höll", "supine": "hållit", "imperative": "håll", "passive": "", "adjective form": "", "cefr": 1, "frequency": None},
    {"infinitive": "försvinna", "english": "disappear", "present": "försvinner", "past": "försvann", "supine": "försvunnit", "imperative": "försvinna", "passive": "", "adjective form": "försvunnen", "cefr": 1, "frequency": 110.33},
    {"infinitive": "ersätta", "english": "replace", "present": "ersätter", "past": "ersatte", "supine": "ersatt", "imperative": "ersätt", "passive": "ersattes", "adjective form": "ersatt", "cefr": 1, "frequency": 86.51},
    {"infinitive": "påpeka", "english": "point out", "present": "påpekar", "past": "påpekade", "supine": "påpekat", "imperative": "påpeka", "passive": "påpekades", "adjective form": "påpekad", "cefr": 1, "frequency": 82.21},
    {"infinitive": "nå", "english": "reach/gain (business)", "present": "når", "past": "nådde", "supine": "nått", "imperative": "nå", "passive": "nås", "adjective form": "nådd", "cefr": 1, "frequency": 209.69},
    {"infinitive": "underlätta", "english": "facilitate", "present": "underlättar", "past": "underlätterade", "supine": "underlätt", "imperative": "underlätta", "passive": "underlättades", "adjective form": "underlättad", "cefr": 2, "frequency": 44.04},
    {"infinitive": "förbli", "english": "remain", "present": "förblir", "past": "förblev", "supine": "förblivit", "imperative": "förbliv", "passive": "", "adjective form": "", "cefr": 2, "frequency": 47.73},
    {"infinitive": "betyda", "present": "betyder", "past": "betydde", "supine": "betytt", "english": "to mean", "cefr": 1, "frequency": 1811.72},
    {"infinitive": "böra", "present": "bör", "past": "borde", "supine": "bort", "english": "should/ought to", "cefr": 1, "frequency": 1743.31},
    {"infinitive": "gälla", "present": "gäller", "past": "gällde", "supine": "gällt", "english": "to apply/concern", "cefr": 1, "frequency": 426.90},
    {"infinitive": "innebära", "present": "innebär", "past": "innebar", "supine": "inneburit", "english": "to mean/imply", "cefr": 1, "frequency": 412.65},
    {"infinitive": "kalla", "present": "kallar", "past": "kallade", "supine": "kallat", "english": "to call/name", "cefr": 1, "frequency": 365.74},
    {"infinitive": "följa", "present": "följer", "past": "följde", "supine": "följt", "english": "to follow", "cefr": 1, "frequency": 359.70},
    {"infinitive": "ske", "present": "sker", "past": "skedde", "supine": "skett", "english": "to happen/occur", "cefr": 1, "frequency": 351.80},
    {"infinitive": "ena", "present": "enar", "past": "enade", "supine": "enat", "english": "to unite", "cefr": 1, "frequency": 340.46},
    {"infinitive": "svara", "present": "svarar", "past": "svarade", "supine": "svarat", "english": "to answer", "cefr": 1, "frequency": 339.80},
    {"infinitive": "mena", "present": "menar", "past": "menade", "supine": "menat", "english": "to mean/intend", "cefr": 1, "frequency": 320.45},
    {"infinitive": "slå", "present": "slår", "past": "slog", "supine": "slagit", "english": "to hit/strike", "cefr": 1, "frequency": 312.71},
    {"infinitive": "föra", "present": "för", "past": "förde", "supine": "fört", "english": "to lead/carry", "cefr": 1, "frequency": 240.44},
    {"infinitive": "anmäla", "present": "anmäler", "past": "anmälde", "supine": "anmält", "english": "to report", "cefr": 1, "frequency": 209.80},
    {"infinitive": "stämma", "present": "stämmer", "past": "stämde", "supine": "stämt", "english": "to be correct/to sue", "cefr": 1, "frequency": 207.42},
    {"infinitive": "dela", "present": "delar", "past": "delade", "supine": "delat", "english": "to share/divide", "cefr": 1, "frequency": 205.43},
    {"infinitive": "tvinga", "present": "tvingar", "past": "tvingade", "supine": "tvingat", "english": "to force", "cefr": 1, "frequency": 196.99},
    {"infinitive": "ändra", "present": "ändrar", "past": "ändrade", "supine": "ändrat", "english": "to change", "cefr": 1, "frequency": 184.81},
    {"infinitive": "tyda", "present": "tyder", "past": "tydde", "supine": "tytt", "english": "to indicate/interpret", "cefr": 1, "frequency": 177.46},
    {"infinitive": "nämna", "present": "nämner", "past": "nämnde", "supine": "nämnt", "english": "to mention", "cefr": 1, "frequency": 159.17},
    {"infinitive": "anta", "present": "antar", "past": "antog", "supine": "antagit", "english": "to assume/adopt", "cefr": 1, "frequency": 156.58},
    {"infinitive": "föreslå", "present": "föreslår", "past": "föreslog", "supine": "föreslagit", "english": "to suggest/propose", "cefr": 1, "frequency": 156.27},
    {"infinitive": "bidra", "present": "bidrar", "past": "bidrog", "supine": "bidragit", "english": "to contribute", "cefr": 1, "frequency": 150.84},
    {"infinitive": "bryta", "present": "bryter", "past": "bröt", "supine": "brutit", "english": "to break", "cefr": 1, "frequency": 142.11},
    {"infinitive": "hävda", "present": "hävdar", "past": "hävdade", "supine": "hävdat", "english": "to claim/assert", "cefr": 1, "frequency": 139.57},
    {"infinitive": "släppa", "present": "släpper", "past": "släppte", "supine": "släppt", "english": "to release/let go", "cefr": 1, "frequency": 134.32},
    {"infinitive": "införa", "present": "inför", "past": "införde", "supine": "infört", "english": "to introduce/implement", "cefr": 1, "frequency": 130.26},
    {"infinitive": "konstatera", "present": "konstaterar", "past": "konstaterade", "supine": "konstaterat", "english": "to state/note", "cefr": 1, "frequency": 126.41},
    {"infinitive": "påstå", "present": "påstår", "past": "påstod", "supine": "påstått", "english": "to claim/assert", "cefr": 1, "frequency": 125.75},
    {"infinitive": "avse", "present": "avser", "past": "avsåg", "supine": "avsett", "english": "to intend/refer to", "cefr": 1, "frequency": 124.91},
    {"infinitive": "ange", "present": "anger", "past": "angav", "supine": "angett", "english": "to state/specify", "cefr": 1, "frequency": 121.39},
    {"infinitive": "uppstå", "present": "uppstår", "past": "uppstod", "supine": "uppstått", "english": "to arise/occur", "cefr": 1, "frequency": 111.37},
    {"infinitive": "bilda", "present": "bildar", "past": "bildade", "supine": "bildat", "english": "to form/educate", "cefr": 1, "frequency": 110.42},
    {"infinitive": "sprida", "present": "sprider", "past": "spred", "supine": "spridit", "english": "to spread", "cefr": 1, "frequency": 107.63},
    {"infinitive": "publicera", "present": "publicerar", "past": "publicerade", "supine": "publicerat", "english": "to publish", "cefr": 1, "frequency": 103.98},
    {"infinitive": "skilja", "present": "skiljer", "past": "skilde", "supine": "skilt", "english": "to separate/distinguish", "cefr": 1, "frequency": 102.57},
]
